from typing import Any

import re
import sys
import copy
import types
import inspect
import keyword

class FrozenInstanceError(AttributeError):
    ...

class _HAS_DEFAULT_FACTORY_CLASS:
    def __repr__(self: Any) -> None: ...

class _MISSING_TYPE:
    ...

class _FIELD_BASE:
    name: Any
    def __init__(self: Any, name: Any) -> None: ...
    def __repr__(self: Any) -> None: ...

class _InitVarMeta(type):
    def __getitem__(self: Any, params: Any) -> None: ...

class InitVar:
    ...

class Field:
    __slots__: Any
    name: Any
    type: Any
    default: Any
    default_factory: Any
    init: Any
    repr: Any
    hash: Any
    compare: Any
    metadata: Any
    _field_type: Any
    def __init__(self: Any, default: Any, default_factory: Any, init: Any, repr: Any, hash: Any, compare: Any, metadata: Any) -> None: ...
    def __repr__(self: Any) -> None: ...
    def __set_name__(self: Any, owner: Any, name: Any) -> None: ...

class _DataclassParams:
    __slots__: Any
    init: Any
    repr: Any
    eq: Any
    order: Any
    unsafe_hash: Any
    frozen: Any
    def __init__(self: Any, init: Any, repr: Any, eq: Any, order: Any, unsafe_hash: Any, frozen: Any) -> None: ...
    def __repr__(self: Any) -> None: ...

def field() -> None: ...

def _tuple_str(obj_name: Any, fields: Any) -> None: ...

def _create_fn(name: Any, args: Any, body: Any) -> None: ...

def _field_assign(frozen: Any, name: Any, value: Any, self_name: Any) -> None: ...

def _field_init(f: Any, frozen: Any, globals: Any, self_name: Any) -> None: ...

def _init_param(f: Any) -> None: ...

def _init_fn(fields: Any, frozen: Any, has_post_init: Any, self_name: Any) -> None: ...

def _repr_fn(fields: Any) -> None: ...

def _frozen_get_del_attr(cls: Any, fields: Any) -> None: ...

def _cmp_fn(name: Any, op: Any, self_tuple: Any, other_tuple: Any) -> None: ...

def _hash_fn(fields: Any) -> None: ...

def _is_classvar(a_type: Any, typing: Any) -> None: ...

def _is_initvar(a_type: Any, dataclasses: Any) -> None: ...

def _is_type(annotation: Any, cls: Any, a_module: Any, a_type: Any, is_type_predicate: Any) -> None: ...

def _get_field(cls: Any, a_name: Any, a_type: Any) -> None: ...

def _set_new_attribute(cls: Any, name: Any, value: Any) -> None: ...

def _hash_set_none(cls: Any, fields: Any) -> None: ...

def _hash_add(cls: Any, fields: Any) -> None: ...

def _hash_exception(cls: Any, fields: Any) -> None: ...

def _process_class(cls: Any, init: Any, repr: Any, eq: Any, order: Any, unsafe_hash: Any, frozen: Any) -> None: ...

def dataclass(_cls: Any = ...) -> None: ...

def fields(class_or_instance: Any) -> None: ...

def _is_dataclass_instance(obj: Any) -> None: ...

def is_dataclass(obj: Any) -> None: ...

def asdict(obj: Any) -> None: ...

def _asdict_inner(obj: Any, dict_factory: Any) -> None: ...

def astuple(obj: Any) -> None: ...

def _astuple_inner(obj: Any, tuple_factory: Any) -> None: ...

def make_dataclass(cls_name: Any, fields: Any) -> None: ...

def replace(obj: Any, **changes: Any) -> None: ...
