from typing import Any, TYPE_CHECKING

import os
import re
import sys
from logging import getLogger
from ast import literal_eval
from codecs import BOM_UTF8, BOM_UTF16, BOM_UTF16_BE, BOM_UTF16_LE
from collections import OrderedDict
import six
import ast
import compiler
from zato.common.util.config import get_env_config_ctx, get_env_config_value
import warnings
from zato.common.ext.validate_ import VdtTypeError


def match_utf8(encoding: Any) -> None: ...

def getObj(s: Any) -> None: ...

class UnknownType(Exception):
    ...

class Builder:
    def build(self: Any, o: Any) -> None: ...
    def build_List(self: Any, o: Any) -> None: ...
    def build_Const(self: Any, o: Any) -> None: ...
    def build_Dict(self: Any, o: Any) -> None: ...
    def build_Tuple(self: Any, o: Any) -> None: ...
    def build_Name(self: Any, o: Any) -> None: ...
    def build_Add(self: Any, o: Any) -> None: ...
    def build_Getattr(self: Any, o: Any) -> None: ...
    def build_UnarySub(self: Any, o: Any) -> None: ...
    def build_UnaryAdd(self: Any, o: Any) -> None: ...

def unrepr(s: Any) -> None: ...

class ConfigObjError(SyntaxError):
    line: Any
    line_number: Any
    def __init__(self: Any, message: Any = ..., line_number: Any = ..., line: Any = ...) -> None: ...

class NestingError(ConfigObjError):
    ...

class ParseError(ConfigObjError):
    ...

class ReloadError(IOError):
    def __init__(self: Any) -> None: ...

class DuplicateError(ConfigObjError):
    ...

class ConfigspecError(ConfigObjError):
    ...

class InterpolationError(ConfigObjError):
    ...

class InterpolationLoopError(InterpolationError):
    def __init__(self: Any, option: Any) -> None: ...

class RepeatSectionError(ConfigObjError):
    ...

class MissingInterpolationOption(InterpolationError):
    def __init__(self: Any, option: Any) -> None: ...

class UnreprError(ConfigObjError):
    ...

class InterpolationEngine:
    _KEYCRE: Any
    _cookie: Any
    section: Any
    def __init__(self: Any, section: Any) -> None: ...
    def interpolate(self: Any, key: Any, value: Any) -> None: ...
    def _fetch(self: Any, key: Any) -> None: ...
    def _parse_match(self: Any, match: Any) -> None: ...

class ConfigParserInterpolation(InterpolationEngine):
    _cookie: Any
    _KEYCRE: Any
    def _parse_match(self: Any, match: Any) -> None: ...

class TemplateInterpolation(InterpolationEngine):
    _cookie: Any
    _delimiter: Any
    _KEYCRE: Any
    def _parse_match(self: Any, match: Any) -> None: ...

def __newobj__(cls: Any, *args: Any) -> None: ...

class Section(OrderedDict):
    __iter__: Any
    __str__: Any
    parent: Any
    main: Any
    depth: Any
    name: Any
    def __setstate__(self: Any, state: Any) -> None: ...
    def __reduce__(self: Any) -> None: ...
    def __init__(self: Any, parent: Any, depth: Any, main: Any, indict: Any = ..., name: Any = ...) -> None: ...
    def _initialise(self: Any) -> None: ...
    def _interpolate(self: Any, key: Any, value: Any) -> None: ...
    def __getitem__(self: Any, key: Any) -> None: ...
    def __setitem__(self: Any, key: Any, value: Any, unrepr: Any = ...) -> None: ...
    def __delitem__(self: Any, key: Any) -> None: ...
    def get(self: Any, key: Any, default: Any = ...) -> None: ...
    def update(self: Any, indict: Any) -> None: ...
    def pop(self: Any, key: Any, default: Any = ...) -> None: ...
    def popitem(self: Any) -> None: ...
    def clear(self: Any) -> None: ...
    def setdefault(self: Any, key: Any, default: Any = ...) -> None: ...
    def items(self: Any) -> None: ...
    def keys(self: Any) -> None: ...
    def values(self: Any) -> None: ...
    def iteritems(self: Any) -> None: ...
    def iterkeys(self: Any) -> None: ...
    def itervalues(self: Any) -> None: ...
    def __repr__(self: Any) -> None: ...
    def dict(self: Any) -> None: ...
    def merge(self: Any, indict: Any) -> None: ...
    def rename(self: Any, oldkey: Any, newkey: Any) -> None: ...
    def walk(self: Any, function: Any, raise_errors: Any = ..., call_on_sections: Any = ..., **keywargs: Any) -> None: ...
    def as_bool(self: Any, key: Any) -> None: ...
    def as_int(self: Any, key: Any) -> None: ...
    def as_float(self: Any, key: Any) -> None: ...
    def as_list(self: Any, key: Any) -> None: ...
    def restore_default(self: Any, key: Any) -> None: ...
    def restore_defaults(self: Any) -> None: ...

class ConfigObj(Section):
    _keyword: Any
    _sectionmarker: Any
    _valueexp: Any
    _listvalueexp: Any
    _nolistvalue: Any
    _single_line_single: Any
    _single_line_double: Any
    _multi_line_single: Any
    _multi_line_double: Any
    _triple_quote: Any
    _bools: Any
    zato_env_config_ctx: get_env_config_ctx
    zato_component: Any
    zato_config_file_name: Any
    zato_env_variable_missing_suffix: Any
    zato_get_env_config_value: Any
    _inspec: Any
    use_zato: Any
    zato_crypto_manager: Any
    zato_secrets_conf: Any
    zato_secrets_url_prefix: Any
    zato_file_name: Any
    _original_configspec: Any
    def __init__(self: Any, infile: Any = ..., options: Any = ..., configspec: Any = ..., encoding: Any = ..., interpolation: Any = ..., raise_errors: Any = ..., list_values: Any = ..., create_empty: Any = ..., file_error: Any = ..., stringify: Any = ..., indent_type: Any = ..., default_encoding: Any = ..., unrepr: Any = ..., write_empty_values: Any = ..., _inspec: Any = ..., use_zato: Any = ..., zato_crypto_manager: Any = ..., zato_secrets_conf: Any = ..., zato_secrets_url_prefix: Any = ...) -> None: ...
    def _load(self: Any, infile: Any, configspec: Any) -> None: ...
    def _initialise(self: Any, options: Any = ...) -> None: ...
    def __repr__(self: Any) -> None: ...
    def _handle_bom(self: Any, infile: Any) -> None: ...
    def _a_to_u(self: Any, aString: Any) -> None: ...
    def _decode(self: Any, infile: Any, encoding: Any) -> None: ...
    def _decode_element(self: Any, line: Any) -> None: ...
    def _str(self: Any, value: Any) -> None: ...
    def _parse(self: Any, infile: Any) -> None: ...
    def _match_depth(self: Any, sect: Any, depth: Any) -> None: ...
    def _handle_error(self: Any, text: Any, ErrorClass: Any, infile: Any, cur_index: Any) -> None: ...
    def _unquote(self: Any, value: Any) -> None: ...
    def _quote(self: Any, value: Any, multiline: Any = ...) -> None: ...
    def _get_single_quote(self: Any, value: Any) -> None: ...
    def _get_triple_quote(self: Any, value: Any) -> None: ...
    def _handle_value(self: Any, value: Any) -> None: ...
    def _multiline(self: Any, value: Any, infile: Any, cur_index: Any, maxline: Any) -> None: ...
    def _handle_configspec(self: Any, configspec: Any) -> None: ...
    def _set_configspec(self: Any, section: Any, copy: Any) -> None: ...
    def _write_line(self: Any, indent_string: Any, entry: Any, this_entry: Any, comment: Any) -> None: ...
    def _write_marker(self: Any, indent_string: Any, depth: Any, entry: Any, comment: Any) -> None: ...
    def _handle_comment(self: Any, comment: Any) -> None: ...
    def write(self: Any, outfile: Any = ..., section: Any = ...) -> None: ...
    def validate(self: Any, validator: Any, preserve_errors: Any = ..., copy: Any = ..., section: Any = ...) -> None: ...
    def reset(self: Any) -> None: ...
    def reload(self: Any) -> None: ...

class SimpleVal:
    baseErrorClass: Any
    def __init__(self: Any) -> None: ...
    def check(self: Any, check: Any, member: Any, missing: Any = ...) -> None: ...

def flatten_errors(cfg: Any, res: Any, levels: Any = ..., results: Any = ...) -> None: ...

def get_extra_values(conf: Any, _prepend: Any = ...) -> None: ...
