from typing import Any

import re
import sys
from pprint import pprint
import socket
import struct
import doctest

def dottedQuadToNum(ip: Any) -> None: ...

def numToDottedQuad(num: Any) -> None: ...

class ValidateError(Exception):
    ...

class VdtMissingValue(ValidateError):
    ...

class VdtUnknownCheckError(ValidateError):
    def __init__(self: Any, value: Any) -> None: ...

class VdtParamError(SyntaxError):
    def __init__(self: Any, name: Any, value: Any) -> None: ...

class VdtTypeError(ValidateError):
    def __init__(self: Any, value: Any) -> None: ...

class VdtValueError(ValidateError):
    def __init__(self: Any, value: Any) -> None: ...

class VdtValueTooSmallError(VdtValueError):
    def __init__(self: Any, value: Any) -> None: ...

class VdtValueTooBigError(VdtValueError):
    def __init__(self: Any, value: Any) -> None: ...

class VdtValueTooShortError(VdtValueError):
    def __init__(self: Any, value: Any) -> None: ...

class VdtValueTooLongError(VdtValueError):
    def __init__(self: Any, value: Any) -> None: ...

class Validator:
    _func_re: Any
    _key_arg: Any
    _list_arg: Any
    _list_members: Any
    _paramfinder: Any
    _matchfinder: Any
    functions: Any
    baseErrorClass: Any
    _cache: Any
    def __init__(self: Any, functions: Any = ...) -> None: ...
    def check(self: Any, check: Any, value: Any, missing: Any = ...) -> None: ...
    def _handle_none(self: Any, value: Any) -> None: ...
    def _parse_with_caching(self: Any, check: Any) -> None: ...
    def _check_value(self: Any, value: Any, fun_name: Any, fun_args: Any, fun_kwargs: Any) -> None: ...
    def _parse_check(self: Any, check: Any) -> None: ...
    def _unquote(self: Any, val: Any) -> None: ...
    def _list_handle(self: Any, listmatch: Any) -> None: ...
    def _pass(self: Any, value: Any) -> None: ...
    def get_default_value(self: Any, check: Any) -> None: ...

def _is_num_param(names: Any, values: Any, to_float: Any = ...) -> None: ...

def is_integer(value: Any, min: Any = ..., max: Any = ...) -> None: ...

def is_float(value: Any, min: Any = ..., max: Any = ...) -> None: ...

def is_boolean(value: Any) -> None: ...

def is_ip_addr(value: Any) -> None: ...

def is_list(value: Any, min: Any = ..., max: Any = ...) -> None: ...

def is_tuple(value: Any, min: Any = ..., max: Any = ...) -> None: ...

def is_string(value: Any, min: Any = ..., max: Any = ...) -> None: ...

def is_int_list(value: Any, min: Any = ..., max: Any = ...) -> None: ...

def is_bool_list(value: Any, min: Any = ..., max: Any = ...) -> None: ...

def is_float_list(value: Any, min: Any = ..., max: Any = ...) -> None: ...

def is_string_list(value: Any, min: Any = ..., max: Any = ...) -> None: ...

def is_ip_addr_list(value: Any, min: Any = ..., max: Any = ...) -> None: ...

def force_list(value: Any, min: Any = ..., max: Any = ...) -> None: ...

def is_mixed_list(value: Any, *args: Any) -> None: ...

def is_option(value: Any, *options: Any) -> None: ...

def _test(value: Any, *args: Any, **keywargs: Any) -> None: ...

def _test2() -> None: ...

def _test3() -> None: ...
