from typing import Any, TYPE_CHECKING

from io import BytesIO
from zato.server.ext.zunicorn.http.errors import NoMoreData, ChunkMissingTerminator, InvalidChunkSize
from zato.server.ext.zunicorn import six


class ChunkedReader:
    req: Any
    parser: self.parse_chunked
    buf: BytesIO
    def __init__(self: Any, req: Any, unreader: Any, BytesIO: Any = ...) -> None: ...
    def read(self: Any, size: Any, integer_types: Any = ..., BytesIO: Any = ...) -> None: ...
    def parse_trailers(self: Any, unreader: Any, data: Any, BytesIO: Any = ...) -> None: ...
    def parse_chunked(self: Any, unreader: Any) -> None: ...
    def parse_chunk_size(self: Any, unreader: Any, data: Any = ..., BytesIO: Any = ...) -> None: ...
    def get_data(self: Any, unreader: Any, buf_write: Any, NoMoreData: Any = ...) -> None: ...

class LengthReader:
    unreader: Any
    length: Any
    def __init__(self: Any, unreader: Any, length: Any) -> None: ...
    def read(self: Any, size: Any, integer_types: Any = ..., BytesIO: Any = ...) -> None: ...

class EOFReader:
    unreader: Any
    buf: six.BytesIO
    finished: Any
    def __init__(self: Any, unreader: Any) -> None: ...
    def read(self: Any, size: Any) -> None: ...

class Body:
    next: Any
    reader: Any
    buf: BytesIO
    def __init__(self: Any, reader: Any, BytesIO: Any = ...) -> None: ...
    def __iter__(self: Any) -> None: ...
    def __next__(self: Any) -> None: ...
    def getsize(self: Any, size: Any) -> None: ...
    def read(self: Any, size: Any = ..., BytesIO: Any = ...) -> None: ...
    def readline(self: Any, size: Any = ..., BytesIO: Any = ...) -> None: ...
    def readlines(self: Any, size: Any = ...) -> None: ...
