from typing import Any


class ParseException(Exception):
    ...

class NoMoreData(IOError):
    def __init__(self: Any, buf: Any = ...) -> None: ...
    def __str__(self: Any) -> None: ...

class InvalidRequestLine(ParseException):
    def __init__(self: Any, req: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class InvalidRequestMethod(ParseException):
    def __init__(self: Any, method: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class InvalidHTTPVersion(ParseException):
    def __init__(self: Any, version: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class InvalidHeader(ParseException):
    def __init__(self: Any, hdr: Any, req: Any = ...) -> None: ...
    def __str__(self: Any) -> None: ...

class InvalidHeaderName(ParseException):
    def __init__(self: Any, hdr: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class InvalidChunkSize(IOError):
    def __init__(self: Any, data: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class ChunkMissingTerminator(IOError):
    def __init__(self: Any, term: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class LimitRequestLine(ParseException):
    def __init__(self: Any, size: Any, max_size: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class LimitRequestHeaders(ParseException):
    def __init__(self: Any, msg: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class InvalidProxyLine(ParseException):
    def __init__(self: Any, line: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class ForbiddenProxyRequest(ParseException):
    def __init__(self: Any, host: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class InvalidSchemeHeaders(ParseException):
    def __str__(self: Any) -> None: ...
