from typing import Any, TYPE_CHECKING



class ParseException(Exception):
    ...

class NoMoreData(IOError):
    buf: Any
    def __init__(self: Any, buf: Any = ...) -> None: ...
    def __str__(self: Any) -> None: ...

class InvalidRequestLine(ParseException):
    req: Any
    code: Any
    def __init__(self: Any, req: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class InvalidRequestMethod(ParseException):
    method: Any
    def __init__(self: Any, method: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class InvalidHTTPVersion(ParseException):
    version: Any
    def __init__(self: Any, version: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class InvalidHeader(ParseException):
    hdr: Any
    req: Any
    def __init__(self: Any, hdr: Any, req: Any = ...) -> None: ...
    def __str__(self: Any) -> None: ...

class InvalidHeaderName(ParseException):
    hdr: Any
    def __init__(self: Any, hdr: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class InvalidChunkSize(IOError):
    data: Any
    def __init__(self: Any, data: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class ChunkMissingTerminator(IOError):
    term: Any
    def __init__(self: Any, term: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class LimitRequestLine(ParseException):
    size: Any
    max_size: Any
    def __init__(self: Any, size: Any, max_size: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class LimitRequestHeaders(ParseException):
    msg: Any
    def __init__(self: Any, msg: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class InvalidProxyLine(ParseException):
    line: Any
    code: Any
    def __init__(self: Any, line: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class ForbiddenProxyRequest(ParseException):
    host: Any
    code: Any
    def __init__(self: Any, host: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class InvalidSchemeHeaders(ParseException):
    def __str__(self: Any) -> None: ...
