from typing import Any

import regex as re
import socket
from errno import ENOTCONN
from zato.server.ext.zunicorn._compat import bytes_to_str
from zato.server.ext.zunicorn.http.unreader import SocketUnreader
from zato.server.ext.zunicorn.http.body import ChunkedReader, LengthReader, EOFReader, Body
from zato.server.ext.zunicorn.http.errors import InvalidHeader, InvalidHeaderName, NoMoreData, InvalidRequestLine, InvalidRequestMethod, InvalidHTTPVersion, LimitRequestLine, LimitRequestHeaders
from zato.server.ext.zunicorn.http.errors import InvalidProxyLine, ForbiddenProxyRequest
from zato.server.ext.zunicorn.http.errors import InvalidSchemeHeaders
from zato.server.ext.zunicorn.six import BytesIO, string_types
from zato.server.ext.zunicorn.util import split_request_uri

class Message:
    def __init__(self: Any, cfg: Any, unreader: Any, MAX_HEADERS: Any = ..., DEFAULT_MAX_HEADERFIELD_SIZE: Any = ...) -> None: ...
    def parse(self: Any, unreader: Any) -> None: ...
    def parse_headers(self: Any, data: Any, bytes_to_str: Any = ...) -> None: ...
    def set_body_reader(self: Any) -> None: ...
    def should_close(self: Any) -> None: ...

class Request(Message):
    def __init__(self: Any, cfg: Any, unreader: Any, req_number: Any = ...) -> None: ...
    def get_data(self: Any, unreader: Any, buf: Any, stop: Any = ..., NoMoreData: Any = ...) -> None: ...
    def parse(self: Any, unreader: Any, BytesIO: Any = ...) -> None: ...
    def read_line(self: Any, unreader: Any, buf: Any, limit: Any = ...) -> None: ...
    def proxy_protocol(self: Any, line: Any) -> None: ...
    def proxy_protocol_access_check(self: Any) -> None: ...
    def parse_proxy_protocol(self: Any, line: Any) -> None: ...
    def parse_request_line(self: Any, line_bytes: Any, METHOD_RE: Any = ..., VERSION_RE: Any = ..., split_request_uri: Any = ..., bytes_to_str: Any = ...) -> None: ...
    def set_body_reader(self: Any, EOFReader: Any = ..., Body: Any = ..., LengthReader: Any = ...) -> None: ...
