from typing import Any, TYPE_CHECKING

import os
from zato.server.ext.zunicorn import six


class Unreader:
    buf: six.BytesIO
    def __init__(self: Any) -> None: ...
    def chunk(self: Any) -> None: ...
    def read(self: Any, size: Any = ...) -> None: ...
    def unread(self: Any, data: Any) -> None: ...

class SocketUnreader(Unreader):
    sock: Any
    mxchunk: Any
    def __init__(self: Any, sock: Any, max_chunk: Any = ...) -> None: ...
    def chunk(self: Any) -> None: ...

class IterUnreader(Unreader):
    iter: iter
    def __init__(self: Any, iterable: Any) -> None: ...
    def chunk(self: Any) -> None: ...
