from typing import Any

import os
from zato.server.ext.zunicorn import six

class Unreader:
    def __init__(self: Any) -> None: ...
    def chunk(self: Any) -> None: ...
    def read(self: Any, size: Any = ...) -> None: ...
    def unread(self: Any, data: Any) -> None: ...

class SocketUnreader(Unreader):
    def __init__(self: Any, sock: Any, max_chunk: Any = ...) -> None: ...
    def chunk(self: Any) -> None: ...

class IterUnreader(Unreader):
    def __init__(self: Any, iterable: Any) -> None: ...
    def chunk(self: Any) -> None: ...
