from typing import Any

import io
import logging
import os
import regex as re
from zato.server.ext.zunicorn import SERVER_SOFTWARE, util
from zato.server.ext.zunicorn._compat import unquote_to_wsgi_str
from zato.server.ext.zunicorn.http.message import HEADER_RE
from zato.server.ext.zunicorn.http.errors import InvalidHeader, InvalidHeaderName
from zato.server.ext.zunicorn.six import string_types, binary_type, reraise
from os import sendfile
from _sendfile import sendfile

class FileWrapper:
    def __init__(self: Any, filelike: Any, blksize: Any = ...) -> None: ...
    def __getitem__(self: Any, key: Any) -> None: ...

def base_environ(cfg: Any, FileWrapper: Any = ..., SERVER_SOFTWARE: Any = ...) -> None: ...

def default_environ(req: Any, sock: Any, cfg: Any, base_environ: Any = ...) -> None: ...

def proxy_environ(req: Any) -> None: ...

class Response:
    def __init__(self: Any, req: Any, sock: Any, cfg: Any) -> None: ...
    def force_close(self: Any) -> None: ...
    def should_close(self: Any) -> None: ...
    def start_response(self: Any, status: Any, headers: Any, exc_info: Any = ...) -> None: ...
    def process_headers(self: Any, headers: Any, HEADER_RE: Any = ..., HEADER_VALUE_RE: Any = ..., string_types: Any = ..., util_is_hoppish: Any = ...) -> None: ...
    def is_chunked(self: Any) -> None: ...
    def default_headers(self: Any, util_http_date: Any = ...) -> None: ...
    def send_headers(self: Any, util_write: Any = ..., util_to_bytestring: Any = ...) -> None: ...
    def write(self: Any, arg: Any, binary_type: Any = ..., util_write: Any = ...) -> None: ...
    def can_sendfile(self: Any) -> None: ...
    def sendfile(self: Any, respiter: Any) -> None: ...
    def write_file(self: Any, respiter: Any) -> None: ...
    def close(self: Any) -> None: ...

def create(req: Any, sock: Any, client: Any, server: Any, cfg: Any, Response: Any = ..., default_environ: Any = ..., string_types: Any = ..., binary_type: Any = ..., unquote_to_wsgi_str: Any = ..., proxy_environ: Any = ...) -> None: ...
