# -*- coding: utf-8 -*-

"""
Copyright (C) 2026, Zato Source s.r.o. https://zato.io

Licensed under AGPLv3, see LICENSE.txt for terms and conditions.
"""

# stdlib
import os
import re

# requests
import requests

# ################################################################################################################################
# ################################################################################################################################

# Where the public model catalog lives - free, unauthenticated and community-maintained
Models_URL = 'https://models.dev/api.json'

# Where the generated module is written, relative to this script
Output_Path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'zato-common', 'src', 'zato', 'common',
    'llm_models.py')

# Maps each Zato provider to its models.dev catalog key, in the order the providers are published
Provider_To_Catalog_Key = {
    'claude': 'anthropic',
    'openai': 'openai',
    'gemini': 'google',
}

# For each provider, the model families to publish, in display order. Each entry is a regex
# that must match the full models.dev model id - the newest release matching it wins.
# When a provider ships a new top-level family, add one entry here and rerun `make llm-models`.
Provider_Families = {
    'claude': (
        r'^claude-fable-[\d-]+$',
        r'^claude-opus-[\d-]+$',
        r'^claude-sonnet-[\d-]+$',
    ),
    'openai': (
        r'^gpt-[\d.]+-terra$',
        r'^gpt-[\d.]+-sol$',
        r'^gpt-[\d.]+-luna$',
    ),
    'gemini': (
        r'^gemini-[\d.]+-pro$',
        r'^gemini-[\d.]+-flash$',
        r'^gemini-[\d.]+-flash-lite$',
    ),
}

# Redundant brand prefixes stripped from display names, e.g. "Claude Fable 5" becomes "Fable 5" -
# Gemini keeps its brand because names like "2.5 Pro" say nothing on their own.
Name_Prefixes_To_Strip = {
    'claude': 'Claude ',
    'openai': '',
    'gemini': '',
}

# The header of the generated module
Module_Header = '''# -*- coding: utf-8 -*-

"""
Copyright (C) 2026, Zato Source s.r.o. https://zato.io

Licensed under AGPLv3, see LICENSE.txt for terms and conditions.
"""

# Generated by `make llm-models` - do not edit by hand.

model_list = [
'''

# The footer of the generated module
Module_Footer = ']\n'

# ################################################################################################################################
# ################################################################################################################################

def get_newest_in_family(catalog_models:'dict', family_pattern:'str') -> 'dict':
    """ Returns the newest catalog model whose id matches the family pattern.
    """
    matcher = re.compile(family_pattern)
    newest = None

    for model_id, model in catalog_models.items():

        # Only stable, released models of this family qualify
        if not matcher.match(model_id):
            continue

        release_date = model.get('release_date')
        if not release_date:
            continue

        # The newest release in the family wins
        if newest is None or release_date > newest['release_date']:
            newest = {
                'id': model_id,
                'name': model['name'],
                'release_date': release_date,
            }

    if newest is None:
        raise Exception('No model matches family pattern `{}`'.format(family_pattern))

    return newest

# ################################################################################################################################

def build_model_list(catalog:'dict') -> 'list':
    """ Builds the full list of models to publish, providers in their fixed order.
    """
    out = []

    for provider, catalog_key in Provider_To_Catalog_Key.items():

        catalog_models = catalog[catalog_key]['models']
        name_prefix = Name_Prefixes_To_Strip[provider]

        for family_pattern in Provider_Families[provider]:

            newest = get_newest_in_family(catalog_models, family_pattern)

            # Strip the redundant brand prefix so the dashboard shows "Fable 5", not "Claude Fable 5"
            name = newest['name']
            if name_prefix and name.startswith(name_prefix):
                name = name[len(name_prefix):]

            out.append({
                'provider': provider,
                'id': newest['id'],
                'name': name,
                'release_date': newest['release_date'],
            })

    return out

# ################################################################################################################################

def write_module(models:'list') -> 'str':
    """ Writes the generated module and returns its path.
    """
    lines = [Module_Header]

    for model in models:
        lines.append("    {{'provider': '{}', 'id': '{}', 'name': '{}'}},\n".format(
            model['provider'], model['id'], model['name']))

    lines.append(Module_Footer)

    output_path = os.path.normpath(Output_Path)
    with open(output_path, 'w') as f:
        _ = f.write(''.join(lines))

    return output_path

# ################################################################################################################################

def main() -> 'None':

    # Download the current catalog ..
    response = requests.get(Models_URL)
    response.raise_for_status()
    catalog = response.json()

    # .. pick the newest release of each configured family ..
    models = build_model_list(catalog)

    # .. show what was chosen ..
    for model in models:
        print('{:8} {} -> {} ({})'.format(model['provider'], model['name'], model['id'], model['release_date']))

    # .. and write out the generated module.
    output_path = write_module(models)
    print('Written to {}'.format(output_path))

# ################################################################################################################################

if __name__ == '__main__':
    main()

# ################################################################################################################################
# ################################################################################################################################
