from typing import Any, TYPE_CHECKING

import os
from django import template
from django.utils.safestring import mark_safe


def bunchget(obj: Any, args: Any) -> None: ...

def url_replace(request: Any, field: Any, value: Any) -> None: ...

def no_value_indicator(value: Any) -> None: ...

def format_float(value: Any, digits: Any = ...) -> None: ...

def get_item(elems: Any, idx: Any) -> None: ...

def endswith(value: Any, suffix: Any) -> None: ...

def get_os_variable(_ignored: Any, name: Any) -> None: ...

def replace_in_string(item: Any, config: Any) -> None: ...
