from typing import Any, TYPE_CHECKING

import json
import uuid
from http.client import HTTPSConnection, HTTPConnection
from logging import getLogger
from traceback import format_exc
from urllib.parse import urlparse
from zato.common.typing_ import any_, anydict, anylist


class AuthType:
    NoAuth: Any
    APIKey: Any

class MCPClient:
    server_id: Any
    endpoint: Any
    auth_type: Any
    auth_data: Any
    _session_id: Any
    def __init__(self: Any, server_id: str, endpoint: str, auth_type: str = ..., auth_data: anydict | None = ...) -> None: ...
    def get_server_info(self: Any) -> anydict: ...
    def _initialize(self: Any) -> anydict: ...
    def _send_initialized_notification(self: Any) -> None: ...
    def _list_tools(self: Any) -> anylist: ...
    def get_tools(self: Any) -> anylist: ...
    def invoke_tool(self: Any, tool_name: str, arguments: anydict) -> any_: ...
    def _get_auth_headers(self: Any) -> anydict: ...
    def _mcp_request(self: Any, payload: anydict, expect_response: bool = ...) -> anydict: ...
    def _parse_sse_response(self: Any, body: str) -> anydict: ...
