from typing import Any

import os
from datetime import timedelta
from http.client import BAD_REQUEST, OK
from logging import getLogger
from traceback import format_exc
from zato.broker.message_handler import handle_broker_msg
from zato.common.api import PubSub
from zato.common.pubsub.models import PubMessage, PubResponse, StatusResponse, Subscription, Topic
from zato.common.pubsub.util import create_subscription_bindings
from zato.common.util.api import as_bool, new_msg_id, new_sub_key, utcnow
from kombu.transport.pyamqp import Message as KombuMessage
from zato.broker.client import BrokerClient
from zato.common.typing_ import any_, anydictnone, dict_, strdict, strlist, strnone

class ModuleCtx:
    Exchange_Name: Any

class Backend:
    topics: dict_[str, Topic]
    subs_by_topic: topic_subs
    def __init__(self: Any, broker_client: BrokerClient) -> None: ...
    def _add_topic(self: Any, topic_name: str, topic: Topic) -> None: ...
    def _delete_topic(self: Any, topic_name: str) -> Topic: ...
    def _has_topic(self: Any, topic_name: str) -> bool: ...
    def on_broker_msg_PUBSUB_SUBSCRIPTION_CREATE(self: Any, msg: strdict) -> None: ...
    def on_broker_msg_PUBSUB_SUBSCRIPTION_DELETE(self: Any, msg: strdict) -> None: ...
    def on_broker_msg_PUBSUB_TOPIC_DELETE(self: Any, msg: strdict) -> None: ...
    def _on_internal_message_callback(self: Any, body: strdict, msg: KombuMessage, name: str, config: strdict) -> None: ...
    def invoke_service_with_pubsub(self: Any, service: str, request: anydictnone = ..., timeout: int = ..., needs_root_elem: bool = ..., cid: str = ...) -> any_: ...
    def get_sec_name_by_username(self: Any, username: str, username_to_sec_name: dict) -> str: ...
    def create_topic(self: Any, cid: str, source: str, topic_name: str) -> None: ...
    def publish_impl(self: Any, cid: str, topic_name: str, msg: PubMessage, username: str, ext_client_id: strnone = ...) -> PubResponse: ...
    def register_subscription(self: Any, cid: str, topic_name: str) -> StatusResponse: ...
    def unregister_subscription(self: Any, cid: str, topic_name: str) -> StatusResponse: ...
