from typing import Any

from logging import getLogger
from zato.common.api import PubSub
from zato.common.util.api import spawn_greenlet
from zato.common.pubsub.backend.common import Backend, ModuleCtx as CommonModuleCtx
from zato.common.pubsub.consumer import start_public_consumer
from zato.broker.client import BrokerClient
from zato.common.typing_ import callable_, dict_, strdict, strlist
from zato.server.connection.amqp_ import Consumer
from zato.server.base.worker import WorkerStore

class ConsumerBackend(Backend):
    consumers: dict_[str, Consumer]
    def __init__(self: Any, worker_store: WorkerStore, broker_client: BrokerClient) -> None: ...
    def _add_consumer(self: Any, sub_key: str, consumer: Consumer) -> None: ...
    def _remove_consumer(self: Any, sub_key: str) -> None: ...
    def start_public_queue_consumer(self: Any, cid: str, topic_name_list: strlist, sec_name: str, sub_key: str, is_delivery_active: bool, on_msg_callback: callable_) -> None: ...
    def stop_public_queue_consumer(self: Any, cid: str, sub_key: str) -> None: ...
    def on_broker_msg_PUBSUB_SUBSCRIPTION_DELETE(self: Any, cid: str, sub_key: str) -> None: ...
    def on_broker_msg_PUBSUB_SUBSCRIPTION_CREATE(self: Any, msg: strdict) -> None: ...
    def on_broker_msg_PUBSUB_SUBSCRIPTION_EDIT(self: Any, msg: strdict) -> None: ...
    def on_broker_msg_PUBSUB_TOPIC_EDIT(self: Any, msg: strdict) -> None: ...
    def on_broker_msg_PUBSUB_TOPIC_DELETE(self: Any, msg: strdict) -> None: ...
