from typing import Any, TYPE_CHECKING

from logging import getLogger
from zato.common.pubsub.backend.common import Backend
from zato.common.pubsub.consumer import start_internal_consumer
from zato.common.pubsub.matcher import PatternMatcher
from zato.common.util.api import replace_secrets, spawn_greenlet
from zato.broker.client import BrokerClient
from zato.common.typing_ import strdict


class RESTBackend(Backend):
    rest_server: Any
    pattern_matcher: PatternMatcher
    def __init__(self: Any, rest_server: PubSubRESTServer, broker_client: BrokerClient) -> None: ...
    def start_internal_pubusb_subscriber(self: Any, server_type: str) -> None: ...
    def _remove_subscriptions_by_username(self: Any, sec_name: str, cid: str) -> list: ...
    def _remove_subscriptions_by_sub_key(self: Any, sub_key: str) -> list: ...
    def on_broker_msg_SECURITY_BASIC_AUTH_CREATE(self: Any, msg: strdict) -> None: ...
    def on_broker_msg_SECURITY_BASIC_AUTH_EDIT(self: Any, msg: strdict) -> None: ...
    def on_broker_msg_SECURITY_BASIC_AUTH_CHANGE_PASSWORD(self: Any, msg: strdict) -> None: ...
    def on_broker_msg_SECURITY_BASIC_AUTH_DELETE(self: Any, msg: strdict) -> None: ...
    def on_broker_msg_PUBSUB_TOPIC_EDIT(self: Any, msg: strdict) -> None: ...
    def on_broker_msg_PUBSUB_PERMISSION_CREATE(self: Any, msg: strdict) -> None: ...
    def on_broker_msg_PUBSUB_PERMISSION_EDIT(self: Any, msg: strdict) -> None: ...
    def on_broker_msg_PUBSUB_PERMISSION_DELETE(self: Any, msg: strdict) -> None: ...
    def on_broker_msg_PUBSUB_SUBSCRIPTION_EDIT(self: Any, msg: strdict) -> None: ...
    def on_broker_msg_PUBSUB_RELOAD_CONFIG(self: Any, msg: strdict) -> None: ...
