from typing import Any

import imaplib
import logging
from zato.common.ext.imbox.imap import ImapTransport
from zato.common.ext.imbox.messages import Messages
from zato.common.ext.imbox.vendors import GmailMessages, hostname_vendorname_dict, name_authentication_string_dict

class Imbox:
    authentication_error_message: Any
    def __init__(self: Any, hostname: Any, username: Any = ..., password: Any = ..., ssl: Any = ..., port: Any = ..., ssl_context: Any = ..., policy: Any = ..., starttls: Any = ..., vendor: Any = ...) -> None: ...
    def __enter__(self: Any) -> None: ...
    def __exit__(self: Any, type: Any, value: Any, traceback: Any) -> None: ...
    def logout(self: Any) -> None: ...
    def mark_seen(self: Any, uid: Any) -> None: ...
    def mark_flag(self: Any, uid: Any) -> None: ...
    def delete(self: Any, uid: Any) -> None: ...
    def copy(self: Any, uid: Any, destination_folder: Any) -> None: ...
    def move(self: Any, uid: Any, destination_folder: Any) -> None: ...
    def messages(self: Any, **kwargs: Any) -> None: ...
    def folders(self: Any) -> None: ...
