from typing import Any

import logging
from traceback import format_exc
from zato.common.api import MISC, SCHEDULER, ZATO_NONE
from zato.common.broker_message import SCHEDULER as SCHEDULER_MSG
from zato.common.util.api import new_cid, spawn_greenlet
from zato.scheduler.backend import Interval, Job, Scheduler as _Scheduler
from zato.common.util.api import parse_datetime
from zato.broker.client import BrokerClient
from zato.common.typing_ import strdict, strdictnone
from zato.scheduler.server import SchedulerServerConfig
from dateutil.parser import parse as parse_datetime

def _start_date(job_data: Any) -> None: ...

class SchedulerAPI:
    broker_client: BrokerClient
    def __init__(self: Any, config: SchedulerServerConfig = ..., run: bool = ...) -> None: ...
    def serve_forever(self: Any) -> None: ...
    def invoke_service(self: Any, name: str, request: strdictnone = ..., timeout: int = ..., **kwargs: Any) -> strdict: ...
    def on_job_executed(self: Any, ctx: Any, extra_data_format: Any = ...) -> None: ...
    def create_edit(self: Any, action: Any, job_data: Any, **kwargs: Any) -> None: ...
    def create_edit_job(self: Any, id: Any, name: Any, old_name: Any, start_time: Any, job_type: Any, service: Any, is_create: Any = ..., max_repeats: Any = ..., days: Any = ..., hours: Any = ..., minutes: Any = ..., seconds: Any = ..., extra: Any = ..., is_active: Any = ..., **kwargs: Any) -> None: ...
    def create_edit_one_time(self: Any, job_data: Any, is_create: Any = ..., **kwargs: Any) -> None: ...
    def create_one_time(self: Any, job_data: Any, **kwargs: Any) -> None: ...
    def edit_one_time(self: Any, job_data: Any, **kwargs: Any) -> None: ...
    def create_edit_interval_based(self: Any, job_data: Any, is_create: Any = ..., **kwargs: Any) -> None: ...
    def create_interval_based(self: Any, job_data: Any, **kwargs: Any) -> None: ...
    def edit_interval_based(self: Any, job_data: Any, **kwargs: Any) -> None: ...
    def delete(self: Any, job_data: Any, **kwargs: Any) -> None: ...
    def execute(self: Any, job_data: Any) -> None: ...
    def stop(self: Any) -> None: ...
    def filter(self: Any, *ignored: Any) -> None: ...
    def on_broker_msg_SCHEDULER_CREATE(self: Any, msg: Any, *ignored_args: Any) -> None: ...
    def on_broker_msg_SCHEDULER_EDIT(self: Any, msg: Any, *ignored_args: Any) -> None: ...
    def on_broker_msg_SCHEDULER_DELETE(self: Any, msg: Any, *ignored_args: Any) -> None: ...
    def on_broker_msg_SCHEDULER_EXECUTE(self: Any, msg: Any, *ignored_args: Any) -> None: ...
