from typing import Any

import datetime
from logging import getLogger
from traceback import format_exc
from dateutil.rrule import rrule, SECONDLY
from paodate import Delta
from zato.common.ext.future.utils import iterkeys, itervalues
from zato.common.api import SCHEDULER
from zato.common.util.api import make_repr, new_cid, spawn_greenlet
from zato.common.util.scheduler import load_scheduler_jobs_by_api, load_scheduler_jobs_by_odb, add_startup_jobs_to_odb_by_api, add_startup_jobs_to_odb_by_odb
from zato.common.typing_ import stranydict
from zato.scheduler.server import SchedulerServerConfig, SchedulerAPI

class Interval:
    __repr__: Any
    def __init__(self: Any, days: int = ..., hours: int = ..., minutes: int = ..., seconds: int = ..., in_seconds: int = ...) -> None: ...
    def __str__(self: Any) -> None: ...
    def get_in_seconds(self: Any) -> None: ...

class Job:
    def __init__(self: Any, id: Any, name: Any, type: Any, interval: Any, start_time: Any = ..., callback: Any = ..., cb_kwargs: Any = ..., max_repeats: Any = ..., on_max_repeats_reached_cb: Any = ..., is_active: Any = ..., clone_start_time: Any = ..., service: Any = ..., extra: Any = ..., old_name: Any = ...) -> None: ...
    def __str__(self: Any) -> None: ...
    def __hash__(self: Any) -> None: ...
    def __eq__(self: Any, other: Any) -> None: ...
    def __lt__(self: Any, other: Any) -> None: ...
    def clone(self: Any, name: Any = ..., is_active: Any = ...) -> None: ...
    def get_start_time(self: Any, start_time: Any) -> None: ...
    def get_context(self: Any) -> None: ...
    def get_sleep_time(self: Any, now: Any) -> None: ...
    def _spawn(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def main_loop(self: Any) -> None: ...
    def run(self: Any) -> None: ...

class Scheduler:
    def __init__(self: Any, config: SchedulerServerConfig, api: SchedulerAPI) -> None: ...
    def on_max_repeats_reached(self: Any, job: Any) -> None: ...
    def _create(self: Any, job: Any, spawn: Any = ...) -> None: ...
    def create(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def edit(self: Any, job: Any) -> None: ...
    def _unschedule(self: Any, job: Any) -> None: ...
    def _unschedule_stop(self: Any, job: Any, message: Any) -> None: ...
    def unschedule(self: Any, job: Any) -> None: ...
    def unschedule_by_name(self: Any, name: Any) -> None: ...
    def stop_job(self: Any, job: Any) -> None: ...
    def stop(self: Any) -> None: ...
    def sleep(self: Any, value: Any) -> None: ...
    def is_scheduler_active(self: Any) -> bool: ...
    def execute(self: Any, name: Any) -> None: ...
    def on_job_executed(self: Any, ctx: stranydict, unschedule_one_time: bool = ...) -> None: ...
    def _spawn(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def spawn_job(self: Any, job: Any) -> None: ...
    def _init_jobs_by_odb(self: Any) -> None: ...
    def _init_jobs_by_api(self: Any) -> None: ...
    def init_jobs(self: Any) -> None: ...
    def run(self: Any) -> None: ...
