from typing import Any

import socket
import logging
from re import sub
from zato.server.ext.zunicorn.glogging import Logger
from zato.server.ext.zunicorn import six

class Statsd(Logger):
    def __init__(self: Any, cfg: Any) -> None: ...
    def critical(self: Any, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def error(self: Any, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def warning(self: Any, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def exception(self: Any, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def info(self: Any, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def debug(self: Any, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def log(self: Any, lvl: Any, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def access(self: Any, resp: Any, req: Any, environ: Any, request_time: Any) -> None: ...
    def gauge(self: Any, name: Any, value: Any) -> None: ...
    def increment(self: Any, name: Any, value: Any, sampling_rate: Any = ...) -> None: ...
    def decrement(self: Any, name: Any, value: Any, sampling_rate: Any = ...) -> None: ...
    def histogram(self: Any, name: Any, value: Any) -> None: ...
    def _sock_send(self: Any, msg: Any) -> None: ...
