{
 "title": "PubSub Performance Dashboard",
 "tags": [
  "rabbitmq",
  "pubsub"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "RAM Used GB"
    }
   ]
  },
  {
   "title": "Network Receive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m])",
     "legendFormat": "Network Receive"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total[1m])",
     "legendFormat": "Network Transmit"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[1m])",
     "legendFormat": "Disk Read"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[1m])",
     "legendFormat": "Disk Write"
    }
   ]
  },
  {
   "title": "Zato Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "zato_pubsub_memory_bytes", "legendFormat": "Memory Usage" }
   ]
  },
  {
   "title": "Zato GC Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "zato_pubsub_gc_objects", "legendFormat": "GC Objects" }
   ]
  },
  {
   "title": "Zato Context Switches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(zato_pubsub_context_switches_total[1m])",
     "legendFormat": "Context Switches/sec - {{type}}"
    }
   ]
  },
  {
   "title": "Zato GC Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(zato_pubsub_gc_collections_total[1m])",
     "legendFormat": "GC Collections/sec - {{type}}"
    }
   ]
  },
  {
   "title": "HAProxy 5xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_http_responses_total{code=\"5xx\"}",
     "legendFormat": "5xx Responses"
    }
   ]
  },
  {
   "title": "HAProxy 4xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_http_responses_total{code=\"4xx\"}",
     "legendFormat": "4xx Responses"
    }
   ]
  },
  {
   "title": "HAProxy 2xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_http_responses_total{code=\"2xx\"}",
     "legendFormat": "2xx Responses"
    }
   ]
  },
  {
   "title": "HAProxy 3xx Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_http_responses_total{code=\"3xx\"}",
     "legendFormat": "3xx Responses"
    }
   ]
  },
  {
   "title": "GC Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zato_pubsub_gc_objects", "legendFormat": "GC Objects" }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zato_pubsub_context_switches_total[1m])",
     "legendFormat": "Context Switches/sec - {{type}}"
    }
   ]
  },
  {
   "title": "GC Collections Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zato_pubsub_gc_collections_total[1m])",
     "legendFormat": "GC Collections/sec - Gen {{generation}}"
    }
   ]
  },
  {
   "title": "GC Objects by Type (Sample)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, zato_pubsub_gc_objects_by_type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "zato_pubsub_tcp_connections", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "IO Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 80 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "rate(zato_pubsub_io_bytes[1m])", "legendFormat": "{{direction}}" }
   ]
  },
  {
   "title": "Gevent Request Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(zato_pubsub_gevent_request_seconds_sum[1m]) / rate(zato_pubsub_gevent_request_seconds_count[1m])",
     "legendFormat": "Gevent Request Time"
    },
    {
     "expr": "rate(zato_pubsub_gunicorn_request_seconds_sum[1m]) / rate(zato_pubsub_gunicorn_request_seconds_count[1m])",
     "legendFormat": "Gunicorn Request Time"
    }
   ]
  },
  {
   "title": "Socket to WSGI Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 88 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(zato_pubsub_socket_to_wsgi_seconds_sum[1m]) / rate(zato_pubsub_socket_to_wsgi_seconds_count[1m])",
     "legendFormat": "Socket to WSGI Time"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_filesystem_size_bytes", "legendFormat": "Total Disk Space - {{device}}" }
   ]
  },
  {
   "title": "Per Partition Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!=\"tmpfs\"}",
     "legendFormat": "Available - {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype!=\"tmpfs\"} - node_filesystem_avail_bytes{fstype!=\"tmpfs\"}",
     "legendFormat": "Used - {{mountpoint}}"
    }
   ]
  }
 ]
}