{
 "title": "REST API Channels and Outgoing Connections",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "REST channels req/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(zato_http_requests_total[1m])) by (channel_name) > 0, \"channel_name\", \"404 Not Found\", \"channel_name\", \"-\")",
     "legendFormat": "{{channel_name}}"
    }
   ]
  },
  {
   "title": "REST channels response time (s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(zato_http_request_duration_seconds_sum[1m])) by (channel_name) / sum(rate(zato_http_request_duration_seconds_count[1m])) by (channel_name) > 0, \"channel_name\", \"404 Not Found\", \"channel_name\", \"-\")",
     "legendFormat": "{{channel_name}}"
    }
   ]
  },
  {
   "title": "REST channels total requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "label_replace(sum(increase(zato_http_requests_total[$__range])) by (channel_name) > 0, \"channel_name\", \"404 Not Found\", \"channel_name\", \"-\")"
    }
   ]
  },
  {
   "title": "REST outgoing connections req/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zato_outgoing_http_requests_total[1m])) by (connection_name) > 0",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  {
   "title": "REST outgoing connections response time (s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zato_outgoing_http_request_duration_seconds_sum[1m])) by (connection_name) / sum(rate(zato_outgoing_http_request_duration_seconds_count[1m])) by (connection_name) > 0",
     "legendFormat": "{{connection_name}}"
    }
   ]
  },
  {
   "title": "REST outgoing connections total requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(zato_outgoing_http_requests_total[$__range])) by (connection_name) > 0"
    }
   ]
  }
 ]
}