{
 "title": "REST API Channels",
 "tags": [
  "rest",
  "default"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "REST channels req/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(zato_http_requests_total[1m])) by (channel_name) > 0, \"channel_name\", \"404 Not Found\", \"channel_name\", \"-\")",
     "legendFormat": "{{channel_name}}"
    }
   ]
  },
  {
   "title": "REST channels response time (s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(zato_http_request_duration_seconds_sum[1m])) by (channel_name) / sum(rate(zato_http_request_duration_seconds_count[1m])) by (channel_name) > 0, \"channel_name\", \"404 Not Found\", \"channel_name\", \"-\")",
     "legendFormat": "{{channel_name}}"
    }
   ]
  },
  {
   "title": "REST channels total requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(sum(zato_http_requests_total) by (channel_name), \"channel_name\", \"404 Not Found\", \"channel_name\", \"-\")"
    }
   ]
  }
 ]
}