{
 "title": "PubSub Performance",
 "tags": [
  "rabbitmq",
  "pubsub"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Message Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rabbitmq_global_messages_delivered_total{protocol=\"amqp091\",queue_type=~\"rabbit_classic_queue|^$\"}[1m]) or rate(rabbitmq_global_messages_received_confirm_total{protocol=\"amqp091\",queue_type=~\"rabbit_classic_queue|^$\"}[1m])",
     "legendFormat": "Messages/sec"
    }
   ]
  },
  {
   "title": "API req/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_http_requests_total{proxy=\"publish_backend\"}[1m])",
     "legendFormat": "Publish req/s"
    },
    {
     "expr": "rate(haproxy_backend_http_requests_total{proxy=\"pull_backend\"}[1m])",
     "legendFormat": "Pull req/s"
    }
   ]
  },
  {
   "title": "API Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_response_time_average_seconds{proxy=\"publish_backend\"}",
     "legendFormat": "Publish client response time"
    },
    {
     "expr": "haproxy_backend_response_time_average_seconds{proxy=\"pull_backend\"}",
     "legendFormat": "Pull client response time"
    }
   ]
  },
  {
   "title": "Health Check Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_check_duration_seconds{proxy=\"publish_backend\"}",
     "legendFormat": "Publish health check duration"
    },
    {
     "expr": "haproxy_server_check_duration_seconds{proxy=\"pull_backend\"}",
     "legendFormat": "Pull health check duration"
    }
   ]
  },
  {
   "title": "Queue Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queue_messages", "legendFormat": "Messages in Queue: {{queue}}" }
   ]
  },
  {
   "title": "RabbitMQ Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_process_resident_memory_bytes",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "RabbitMQ GC Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rabbitmq_erlang_gc_runs_total[1m])",
     "legendFormat": "GC runs/sec"
    }
   ]
  },
  {
   "title": "RabbitMQ Connection Reductions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rabbitmq_connection_process_reductions_total[1m])",
     "legendFormat": "Connection reductions/sec"
    }
   ]
  },
  {
   "title": "Top CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]) * 100)",
     "legendFormat": "{{mode}} - {{cpu}}"
    }
   ]
  }
 ]
}