{
 "title": "Pub/Sub Performance Details",
 "tags": [
  "rabbitmq",
  "pubsub"
 ],
 "panels": [
  {
   "title": "Message Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(rabbitmq_global_messages_received_confirm_total{protocol=\"amqp091\",queue_type=~\"rabbit_classic_queue|^$\"}[1m]), \"type\", \"Received\", \"\", \"\") or label_replace(rate(rabbitmq_global_messages_delivered_total{protocol=\"amqp091\",queue_type=~\"rabbit_classic_queue|^$\"}[1m]), \"type\", \"Delivered\", \"\", \"\")",
     "legendFormat": "{{type}} messages/sec"
    }
   ]
  },
  {
   "title": "API req/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(haproxy_backend_http_requests_total{proxy=\"publish_backend\"}[1m])",
     "legendFormat": "Publish req/s"
    },
    {
     "expr": "rate(haproxy_backend_http_requests_total{proxy=\"pull_backend\"}[1m])",
     "legendFormat": "Pull req/s"
    }
   ]
  },
  {
   "title": "API Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_response_time_average_seconds{proxy=\"publish_backend\"}",
     "legendFormat": "Publish client response time"
    },
    {
     "expr": "haproxy_backend_response_time_average_seconds{proxy=\"pull_backend\"}",
     "legendFormat": "Pull client response time"
    }
   ]
  },
  {
   "title": "Health Check Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_server_check_duration_seconds{proxy=\"publish_backend\"}",
     "legendFormat": "Publish health check duration"
    },
    {
     "expr": "haproxy_server_check_duration_seconds{proxy=\"pull_backend\"}",
     "legendFormat": "Pull health check duration"
    }
   ]
  },
  {
   "title": "Queue Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queue_messages", "legendFormat": "Messages in Queue: {{queue}}" }
   ]
  },
  {
   "title": "RabbitMQ Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_process_resident_memory_bytes",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "RabbitMQ GC Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rabbitmq_erlang_gc_runs_total[1m])",
     "legendFormat": "GC runs/sec"
    }
   ]
  },
  {
   "title": "Queue Operation Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(zato_pubsub_queue_op_seconds_sum{op=\"add\"}[1m]) / rate(zato_pubsub_queue_op_seconds_count{op=\"add\"}[1m])",
     "legendFormat": "Add to queue time"
    },
    {
     "expr": "rate(zato_pubsub_queue_op_seconds_sum{op=\"get\"}[1m]) / rate(zato_pubsub_queue_op_seconds_count{op=\"get\"}[1m])",
     "legendFormat": "Get from queue time"
    }
   ]
  },
  {
   "title": "Consumer Message Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zato_messages_consumed_total[1m])",
     "legendFormat": "Consumer {{consumer_range}} messages/sec"
    }
   ]
  },
  {
   "title": "Consumer Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(zato_consume_request_duration_seconds_sum[1m]) / rate(zato_consume_request_duration_seconds_count[1m])",
     "legendFormat": "Consumer {{consumer_range}} avg request duration"
    }
   ]
  }
 ]
}