from typing import Any

import ast
import gc
import importlib.util
import inspect
import linecache
import logging
import os
import random
import re
import signal
import threading
import socket
import sys
from ast import literal_eval
from base64 import b64decode
from binascii import hexlify as binascii_hexlify
from contextlib import closing
from copy import deepcopy
from datetime import datetime, timedelta, timezone
from getpass import getuser as getpass_getuser
from glob import glob
from inspect import isfunction, ismethod
from itertools import tee, zip_longest
from io import StringIO
from logging.config import dictConfig
from operator import itemgetter
from os.path import abspath, isabs, join
from pathlib import Path
from pprint import pprint as _pprint, PrettyPrinter
from string import Template
from subprocess import Popen, PIPE
from tempfile import gettempdir
from threading import current_thread
from time import sleep
from traceback import format_exc
from types import ModuleType
from uuid import uuid4
from bunch import Bunch, bunchify
from dateutil.parser import parse as dt_parse
from OpenSSL import crypto
import pytz
import sqlalchemy as sa
from sqlalchemy import orm
from texttable import Texttable
import requests
import yaml
from builtins import bytes
from zato.common.ext.future.utils import iteritems, raise_
from zato.common.py23_.past.builtins import basestring, cmp, reduce, unicode
from six import PY3
from six.moves.urllib.parse import urlparse
from zato.common.py23_ import ifilter, izip
from zato.common.api import CHANNEL, CLI_ARG_SEP, DATA_FORMAT, engine_def, engine_def_sqlite, MISC, Secret_Shadow, SIMPLE_IO, TRACE1, zato_no_op_marker, ZATO_NOT_GIVEN
from zato.common.broker_message import HOT_DEPLOY, SERVICE
from zato.common.const import SECRETS, ServiceConst
from zato.common.crypto.api import CryptoManager
from zato.common.exception import ZatoException
from zato.common.ext.configobj_ import ConfigObj
from zato.common.ext.validate_ import is_boolean, is_integer, VdtTypeError
from zato.common.json_internal import dumps, loads
from zato.common.odb.model import Cluster, HTTPBasicAuth, HTTPSOAP, Server
from zato.common.util.config import enrich_config_from_environment
from zato.common.util.python_ import get_current_stack
from zato.common.util.tcp import get_free_port, is_port_taken, wait_for_zato_ping, wait_until_port_free, wait_until_port_taken
from zato.common.util.eval_ import as_bool, as_list
from zato.common.util.file_system import fs_safe_name, fs_safe_now
from zato.common.util.logging_ import ColorFormatter
from zato.common.util.open_ import open_r, open_w
from zato.common.util.snowflake import new_snowflake
from zato.common.util.time_ import utcnow
from ciso8601 import parse_datetime
from functools import cmp_to_key
from typing import Iterable as iterable
from zato.client import ZatoClient
from zato.common.typing_ import any_, anydict, callable_, dictlist, intlist, listnone, strlist, strlistnone, strnone, strset
from zato.common.const import SECRETS
from logging import getLogger
from zato.common.crypto.api import ServerCryptoManager
from zato.client import get_client_from_server_conf as client_get_client_from_server_conf
import psutil
from tabulate import tabulate
from dateutil.parser import parse as parse_datetime

class ModuleCtx:
    PID_To_Port_Pattern: Any

def is_encrypted(data: str | bytes) -> bool: ...

def is_method(class_: Any, func: Any = ...) -> None: ...

def absjoin(base: Any, path: Any) -> None: ...

def absolutize(path: Any, base: Any = ...) -> None: ...

def current_host() -> None: ...

def current_user(_getpass_getuser: Any = ...) -> None: ...

def pprint(obj: Any) -> None: ...

def get_zato_command() -> None: ...

def object_attrs(_object: Any, ignore_double_underscore: Any, to_avoid_list: Any, sort: Any) -> None: ...

def make_repr(_object: Any, ignore_double_underscore: Any = ..., to_avoid_list: Any = ..., sort: Any = ...) -> None: ...

def to_form(_object: Any) -> None: ...

def _new_cid(prefix: str = ..., needs_machine_id: bool = ...) -> str: ...

def new_cid_server(needs_machine_id: bool = ...) -> str: ...

def new_cid_pubsub() -> str: ...

def new_cid_cli() -> str: ...

def new_cid_scheduler() -> str: ...

def new_cid_broker_client() -> str: ...

def new_msg_id() -> str: ...

def new_sub_key(username: str) -> str: ...

def new_cid_queue_consumer() -> str: ...

def make_cid_public(cid: str) -> str: ...

def get_user_config_name(name: str) -> str: ...

def convert_config_values(config: Bunch) -> Bunch: ...

def _get_config() -> Bunch | ConfigObj: ...

def get_config(repo_location: Any, config_name: Any, bunchified: Any = ..., needs_user_config: Any = ..., crypto_manager: Any = ..., secrets_conf: Any = ..., raise_on_error: Any = ..., log_exception: Any = ..., require_exists: Any = ..., conf_location: Any = ...) -> Bunch | ConfigObj: ...

def get_config_from_file(conf_location: Any, config_name: Any) -> None: ...

def set_up_logging(repo_location: str) -> None: ...

def get_config_from_string(data: Any) -> None: ...

def get_current_user() -> None: ...

def service_name_from_impl(impl_name: Any) -> None: ...

def deployment_info(method: Any, object_: Any, timestamp: Any, fs_location: Any, remote_host: Any = ..., remote_user: Any = ..., should_deploy_in_place: Any = ...) -> None: ...

def get_body_payload(body: Any) -> None: ...

def payload_from_request(json_parser: Any, cid: Any, request: Any, data_format: Any, transport: Any, channel_item: Any = ...) -> None: ...

def splitext(path: Any) -> None: ...

def is_archive_file(name: Any) -> None: ...

def is_python_file(name: Any) -> None: ...

class _DummyLink:
    def __init__(self: Any, url: Any) -> None: ...

class ModuleInfo:
    def __init__(self: Any, file_name: Any, module: Any) -> None: ...

def import_module_from_path(file_name: Any, base_dir: Any = ...) -> None: ...

def visit_py_source(dir_name: Any, order_patterns: Any = ...) -> any_: ...

def _os_remove(path: Any) -> None: ...

def hot_deploy(parallel_server: Any, file_name: Any, path: Any, delete_path: Any = ..., notify: Any = ..., should_deploy_in_place: Any = ...) -> None: ...

def multikeysort(items: Any, columns: Any) -> None: ...

def grouper(n: Any, iterable: Any, fillvalue: Any = ...) -> any_: ...

def pairwise(iterable: Any) -> None: ...

def from_local_to_utc(dt: Any, tz_name: Any, dayfirst: Any = ...) -> None: ...

def from_utc_to_local(dt: Any, tz_name: Any) -> None: ...

def _now(tz: Any) -> None: ...

def now(tz: Any = ...) -> None: ...

def datetime_to_seconds(dt: Any) -> None: ...

def uncamelify(s: Any, separator: Any = ..., elem_func: Any = ...) -> None: ...

def get_component_name(prefix: Any = ...) -> None: ...

def dotted_getattr(o: Any, path: Any) -> None: ...

def hexlify(item: Any, _hexlify: Any = ...) -> None: ...

def validate_input_dict(cid: Any, *validation_info: Any) -> None: ...

class SafePrettyPrinter(PrettyPrinter):
    def format(self: Any, obj: Any, context: Any, maxlevels: Any, level: Any) -> None: ...

def spformat(obj: Any, depth: Any = ...) -> None: ...

def formatvalue(v: Any) -> None: ...

def get_stack(f: Any, with_locals: Any = ...) -> None: ...

def get_threads_traceback(pid: Any) -> None: ...

def get_greenlets_traceback(pid: Any) -> None: ...

def dump_stacks(*ignored: Any) -> None: ...

def register_diag_handlers() -> None: ...

def parse_simple_type(value: any_, convert_bool: bool = ...) -> any_: ...

def parse_literal_dict(value: str) -> str | anydict: ...

def parse_extra_into_dict(lines: str | bytes, convert_bool: bool = ...) -> None: ...

class LoggerWriter:
    def __init__(self: Any, logger: Any, level: Any) -> None: ...
    def write(self: Any, message: Any) -> None: ...

def get_haproxy_agent_pidfile(component_dir: Any) -> None: ...

def store_pidfile(component_dir: Any, pidfile: Any = ...) -> None: ...

def ping_odoo(conn: Any) -> None: ...

def ping_sap(conn: Any) -> None: ...

class StaticConfig(Bunch):
    def __init__(self: Any, base_dir: Any) -> None: ...
    def read_file(self: Any, full_path: Any, file_name: Any) -> None: ...
    def read_directory(self: Any, root_dir: Any) -> None: ...

def get_basic_auth_credentials(auth: Any) -> None: ...

def get_http_json_channel(name: Any, service: Any, cluster: Any, security: Any) -> None: ...

def get_engine(args: Any) -> None: ...

def get_session(engine: Any) -> None: ...

def get_crypto_manager_from_server_config(config: Any, repo_dir: Any) -> None: ...

def get_odb_session_from_server_config(config: Any, cm: Any, odb_password_encrypted: Any) -> None: ...

def get_odb_session_from_component_dir(component_dir: Any, config_file: Any, CryptoManagerClass: Any) -> None: ...

def get_odb_session_from_server_dir(server_dir: Any) -> None: ...

def get_server_client_auth(config: Any, repo_dir: Any, cm: Any, odb_password_encrypted: Any) -> any_: ...

def get_client_from_server_conf(server_dir: Any, require_server: Any = ..., stdin_data: Any = ...) -> ZatoClient: ...

def get_repo_dir_from_component_dir(component_dir: str) -> str: ...

def get_engine_url(args: Any) -> None: ...

def startup_service_payload_from_path(name: Any, value: Any, repo_location: Any) -> None: ...

def invoke_startup_services(source: Any, key: Any, fs_server_config: Any, repo_location: Any, broker_client: Any = ..., service_name: Any = ..., skip_include: Any = ..., worker_store: Any = ...) -> None: ...

def timeouting_popen(command: Any, timeout: Any, timeout_msg: Any, rc_non_zero_msg: Any, common_msg: Any = ...) -> None: ...

def spawn_greenlet(callable: Any, *args: Any, **kwargs: Any) -> None: ...

def get_logger_for_class(class_: Any) -> None: ...

def get_worker_pids_by_parent(parent_pid: int) -> intlist: ...

def get_worker_pids() -> None: ...

def update_bind_port(data: Any, idx: Any) -> None: ...

def start_connectors(worker_store: Any, service_name: Any, data: Any) -> None: ...

def require_tcp_port(address: Any) -> None: ...

def update_apikey_username_to_channel(config: Any) -> None: ...

def get_response_value(response: Any) -> None: ...

def parse_cmd_line_options(argv: Any) -> None: ...

def get_sa_model_columns(model: Any) -> None: ...

def is_func_overridden(func: Any) -> None: ...

def get_sql_engine_display_name(engine: Any, fs_sql_config: Any) -> None: ...

def pretty_format_float(value: Any) -> None: ...

def wait_for_predicate(predicate_func: Any, timeout: Any, interval: Any, log_msg_details: Any = ..., needs_log: Any = ..., *args: Any, **kwargs: Any) -> bool: ...

def wait_for_dict_key_by_get_func(get_key_func: Any, key: Any, timeout: Any = ..., interval: Any = ...) -> any_: ...

def wait_for_dict_key(_dict: Any, key: Any, timeout: Any = ..., interval: Any = ...) -> any_: ...

def wait_for_file(full_path: str, timeout: int = ..., interval: float = ...) -> any_: ...

def wait_for_200_ok(address: Any) -> None: ...

def hex_sequence_to_bytes(elems: Any) -> None: ...

def tabulate_dictlist(data: dictlist, skip_keys: listnone = ...) -> str: ...

def needs_suffix(item: any_) -> bool: ...

def get_new_tmp_full_path(file_name: str = ...) -> str: ...

def get_ipc_pid_port_path(cluster_name: str, server_name: str, pid: int) -> str: ...

def save_ipc_pid_port(cluster_name: str, server_name: str, pid: int, port: int) -> None: ...

def load_ipc_pid_port(cluster_name: str, server_name: str, pid: int) -> int: ...

def make_list_from_string_list(value: str, separator: str) -> strlist: ...

def validate_python_syntax(data: str) -> None: ...

class _DemoPyFsLocations:
    pickup_incoming_full_path: str
    work_dir_full_path: str

def get_demo_py_fs_locations(base_dir: str) -> _DemoPyFsLocations: ...

def find_internal_modules(root: ModuleType) -> strlist: ...

def publish_file(broker_client: Any, cid: str, file_path: str) -> dict: ...

def publish_enmasse(broker_client: Any, cid: str, file_path: str) -> dict: ...

def publish_user_conf(broker_client: Any, cid: str, file_path: str) -> dict: ...

def get_absolute_path(base_dir: str, relative_path: str) -> str: ...

def replace_secrets(data: any_) -> strdict: ...

def rebuild_subscription_dict_list(subscription_list: Any) -> None: ...
