from typing import Any, TYPE_CHECKING

import os
from logging import getLogger
from pathlib import Path
from traceback import format_exc
from urllib.parse import parse_qsl, urlparse, urlunparse
from bunch import Bunch
from parse import PARSE_RE as parse_re
from zato.common.api import EnvConfigCtx, EnvVariable, SCHEDULER, Secret_Shadow, URLInfo
from zato.common.const import SECRETS
from zato.common.ext.configobj_ import ConfigObj
from zato.common.util.tcp import get_current_ip
from zato.common.crypto.api import CryptoManager
from zato.common.typing_ import any_, strdict
from zato.server.base.parallel import ParallelServer
from io import StringIO
from zato.common.util import get_config


def get_url_protocol_from_config_item(use_tls: bool) -> str: ...

def get_scheduler_api_client_for_server_auth_required(args: any_) -> str: ...

def get_scheduler_api_client_for_server_username(args: any_) -> str: ...

def get_scheduler_api_client_for_server_password(args: any_, cm: CryptoManager) -> str: ...

def make_name_env_compatible(name: str) -> str: ...

def get_env_config_ctx(file_path: str | any_) -> EnvConfigCtx: ...

def enrich_config_from_environment(file_name: str, config: Bunch) -> Bunch: ...

def get_env_config_value(component: str, file_name: str, stanza: str, key: str, use_default: bool = ...) -> str: ...

def resolve_name(name: str) -> str: ...

def resolve_value(key: Any, value: Any, decrypt_func: Any = ..., _default: Any = ..., _secrets: Any = ...) -> None: ...

def resolve_env_variables(data: Any) -> None: ...

def _replace_query_string_items(server: ParallelServer, data: any_) -> str: ...

def replace_query_string_items(server: ParallelServer, data: any_) -> str: ...

def replace_query_string_items_in_dict(server: ParallelServer, data: strdict) -> None: ...

def extract_param_placeholders(data: str) -> any_: ...

def get_config_object(repo_location: str, conf_file: str) -> Bunch | ConfigObj: ...

def update_config_file(config: ConfigObj, repo_location: str, conf_file: str) -> None: ...

def parse_url_address(address: str, default_port: int) -> URLInfo: ...
