from typing import Any

from collections.abc import MutableMapping
from time import time
from sortedcontainers import SortedKeyList

class ExpiringDict(MutableMapping):
    _store: dict
    _keys: SortedKeyList
    _ttl: Any
    impl_lock: Lock
    _interval: Any
    def __init__(self: Any, ttl: Any = ..., interval: Any = ..., *args: Any, **kwargs: Any) -> None: ...
    def _sort_func(self: Any, elem: Any) -> None: ...
    def flush(self: Any) -> None: ...
    def _worker(self: Any) -> None: ...
    def get(self: Any, key: Any, default: Any = ...) -> None: ...
    def set(self: Any, key: Any, value: Any, ttl: Any = ...) -> None: ...
    def ttl(self: Any, key: Any, value: Any, ttl: Any) -> None: ...
    def delete(self: Any, key: Any) -> None: ...
    def _set_with_expire(self: Any, key: Any, value: Any, ttl: Any) -> None: ...
    def __iter__(self: Any) -> None: ...
    def __len__(self: Any) -> None: ...
    def __delitem__(self: Any, *ignored_args: Any, **ignored_kwargs: Any) -> None: ...
    def __getitem__(self: Any, *ignored_args: Any, **ignored_kwargs: Any) -> None: ...
    def __setitem__(self: Any, *ignored_args: Any, **ignored_kwargs: Any) -> None: ...
