from typing import Any

import copy
from collections.abc import Mapping
from io import BytesIO
from urllib.parse import parse_qsl, quote, urlencode
from multipart import parse_form_data
from zato.common.typing_ import any_, stranydict

def get_proxy_config(config: Any) -> None: ...

def get_form_data(wsgi_environ: stranydict, as_dict: bool = ...) -> stranydict: ...

def bytes_to_text(s: Any, encoding: Any) -> None: ...

class MultiValueDict(dict):
    def __init__(self: Any, key_to_list_mapping: Any = ...) -> None: ...
    def __repr__(self: Any) -> None: ...
    def __getitem__(self: Any, key: Any) -> None: ...
    def __setitem__(self: Any, key: Any, value: Any) -> None: ...
    def __copy__(self: Any) -> None: ...
    def __deepcopy__(self: Any, memo: Any) -> None: ...
    def __getstate__(self: Any) -> None: ...
    def __setstate__(self: Any, obj_dict: Any) -> None: ...
    def get(self: Any, key: Any, default: Any = ...) -> None: ...
    def _getlist(self: Any, key: Any, default: Any = ..., force_list: Any = ...) -> None: ...
    def getlist(self: Any, key: Any, default: Any = ...) -> None: ...
    def setlist(self: Any, key: Any, list_: Any) -> None: ...
    def setdefault(self: Any, key: Any, default: Any = ...) -> None: ...
    def setlistdefault(self: Any, key: Any, default_list: Any = ...) -> None: ...
    def appendlist(self: Any, key: Any, value: Any) -> None: ...
    def items(self: Any) -> None: ...
    def lists(self: Any) -> None: ...
    def values(self: Any) -> None: ...
    def copy(self: Any) -> None: ...
    def update(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def dict(self: Any) -> None: ...

class QueryDict(MultiValueDict):
    _mutable: Any
    _encoding: Any
    encoding: Any
    _mutable: Any
    def __init__(self: Any, query_string: Any = ..., mutable: Any = ..., encoding: Any = ...) -> None: ...
    @classmethod
    def fromkeys(cls: Any, iterable: Any, value: Any = ..., mutable: Any = ..., encoding: Any = ...) -> None: ...
    @property
    def encoding(self: Any) -> None: ...
    def encoding(self: Any, value: Any) -> None: ...
    def _assert_mutable(self: Any) -> None: ...
    def __setitem__(self: Any, key: Any, value: Any) -> None: ...
    def __delitem__(self: Any, key: Any) -> None: ...
    def __copy__(self: Any) -> None: ...
    def __deepcopy__(self: Any, memo: Any) -> None: ...
    def setlist(self: Any, key: Any, list_: Any) -> None: ...
    def setlistdefault(self: Any, key: Any, default_list: Any = ...) -> None: ...
    def appendlist(self: Any, key: Any, value: Any) -> None: ...
    def pop(self: Any, key: Any, *args: Any) -> None: ...
    def popitem(self: Any) -> None: ...
    def clear(self: Any) -> None: ...
    def setdefault(self: Any, key: Any, default: Any = ...) -> None: ...
    def copy(self: Any) -> None: ...
    def urlencode(self: Any, safe: Any = ...) -> None: ...
