from typing import Any

from zato.common.typing_ import binaryio_, iobytes_, textio_

def open_r(path: str, encoding: str = ...) -> textio_: ...

def open_rb(path: str) -> binaryio_: ...

def open_rw(path: str, encoding: str = ...) -> textio_: ...

def open_w(path: str, encoding: str = ...) -> textio_: ...

def open_wb(path: str) -> iobytes_: ...
