from typing import Any, TYPE_CHECKING



class SortedDict(dict):
    def __iter__(self: Any) -> None: ...
    def items(self: Any) -> None: ...
    def keys(self: Any) -> None: ...
    def values(self: Any) -> None: ...
