from typing import Any, TYPE_CHECKING

from datetime import datetime, timedelta, timezone
from time import time, time_ns
import logging
import arrow
from tzlocal import get_localzone
from zato.common.py23_.past.builtins import unicode
from zato.common.typing_ import any_

utcnow = utc_now

class ModuleCtx:
    Date_Format: Any
    Date_Time_Format: Any
    Timestamp_Format: Any

def utc_now() -> None: ...

def native_to_utc(dt: Any) -> None: ...

def datetime_to_ms(dt: Any) -> None: ...

def datetime_to_sec(dt: Any) -> None: ...

def utcnow_as_ms(_time: Any = ...) -> None: ...

def utcnow_from_ns() -> None: ...

def datetime_from_ms(ms: float, isoformat: bool = ...) -> str | datetime: ...

class TimeUtil:
    def now(self: Any, format: Any = ..., tz: Any = ..., needs_format: Any = ..., delta: Any = ...) -> str | datetime: ...
    def _time_from(self: Any, value: Any, delta: Any, format: Any, needs_format: Any) -> None: ...
    def one_day_from(self: Any, date: Any, format: Any = ..., needs_format: Any = ...) -> None: ...
    def one_hour_from(self: Any, date: Any, format: Any = ..., needs_format: Any = ...) -> None: ...
    def one_minute_from(self: Any, date: Any, format: Any = ..., needs_format: Any = ...) -> None: ...
    def yesterday(self: Any, format: Any = ..., tz: Any = ..., needs_format: Any = ...) -> None: ...
    def tomorrow(self: Any, format: Any = ..., tz: Any = ..., needs_format: Any = ...) -> None: ...
    def utcnow(self: Any, format: Any = ..., needs_format: Any = ...) -> any_: ...
    def utcnow_as_float(self: Any, format: Any = ..., needs_format: Any = ...) -> any_: ...
    def today(self: Any, format: Any = ..., tz: Any = ..., needs_format: Any = ...) -> None: ...
    def isonow(self: Any, tz: Any = ..., needs_format: Any = ..., _format: Any = ...) -> None: ...
    def isoutcnow(self: Any, needs_format: Any = ..., _format: Any = ...) -> None: ...
    def reformat(self: Any, value: Any, from_: Any, to: Any) -> None: ...
