from typing import Any

import os
import shutil
import subprocess
import tempfile
import time
from datetime import datetime, timezone
from logging import getLogger, Formatter, DEBUG
from logging.handlers import RotatingFileHandler
from traceback import format_exc
from urllib.error import HTTPError
from urllib.request import Request, urlopen
import humanize
from zato.common.json_internal import dumps, loads
from zato.common.util.tcp import wait_until_port_free
from zato.common.typing_ import listnone, strnone
import redis as redis_module
from zoneinfo import ZoneInfo
import calendar
import getpass

def setup_update_file_logger(base_dir: strnone = ..., component_name: str = ...) -> None: ...

class UpdaterConfig:
    redis_host: Any
    redis_port: Any
    redis_db: Any
    current_dir: Any
    base_dir: Any
    zato_path: Any
    github_repo: Any
    github_branch: Any
    default_version: Any
    audit_log_key: Any
    schedule_key: Any
    lock_key: Any
    lock_timeout: Any
    audit_log_max_entries: Any
    def __init__(self: Any) -> None: ...

class Updater:
    config: Any
    def __init__(self: Any, config: UpdaterConfig) -> None: ...
    def _setup_update_logger(self: Any) -> None: ...
    def get_component_path(self: Any, component_name: str) -> str: ...
    def restart_auxiliary_processes(self: Any) -> dict: ...
    def restart_auxiliary_process(self: Any, process_name: str, script_path: str, args: listnone = ...) -> dict: ...
    def get_component_port(self: Any, component_name: str) -> int: ...
    def get_redis_connection(self: Any) -> None: ...
    def add_audit_log_entry(self: Any, update_type: str, version_from: str, version_to: str, start_time: datetime, end_time: datetime) -> None: ...
    def get_audit_log_entries(self: Any, count: int = ...) -> list: ...
    def find_file_in_parents(self: Any, target_path: str) -> strnone: ...
    def get_zato_version(self: Any) -> str: ...
    def run_command(self: Any, command: list, cwd: strnone = ..., timeout: int = ..., log_prefix: str = ...) -> dict: ...
    def get_changed_files(self: Any) -> list: ...
    def has_directory_changes(self: Any, changed_files: list, directory: str) -> bool: ...
    def download_and_install(self: Any, update_script_name: str = ..., update_type: str = ..., schedule: strnone = ..., exclude_from_restart: listnone = ...) -> dict: ...
    def check_latest_version(self: Any) -> dict: ...
    def save_schedule(self: Any, schedule_data: dict) -> dict: ...
    def load_schedule(self: Any) -> dict: ...
    def delete_schedule(self: Any) -> dict: ...
    def acquire_lock(self: Any) -> bool: ...
    def release_lock(self: Any) -> None: ...
    def _get_last_update_time(self: Any) -> datetime | None: ...
    def _set_last_update_time(self: Any) -> None: ...
    def _get_min_interval_minutes(self: Any, frequency: str) -> int: ...
    def should_run_scheduled_update(self: Any) -> bool: ...
    def kill_process_by_port(self: Any, port: int) -> bool: ...
    def kill_orphaned_processes(self: Any, component_name: str) -> None: ...
    def stop_component(self: Any, component_name: str, component_path: str, port: int = ...) -> dict: ...
    def _stop_proxy_component(self: Any) -> dict: ...
    def stop_pubsub_component(self: Any, component_name: str) -> dict: ...
    def start_pubsub_component(self: Any, component_name: str) -> dict: ...
    def start_component(self: Any, component_name: str, component_path: str) -> dict: ...
    def _start_proxy_component(self: Any) -> dict: ...
    def get_stored_changed_files(self: Any) -> list: ...
    def restart_component(self: Any, component_name: str, component_path: str, port: int = ..., check_changes: bool = ...) -> dict: ...
    def restart_all_components(self: Any, exclude_components: listnone = ..., changed_files: listnone = ...) -> dict: ...
