from typing import Any

import logging
from zato.cli.enmasse.util import preprocess_item
from zato.common.odb.model import CacheBuiltin, Cluster, to_json
from zato.common.odb.query import cache_builtin_list
from zato.common.util.sql import set_instance_opaque_attrs
from sqlalchemy.orm.session import Session as SASession
from zato.cli.enmasse.importer import EnmasseYAMLImporter
from zato.common.typing_ import any_, anydict, anylist, listtuple

class CacheImporter:
    def __init__(self: Any, importer: EnmasseYAMLImporter) -> None: ...
    def _process_cache_defs(self: Any, query_result: any_, cache_type: str, out: dict) -> None: ...
    def get_cache_defs_from_db(self: Any, session: SASession, cluster_id: int) -> anydict: ...
    def compare_cache_defs(self: Any, yaml_defs: anylist, db_defs: anydict) -> tuple: ...
    def _create_builtin_cache(self: Any, cache_def: anydict, cluster: any_) -> any_: ...
    def create_cache_definition(self: Any, cache_def: anydict, session: SASession) -> any_: ...
    def update_cache_definition(self: Any, cache_def: anydict, session: SASession) -> any_: ...
    def sync_cache_definitions(self: Any, cache_list: anylist, session: SASession) -> listtuple: ...
