from typing import Any, TYPE_CHECKING

import logging
from zato.cli.enmasse.util import preprocess_item
from zato.common.api import CONNECTION, GENERIC, URL_TYPE
from zato.common.odb.model import GenericConn, HTTPSOAP, to_json
from zato.common.odb.query.generic import connection_list
from zato.common.util.sql import set_instance_opaque_attrs
from sqlalchemy.orm.session import Session as SASession
from zato.cli.enmasse.importer import EnmasseYAMLImporter
from zato.common.typing_ import any_, anydict, anylist, listtuple


class ChannelOpenAPIImporter:
    connection_type: Any
    connection_defaults: Any
    importer: Any
    channel_openapi_defs: Any
    def __init__(self: Any, importer: EnmasseYAMLImporter) -> None: ...
    def _process_defs(self: Any, query_result: any_, out: dict) -> None: ...
    def get_defs_from_db(self: Any, session: SASession, cluster_id: int) -> anydict: ...
    def _get_rest_channels_map(self: Any, session: SASession, cluster_id: int) -> dict: ...
    def compare_defs(self: Any, yaml_defs: anylist, db_defs: anydict) -> tuple: ...
    def create_definition(self: Any, channel_def: anydict, session: SASession, rest_channels_map: dict) -> any_: ...
    def update_definition(self: Any, channel_def: anydict, session: SASession, rest_channels_map: dict) -> any_: ...
    def sync_channel_openapi(self: Any, channel_list: anylist, session: SASession) -> listtuple: ...
