from typing import Any, TYPE_CHECKING

from json import loads
import logging
from zato.cli.enmasse.util import preprocess_item, security_needs_update
from zato.common.api import CONNECTION, URL_TYPE
from zato.common.odb.model import HTTPSOAP, Service, to_json
from zato.common.util.sql import get_security_by_id, set_instance_opaque_attrs
from sqlalchemy.orm.session import Session as SASession
from zato.cli.enmasse.importer import EnmasseYAMLImporter
from zato.common.typing_ import any_, anydict, anylist, listtuple


class ChannelImporter:
    importer: Any
    def __init__(self: Any, importer: EnmasseYAMLImporter) -> None: ...
    def get_rest_channels_from_db(self: Any, session: SASession, cluster_id: int) -> anydict: ...
    def compare_channel_rest(self: Any, yaml_defs: anylist, db_defs: anydict) -> listtuple: ...
    def _groups_need_update(self: Any, item: anydict, db_def: anydict) -> bool: ...
    def _gateway_service_list_needs_update(self: Any, item: anydict, db_def: anydict) -> bool: ...
    def _preprocess_security_groups(self: Any, channel_def: anydict) -> list: ...
    def create_channel_rest(self: Any, channel_def: anydict, session: SASession) -> any_: ...
    def update_channel_rest(self: Any, channel_def: anydict, session: SASession) -> any_: ...
    def sync_channel_rest(self: Any, channel_list: anylist, session: SASession) -> listtuple: ...
