from typing import Any

import logging
from uuid import uuid4
from zato.cli.enmasse.util import preprocess_item
from zato.common.odb.model import SMTP, to_json
from zato.common.odb.query import email_smtp_list
from zato.common.util.sql import set_instance_opaque_attrs
from sqlalchemy.orm.session import Session as SASession
from zato.cli.enmasse.importer import EnmasseYAMLImporter
from zato.common.typing_ import any_, anydict, anylist, listtuple

class SMTPImporter:
    importer: Any
    smtp_defs: Any
    def __init__(self: Any, importer: EnmasseYAMLImporter) -> None: ...
    def _process_smtp_defs(self: Any, query_result: any_, out: dict) -> None: ...
    def get_smtp_defs_from_db(self: Any, session: SASession, cluster_id: int) -> anydict: ...
    def compare_smtp_defs(self: Any, yaml_defs: anylist, db_defs: anydict) -> tuple: ...
    def create_smtp_definition(self: Any, smtp_def: anydict, session: SASession) -> any_: ...
    def update_smtp_definition(self: Any, smtp_def: anydict, session: SASession) -> any_: ...
    def sync_smtp_definitions(self: Any, smtp_list: anylist, session: SASession) -> listtuple: ...
