from typing import Any

import logging
from zato.cli.enmasse.util import preprocess_item
from zato.common.odb.model import ElasticSearch, to_json
from zato.common.odb.query import search_es_list
from zato.common.util.sql import set_instance_opaque_attrs
from sqlalchemy.orm.session import Session as SASession
from zato.cli.enmasse.importer import EnmasseYAMLImporter
from zato.common.typing_ import any_, anydict, anylist, listtuple

class ElasticSearchImporter:
    importer: Any
    es_defs: Any
    def __init__(self: Any, importer: EnmasseYAMLImporter) -> None: ...
    def _process_es_defs(self: Any, query_result: any_, out: dict) -> None: ...
    def get_es_defs_from_db(self: Any, session: SASession, cluster_id: int) -> anydict: ...
    def compare_es_defs(self: Any, yaml_defs: anylist, db_defs: anydict) -> tuple: ...
    def _process_host_field(self: Any, es_def: anydict) -> anydict: ...
    def create_es_definition(self: Any, es_def: anydict, session: SASession) -> any_: ...
    def update_es_definition(self: Any, es_def: anydict, session: SASession) -> any_: ...
    def sync_es_definitions(self: Any, es_list: anylist, session: SASession) -> listtuple: ...
