from typing import Any

import logging
from zato.common.api import PubSub
from zato.common.odb.model import PubSubPermission, SecurityBase
from zato.common.odb.query import pubsub_permission_list
from zato.common.util.sql import set_instance_opaque_attrs
from zato.common.typing_ import any_, anydict, stranydict
from sqlalchemy.orm.session import Session as SASession

class PubSubPermissionImporter:
    def __init__(self: Any, importer: any_) -> None: ...
    def _process_pubsub_permission_defs(self: Any, query_result: any_, out: dict) -> None: ...
    def get_pubsub_permission_defs_from_db(self: Any, session: SASession, cluster_id: int) -> anydict: ...
    def create_pubsub_permission_definition(self: Any, definition: stranydict, session: SASession) -> PubSubPermission: ...
    def update_pubsub_permission_definition(self: Any, definition: stranydict, session: SASession) -> PubSubPermission: ...
    def should_create_pubsub_permission_definition(self: Any, yaml_def: stranydict, db_defs: anydict) -> bool: ...
    def should_update_pubsub_permission_definition(self: Any, yaml_def: stranydict, db_def: stranydict) -> bool: ...
    def get_security_base_id_by_name(self: Any, security_name: str, session: SASession) -> int: ...
    def sync_pubsub_permission_definitions(self: Any, permission_list: list, session: SASession) -> tuple: ...
