from typing import Any

import logging
from zato.common.api import PubSub
from zato.common.odb.model import PubSubSubscription, PubSubSubscriptionTopic, PubSubTopic, SecurityBase, HTTPSOAP
from zato.common.util.api import new_sub_key
from zato.common.util.sql import set_instance_opaque_attrs
from zato.common.typing_ import any_, anydict, stranydict
from sqlalchemy.orm.session import Session as SASession

class PubSubSubscriptionImporter:
    importer: Any
    pubsub_subscription_defs: Any
    def __init__(self: Any, importer: any_) -> None: ...
    def _process_pubsub_subscription_defs(self: Any, query_result: any_, out: dict) -> None: ...
    def get_pubsub_subscription_defs_from_db(self: Any, session: SASession, cluster_id: int) -> anydict: ...
    def create_pubsub_subscription_definition(self: Any, definition: stranydict, session: SASession) -> PubSubSubscription: ...
    def update_pubsub_subscription_definition(self: Any, definition: stranydict, session: SASession) -> PubSubSubscription: ...
    def find_existing_subscription_for_security(self: Any, db_defs: anydict, sec_base_id: int) -> stranydict: ...
    def should_create_pubsub_subscription_definition(self: Any, yaml_def: stranydict, db_defs: anydict, sec_base_id: int) -> bool: ...
    def should_update_pubsub_subscription_definition(self: Any, yaml_def: stranydict, db_def: stranydict) -> bool: ...
    def get_security_base_id_by_name(self: Any, security_name: str, session: SASession) -> int: ...
    def get_topic_id_by_name(self: Any, topic_name: str, session: SASession) -> int: ...
    def get_rest_endpoint_id_by_name(self: Any, endpoint_name: str, session: SASession) -> int: ...
    def sync_pubsub_subscription_definitions(self: Any, subscription_list: list, session: SASession) -> tuple: ...
