from typing import Any, TYPE_CHECKING

import logging
from zato.common.odb.model import PubSubTopic, to_json
from zato.common.odb.query import pubsub_topic_list
from zato.common.util.sql import set_instance_opaque_attrs
from zato.common.typing_ import any_, anydict, stranydict
from sqlalchemy.orm.session import Session as SASession


class PubSubTopicImporter:
    importer: Any
    pubsub_topic_defs: Any
    def __init__(self: Any, importer: any_) -> None: ...
    def _process_pubsub_topic_defs(self: Any, query_result: any_, out: dict) -> None: ...
    def get_pubsub_topic_defs_from_db(self: Any, session: SASession, cluster_id: int) -> anydict: ...
    def create_pubsub_topic_definition(self: Any, definition: stranydict, session: SASession) -> PubSubTopic: ...
    def update_pubsub_topic_definition(self: Any, definition: stranydict, session: SASession) -> PubSubTopic: ...
    def should_create_pubsub_topic_definition(self: Any, yaml_def: stranydict, db_defs: anydict) -> bool: ...
    def should_update_pubsub_topic_definition(self: Any, yaml_def: stranydict, db_def: stranydict) -> bool: ...
    def sync_pubsub_topic_definitions(self: Any, topic_list: list, session: SASession) -> tuple: ...
