from typing import Any

import logging
from datetime import datetime, timedelta, timezone
from zato.cli.enmasse.util import preprocess_item
from zato.common.odb.model import Job, IntervalBasedJob, Service, to_json
from zato.common.odb.query import job_list
from zato.common.util.api import parse_datetime
from zato.common.util.sql import set_instance_opaque_attrs
from sqlalchemy.orm.session import Session as SASession
from zato.cli.enmasse.importer import EnmasseYAMLImporter
from zato.common.typing_ import any_, anydict, anylist, listtuple

def compute_next_start_date(start_date: Any, job_def: Any) -> None: ...

class SchedulerImporter:
    def __init__(self: Any, importer: EnmasseYAMLImporter) -> None: ...
    def _process_job_defs(self: Any, query_result: any_, out: dict) -> None: ...
    def get_job_defs_from_db(self: Any, session: SASession, cluster_id: int) -> anydict: ...
    def compare_job_defs(self: Any, yaml_defs: anylist, db_defs: anydict) -> tuple: ...
    def create_job_definition(self: Any, job_def: anydict, session: SASession) -> any_: ...
    def update_job_definition(self: Any, job_def: anydict, session: SASession) -> any_: ...
    def sync_job_definitions(self: Any, job_list: anylist, session: SASession) -> listtuple: ...
