from typing import Any

import logging
from uuid import uuid4
from zato.cli.enmasse.util import preprocess_item
from zato.common.odb.model import HTTPBasicAuth, APIKeySecurity, NTLM, OAuth, to_json
from zato.common.odb.query import basic_auth_list, apikey_security_list, ntlm_list, oauth_list
from zato.common.util.sql import set_instance_opaque_attrs
from sqlalchemy.orm.session import Session as SASession
from zato.cli.enmasse.importer import EnmasseYAMLImporter
from zato.common.typing_ import any_, anydict, anylist, listtuple
from zato.common.json_internal import loads

class SecurityImporter:
    importer: Any
    def __init__(self: Any, importer: EnmasseYAMLImporter) -> None: ...
    def _process_security_defs(self: Any, query_result: any_, sec_type: str, out: dict) -> None: ...
    def get_security_defs_from_db(self: Any, session: SASession, cluster_id: int) -> anydict: ...
    def compare_security_defs(self: Any, yaml_defs: anylist, db_defs: anydict) -> listtuple: ...
    def _create_basic_auth(self: Any, security_def: anydict, cluster: any_) -> any_: ...
    def _create_apikey(self: Any, security_def: anydict, cluster: any_) -> any_: ...
    def _create_ntlm(self: Any, security_def: anydict, cluster: any_) -> any_: ...
    def _create_bearer_token(self: Any, security_def: anydict, cluster: any_) -> any_: ...
    def create_security_definition(self: Any, security_def: anydict, session: SASession) -> any_: ...
    def _update_definition(self: Any, definition: any_, security_def: anydict) -> any_: ...
    def get_class_by_type(self: Any, sec_type: Any) -> None: ...
    def update_security_definition(self: Any, sec_def: anydict, session: SASession, db_defs: anydict) -> any_: ...
    def sync_security_definitions(self: Any, security_list: anylist, session: SASession) -> listtuple: ...
