from typing import Any

import logging
from uuid import uuid4
from zato.cli.enmasse.util import get_engine_from_type, preprocess_item
from zato.common.odb.model import SQLConnectionPool, to_json
from zato.common.odb.query import out_sql_list
from zato.common.util.sql import set_instance_opaque_attrs
from sqlalchemy.orm.session import Session as SASession
from zato.cli.enmasse.importer import EnmasseYAMLImporter
from zato.common.typing_ import any_, anydict, anylist, listtuple

class SQLImporter:
    importer: Any
    sql_defs: Any
    def __init__(self: Any, importer: EnmasseYAMLImporter) -> None: ...
    def _process_sql_defs(self: Any, query_result: any_, out: dict) -> None: ...
    def get_sql_defs_from_db(self: Any, session: SASession, cluster_id: int) -> anydict: ...
    def compare_sql_defs(self: Any, yaml_defs: anylist, db_defs: anydict) -> tuple: ...
    def create_sql_definition(self: Any, sql_def: anydict, session: SASession) -> any_: ...
    def update_sql_definition(self: Any, sql_def: anydict, session: SASession) -> any_: ...
    def sync_sql_definitions(self: Any, sql_list: anylist, session: SASession) -> listtuple: ...
