# -*- coding: utf-8 -*-

"""
Copyright (C) 2026, Zato Source s.r.o. https://zato.io

Licensed under AGPLv3, see LICENSE.txt for terms and conditions.
"""

# Type stubs for the zato_fhir_r4_0_1_core Rust extension.

# stdlib
from typing import Any

# ################################################################################################################################
# ################################################################################################################################

class ValidationError:

    path: str
    code: str
    message: str

    def __init__(self, path: str, code: str, message: str) -> None: ...

# ################################################################################################################################
# ################################################################################################################################

class ValidationResult:

    errors: list[ValidationError]

    @property
    def is_valid(self) -> bool: ...

    def add_error(self, path: str, code: str, message: str) -> None: ...

# ################################################################################################################################
# ################################################################################################################################

def to_dict(obj: Any) -> dict[str, Any]: ...

def from_dict(data: dict[str, Any], cls: type) -> Any: ...

def get_path(obj: Any, path: str) -> Any: ...

def set_path(obj: Any, path: str, value: Any) -> bool: ...

def parse_path(path: str) -> list[dict[str, Any]]: ...

def validate(obj: Any, path: str | None = None) -> ValidationResult: ...

def validate_valueset_binding(obj: Any, path: str | None = None, include_extensible: bool = True) -> ValidationResult: ...

def rs_validate_to_outcome(obj: Any, include_valueset: bool = True) -> Any: ...

def generate_narrative(resource: Any, template: Any | None = None) -> Any: ...

def py_pluralize(word: str, count: int) -> str: ...

def count_with_noun(count: int, singular: str) -> str: ...

def py_to_label(field_name: str) -> str: ...

def get_extension(resource: Any, url: str) -> Any: ...

def get_extensions_by_url(resource: Any, url: str) -> Any: ...

def has_extension(resource: Any, url: str) -> bool: ...

def add_extension(resource: Any, url: str, value: Any, value_type: str = 'string') -> None: ...

def set_extension(resource: Any, url: str, value: Any) -> None: ...

def remove_extension(resource: Any, url: str) -> bool: ...

def get_extension_text(resource: Any, url: str) -> Any: ...

def set_extension_text(resource: Any, url: str, value: Any) -> None: ...

def get_nested_extension(resource: Any, urls: list[str]) -> Any: ...

def rs_bundle_to_dict(data: Any) -> Any: ...

def rs_bundle_to_json(data: Any, indent: int | None = None) -> str: ...

def rs_bundle_from_json(raw: str) -> Any: ...

def rs_create_bundle(resources: list[Any], bundle_type: str = 'collection', id: str | None = None) -> Any: ...

def rs_build_typed_bundle(entries: list[Any], bundle_type: str) -> Any: ...

def rs_build_searchset(resources: list[Any], total: int | None = None) -> Any: ...

def rs_bundle_get_resource(entries: list[Any], index: int) -> Any: ...

def rs_bundle_get_resources(entries: list[Any]) -> Any: ...

def rs_deserialize_contained(contained_list: list[Any]) -> Any: ...

def rs_resolve_contained(obj: Any, ref_id: str) -> Any: ...

def rs_resolve_bundle(bundle: Any, ref_input: Any) -> Any: ...
