{{- if not .Values.password.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zato.fullname" . }}
  labels:
    {{- include "zato.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.password.key }}: {{ required "password.value must be set when password.existingSecret is empty" .Values.password.value | quote }}
{{- end }}
