from typing import Any

from __future__ import absolute_import, division

class DictalchemyError(Exception):
    ...

class UnsupportedRelationError(DictalchemyError):
    def __init__(self: Any, relation_key: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class MissingRelationError(DictalchemyError):
    def __init__(self: Any, relation_key: Any) -> None: ...
    def __str__(self: Any) -> None: ...
