# -*- coding: utf-8 -*-

"""
Copyright (C) 2026, Zato Source s.r.o. https://zato.io

Licensed under AGPLv3, see LICENSE.txt for terms and conditions.
"""

# This file is generated by generate_edifact_message_tests.py - do not edit it by hand.

# stdlib
import unittest

# Zato
from zato.edifact import parse_edifact
from zato.edifact.syntax import parse_una, split_segments
from zato.edifact.testing.live_util import load_message, md_path_for

# ##################################################################################################################################
# ##################################################################################################################################

_md_path = md_path_for('un', 'un-supply-chain.md')

def _normalized_lines(raw:'str') -> 'list[str]':
    """ Normalizes wire text to one segment per line, the same form serialize() produces.
    """
    separators, rest = parse_una(raw)

    out:'list[str]' = []

    if raw.startswith('UNA'):
        una_length = len(raw) - len(rest)
        out.append(raw[:una_length])

    for segment_text in split_segments(rest, separators):
        if not segment_text.endswith(separators.terminator):
            segment_text = segment_text + separators.terminator
        out.append(segment_text)

    return out

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg01(unittest.TestCase):
    """ Based on live/un/un-supply-chain.md, message no. 1
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 1)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 22)
        self.assertEqual(interchange.header.sender.identification, 'ORDERAPP')
        self.assertEqual(interchange.header.recipient.identification, 'BOOKSHOP')

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 1)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg02(unittest.TestCase):
    """ Based on live/un/un-supply-chain.md, message no. 2
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 2)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 19)
        self.assertEqual(interchange.header.sender.identification, 'SHIPLINE')
        self.assertEqual(interchange.header.recipient.identification, 'TERMINAL')

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 2)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg03(unittest.TestCase):
    """ Based on live/un/un-supply-chain.md, message no. 3
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 3)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 52)
        self.assertEqual(interchange.header.sender.identification, 'BLC')
        self.assertEqual(interchange.header.recipient.identification, 'ECA')

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 3)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

if __name__ == '__main__':
    _ = unittest.main()
