from typing import Any

import traceback
from logging import getLogger
import cython as cy
from zato.common.api import DATA_FORMAT
from zato.simpleio import CySimpleIO
from zato.common.py23_.past.builtins import unicode as past_unicode

class SimpleIOPayload:
    sio: Any
    all_output_elem_names: Any
    output_repeated: Any
    cid: Any
    data_format: Any
    user_attrs_dict: Any
    user_attrs_list: Any
    zato_meta: Any
    def __cinit__(self: Any, sio: CySimpleIO, all_output_elem_names: list, cid: Any, data_format: Any) -> None: ...
    def __iter__(self: Any) -> None: ...
    def __setitem__(self: Any, key: Any, value: Any) -> None: ...
    def __setattr__(self: Any, key: Any, value: Any) -> None: ...
    def __getattr__(self: Any, key: Any) -> None: ...
    def __getitem__(self: Any, key: Any) -> None: ...
    def get(self: Any, key: Any) -> None: ...
    def has_data(self: Any) -> None: ...
    def _extract_payload_attrs(self: Any, item: object) -> dict: ...
    def _extract_payload_attrs_dict(self: Any, item: object) -> dict: ...
    def _is_sqlalchemy(self: Any, item: object) -> None: ...
    def _preprocess_payload_attrs(self: Any, value: Any) -> None: ...
    def set_payload_attrs(self: Any, value: object) -> None: ...
    def getvalue(self: Any, serialize: bool = ..., force_dict_serialisation: bool = ...) -> None: ...
    def append(self: Any, value: Any) -> None: ...
