from typing import Any

import logging
from functools import wraps
from bunch import bunchify
from sqlalchemy import and_, func, not_, or_
from sqlalchemy.sql.expression import case
from zato.common.api import CACHE, DEFAULT_HTTP_PING_METHOD, DEFAULT_HTTP_POOL_SIZE, GENERIC, HTTP_SOAP_SERIALIZATION_TYPE, PARAMS_PRIORITY, PubSub, URL_PARAMS_PRIORITY
from zato.common.json_internal import loads
from zato.common.odb.model import APIKeySecurity, CacheBuiltin, ChannelAMQP, Cluster, DeployedService, ElasticSearch, HTTPBasicAuth, HTTPSOAP, IMAP, IntervalBasedJob, Job, NTLM, OAuth, OutgoingOdoo, OutgoingAMQP, OutgoingFTP, PubSubPermission, PubSubSubscription, PubSubSubscriptionTopic, PubSubTopic, SecurityBase, Server, Service, SMTP, SQLConnectionPool, OutgoingSAP
from zato.common.util.search import SearchResults as _SearchResults

def count(session: Any, q: Any) -> None: ...

class _QueryConfig:
    @staticmethod
    def supports_kwargs(query_func: Any) -> None: ...

class _SearchWrapper:
    total: q.session.execute.scalar
    q: q.slice
    def __init__(self: Any, q: Any, default_page_size: Any = ..., **config: Any) -> None: ...

def query_wrapper(func: Any) -> None: ...

def bunch_maker(func: Any) -> None: ...

def internal_channel_list(session: Any, cluster_id: Any) -> None: ...

def _job(session: Any, cluster_id: Any) -> None: ...

def job_list(session: Any, cluster_id: Any, service_name: Any = ..., needs_columns: Any = ...) -> None: ...

def job_by_id(session: Any, cluster_id: Any, job_id: Any) -> None: ...

def job_by_name(session: Any, cluster_id: Any, name: Any) -> None: ...

def _sec_base(session: Any, cluster_id: Any) -> None: ...

def sec_base(session: Any, cluster_id: Any, sec_base_id: Any, use_one: Any = ...) -> None: ...

def apikey_security_list(session: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...

def basic_auth_list(session: Any, cluster_id: Any, cluster_name: Any = ..., needs_columns: Any = ...) -> None: ...

def ntlm_list(session: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...

def oauth_list(session: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...

def _out_amqp(session: Any, cluster_id: Any) -> None: ...

def out_amqp(session: Any, cluster_id: Any, id: Any) -> None: ...

def out_amqp_list(session: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...

def _channel_amqp(session: Any, cluster_id: Any) -> None: ...

def channel_amqp(session: Any, cluster_id: Any, id: Any) -> None: ...

def channel_amqp_list(session: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...

def _http_soap(session: Any, cluster_id: Any) -> None: ...

def http_soap_security_list(session: Any, cluster_id: Any, connection: Any = ...) -> None: ...

def http_soap(session: Any, cluster_id: Any, item_id: Any = ..., name: Any = ...) -> None: ...

def http_soap_list(session: Any, cluster_id: Any, connection: Any = ..., transport: Any = ..., return_internal: Any = ..., data_format: Any = ..., needs_columns: Any = ..., *args: Any, **kwargs: Any) -> None: ...

def _out_sql(session: Any, cluster_id: Any) -> None: ...

def out_sql(session: Any, cluster_id: Any, id: Any) -> None: ...

def out_sql_list(session: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...

def _out_ftp(session: Any, cluster_id: Any) -> None: ...

def out_ftp(session: Any, cluster_id: Any, id: Any) -> None: ...

def out_ftp_list(session: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...

def _service(session: Any, cluster_id: Any) -> None: ...

def service(session: Any, cluster_id: Any, id: Any = ..., name: Any = ...) -> None: ...

def service_list(session: Any, cluster_id: Any, return_internal: Any = ..., include_list: Any = ..., needs_columns: Any = ...) -> None: ...

def service_list_with_include(session: Any, cluster_id: Any, include_list: Any, needs_columns: Any = ...) -> None: ...

def service_id_list(session: Any, cluster_id: Any, name_list: Any = ...) -> None: ...

def service_deployment_list(session: Any, service_id: Any = ..., include_internal: Any = ...) -> None: ...

def _search_es(session: Any, cluster_id: Any) -> None: ...

def search_es_list(session: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...

def _server(session: Any, cluster_id: Any, cluster_name: Any) -> None: ...

def server_list(session: Any, cluster_id: Any, cluster_name: Any, up_status: Any = ..., needs_columns: Any = ...) -> None: ...

def server_by_name(session: Any, cluster_id: Any, cluster_name: Any, server_name: Any) -> None: ...

def server_by_id(session: Any, cluster_id: Any, server_id: Any) -> None: ...

def _email_smtp(session: Any, cluster_id: Any) -> None: ...

def email_smtp(session: Any, cluster_id: Any, id: Any) -> None: ...

def email_smtp_list(session: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...

def _email_imap(session: Any, cluster_id: Any) -> None: ...

def email_imap(session: Any, cluster_id: Any, id: Any) -> None: ...

def email_imap_list(session: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...

def cache_by_id(session: Any, cluster_id: Any, cache_id: Any) -> None: ...

def _cache_builtin(session: Any, cluster_id: Any) -> None: ...

def cache_builtin(session: Any, cluster_id: Any, id: Any) -> None: ...

def cache_builtin_list(session: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...

def _out_odoo(session: Any, cluster_id: Any) -> None: ...

def out_odoo(session: Any, cluster_id: Any, id: Any) -> None: ...

def out_odoo_list(session: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...

def _out_sap(session: Any, cluster_id: Any) -> None: ...

def out_sap(session: Any, cluster_id: Any, id: Any) -> None: ...

def out_sap_list(session: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...

def _pubsub_topic(session: Any, cluster_id: Any) -> None: ...

def pubsub_topic(session: Any, cluster_id: Any, id: Any) -> None: ...

def pubsub_topic_list(session: Any, cluster_id: Any, filter_by: Any = ..., needs_columns: Any = ...) -> None: ...

def _pubsub_permission(session: Any, cluster_id: Any, id: Any) -> None: ...

def pubsub_permission(session: Any, cluster_id: Any, id: Any) -> None: ...

def pubsub_permission_list(session: Any, cluster_id: Any, filter_by: Any = ..., needs_columns: Any = ..., **config: Any) -> None: ...

def _pubsub_subscription(session: Any, cluster_id: Any) -> None: ...

def pubsub_subscription(session: Any, cluster_id: Any, id: Any) -> None: ...

def pubsub_subscription_list(session: Any, cluster_id: Any, filter_by: Any = ..., needs_columns: Any = ...) -> None: ...
