from typing import Any

from zato.common.api import CONNECTION
from zato.common.odb.model import HTTPSOAP
from sqlalchemy import and_, select
from sqlalchemy import Column
from sqlalchemy.orm.session import Session as SASession
from zato.common.odb.model.base import Base as BaseTable
from zato.common.typing_ import any_, anylist, anylistnone, strlist

def get_object_list_by_columns(session: SASession, columns: anylist, order_by: any_ = ...) -> anylist: ...

def get_object_list(session: SASession, table: BaseTable) -> anylist: ...

def get_object_list_by_where_impl(session: SASession, table: BaseTable, where_list: str | anylistnone) -> anylist: ...

def get_object_list_by_where(session: SASession, table: BaseTable, value: str | strlist, extra_where_list: str | anylistnone, attr_name: str, attr_func: str) -> anylist: ...

def get_object_list_by_id_list(session: SASession, table: BaseTable, object_name_list: str, extra_where_list: str | anylistnone = ...) -> anylist: ...

def get_object_list_by_name_list(session: SASession, table: BaseTable, object_name_list: str, extra_where_list: str | anylistnone = ...) -> anylist: ...

def get_object_list_by_name_contains(session: SASession, table: BaseTable, pattern: str | strlist, extra_where_list: str | anylistnone = ...) -> anylist: ...

def get_rest_list_by_name_pattern(session: SASession, pattern: str, is_channel: bool) -> anylist: ...

def get_rest_channel_list_by_name_pattern(session: SASession, pattern: str) -> anylist: ...

def get_rest_outgoing_list_by_name_pattern(session: SASession, pattern: str) -> anylist: ...
