from typing import Any, TYPE_CHECKING

from logging import getLogger
from sqlalchemy import and_, delete, exists, insert, update
from zato.common.api import GENERIC, NotGiven
from zato.common.odb.model import GenericConn as ModelGenericConn, GenericObject as ModelGenericObject
from zato.common.odb.query import query_wrapper
from zato.common.typing_ import cast_
from zato.common.util.api import utcnow
from zato.common.util.sql import get_dict_with_opaque
from sqlalchemy.orm import Session as SASession
from zato.common.typing_ import any_, dictlist, intnone, strdict, strintnone, strnone

_generic_attr_name = GENERIC.ATTR_NAME
ModelGenericObjectTable: any_ = ModelGenericObject.__table__

class GenericObjectWrapper:
    type_: strnone
    subtype: strnone
    model_class: type_[ModelGenericObject]
    session: Any
    cluster_id: Any
    def __init__(self: Any, session: SASession, cluster_id: int) -> None: ...
    def build_list_item_from_sql_row(self: Any, row: strdict) -> strdict: ...
    def _build_get_where_query(self: Any, name: str) -> any_: ...
    def get(self: Any, name: str, type_: strnone = ...) -> any_: ...
    def get_list(self: Any, type_: strnone = ..., subtype: strnone = ...) -> dictlist: ...
    def exists(self: Any, name: str) -> bool: ...
    def create_many(self: Any, item_list: dictlist, type_: strnone = ..., subtype: strnone = ...) -> any_: ...
    def create(self: Any, name: str, opaque: str, type_: strnone = ..., subtype: strnone = ...) -> any_: ...
    def update(self: Any, name: str, opaque: any_ = ..., type_: strnone = ...) -> any_: ...
    def delete_by_id(self: Any, id: int) -> any_: ...
    def delete_by_parent_object_id(self: Any, parent_object_id: int) -> any_: ...
    def delete_by_name(self: Any, name: str) -> any_: ...
    def store(self: Any, name: str, opaque: str) -> None: ...

class GroupsWrapper(GenericObjectWrapper):
    def build_list_item_from_sql_row(self: Any, row: strdict) -> strdict: ...

def connection_list(session: SASession, cluster_id: int, type_: strnone = ..., needs_columns: bool = ...) -> any_: ...
