line-length    = 160
target-version = "py310"

extend-exclude = [
    "**/brython",
    "**/playwright_/*.py",
    "**/src/zato/common/ext",
    "**/src/zato/common/py23_",
]

[lint]
select = [
    "F",     # pyflakes (includes F841 unused variables, F811 redefined unused, F401 unused imports)
    "W",     # pycodestyle warnings
    "E",     # pycodestyle errors
]

[lint.flake8-quotes]
inline-quotes    = "single"
multiline-quotes = "single"
docstring-quotes = "double"

[format]
quote-style = "single"
