from typing import Any

from zato.admin.web.views.ai.tools.definitions_create import all_create_tools
from zato.admin.web.views.ai.tools.definitions_delete import all_delete_tools
from zato.admin.web.views.ai.tools.definitions_update import all_update_tools
from zato.common.typing_ import anylist

def get_all_tools() -> anylist: ...

def get_all_tool_names() -> anylist: ...

def get_all_create_tools() -> anylist: ...

def get_all_create_tool_names() -> anylist: ...

def is_create_tool(tool_name: str) -> bool: ...

def get_all_delete_tools() -> anylist: ...

def get_all_delete_tool_names() -> anylist: ...

def is_delete_tool(tool_name: str) -> bool: ...

def get_all_update_tools() -> anylist: ...

def get_all_update_tool_names() -> anylist: ...

def is_update_tool(tool_name: str) -> bool: ...
