from typing import Any

import ast
from logging import getLogger
import yaml
from zato.common.typing_ import anydict, anylist

def _get_config() -> anydict: ...

def _extract_service_names_ast(code: str) -> list: ...

def _get_provided_names(tool_calls: anylist) -> anydict: ...

def _get_required_names(tool_call: anydict) -> anydict: ...

def build_dependency_graph(tool_calls: anylist) -> anydict: ...

def topological_sort_waves(tool_calls: anylist) -> anylist: ...
