from typing import Any, TYPE_CHECKING

from inspect import isclass
from zato.common.ext.future.utils import iteritems
from zato.common.py23_.past.builtins import cmp
from zato.common.ext.candv import Constants as _Constants, ValueConstant as _ValueConstant


class Constants(_Constants):
    values: Any

class ValueConstant(_ValueConstant):
    def __cmp__(self: Any, other: Any) -> None: ...

class MESSAGE:
    MESSAGE_TYPE_LENGTH: Any
    TOKEN_LENGTH: Any
    TOKEN_START: Any
    TOKEN_END: Any
    PAYLOAD_START: Any
    NULL_TOKEN: Any

class MESSAGE_TYPE:
    TO_SCHEDULER: Any
    TO_PARALLEL_ANY: Any
    TO_PARALLEL_ALL: Any
    USER_DEFINED_START: Any

class SCHEDULER(Constants):
    PAUSE: Any
    RESUME: Any
    CREATE: Any
    EDIT: Any
    DELETE: Any
    EXECUTE: Any
    JOB_EXECUTED: Any
    SET_JOB_INACTIVE: Any
    SET_SERVER_ADDRESS: Any
    SET_SCHEDULER_ADDRESS: Any

class SECURITY(Constants):
    BASIC_AUTH_CREATE: Any
    BASIC_AUTH_EDIT: Any
    BASIC_AUTH_DELETE: Any
    BASIC_AUTH_CHANGE_PASSWORD: Any
    OAUTH_CREATE: Any
    OAUTH_EDIT: Any
    OAUTH_DELETE: Any
    OAUTH_CHANGE_PASSWORD: Any
    NTLM_CREATE: Any
    NTLM_EDIT: Any
    NTLM_DELETE: Any
    NTLM_CHANGE_PASSWORD: Any
    APIKEY_CREATE: Any
    APIKEY_EDIT: Any
    APIKEY_DELETE: Any
    APIKEY_CHANGE_PASSWORD: Any

class OUTGOING(Constants):
    AMQP_CREATE: Any
    AMQP_EDIT: Any
    AMQP_DELETE: Any
    AMQP_PUBLISH: Any
    SQL_CREATE_EDIT: Any
    SQL_CHANGE_PASSWORD: Any
    SQL_DELETE: Any
    HTTP_SOAP_CREATE_EDIT: Any
    HTTP_SOAP_DELETE: Any
    FTP_CREATE_EDIT: Any
    FTP_DELETE: Any
    FTP_CHANGE_PASSWORD: Any
    ODOO_CREATE: Any
    ODOO_EDIT: Any
    ODOO_DELETE: Any
    ODOO_CHANGE_PASSWORD: Any
    SAP_CREATE: Any
    SAP_EDIT: Any
    SAP_DELETE: Any
    SAP_CHANGE_PASSWORD: Any
    REST_WRAPPER_CHANGE_PASSWORD: Any

class CHANNEL(Constants):
    AMQP_CREATE: Any
    AMQP_EDIT: Any
    AMQP_DELETE: Any
    AMQP_MESSAGE_RECEIVED: Any
    HTTP_SOAP_CREATE_EDIT: Any
    HTTP_SOAP_DELETE: Any
    FTP_CREATE: Any
    FTP_EDIT: Any
    FTP_DELETE: Any
    FTP_PING: Any
    FTP_USER_CREATE: Any
    FTP_USER_EDIT: Any
    FTP_USER_DELETE: Any
    FTP_USER_CHANGE_PASSWORD: Any

class SERVICE(Constants):
    EDIT: Any
    DELETE: Any
    PUBLISH: Any
    INVOKE: Any

class HOT_DEPLOY(Constants):
    CREATE_SERVICE: Any
    CREATE_STATIC: Any
    CREATE_USER_CONF: Any
    UPDATE_ENMASSE: Any
    AFTER_DEPLOY: Any

class SEARCH(Constants):
    CREATE: Any
    EDIT: Any
    DELETE: Any
    ES_CREATE: Any
    ES_EDIT: Any
    ES_DELETE: Any
    ES_CHANGE_PASSWORD: Any

class EMAIL(Constants):
    SMTP_CREATE: Any
    SMTP_EDIT: Any
    SMTP_DELETE: Any
    SMTP_CHANGE_PASSWORD: Any
    IMAP_CREATE: Any
    IMAP_EDIT: Any
    IMAP_DELETE: Any
    IMAP_CHANGE_PASSWORD: Any

class CACHE(Constants):
    BUILTIN_CREATE: Any
    BUILTIN_EDIT: Any
    BUILTIN_DELETE: Any
    BUILTIN_STATE_CHANGED_CLEAR: Any
    BUILTIN_STATE_CHANGED_DELETE: Any
    BUILTIN_STATE_CHANGED_DELETE_BY_PREFIX: Any
    BUILTIN_STATE_CHANGED_DELETE_BY_SUFFIX: Any
    BUILTIN_STATE_CHANGED_DELETE_BY_REGEX: Any
    BUILTIN_STATE_CHANGED_DELETE_CONTAINS: Any
    BUILTIN_STATE_CHANGED_DELETE_NOT_CONTAINS: Any
    BUILTIN_STATE_CHANGED_DELETE_CONTAINS_ALL: Any
    BUILTIN_STATE_CHANGED_DELETE_CONTAINS_ANY: Any
    BUILTIN_STATE_CHANGED_EXPIRE: Any
    BUILTIN_STATE_CHANGED_EXPIRE_BY_PREFIX: Any
    BUILTIN_STATE_CHANGED_EXPIRE_BY_SUFFIX: Any
    BUILTIN_STATE_CHANGED_EXPIRE_BY_REGEX: Any
    BUILTIN_STATE_CHANGED_EXPIRE_CONTAINS: Any
    BUILTIN_STATE_CHANGED_EXPIRE_NOT_CONTAINS: Any
    BUILTIN_STATE_CHANGED_EXPIRE_CONTAINS_ALL: Any
    BUILTIN_STATE_CHANGED_EXPIRE_CONTAINS_ANY: Any
    BUILTIN_STATE_CHANGED_SET: Any
    BUILTIN_STATE_CHANGED_SET_BY_PREFIX: Any
    BUILTIN_STATE_CHANGED_SET_BY_SUFFIX: Any
    BUILTIN_STATE_CHANGED_SET_BY_REGEX: Any
    BUILTIN_STATE_CHANGED_SET_CONTAINS: Any
    BUILTIN_STATE_CHANGED_SET_NOT_CONTAINS: Any
    BUILTIN_STATE_CHANGED_SET_CONTAINS_ALL: Any
    BUILTIN_STATE_CHANGED_SET_CONTAINS_ANY: Any

class GENERIC(Constants):
    CONNECTION_CREATE: Any
    CONNECTION_EDIT: Any
    CONNECTION_DELETE: Any
    CONNECTION_CHANGE_PASSWORD: Any

class Common(Constants):
    Sync_Objects: Any

class Groups(Constants):
    Edit: Any
    Edit_Member_List: Any
    Delete: Any

class PUBSUB(Constants):
    RELOAD_CONFIG: Any
    TOPIC_CREATE: Any
    TOPIC_EDIT: Any
    TOPIC_DELETE: Any
    PERMISSION_CREATE: Any
    PERMISSION_EDIT: Any
    PERMISSION_DELETE: Any
    SUBSCRIPTION_CREATE: Any
    SUBSCRIPTION_EDIT: Any
    SUBSCRIPTION_DELETE: Any
