from typing import Any

from __future__ import absolute_import, division, print_function, unicode_literals
from logging import getLogger

class Dispatcher:
    def __init__(self: Any) -> None: ...
    def _listen(self: Any, event: Any, callback: Any, **opaque: Any) -> None: ...
    def listen(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def listen_for_updates(self: Any, msg: Any, callback: Any, **opaque: Any) -> None: ...
    def notify(self: Any, event: Any, ctx: Any) -> None: ...
