from typing import Any, TYPE_CHECKING

from logging import getLogger
from traceback import format_exc
from sqlalchemy.pool import QueuePool as SAQueuePool
from sqlalchemy.pool.dbapi_proxy import _DBProxy
from zato.common.api import MS_SQL
from zato.common.typing_ import stranydict
import pytds


def get_queue_pool(pool_kwargs: Any) -> None: ...

class SimpleSession:
    api: Any
    def __init__(self: Any, api: MSSQLDirectAPI) -> None: ...
    def __call__(self: Any) -> None: ...
    def execute(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def callproc(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def ping(self: Any, *args: Any, **kwargs: Any) -> None: ...

class MSSQLDirectAPI:
    name: Any
    ping_query: Any
    _name: Any
    _connect_kwargs: Any
    _pool_kwargs: Any
    _pool: _DBProxy
    def __init__(self: Any, name: Any, pool_size: Any, connect_kwargs: Any, extra: Any) -> None: ...
    def connect(self: Any) -> None: ...
    def dispose(self: Any) -> None: ...
    def execute(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def ping(self: Any) -> None: ...
    def _return_proc_rows(self: Any, conn: Any, proc_name: Any, params: Any = ...) -> None: ...
    def _yield_proc_rows(self: Any, conn: Any, proc_name: Any, params: Any = ...) -> None: ...
    def callproc(self: Any, name: Any, params: Any = ..., use_yield: Any = ...) -> None: ...
