from typing import Any, TYPE_CHECKING

from operator import itemgetter


class PathAccessException(Exception):
    ...

class BaseFileClient:
    config: Any
    def __init__(self: Any, config: Any) -> None: ...
    def sort_result(self: Any, result: Any) -> None: ...
    def create_directory(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def delete_directory(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def get(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def get_as_file_object(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def store(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def move_file(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def delete_file(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def list(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def touch(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def path_exists(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def ping(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def close(self: Any, *args: Any, **kwargs: Any) -> None: ...
