from typing import Any

from logging import getLogger
from base import BaseFileClient
from typing import BinaryIO
from fs.ftpfs import FTPFS
from fs.info import Info

class FTPFileClient(BaseFileClient):
    def __init__(self: Any, conn: Any, config: Any) -> None: ...
    def create_directory(self: Any, path: Any) -> None: ...
    def delete_directory(self: Any, path: Any) -> None: ...
    def get(self: Any, path: Any) -> None: ...
    def get_as_file_object(self: Any, path: Any, file_object: Any) -> None: ...
    def move_file(self: Any, path_from: Any, path_to: Any) -> None: ...
    def store(self: Any, path: Any, data: Any) -> None: ...
    def delete_file(self: Any, path: Any) -> None: ...
    def list(self: Any, path: Any) -> None: ...
    def touch(self: Any, path: Any) -> None: ...
    def path_exists(self: Any, path: Any) -> None: ...
    def ping(self: Any) -> None: ...
    def close(self: Any) -> None: ...
