from typing import Any

import argparse
from logging import basicConfig, getLogger, INFO
from gunicorn.app.base import BaseApplication
from zato.common.pubsub.test.config import load_config
from zato.common.pubsub.test.server import PubSubTestServer
from typing import Dict, Optional
from zato.common.pubsub.test.config import AppConfig

class GunicornApp(BaseApplication):
    options: Any
    application: Any
    def __init__(self: Any, app: PubSubTestServer, options: dict = ...) -> None: ...
    def load_config(self: Any) -> None: ...
    def load(self: Any) -> PubSubTestServer: ...

def parse_args() -> argparse.Namespace: ...

def setup_logging(log_level: str = ...) -> None: ...

def run_with_gevent(app: PubSubTestServer) -> None: ...

def run_with_gunicorn(app: PubSubTestServer, workers: int = ..., timeout: int = ...) -> None: ...

def main() -> None: ...
