from typing import Any

from collections import defaultdict
from datetime import datetime
from itertools import groupby
from typing import Dict, List, Tuple
from zato.common.pubsub.test.models import Message, TestCollector, QueueStats

def _format_time(dt: datetime) -> str: ...

def _calculate_queue_stats(collector: TestCollector) -> dict: ...

def _calculate_topic_stats(collector: TestCollector) -> dict: ...

def _generate_summary_section(collector: TestCollector) -> str: ...

def _generate_queue_stats_section(collector: TestCollector) -> str: ...

def _generate_topic_stats_section(collector: TestCollector) -> str: ...

def generate_html_report(collector: TestCollector) -> str: ...
