from typing import Any

from logging import getLogger
from yaml import safe_load as yaml_load
from typing import Dict, List, Set, Tuple

class UsersYAMLParser:
    users_yaml_path: Any
    data: Any
    def __init__(self: Any, users_yaml_path: Any) -> None: ...
    def _load_yaml(self: Any) -> None: ...
    def get_users(self: Any) -> list: ...
    def get_topics(self: Any) -> list: ...
    def get_subscribers_for_topic(self: Any, topic_name: str) -> set: ...
    def get_subscriptions(self: Any) -> dict: ...

def calculate_expected_messages(users_yaml_path: str, messages_per_topic_per_user: int) -> int: ...

def calculate_message_distribution(users_yaml_path: str, messages_per_topic_per_user: int) -> dict: ...
