from typing import Any

import logging
import os
from contextlib import closing
from copy import deepcopy
from datetime import datetime
from io import StringIO
from logging import DEBUG, getLogger
from threading import RLock
from time import time
from bunch import Bunch, bunchify
from sqlalchemy import and_, create_engine, event, select
from sqlalchemy.exc import IntegrityError, OperationalError
from sqlalchemy.orm import sessionmaker, scoped_session
from sqlalchemy.orm.query import Query
from sqlalchemy.pool import NullPool
from sqlalchemy.sql.expression import true
from sqlalchemy.sql.type_api import TypeEngine
from zato.common.api import DEPLOYMENT_STATUS, HTTP_SOAP, MS_SQL, NotGiven, SEC_DEF_TYPE, SECRET_SHADOW, SERVER_UP_STATUS, UNITTEST, ZATO_NONE, ZATO_ODB_POOL_NAME
from zato.common.exception import Inactive
from zato.common.mssql_direct import MSSQLDirectAPI, SimpleSession
from zato.common.odb import query
from zato.common.odb.ping import get_ping_query
from zato.common.odb.model import APIKeySecurity, Cluster, DeployedService, DeploymentPackage, DeploymentStatus, HTTPBasicAuth, NTLM, SecurityBase, Server, Service
from zato.common.odb.testing import UnittestEngine
from zato.common.odb.query import generic as query_generic
from zato.common.util.api import current_host, get_component_name, get_engine_url, new_cid, parse_extra_into_dict, spawn_greenlet
from zato.common.util.sql import ElemsWithOpaqueMaker, elems_with_opaque
from zato.common.util.time_ import utcnow
from zato.common.util.url_dispatcher import get_match_target
from sqlalchemy.orm import Session as SASession
from zato.common.crypto.api import CryptoManager
from zato.common.odb.model import Cluster as ClusterModel, Server as ServerModel
from zato.common.typing_ import any_, anylistnone, anyset, callable_, commondict, strdict, strdictnone
from zato.server.base.parallel import ParallelServer

class SQLRow:
    def __init__(self: Any, elem: Any) -> None: ...
    def __getattr__(self: Any, key: Any) -> None: ...
    def __getitem__(self: Any, idx: Any) -> None: ...
    def __setitem__(self: Any, idx: Any, value: Any) -> None: ...
    def __nonzero__(self: Any) -> None: ...
    def __repr__(self: Any) -> None: ...
    def get_value(self: Any) -> commondict: ...

class SessionWrapper:
    _Session: SASession
    def __init__(self: Any) -> None: ...
    def init_session(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def _init_session(self: Any, name: Any, config: Any, pool: Any, use_scoped_session: Any = ...) -> None: ...
    def execute(self: Any, query: str, params: strdictnone = ...) -> any_: ...
    def one(self: Any, *args: any_, **kwargs: any_) -> any_: ...
    def one_or_none(self: Any, *args: any_, **kwargs: any_) -> any_: ...
    def callproc(self: Any, proc_name: str, params: anylistnone = ...) -> any_: ...
    def session(self: Any) -> SASession: ...
    def close(self: Any) -> None: ...

class WritableTupleQuery(Query):
    def __iter__(self: Any) -> None: ...

class SQLConnectionPool:
    __repr__: Any
    conn: Any
    impl: Any
    def __init__(self: Any, name: str, config: strdict, config_no_sensitive: strdict, should_init: bool = ...) -> None: ...
    def init(self: Any) -> None: ...
    def __str__(self: Any) -> None: ...
    def _is_oracle_engine(self: Any, engine_url: str) -> bool: ...
    def _is_sa_engine(self: Any, engine_url: str) -> bool: ...
    def _is_unittest_engine(self: Any, engine_url: str) -> bool: ...
    def _create_unittest_engine(self: Any, engine_url: Any, config: Any) -> None: ...
    def _create_oracle_engine(self: Any, engine_url: Any, config: Any) -> None: ...
    def _create_engine(self: Any, engine_url: Any, config: Any, extra: Any) -> None: ...
    def on_checkin(self: Any, dbapi_conn: Any, conn_record: Any) -> None: ...
    def on_checkout(self: Any, dbapi_conn: Any, conn_record: Any, conn_proxy: Any) -> None: ...
    def on_connect(self: Any, dbapi_conn: Any, conn_record: Any) -> None: ...
    def on_first_connect(self: Any, dbapi_conn: Any, conn_record: Any) -> None: ...
    def ping(self: Any, fs_sql_config: Any) -> None: ...
    def _conn(self: Any) -> None: ...
    def _impl(self: Any) -> None: ...

class PoolStore:
    get: Any
    set_item: Any
    __repr__: Any
    def __init__(self: Any, sql_conn_class: Any = ...) -> None: ...
    def __getitem__(self: Any, name: Any, enforce_is_active: Any = ...) -> None: ...
    def __setitem__(self: Any, name: Any, config: Any) -> None: ...
    def add_unittest_item(self: Any, name: Any, fs_sql_config: Any = ...) -> None: ...
    def __delitem__(self: Any, name: Any) -> None: ...
    def __str__(self: Any) -> None: ...
    def change_password(self: Any, name: Any, password: Any) -> None: ...
    def cleanup_on_stop(self: Any) -> None: ...

class _Server:
    def __init__(self: Any, odb_server: Any, odb_cluster: Any) -> None: ...

class ODBManager(SessionWrapper):
    parallel_server: ParallelServer
    well_known_data: str
    token: str
    crypto_manager: CryptoManager
    server_id: int
    server_name: str
    cluster_id: int
    pool: SQLConnectionPool
    decrypt_func: callable_
    server: ServerModel
    cluster: ClusterModel
    encrypt_sec_apikey: Any
    encrypt_sec_basic_auth: Any
    encrypt_sec_ntlm: Any
    encrypt_sec_oauth: Any
    def on_deployment_finished(self: Any) -> None: ...
    def fetch_server(self: Any, odb_config: Any) -> None: ...
    def get_servers(self: Any, up_status: Any = ..., filter_out_self: Any = ...) -> None: ...
    def get_missing_services(self: Any, server: Any, locally_deployed: Any) -> anyset: ...
    def server_up_down(self: Any, token: Any, status: Any, update_host: Any = ..., bind_host: Any = ..., bind_port: Any = ..., preferred_address: Any = ..., crypto_use_tls: Any = ...) -> None: ...
    def get_url_security(self: Any, cluster_id: Any, connection: Any = ..., any_internal: Any = ...) -> None: ...
    def get_sql_internal_service_list(self: Any, cluster_id: Any) -> None: ...
    def get_basic_data_service_list(self: Any, session: Any) -> None: ...
    def get_basic_data_deployed_service_list(self: Any) -> None: ...
    def add_services(self: Any, session: Any, data: Any) -> None: ...
    def add_deployed_services(self: Any, session: Any, data: Any) -> None: ...
    def drop_deployed_services_by_name(self: Any, session: Any, service_id_list: Any) -> None: ...
    def drop_deployed_services(self: Any, server_id: Any) -> None: ...
    def is_service_active(self: Any, service_id: Any) -> None: ...
    def hot_deploy(self: Any, deployment_time: Any, details: Any, payload_name: Any, payload: Any, server_id: Any) -> None: ...
    def add_delivery(self: Any, deployment_time: Any, details: Any, service: Any, source_info: Any) -> None: ...
    def get_internal_channel_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def get_http_soap_list(self: Any, cluster_id: Any, connection: Any = ..., transport: Any = ..., needs_columns: Any = ...) -> None: ...
    def get_job_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def get_service_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def get_service_id_list(self: Any, session: Any, cluster_id: Any, name_list: Any) -> None: ...
    def get_service_list_with_include(self: Any, session: Any, cluster_id: Any, include_list: Any, needs_columns: Any = ...) -> None: ...
    def get_apikey_security_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def get_basic_auth_list(self: Any, cluster_id: Any, cluster_name: Any, needs_columns: Any = ...) -> None: ...
    def get_ntlm_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def get_oauth_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def get_channel_amqp(self: Any, cluster_id: Any, channel_id: Any) -> None: ...
    def get_channel_amqp_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def get_out_amqp(self: Any, cluster_id: Any, out_id: Any) -> None: ...
    def get_out_amqp_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def get_out_sql(self: Any, cluster_id: Any, out_id: Any) -> None: ...
    def get_out_sql_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def get_out_odoo(self: Any, cluster_id: Any, out_id: Any) -> None: ...
    def get_out_odoo_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def get_out_sap(self: Any, cluster_id: Any, out_id: Any) -> None: ...
    def get_out_sap_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def get_out_ftp(self: Any, cluster_id: Any, out_id: Any) -> None: ...
    def get_out_ftp_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def get_cache_builtin(self: Any, cluster_id: Any, id: Any) -> None: ...
    def get_cache_builtin_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def get_search_es_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def get_email_smtp_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def get_email_imap_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def get_generic_connection_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def get_pubsub_subscription_list(self: Any, cluster_id: Any, needs_columns: Any = ...) -> None: ...
    def encrypt_sec_base(self: Any, session: Any, id: Any, attr_name: Any, encrypted_value: Any) -> None: ...
