from typing import Any

from __future__ import absolute_import, division, print_function, unicode_literals
import logging
from zato.common.api import UNITTEST

class UnittestCursor:
    result: Any
    def __init__(self: Any, result: Any = ...) -> None: ...
    def close(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def fetchall(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def _getter(self: Any, *args: Any, **kwargs: Any) -> None: ...

class UnittestSession:
    engine: Any
    def __init__(self: Any, engine: Any) -> None: ...
    def execute(self: Any, query: Any, *args: Any, **kwargs: Any) -> None: ...
    def begin(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def close(self: Any, *args: Any, **kwargs: Any) -> None: ...

class UnittestEngine:
    name: Any
    _contextual_connect: Any
    engine_url: Any
    config: Any
    def __init__(self: Any, engine_url: Any, config: Any) -> None: ...
    def connect(self: Any) -> None: ...
