from typing import Any, TYPE_CHECKING

from __future__ import absolute_import, division, print_function, unicode_literals
from bunch import bunchify
from zato.url_dispatcher import Matcher


class Response:
    data: Any
    status_code: Any
    def __init__(self: Any, data: Any) -> None: ...
    def json(self: Any) -> None: ...

class RequestsAdapter:
    _get_handlers: Any
    _post_handlers: Any
    def __init__(self: Any) -> None: ...
    def _on_request(self: Any, path: Any, config: Any, args: Any, kwargs: Any) -> None: ...
    def get(self: Any, path: Any, *args: Any, **kwargs: Any) -> None: ...
    def post(self: Any, path: Any, *args: Any, **kwargs: Any) -> None: ...
    def _add_handler(self: Any, path: Any, func: Any, config: Any) -> None: ...
    def add_get_handler(self: Any, path: Any, func: Any) -> None: ...
    def add_post_handler(self: Any, path: Any, func: Any) -> None: ...
