from typing import Any

import redis

def get_redis_client() -> redis.Redis: ...

def is_valid_provider(provider: str) -> bool: ...

def get_api_key(provider: str) -> str | None: ...

def set_api_key(provider: str, api_key: str) -> None: ...

def delete_api_key(provider: str) -> None: ...

def get_all_api_key_status() -> dict: ...
