from typing import Any

from logging import getLogger
from traceback import format_exc
from zato.common.util.api import spawn_greenlet
from zato.server.base.worker.common import WorkerImpl
from bunch import Bunch
from zato.common.typing_ import any_, dictnone, strnone
from zato.server.base.worker import WorkerStore

class AMQP(WorkerImpl):
    def amqp_connection_create(self: WorkerStore, msg: Bunch) -> None: ...
    def on_broker_msg_OUTGOING_AMQP_CREATE(self: WorkerStore, msg: Bunch) -> None: ...
    def on_broker_msg_OUTGOING_AMQP_EDIT(self: WorkerStore, msg: Bunch) -> None: ...
    def on_broker_msg_OUTGOING_AMQP_DELETE(self: WorkerStore, msg: Bunch) -> None: ...
    def on_broker_msg_CHANNEL_AMQP_CREATE(self: WorkerStore, msg: Bunch) -> None: ...
    def on_broker_msg_CHANNEL_AMQP_EDIT(self: WorkerStore, msg: Bunch) -> None: ...
    def on_broker_msg_CHANNEL_AMQP_DELETE(self: WorkerStore, msg: Bunch) -> None: ...
    def amqp_invoke(self: WorkerStore, out_name: str, msg: Bunch, exchange: str = ..., routing_key: strnone = ..., properties: dictnone = ..., headers: dictnone = ..., **kwargs: any_) -> any_: ...
    def _amqp_invoke_async(self: WorkerStore, *args: any_, **kwargs: any_) -> None: ...
    def amqp_invoke_async(self: WorkerStore, *args: any_, **kwargs: any_) -> None: ...
