from typing import Any

from base64 import b64decode
from zato.common.api import CACHE
from zato.server.base.worker.common import WorkerImpl
from zato.common.py23_ import pickle_loads
from bunch import Bunch
from zato.server.base.worker import WorkerStore

class CacheBuiltin(WorkerImpl):
    def on_broker_msg_CACHE_BUILTIN_CREATE(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_EDIT(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_DELETE(self: WorkerStore, msg: Any) -> None: ...
    def _unpickle_msg(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_SET(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_SET_BY_PREFIX(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_SET_BY_SUFFIX(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_SET_BY_REGEX(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_SET_CONTAINS(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_SET_NOT_CONTAINS(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_SET_CONTAINS_ALL(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_SET_CONTAINS_ANY(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_DELETE(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_DELETE_BY_PREFIX(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_DELETE_BY_SUFFIX(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_DELETE_BY_REGEX(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_DELETE_CONTAINS(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_DELETE_NOT_CONTAINS(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_DELETE_CONTAINS_ALL(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_DELETE_CONTAINS_ANY(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_EXPIRE(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_EXPIRE_BY_PREFIX(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_EXPIRE_BY_SUFFIX(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_EXPIRE_BY_REGEX(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_EXPIRE_CONTAINS(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_EXPIRE_NOT_CONTAINS(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_EXPIRE_CONTAINS_ALL(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_EXPIRE_CONTAINS_ANY(self: WorkerStore, msg: Any) -> None: ...
    def on_broker_msg_CACHE_BUILTIN_STATE_CHANGED_CLEAR(self: WorkerStore, msg: Any) -> None: ...
