from typing import Any

from bunch import Bunch
from zato.common.api import GENERIC as COMMON_GENERIC, LDAP, ZATO_NONE
from zato.common.broker_message import GENERIC as GENERIC_BROKER_MSG
from zato.common.const import SECRETS
from zato.common.util.api import as_bool, parse_simple_type
from zato.common.util.config import replace_query_string_items_in_dict
from zato.distlock import PassThrough as PassThroughLock
from zato.server.base.worker.common import WorkerImpl
from zato.server.generic.connection import GenericConnection
from logging import Logger
from zato.common.typing_ import any_, callable_, stranydict, strnone, tuple_
from zato.server.connection.queue import Wrapper

class Generic(WorkerImpl):
    logger: Logger
    generic_conn_api: stranydict
    _generic_conn_handler: stranydict
    _get_generic_impl_func: callable_
    on_broker_msg_GENERIC_CONNECTION_CHANGE_PASSWORD: Any
    def _find_conn_info(self: Any, item_id: int, item_name: str = ...) -> tuple_: ...
    def get_conn_dict_by_id(self: Any, conn_id: int) -> dict | None: ...
    def is_active_generic_conn(self: Any, conn_id: int) -> bool: ...
    def _delete_generic_connection(self: Any, msg: stranydict) -> None: ...
    def _create_generic_connection(self: Any, msg: stranydict, needs_roundtrip: bool = ..., skip: any_ = ..., raise_exc: bool = ..., is_starting: bool = ...) -> None: ...
    def _edit_generic_connection(self: Any, msg: stranydict, skip: any_ = ..., secret: strnone = ...) -> None: ...
    def ping_generic_connection(self: Any, conn_id: int) -> None: ...
    def _change_password_generic_connection(self: Any, msg: stranydict) -> None: ...
    def reconnect_generic(self: Any, conn_id: int) -> None: ...
    def _on_broker_msg_GENERIC_CONNECTION_COMMON_ACTION(self: Any, msg: stranydict, *args: any_, **kwargs: any_) -> None: ...
    def on_broker_msg_GENERIC_CONNECTION_CREATE(self: Any, *args: any_, **kwargs: any_) -> any_: ...
    def on_broker_msg_GENERIC_CONNECTION_EDIT(self: Any, msg: stranydict, *args: any_, **kwargs: any_) -> None: ...
    def on_broker_msg_GENERIC_CONNECTION_DELETE(self: Any, *args: any_, **kwargs: any_) -> any_: ...
    def _generic_normalize_config_outconn_ldap(self: Any, config: stranydict) -> None: ...
    def generic_normalize_config(self: Any, config: stranydict) -> None: ...
