# -*- coding: utf-8 -*-

"""
Copyright (C) 2026, Zato Source s.r.o. https://zato.io

Licensed under AGPLv3, see LICENSE.txt for terms and conditions.
"""

# Converts VS Code color theme files into our theme css files.
#
# Sources live in themes-in/: each <slug>.json is a theme in the VS Code
# color theme format (JSONC, a colors map keyed by workbench color ids),
# and each themes-in/overrides/<slug>.json carries the theme's origin and
# license metadata plus optional pins of our tokens, applied last. Our own
# palettes, Zato Dark and Zato Light, are just such source files too - one
# kind of source for everything.
#
# For every theme the converter emits static/webapp/css/themes/<slug>.css
# with the full token set scoped by html[data-theme="<slug>"], plus
# static/webapp/js/themes-index.js (the list the settings panel shows) and
# templates/webapp/themes.html (the link tags webapp/base.html includes).
#
# Everything is resolved at conversion time: mapping chains first, then
# per-type defaults, then the pins on the mapped tokens, then the derived
# values (surface mixes and alpha tints) and last the pins on those. The
# pages never compute a color at runtime.

# stdlib
import argparse
import json
import os

# Zato
from zato.common.typing_ import anydict, dictlist, strdict, strlist
from zato.common.webapp.ui.themes.colors import channel_distance, composite, is_opaque, mix, parse_hex, rgb_tuple, to_hex
from zato.common.webapp.ui.themes.jsonc import load_theme
from zato.common.webapp.ui.themes.tokens import actions, default_theme, defaults, links, logo_directory, logo_opacity, \
    logos, mapping, marks, min_surface_distance, mixes, rule_names, shadows, surface_wash_ratio, ThemeConversionError, \
    tints, token_order

# ################################################################################################################################
# ################################################################################################################################

sort_key_tuple = tuple[int, str]

# ################################################################################################################################

# Where this package keeps its theme sources and where the generated
# files land inside the UI kit's static and template trees.
_themes_package_dir = os.path.dirname(os.path.abspath(__file__))
_ui_dir = os.path.dirname(_themes_package_dir)

_default_themes_dir   = os.path.join(_themes_package_dir, 'themes-in')
_default_out_css_dir  = os.path.join(_ui_dir, 'static', 'webapp', 'css', 'themes')
_assets_dir           = os.path.join(_ui_dir, 'static', 'webapp', 'assets')
_default_out_index    = os.path.join(_ui_dir, 'static', 'webapp', 'js', 'themes-index.js')
_default_out_template = os.path.join(_ui_dir, 'templates', 'webapp', 'themes.html')

# The base a translucent background itself flattens over, per theme type
_dark_base:'rgb_tuple'  = (0, 0, 0)
_light_base:'rgb_tuple' = (255, 255, 255)

# Our own themes lead the list, in this order, and everything imported
# follows them alphabetically
_own_themes = ['zato-dark', 'zato-light']

# ################################################################################################################################

def _flatten(value:'str', base:'rgb_tuple', slug:'str') -> 'rgb_tuple':
    """ Reads one color and flattens it over the base if it is translucent,
    so our tokens are always opaque.
    """
    red, green, blue, alpha = parse_hex(value, slug)

    if is_opaque(alpha):
        out = (red, green, blue)
    else:
        out = composite((red, green, blue), alpha, base)

    return out

# ################################################################################################################################

def _resolve_token(token:'str', colors:'anydict', type_defaults:'strdict', base:'rgb_tuple', slug:'str') -> 'rgb_tuple':
    """ Resolves one mapped token: the first present key in its chain wins
    and the per-type default catches the rest.
    """
    for key in mapping[token]:
        if key in colors:
            value = colors[key]
            break
    else:
        value = type_defaults[token]

    out = _flatten(value, base, slug)
    return out

# ################################################################################################################################

def _render_css(slug:'str', theme_name:'str', meta:'anydict', tokens:'strdict') -> 'str':
    """ Renders one theme's css text, every token in the shared output order, in the
    shape make css leaves every other stylesheet in.
    """
    lines = [
        f'/* {theme_name} - generated by zato.common.webapp.ui.themes, do not edit.',
        f'   Source: themes-in/{slug}.json',
        f'   Origin: {meta["origin"]}',
        f'   License: {meta["license"]} */',
        f'html[data-theme="{slug}"] {{',
    ]
    for token in token_order:
        lines.append(f'    {token}: {tokens[token]};')
    lines.append('}')
    lines.append('')

    out = '\n'.join(lines)
    return out

# ################################################################################################################################

def convert_one(theme_path:'str', overrides_dir:'str') -> 'anydict':
    """ Converts one theme source into its css text plus metadata.
    """
    file_name = os.path.basename(theme_path)
    slug = os.path.splitext(file_name)[0]
    theme = load_theme(theme_path)

    # Every theme carries an overrides file, even one pinning nothing:
    # that is where its origin and license are recorded.
    overrides_path = os.path.join(overrides_dir, slug + '.json')
    if not os.path.exists(overrides_path):
        message = f'{slug}: missing {overrides_path}, every theme needs an overrides file' + \
            ' with its origin and license metadata, even when it pins no tokens'
        raise ThemeConversionError(message)

    with open(overrides_path) as overrides_file:
        overrides = json.load(overrides_file)

    meta = overrides['meta']
    for required in ('origin', 'license'):
        if required not in meta:
            raise ThemeConversionError(f'{slug}: overrides meta lacks {required!r}')

    theme_type = theme['type']
    if theme_type is None:

        # Some sources, VS Code's own high contrast files among them,
        # carry no type at all: the overrides meta must say it then.
        theme_type = meta.get('type')

    if theme_type not in ('dark', 'light'):
        raise ThemeConversionError(f'{slug}: theme type must be dark or light, got {theme_type!r}')

    # The overrides meta names the theme when it wants to: an imported source
    # keeps its upstream file untouched and is still listed under our own name.
    theme_name = meta.get('name')
    if theme_name is None:
        theme_name = theme['name']

    if theme_name is None:
        raise ThemeConversionError(f'{slug}: neither the theme file nor the overrides meta has a name')

    colors = theme['colors']
    type_defaults = defaults[theme_type]

    # The background is resolved first: translucent colors anywhere else
    # are flattened over it, and it itself flattens over pure black or
    # pure white if a theme should ever make it translucent ..
    if theme_type == 'dark':
        base = _dark_base
    else:
        base = _light_base

    background = _resolve_token('--background', colors, type_defaults, base, slug)
    resolved = {'--background': background}

    # .. the rest of the mapped tokens flatten over that background ..
    for token in mapping:
        if token not in resolved:
            resolved[token] = _resolve_token(token, colors, type_defaults, background, slug)

    # .. every pin is checked here, before anything is derived, so a typo in
    # an overrides file fails the run rather than reaching a theme file ..
    overridden = overrides['tokens']

    for token in overridden:
        if token not in token_order:
            raise ThemeConversionError(f'{slug}: overrides pin unknown token {token!r}')

    # .. a pin on a mapped token lands before the derived values, so pinning
    # an accent recolors the washes made of it and pinning a surface recolors
    # the mixes made of it ..
    for token, value in overridden.items():
        if token in mapping:
            resolved[token] = _flatten(value, background, slug)

    tokens:'strdict' = {}
    for token, rgb in resolved.items():
        tokens[token] = to_hex(rgb)

    # .. surfaces without a VS Code id come from mixes of resolved tokens ..
    for token, (from_token, to_token, ratio) in mixes.items():
        mixed = mix(resolved[from_token], resolved[to_token], ratio)
        tokens[token] = to_hex(mixed)

    # .. the problems panel must always be a different color: themes that
    # paint their panels with the very background color make the mix land
    # on the background itself, so it gets a wash of the text color over
    # the background instead ..
    problems_ratio = mixes['--problems-background'][2]
    problems = mix(background, resolved['--panel'], problems_ratio)
    distance = channel_distance(problems, background)
    if distance < min_surface_distance:
        washed = mix(background, resolved['--text'], surface_wash_ratio)
        tokens['--problems-background'] = to_hex(washed)

    # .. the translucent washes, same alphas for every theme ..
    for token, (source, alpha) in tints.items():
        red, green, blue = resolved[source]
        tokens[token] = f'rgba({red},{green},{blue},{alpha})'

    tokens.update(shadows[theme_type])

    # .. the rule name color and its wash, the same yellow in every theme ..
    tokens.update(rule_names[theme_type])

    # .. the wash of a marked element and the hover veil, the same in every theme, then
    # the action button surface and the link rule, each in the shade its kind calls for ..
    tokens.update(marks)
    tokens.update(actions[theme_type])
    tokens.update(links[theme_type])

    # .. the logo the theme is drawn with, the one its type calls for
    # unless its overrides meta names another file ..
    logo_file = meta.get('logo')
    if logo_file is None:
        logo_file = logos[theme_type]

    logo_path = os.path.join(_assets_dir, logo_file)
    if not os.path.exists(logo_path):
        raise ThemeConversionError(f'{slug}: no such logo file, {logo_path}')

    tokens['--logo'] = f"url('{logo_directory}/{logo_file}')"
    tokens['--logo-opacity'] = logo_opacity

    # .. and the pins on the derived tokens land last, the room for our own
    # customizations on top of any imported scheme.
    for token, value in overridden.items():
        if token not in mapping:
            tokens[token] = value

    css = _render_css(slug, theme_name, meta, tokens)

    out = {'slug': slug, 'name': theme_name, 'type': theme_type, 'css': css}
    return out

# ################################################################################################################################

def _theme_sort_key(theme:'anydict') -> 'sort_key_tuple':
    """ Our own themes lead the list in their own order, the rest stay alphabetical.
    """
    slug = theme['slug']

    if slug in _own_themes:
        rank = _own_themes.index(slug)
    else:
        rank = len(_own_themes)

    out = (rank, theme['name'])
    return out

# ################################################################################################################################

def _write_index(themes:'dictlist', out_index:'str') -> 'None':
    """ Writes the index the settings panel shows.
    """
    slugs = [theme['slug'] for theme in themes]

    # The pages are drawn in this theme until somebody picks another one,
    # so a run that would leave them pointing at a missing file stops here.
    if default_theme not in slugs:
        raise ThemeConversionError(f'the default theme {default_theme!r} is not among the converted ones, {slugs}')

    lines = [
        "'use strict';",
        '',
        '// Generated by zato.common.webapp.ui.themes, do not edit.',
        f"window.themesDefault = '{default_theme}';",
        'window.themesIndex = [',
    ]
    for theme in themes:
        entry = "    {{slug: '{slug}', name: '{name}', type: '{type}'}},".format(**theme)
        lines.append(entry)
    lines.append('];')
    lines.append('')

    with open(out_index, 'w') as index_file:
        _ = index_file.write('\n'.join(lines))

    print(f'wrote {out_index}')

# ################################################################################################################################

def _write_template(themes:'dictlist', out_template:'str') -> 'None':
    """ Writes the link tags webapp/base.html includes.
    """
    lines = ['{% load static %}{# Generated by zato.common.webapp.ui.themes, do not edit. #}']
    for theme in themes:
        line = '<link rel="stylesheet" href="{{% static \'webapp/css/themes/{slug}.css\' %}}">'.format(**theme)
        lines.append(line)
    lines.append('')

    with open(out_template, 'w') as template_file:
        _ = template_file.write('\n'.join(lines))

    print(f'wrote {out_template}')

# ################################################################################################################################

def convert_all(themes_dir:'str', out_css_dir:'str', out_index:'str', out_template:'str') -> 'None':
    """ Converts every theme source and writes the css files, the index
    and the template.
    """
    overrides_dir = os.path.join(themes_dir, 'overrides')

    theme_files:'strlist' = []
    for entry in sorted(os.listdir(themes_dir)):
        if not entry.endswith('.json'):
            continue
        entry_path = os.path.join(themes_dir, entry)
        if os.path.isfile(entry_path):
            theme_files.append(entry)

    if not theme_files:
        raise ThemeConversionError(f'no theme files in {themes_dir}')

    # Convert everything first, so a broken theme stops the run before
    # any file is written ..
    themes:'dictlist' = []

    for entry in theme_files:
        theme_path = os.path.join(themes_dir, entry)
        converted = convert_one(theme_path, overrides_dir)
        themes.append(converted)

    # .. our own themes lead the list, the rest stay alphabetical ..
    themes.sort(key=_theme_sort_key)

    # .. one css file per theme ..
    os.makedirs(out_css_dir, exist_ok=True)

    for theme in themes:
        css_path = os.path.join(out_css_dir, theme['slug'] + '.css')
        with open(css_path, 'w') as css_file:
            _ = css_file.write(theme['css'])
        print(f'wrote {css_path}')

    # .. and the two generated companions the pages load.
    _write_index(themes, out_index)
    _write_template(themes, out_template)

# ################################################################################################################################

def main() -> 'None':

    parser = argparse.ArgumentParser(description='VS Code themes to our theme css')
    _ = parser.add_argument('--themes-dir', default=_default_themes_dir)
    _ = parser.add_argument('--out-css-dir', default=_default_out_css_dir)
    _ = parser.add_argument('--out-index', default=_default_out_index)
    _ = parser.add_argument('--out-template', default=_default_out_template)
    args = parser.parse_args()

    convert_all(args.themes_dir, args.out_css_dir, args.out_index, args.out_template)

# ################################################################################################################################
# ################################################################################################################################

if __name__ == '__main__':
    main()

# ################################################################################################################################
# ################################################################################################################################
