from typing import Any, TYPE_CHECKING

from http.client import OK
from logging import getLogger
from traceback import format_exc
from kombu.connection import Connection as KombuConnection
from kombu.entity import Exchange, Queue
import requests
from requests.auth import HTTPBasicAuth
from zato.common.api import PubSub
from zato.common.pubsub.util import get_broker_config
from zato.common.util.api import new_cid_broker_client, wait_for_predicate
from zato.common.pubsub.common import BrokerConfig
from zato.common.typing_ import any_, dictlist, strdictnone, strlist, callable_


class BrokerConnection(KombuConnection):
    def ensure_connection(self: Any, *args: Any, **kwargs: Any) -> None: ...

class AMQP:
    def _wait_for_completion(self: Any, func: callable_, log_message: str, *args: any_, **kwargs: any_) -> any_: ...
    def _get_connection(self: Any, broker_config: BrokerConfig | None = ..., needs_ensure: bool = ...) -> BrokerConnection: ...
    def get_connection(self: Any, *args: Any, **kwargs: Any) -> BrokerConnection: ...
    def _create_bindings(self: Any, cid: str, sub_key: str, exchange_name: str, queue_name: str, routing_key: str, conn: BrokerConnection | None = ..., queue_arguments: strdictnone = ...) -> None: ...
    def create_bindings(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def _delete_bindings(self: Any, cid: str, sub_key: str, exchange_name: str, queue_name: str, routing_key: str, conn: BrokerConnection | None = ...) -> None: ...
    def delete_bindings(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def _delete_queue(self: Any, cid: str, queue_name: str) -> None: ...
    def delete_queue(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def _get_bindings(self: Any, cid: str, exchange_name: str) -> dictlist: ...
    def get_bindings(self: Any, *args: Any, **kwargs: Any) -> dictlist: ...
    def update_bindings(self: Any, cid: str, sub_key: str, exchange_name: str, queue_name: str, new_routing_key_list: strlist, conn: BrokerConnection | None = ...) -> dict: ...
    def _delete_topic(self: Any, cid: str, topic_name: str, exchange_name: str = ..., conn: BrokerConnection | None = ...) -> None: ...
    def delete_topic(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def get_bindings_by_queue(self: Any, cid: str, queue_name: str, exchange_name: str) -> dictlist: ...
    def queue_has_bindings(self: Any, cid: str, queue_name: str, exchange_name: str) -> bool: ...
    def get_bindings_by_routing_key(self: Any, cid: str, exchange_name: str, routing_key: str) -> dictlist: ...
    def _rename_topic(self: Any, cid: str, old_topic_name: str, new_topic_name: str, exchange_name: str, conn: BrokerConnection | None = ...) -> None: ...
    def rename_topic(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def _create_internal_queue(self: Any, queue_name: str) -> None: ...
    def create_internal_queue(self: Any, *args: Any, **kwargs: Any) -> None: ...
