from typing import Any

from contextlib import closing
from copy import deepcopy
from dataclasses import dataclass
from sqlalchemy import insert
from zato.common.api import GENERIC, Sec_Def_Type
from zato.common.odb.model import HTTPBasicAuth, SecurityBase
from zato.common.odb.query.common import get_object_list_by_columns, get_object_list_by_name_list
from zato.common.crypto.api import CryptoManager
from zato.common.typing_ import cast_
from zato.server.service import Model, Service
from sqlalchemy.orm.session import Session as SASession
from zato.common.typing_ import any_, dictlist, strdict

class ObjectContainer(Model):
    basic_auth: dictlist | None

class ItemsInfo(Model):
    to_add: dictlist
    to_update: dictlist

class ImportObjects(Service):
    name: Any
    def handle(self: Any) -> None: ...
    def _get_rest_conn_id_by_name(self: Any, name: str) -> int: ...
    def _get_rest_conn_id_by_item(self: Any, item: strdict) -> int | None: ...
    def _handle_basic_auth_input(self: Any, incoming: dictlist, existing: dictlist) -> ItemsInfo: ...
    def _get_basic_auth_realm_by_sec_name(self: Any, incoming: dictlist, name: str) -> str: ...
    def create_basic_auth(self: Any, session: SASession, values: dictlist, incoming: dictlist) -> None: ...
    def create_objects(self: Any, table: any_, values: dictlist) -> any_: ...
    def update_objects(self: Any, session: SASession, table: any_, values: dictlist) -> any_: ...
    def _find_items(self: Any, incoming: dictlist, existing: dictlist) -> ItemsInfo: ...
    def _get_sec_list(self: Any, session: SASession) -> dictlist: ...
    def _get_existing_data(self: Any, session: SASession) -> ObjectContainer: ...
