from typing import Any

from contextlib import closing
from sqlalchemy import and_, func, select
from zato.common.api import GENERIC, Groups, SEC_DEF_TYPE
from zato.common.groups import Member
from zato.common.odb.model import GenericObject as ModelGenericObject
from zato.common.odb.query.generic import GroupsWrapper
from zato.common.typing_ import any_, anydict, anylist, intnone, list_, strlist
from zato.server.base.parallel import ParallelServer

class GroupsManager:
    def __init__(self: Any, server: ParallelServer, session: any_ = ...) -> None: ...
    def create_group(self: Any, group_type: str, group_name: str) -> str: ...
    def edit_group(self: Any, group_id: int, group_type: str, group_name: str) -> None: ...
    def delete_group(self: Any, group_id: int) -> None: ...
    def get_group_list(self: Any, group_type: str) -> anylist: ...
    def get_member_list(self: Any, group_type: str, group_id: intnone = ...) -> list_[Member]: ...
    def get_member_count(self: Any, group_type: str) -> anydict: ...
    def add_members_to_group(self: Any, group_id: int, member_id_list: strlist) -> None: ...
    def remove_members_from_group(self: Any, group_id: str, member_id_list: strlist) -> None: ...
