from typing import Any

from logging import getLogger
from uuid import uuid4
from zato.common.api import Groups, Sec_Def_Type
from zato.common.crypto.api import is_string_equal
from zato.common.groups import Member
from zato.common.typing_ import anydict, boolnone, dict_, intanydict, intlist, intnone, intset, list_, strlist
from zato.server.base.parallel import ParallelServer

class _BasicAuthSecDef:
    security_id: int
    username: str
    password: str

class _APIKeySecDef:
    security_id: int
    header_value: str

class SecurityGroupsCtx:
    channel_id: int
    security_groups: intset
    group_to_sec_map: intanydict
    basic_auth_credentials: dict_[str, _BasicAuthSecDef]
    apikey_credentials: dict_[str, _APIKeySecDef]
    server: Any
    group_to_sec_map: Any
    security_groups: set
    basic_auth_credentials: Any
    apikey_credentials: Any
    _lock: RLock
    def __init__(self: Any, server: ParallelServer) -> None: ...
    def check_security_basic_auth(self: Any, cid: str, channel_name: str, username: str, password: str) -> intnone: ...
    def _get_basic_auth_by_security_id(self: Any, security_id: int) -> _BasicAuthSecDef | None: ...
    def _get_apikey_by_security_id(self: Any, security_id: int) -> _APIKeySecDef | None: ...
    def _has_security_id(self: Any, security_id: int) -> bool: ...
    def _after_auth_created(self: Any, group_id: int, security_id: int) -> None: ...
    def _after_auth_deleted(self: Any, security_id: int) -> None: ...
    def _create_basic_auth(self: Any, security_id: int, username: str, password: str) -> None: ...
    def _create_apikey(self: Any, security_id: int, header_value: str) -> None: ...
    def set_basic_auth(self: Any, security_id: int, username: str, password: str) -> None: ...
    def edit_apikey(self: Any, security_id: int, header_value: str) -> None: ...
    def _delete_basic_auth(self: Any, security_id: int) -> boolnone: ...
    def _delete_apikey(self: Any, security_id: int) -> boolnone: ...
    def delete_basic_auth(self: Any, security_id: int) -> None: ...
    def delete_apikey(self: Any, security_id: int) -> None: ...
    def check_security_apikey(self: Any, cid: str, channel_name: str, header_value: str) -> intnone: ...
    def _on_basic_auth_created(self: Any, group_id: int, security_id: int, username: str, password: str) -> None: ...
    def on_basic_auth_created(self: Any, group_id: int, security_id: int, username: str, password: str) -> None: ...
    def set_current_basic_auth(self: Any, security_id: int, current_username: str, password: str) -> None: ...
    def _on_basic_auth_deleted(self: Any, security_id: int) -> None: ...
    def on_basic_auth_deleted(self: Any, security_id: int) -> None: ...
    def _on_apikey_created(self: Any, group_id: int, security_id: int, header_value: str) -> None: ...
    def on_apikey_created(self: Any, group_id: int, security_id: int, header_value: str) -> None: ...
    def set_current_apikey(self: Any, security_id: int, header_value: str) -> None: ...
    def _on_apikey_deleted(self: Any, security_id: int) -> None: ...
    def on_apikey_deleted(self: Any, security_id: int) -> None: ...
    def on_group_deleted(self: Any, group_id: int) -> None: ...
    def _get_sec_def_by_id(self: Any, security_id: int) -> anydict: ...
    def _get_sec_def_type_by_id(self: Any, security_id: int) -> str: ...
    def has_members(self: Any) -> bool: ...
    def on_member_added_to_group(self: Any, group_id: int, security_id: int) -> None: ...
    def _on_member_removed_from_group(self: Any, group_id: int, security_id: int) -> None: ...
    def on_member_removed_from_group(self: Any, group_id: int, security_id: int) -> None: ...
    def on_group_assigned_to_channel(self: Any, group_id: int, members: list_[Member]) -> None: ...
    def on_group_unassigned_from_channel(self: Any, group_id: int) -> None: ...

class SecurityGroupsCtxBuilder:
    members: list_[Member]
    server: Any
    def __init__(self: Any, server: ParallelServer) -> None: ...
    def populate_members(self: Any) -> None: ...
    def _get_members_by_group_id(self: Any, group_id: int) -> list_[Member]: ...
    def build_ctx(self: Any, channel_id: int, security_groups: intlist) -> SecurityGroupsCtx: ...
