from typing import Any, TYPE_CHECKING

from __future__ import absolute_import, division, print_function, unicode_literals
import logging
from copy import deepcopy
from traceback import format_exc
from bunch import Bunch, bunchify
from zato.common.api import SECRET_SHADOW
from zato.common.dispatch import dispatcher
from zato.common.exception import Inactive
from zato.common.util.api import new_cid_server


class BasePoolAPI:
    get: Any
    create: Any
    _conn_store: Any
    def __init__(self: Any, conn_store: Any) -> None: ...
    def __getitem__(self: Any, name: Any) -> None: ...
    def create_def(self: Any, name: Any, msg: Any, on_connection_established_callback: Any = ..., *args: Any, **kwargs: Any) -> None: ...
    def edit_def(self: Any, name: Any, msg: Any, on_connection_established_callback: Any = ..., *args: Any, **kwargs: Any) -> None: ...
    def delete_def(self: Any, name: Any) -> None: ...
    def change_password_def(self: Any, config: Any) -> None: ...

class BaseConnPoolStore:
    conn_name: Any
    dispatcher_events: Any
    dispatcher_listen_for: Any
    _gevent: Any
    _RLock: Any
    sessions: Any
    lock: self._RLock
    keep_connecting: set
    dispatcher_backlog: Any
    def __init__(self: Any) -> None: ...
    def __getitem__(self: Any, name: Any) -> None: ...
    def get(self: Any, name: Any) -> None: ...
    def create_session(self: Any, name: Any, config: Any) -> None: ...
    def _log_connection_error(self: Any, name: Any, config_no_sensitive: Any, e: Any, additional: Any = ...) -> None: ...
    def get_config_no_sensitive(self: Any, config: Any) -> None: ...
    def _create(self: Any, name: Any, config: Any, on_connection_established_callback: Any = ..., *args: Any, **kwargs: Any) -> None: ...
    def create(self: Any, name: Any, config: Any, on_connection_established_callback: Any = ..., *args: Any, **kwargs: Any) -> None: ...
    def delete_session(self: Any, name: Any) -> None: ...
    def delete_session_hook(self: Any, session: Any) -> None: ...
    def delete(self: Any, name: Any) -> None: ...
    def edit(self: Any, name: Any, config: Any, on_connection_established_callback: Any = ..., *args: Any, **kwargs: Any) -> None: ...
    def change_password(self: Any, password_data: Any) -> None: ...
    def check_dispatcher_backlog(self: Any, item: Any) -> None: ...
    def dispatcher_callback(self: Any, event: Any, ctx: Any, **opaque: Any) -> None: ...
    def on_dispatcher_events(self: Any, events: Any) -> None: ...
