from typing import Any

import sys
from datetime import timedelta
from logging import getLogger
from socket import error as socket_error
from ssl import SSLError
from traceback import format_exc, format_tb
from urllib.parse import unquote, urlparse
from amqp import spec
from amqp.exceptions import ConsumerCancelled
from azure.servicebus import ServiceBusClient, ServiceBusMessage
from kombu import Connection, Consumer as KombuConsumer, pools, Queue
from kombu.transport.pyamqp import Connection as PyAMQPConnection, SSLTransport, Transport
from zato.common.api import AMQP, CHANNEL, PubSub, SECRET_SHADOW
from zato.common.pubsub.util import ConsumerManager, get_broker_config
from zato.common.typing_ import cast_
from zato.common.util.api import get_component_name, new_cid_queue_consumer, utcnow, wait_for_predicate
from zato.common.version import get_version
from zato.server.connection.connector import Connector, Inactive
from amqp.transport import TCPTransport
from bunch import Bunch
from kombu.connection import Connection as KombuAMQPConnection
from kombu.messaging import Producer as KombuProducer
from kombu.pools import ProducerPool as KombuProducerPool
from zato.common.typing_ import any_, callable_, strdict, strdictnone, strtuple, type_

def get_connection_class(object_name: str, suffix: str, is_tls: bool) -> type_[KombuAMQPConnection]: ...

def _is_tls_config(config: Bunch) -> bool: ...

def _is_azure_service_bus(address: str) -> bool: ...

def _build_azure_conn_string(address: str, username: str, password: str) -> str: ...

def _close_amqp_transport(connection: PyAMQPConnection) -> None: ...

def _do_close_connection(cid: str, connection: KombuAMQPConnection, max_wait_time: int) -> None: ...

def close_connection(cid: str, connection: KombuAMQPConnection, max_wait_time: int = ...) -> None: ...

class _AMQPMessage:
    __slots__: Any
    body: Any
    impl: Any
    def __init__(self: Any, body: Any, impl: Any) -> None: ...

class Producer:
    config: Any
    name: Any
    get_conn_class_func: Any
    conn: Any
    pool: _Producers
    def __init__(self: Any, config: Bunch) -> None: ...
    def acquire(self: Any, *args: Any, **kwargs: Any) -> KombuProducer: ...
    def stop(self: Any) -> None: ...

class AzureServiceBusProducer:
    config: Any
    name: Any
    client: ServiceBusClient.from_connection_string
    sender: self.client.get_queue_sender
    def __init__(self: Any, config: Bunch) -> None: ...
    def publish(self: Any, msg: str, **kwargs: any_) -> None: ...
    def stop(self: Any) -> None: ...

class _AzureMessageWrapper:
    _msg: Any
    _receiver: Any
    def __init__(self: Any, msg: Any, receiver: Any) -> None: ...
    def ack(self: Any) -> None: ...
    def reject(self: Any) -> None: ...

class AzureServiceBusConsumer:
    cid: new_cid_queue_consumer
    config: Any
    name: Any
    on_amqp_message: Any
    _keep_running: Any
    is_stopped: Any
    is_connected: Any
    start_called: Any
    client: Any
    receiver: Any
    def __init__(self: Any, config: Bunch, on_amqp_message: callable_) -> None: ...
    @property
    def keep_running(self: Any) -> bool: ...
    def keep_running(self: Any, value: bool) -> None: ...
    def start(self: Any) -> None: ...
    def stop(self: Any) -> None: ...
    def wait_until_connected(self: Any, timeout: int = ...) -> bool: ...
    def _is_connected(self: Any) -> bool: ...

class Consumer:
    cid: new_cid_queue_consumer
    config: Any
    name: Any
    queue: Any
    on_amqp_message: Any
    _keep_running: Any
    is_stopped: Any
    is_connected: Any
    timeout: Any
    consumer_manager: ConsumerManager
    start_called: Any
    def __init__(self: Any, config: Bunch, on_amqp_message: callable_) -> None: ...
    @property
    def keep_running(self: Any) -> bool: ...
    def keep_running(self: Any, value: bool) -> None: ...
    def _on_amqp_message(self: Any, body: Any, msg: Any) -> None: ...
    def _get_consumer(self: Any, always_log_when_connected: bool = ..., _no_ack: strdict = ..., _gevent_sleep: callable_ = ...) -> Consumer | None: ...
    def start(self: Any, conn_errors: Any = ..., _gevent_sleep: Any = ...) -> None: ...
    def stop(self: Any) -> None: ...
    def _is_connected(self: Any) -> bool: ...
    def wait_until_connected(self: Any, timeout: int = ...) -> bool: ...

class ConnectorAMQP(Connector):
    start_in_greenlet: Any
    should_log_started_stopped: Any
    def _get_conn_class(self: Any, suffix: Any, is_tls: Any) -> None: ...
    def _start(self: Any) -> None: ...
    def _start_azure(self: Any) -> None: ...
    def _start_amqp(self: Any) -> None: ...
    def _stop(self: Any) -> None: ...
    def on_amqp_message(self: Any, body: Any, msg: Any, channel_name: Any, channel_config: Any, _AMQPMessage: Any = ..., _CHANNEL_AMQP: Any = ..., _RECEIVED: Any = ..., _ZATO_ACK_MODE_ACK: Any = ...) -> None: ...
    def _add_auth_placeholders(self: Any, address: str) -> str: ...
    def _get_conn_string(self: Any, needs_password: bool = ...) -> str: ...
    def get_log_details(self: Any) -> None: ...
    def _enrich_channel_config(self: Any, config: Bunch) -> None: ...
    def create_channels(self: Any) -> None: ...
    def create_outconns(self: Any) -> None: ...
    def _create_consumer(self: Any, config: Bunch) -> None: ...
    def _create_producers(self: Any, config: Bunch) -> None: ...
    def _stop_consumers(self: Any) -> None: ...
    def _stop_producers(self: Any) -> None: ...
    def _create_channel(self: Any, config: Bunch) -> None: ...
    def create_channel(self: Any, config: Bunch) -> None: ...
    def edit_channel(self: Any, config: Bunch) -> None: ...
    def _delete_channel(self: Any, config: Any, delete_from_channels: Any = ...) -> None: ...
    def delete_channel(self: Any, config: Bunch) -> None: ...
    def _create_outconn(self: Any, config: Bunch) -> None: ...
    def create_outconn(self: Any, config: Bunch) -> None: ...
    def edit_outconn(self: Any, config: Bunch) -> None: ...
    def _delete_outconn(self: Any, config: Bunch) -> None: ...
    def delete_outconn(self: Any, config: Bunch) -> None: ...
    def invoke(self: Any, msg: str, exchange: str = ..., routing_key: str | None = ..., properties: strdictnone = ..., headers: strdictnone = ..., _default_out_keys: strtuple = ..., **kwargs: any_) -> None: ...
