from typing import Any

from base64 import b64encode
from logging import getLogger
from traceback import format_exc
from zato.cache import Cache as _CyCache
from zato.common.api import CACHE, ZATO_NOT_GIVEN
from zato.common.broker_message import CACHE as CACHE_BROKER_MSG
from zato.common.typing_ import cast_
from zato.common.util.api import as_bool
from zato.common.ext.future.utils import iteritems, itervalues
from zato.common.py23_.past.builtins import basestring
from zato.common.py23_ import pickle_dumps
from zato.common.typing_ import any_

class Cache:
    config: Any
    after_state_changed_callback: Any
    needs_sync: Any
    impl: _CyCache
    def __init__(self: Any, config: Any) -> None: ...
    def __getitem__(self: Any, key: Any) -> None: ...
    def __setitem__(self: Any, key: Any, value: Any) -> None: ...
    def __delitem__(self: Any, key: Any) -> None: ...
    def __contains__(self: Any, key: Any) -> None: ...
    def __len__(self: Any) -> None: ...
    def get(self: Any, key: Any, default: Any = ..., details: Any = ...) -> any_: ...
    def has_key(self: Any, key: Any, default: Any = ..., details: Any = ...) -> bool: ...
    def get_by_prefix(self: Any, key: Any, details: Any = ..., limit: Any = ...) -> None: ...
    def get_by_suffix(self: Any, key: Any, details: Any = ..., limit: Any = ...) -> None: ...
    def get_by_regex(self: Any, key: Any, details: Any = ..., limit: Any = ...) -> None: ...
    def get_contains(self: Any, key: Any, details: Any = ..., limit: Any = ...) -> None: ...
    def get_not_contains(self: Any, key: Any, details: Any = ..., limit: Any = ...) -> None: ...
    def get_contains_all(self: Any, key: Any, details: Any = ..., limit: Any = ...) -> None: ...
    def get_contains_any(self: Any, key: Any, details: Any = ..., limit: Any = ...) -> None: ...
    def set(self: Any, key: Any, value: Any, expiry: Any = ..., details: Any = ..., _OP: Any = ...) -> None: ...
    def set_by_prefix(self: Any, key: Any, value: Any, expiry: Any = ..., return_found: Any = ..., details: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def set_by_suffix(self: Any, key: Any, value: Any, expiry: Any = ..., return_found: Any = ..., details: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def set_by_regex(self: Any, key: Any, value: Any, expiry: Any = ..., return_found: Any = ..., details: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def set_contains(self: Any, key: Any, value: Any, expiry: Any = ..., return_found: Any = ..., details: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def set_not_contains(self: Any, key: Any, value: Any, expiry: Any = ..., return_found: Any = ..., details: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def set_contains_all(self: Any, key: Any, value: Any, expiry: Any = ..., return_found: Any = ..., details: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def set_contains_any(self: Any, key: Any, value: Any, expiry: Any = ..., return_found: Any = ..., details: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def delete(self: Any, key: Any, raise_key_error: Any = ..., _OP: Any = ...) -> None: ...
    def delete_by_prefix(self: Any, key: Any, return_found: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def delete_by_suffix(self: Any, key: Any, return_found: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def delete_by_regex(self: Any, key: Any, return_found: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def delete_contains(self: Any, key: Any, return_found: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def delete_not_contains(self: Any, key: Any, return_found: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def delete_contains_all(self: Any, key: Any, return_found: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def delete_contains_any(self: Any, key: Any, return_found: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def expire(self: Any, key: Any, expiry: Any = ..., _OP: Any = ...) -> None: ...
    def expire_by_prefix(self: Any, key: Any, expiry: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def expire_by_suffix(self: Any, key: Any, expiry: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def expire_by_regex(self: Any, key: Any, expiry: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def expire_contains(self: Any, key: Any, expiry: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def expire_not_contains(self: Any, key: Any, expiry: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def expire_contains_all(self: Any, key: Any, expiry: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def expire_contains_any(self: Any, key: Any, expiry: Any = ..., limit: Any = ..., _OP: Any = ...) -> None: ...
    def keys(self: Any) -> None: ...
    def iterkeys(self: Any) -> None: ...
    def values(self: Any) -> None: ...
    def itervalues(self: Any) -> None: ...
    def items(self: Any) -> None: ...
    def iteritems(self: Any) -> None: ...
    def clear(self: Any, _CLEAR: Any = ...) -> None: ...
    def update_config(self: Any, config: Any) -> None: ...
    def _delete_expired(self: Any, interval: Any = ..., _sleep: Any = ...) -> None: ...
    def sync_after_set(self: Any, data: Any) -> None: ...
    def sync_after_set_by_prefix(self: Any, data: Any) -> None: ...
    def sync_after_set_by_suffix(self: Any, data: Any) -> None: ...
    def sync_after_set_by_regex(self: Any, data: Any) -> None: ...
    def sync_after_set_contains(self: Any, data: Any) -> None: ...
    def sync_after_set_not_contains(self: Any, data: Any) -> None: ...
    def sync_after_set_contains_all(self: Any, data: Any) -> None: ...
    def sync_after_set_contains_any(self: Any, data: Any) -> None: ...
    def sync_after_delete(self: Any, data: Any) -> None: ...
    def sync_after_delete_by_prefix(self: Any, data: Any) -> None: ...
    def sync_after_delete_by_suffix(self: Any, data: Any) -> None: ...
    def sync_after_delete_by_regex(self: Any, data: Any) -> None: ...
    def sync_after_delete_contains(self: Any, data: Any) -> None: ...
    def sync_after_delete_not_contains(self: Any, data: Any) -> None: ...
    def sync_after_delete_contains_all(self: Any, data: Any) -> None: ...
    def sync_after_delete_contains_any(self: Any, data: Any) -> None: ...
    def sync_after_expire(self: Any, data: Any) -> None: ...
    def sync_after_expire_by_prefix(self: Any, data: Any) -> None: ...
    def sync_after_expire_by_suffix(self: Any, data: Any) -> None: ...
    def sync_after_expire_by_regex(self: Any, data: Any) -> None: ...
    def sync_after_expire_contains(self: Any, data: Any) -> None: ...
    def sync_after_expire_not_contains(self: Any, data: Any) -> None: ...
    def sync_after_expire_contains_all(self: Any, data: Any) -> None: ...
    def sync_after_expire_contains_any(self: Any, data: Any) -> None: ...
    def sync_after_clear(self: Any) -> None: ...

class _NotConfiguredAPI:
    get: Any
    def set(self: Any, *args: Any, **kwargs: Any) -> None: ...

class CacheAPI:
    server: Any
    lock: RLock
    default: cast_
    caches: Any
    builtin: Any
    def __init__(self: Any, server: Any) -> None: ...
    def _maybe_set_default(self: Any, config: Any, cache: Any) -> None: ...
    def after_state_changed(self: Any, op: Any, cache_name: Any, data: Any, _broker_msg: Any = ..., _pickle_dumps: Any = ...) -> None: ...
    def _create_builtin(self: Any, config: Any) -> None: ...
    def _add_cache(self: Any, config: Any, cache: Any) -> None: ...
    def _create(self: Any, config: Any) -> None: ...
    def create(self: Any, config: Any) -> None: ...
    def _edit(self: Any, config: Any) -> None: ...
    def edit(self: Any, config: Any) -> None: ...
    def _delete(self: Any, cache_type: Any, name: Any) -> None: ...
    def delete(self: Any, config: Any) -> None: ...
    def _clear(self: Any, cache_type: Any, name: Any) -> None: ...
    def clear(self: Any, cache_type: Any, name: Any) -> None: ...
    def _get_cache(self: Any, cache_type: str, name: str) -> Cache: ...
    def get_cache(self: Any, cache_type: str, name: str) -> Cache: ...
    def get_builtin_cache(self: Any, name: Any) -> None: ...
    def get_size(self: Any, cache_type: Any, name: Any) -> None: ...
    def sync_after_set(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_set_by_prefix(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_set_by_suffix(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_set_by_regex(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_set_contains(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_set_not_contains(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_set_contains_all(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_set_contains_any(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_delete(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_delete_by_prefix(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_delete_by_suffix(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_delete_by_regex(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_delete_contains(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_delete_not_contains(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_delete_contains_all(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_delete_contains_any(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_expire(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_expire_by_prefix(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_expire_by_suffix(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_expire_by_regex(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_expire_contains(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_expire_not_contains(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_expire_contains_all(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_expire_contains_any(self: Any, cache_type: Any, data: Any) -> None: ...
    def sync_after_clear(self: Any, cache_type: Any, data: Any) -> None: ...
