from typing import Any, TYPE_CHECKING

from copy import deepcopy
from datetime import datetime
from logging import getLogger
from traceback import format_exc
from zato.common.util.api import spawn_greenlet
from bunch import Bunch
from zato.common.typing_ import any_, dict_, dictnone, callable_, callnone, type_
from zato.common.model.connector import ConnectorConfig
from zato.server.base.parallel import ParallelServer


class Connector_Type:
    ...

class Inactive(Exception):
    ...

class EventLogger:
    enter_verb: Any
    exit_verb: Any
    enter_func: Any
    exit_func: Any
    predicate_func: Any
    def __init__(self: Any, enter_verb: Any, exit_verb: Any, enter_func: Any, exit_func: Any, predicate_func: Any = ...) -> None: ...
    def __enter__(self: Any) -> None: ...
    def __exit__(self: Any, *args: Any, **kwargs: Any) -> None: ...

class Connector:
    start_in_greenlet: Any
    should_log_started_stopped: Any
    _get_conn_string: Any
    get_prev_log_details: Any
    name: Any
    type: Any
    config: Any
    on_message_callback: Any
    auth_func: Any
    service: getattr
    channels: Any
    outconns: Any
    id: Any
    is_active: Any
    is_inactive: Any
    is_connected: Any
    keep_connecting: Any
    keep_running: Any
    lock: RLock
    id_self: hex
    conn: Any
    def __init__(self: Any, name: str, type: str, config: Bunch, on_message_callback: callable_, auth_func: callnone = ..., channels: dictnone = ..., outconns: dictnone = ..., parallel_server: ParallelServer | None = ...) -> None: ...
    def get_log_details(self: Any) -> str: ...
    def _start_loop(self: Any) -> None: ...
    def create_channels(self: Any) -> None: ...
    def create_outconns(self: Any) -> None: ...
    def create_channel(self: Any, config: Bunch) -> None: ...
    def edit_channel(self: Any, config: Bunch) -> None: ...
    def delete_channel(self: Any, config: Bunch) -> None: ...
    def create_outconn(self: Any, config: Bunch) -> None: ...
    def edit_outconn(self: Any, config: Bunch) -> None: ...
    def delete_outconn(self: Any, config: Bunch) -> None: ...
    def _start(self: Any) -> None: ...
    def _send(self: Any, msg: any_, *args: any_, **kwargs: any_) -> None: ...
    def send(self: Any, msg: any_, *args: any_, **kwargs: any_) -> None: ...
    def _start_stop_logger(self: Any, enter_verb: str, exit_verb: str, predicate_func: callnone = ...) -> EventLogger: ...
    def _info_start_stop(self: Any, verb: str, predicate: callnone = ...) -> None: ...
    def _wait_until_connected(self: Any) -> bool: ...
    def _spawn_start(self: Any) -> None: ...
    def start(self: Any, needs_log: bool = ...) -> None: ...
    def stop(self: Any) -> None: ...
    def _stop(self: Any) -> None: ...
    def get_conn_report(self: Any) -> None: ...

class ConnectorStore:
    type: Any
    connector_class: Any
    parallel_server: Any
    lock: RLock
    def __init__(self: Any, type: str, connector_class: type_, parallel_server: ParallelServer | None = ...) -> None: ...
    def _create(self: Any, name: str, config: Bunch, on_message_callback: callnone = ..., auth_func: callnone = ..., channels: dictnone = ..., outconns: dictnone = ..., needs_start: bool = ...) -> None: ...
    def create(self: Any, name: str, config: Bunch, on_message_callback: callnone = ..., auth_func: callnone = ..., channels: dictnone = ..., outconns: dictnone = ..., needs_start: bool = ...) -> None: ...
    def _edit(self: Any, old_name: str, config: Bunch) -> None: ...
    def edit(self: Any, old_name: str, config: Bunch, *ignored_args: Any) -> None: ...
    def _delete(self: Any, name: str) -> Connector: ...
    def delete(self: Any, name: str) -> Connector: ...
    def change_password(self: Any, name: str, config: Bunch) -> None: ...
    def create_channel(self: Any, name: str, config: Bunch) -> None: ...
    def edit_channel(self: Any, name: str, config: Bunch) -> None: ...
    def delete_channel(self: Any, name: str, config: Bunch) -> None: ...
    def create_outconn(self: Any, name: str, config: Bunch) -> None: ...
    def edit_outconn(self: Any, name: str, config: Bunch) -> None: ...
    def delete_outconn(self: Any, name: str, config: Bunch) -> None: ...
    def start(self: Any, name: str | None = ...) -> None: ...
    def invoke(self: Any, name: str, *args: any_, **kwargs: any_) -> None: ...
    def notify_pubsub_message(self: Any, name: str, *args: any_, **kwargs: any_) -> None: ...
