from typing import Any, TYPE_CHECKING

from base64 import b64decode
from contextlib import contextmanager
from io import BytesIO
from logging import getLogger, INFO
from mimetypes import guess_type as guess_mime_type
from traceback import format_exc
from zato.common.ext.imbox import Imbox as _Imbox
from zato.common.ext.imbox.imap import ImapTransport as _ImapTransport
from zato.common.ext.imbox.parser import parse_email, Struct
from zato.server.ext.outbox import AnonymousOutbox, Attachment, Email, Outbox
from zato.common.py23_.past.builtins import basestring, unicode
from zato.common.api import IMAPMessage, EMAIL
from zato.server.connection.cloud.microsoft_365 import Microsoft365Client
from zato.server.store import BaseAPI, BaseStore
from O365.mailbox import MailBox
from O365.message import Message as MS365Message
from zato.common.typing_ import any_, anylist


class GenericIMAPMessage(IMAPMessage):
    def delete(self: Any) -> None: ...
    def mark_seen(self: Any) -> None: ...

class Microsoft365IMAPMessage(IMAPMessage):
    impl: MS365Message
    def delete(self: Any) -> None: ...
    def mark_seen(self: Any) -> None: ...

class Imbox(_Imbox):
    config: Any
    config_no_sensitive: Any
    server: ImapTransport
    connection: self.server.connect
    def __init__(self: Any, config: Any, config_no_sensitive: Any) -> None: ...
    def __repr__(self: Any) -> None: ...
    def fetch_by_uid(self: Any, uid: Any) -> None: ...
    def search(self: Any, criteria: Any) -> None: ...
    def fetch_list(self: Any, criteria: Any) -> None: ...
    def close(self: Any) -> None: ...

class ImapTransport(_ImapTransport):
    def connect(self: Any, username: Any, password: Any, debug_level: Any) -> None: ...

class EMailAPI:
    smtp: Any
    imap: Any
    def __init__(self: Any, smtp: Any, imap: Any) -> None: ...

class _Connection:
    def __repr__(self: Any) -> None: ...

class SMTPConnection(_Connection):
    config: Any
    config_no_sensitive: Any
    conn_args: Any
    conn_class: Any
    def __init__(self: Any, config: Any, config_no_sensitive: Any) -> None: ...
    def send(self: Any, msg: Any, from_: Any = ...) -> bool: ...

class SMTPAPI(BaseAPI):
    ...

class SMTPConnStore(BaseStore):
    def create_impl(self: Any, config: Any, config_no_sensitive: Any) -> None: ...

class _IMAPConnection(_Connection):
    config: Any
    config_no_sensitive: Any
    def __init__(self: Any, config: Any, config_no_sensitive: Any) -> None: ...
    def get(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def ping(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def delete(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def mark_seen(self: Any, *args: Any, **kwargs: Any) -> None: ...

class GenericIMAPConnection(_IMAPConnection):
    def get_connection(self: Any) -> None: ...
    def get(self: Any, folder: Any = ...) -> None: ...
    def ping(self: Any) -> None: ...
    def delete(self: Any, *uids: Any) -> None: ...
    def mark_seen(self: Any, *uids: Any) -> None: ...

class Microsoft365IMAPConnection(_IMAPConnection):
    def _extract_list_of_addresses(self: Any, native_elem: any_) -> anylist: ...
    def _extract_attachments(self: Any, native_message: MS365Message) -> anylist: ...
    def _convert_to_imap_message(self: Any, msg_id: str, native_message: MS365Message) -> IMAPMessage: ...
    def _get_mailbox(self: Any) -> MailBox: ...
    def get(self: Any, folder: Any = ..., filter: Any = ...) -> None: ...
    def ping(self: Any) -> None: ...

class IMAPConnStore(BaseStore):
    _impl_class: Any
    def create_impl(self: Any, config: Any, config_no_sensitive: Any) -> None: ...

class IMAPAPI(BaseAPI):
    ...
