from typing import Any, TYPE_CHECKING

import os
from datetime import datetime, timedelta, timezone
from arrow import Arrow
from dateutil.parser import parse as dt_parse
from dateutil.tz.tz import tzutc
from requests import delete as requests_delete, get as requests_get, head as requests_head, patch as requests_patch, post as requests_post, put as requests_put
from zato.common.api import SCHEDULER
from zato.common.json_internal import dumps
from requests import Response
from zato.common.typing_ import any_, callnone
from zato.server.base.parallel import ParallelServer
from zato.server.config import ConfigDict
from zato.server.connection.http_soap.outgoing import HTTPSOAPWrapper
from zato.server.service import Service

_utz_utc = timezone.utc

class SchedulerFacade:
    server: Any
    def __init__(self: Any, server: ParallelServer) -> None: ...
    def onetime(self: Any, invoking_service: Any, target_service: Any, name: Any = ...) -> int: ...

class RESTFacade:
    cid: str
    _out_plain_http: ConfigDict
    name_prefix: str
    needs_facade: bool
    has_path_in_args: bool
    before_call_func: callnone
    after_call_func: callnone
    def init(self: Any, cid: str, _out_plain_http: ConfigDict) -> None: ...
    def delete(self: Any, *args: any_, **kwargs: any_) -> any_: ...
    def get(self: Any, *args: any_, **kwargs: any_) -> any_: ...
    def head(self: Any, *args: any_, **kwargs: any_) -> any_: ...
    def patch(self: Any, *args: any_, **kwargs: any_) -> any_: ...
    def post(self: Any, *args: any_, **kwargs: any_) -> any_: ...
    def put(self: Any, *args: any_, **kwargs: any_) -> any_: ...
    def _get(self: Any, orig_name: str, needs_prefix: bool = ...) -> RESTInvoker: ...
    def __getitem__(self: Any, name: str) -> RESTInvoker: ...
    def __getattr__(self: Any, attr_name: str) -> RESTInvoker: ...

class RESTInvoker:
    conn: Any
    container: Any
    send: Any
    def __init__(self: Any, conn: HTTPSOAPWrapper, container: RESTFacade) -> None: ...
    def call_rest_func(self: Any, func_name: str, conn_name: str, *args: any_, **kwargs: str) -> any_: ...
    def call_wrapper(self: Any, *args: any_, **kwargs: any_) -> any_: ...
    def get(self: Any, *args: any_, **kwargs: str) -> any_: ...
    def delete(self: Any, *args: any_, **kwargs: str) -> any_: ...
    def options(self: Any, *args: any_, **kwargs: str) -> any_: ...
    def post(self: Any, *args: any_, **kwargs: str) -> any_: ...
    def put(self: Any, *args: any_, **kwargs: str) -> any_: ...
    def patch(self: Any, *args: any_, **kwargs: str) -> any_: ...
    def ping(self: Any, *args: any_, **kwargs: str) -> any_: ...
    def upload(self: Any, *args: any_, **kwargs: str) -> any_: ...

class KeysightVisionFacade(RESTFacade):
    name_prefix: Any
    has_path_in_args: Any

class KeysightHawkeyeFacade(RESTFacade):
    name_prefix: Any
    has_path_in_args: Any
    def before_call_func(self: Any, func_name: Any, conn_name: Any, conn: Any, *args: Any, **kwargs: Any) -> any_: ...
    def after_call_func(self: Any, func_name: Any, conn_name: Any, conn: Any, result: Any, *args: Any, **kwargs: Any) -> any_: ...

class KeysightContainer:
    vision: KeysightVisionFacade
    hawkeye: KeysightHawkeyeFacade
    def init(self: Any, cid: str, _out_plain_http: ConfigDict) -> None: ...
