from typing import Any, TYPE_CHECKING

from __future__ import absolute_import, division, print_function, unicode_literals
import logging
from copy import deepcopy
from threading import RLock
from traceback import format_exc
from fs.ftpfs import FTPFS
from zato.common.api import SECRET_SHADOW, TRACE1
from zato.common.exception import Inactive
from zato.common.ext.future.utils import PY2


class FTPFacade(FTPFS):
    def conn(self: Any) -> None: ...

class FTPStore:
    conn_params: Any
    _lock: RLock
    def __init__(self: Any) -> None: ...
    def _add(self: Any, params: Any) -> None: ...
    def add_params(self: Any, params_list: Any) -> None: ...
    def get_conn_names(self: Any) -> None: ...
    def _get(self: Any, params: Any) -> None: ...
    def get(self: Any, name: Any) -> None: ...
    def get_by_id(self: Any, connection_id: Any) -> None: ...
    def create_edit(self: Any, params: Any, old_name: Any) -> None: ...
    def change_password(self: Any, name: Any, password: Any) -> None: ...
    def delete(self: Any, name: Any) -> None: ...
