from typing import Any, TYPE_CHECKING

from logging import getLogger
from zato.distlock import PassThrough as PassThroughLock
from zato.common.typing_ import any_, anylist, callable_
from zato.distlock import Lock
from zato.server.base.parallel import ParallelServer


class ConnectionPoolWrapper:
    type_: Any
    items: Any
    server: Any
    def __init__(self: Any, server: ParallelServer, type_: str) -> None: ...
    def _lock(self: Any, config_id: any_) -> Lock: ...
    def get_update_lock(self: Any) -> callable_: ...
    def get_func_call_lock(self: Any) -> callable_: ...
    def add_item(self: Any) -> None: ...
    def delete_all(self: Any) -> None: ...
    def has_item(self: Any) -> bool: ...
    def delete_item(self: Any) -> None: ...
