from typing import Any

from logging import getLogger
from datetime import datetime, timedelta
from time import sleep
from traceback import format_exc
from zato.common.api import GENERIC as COMMON_GENERIC
from zato.common.typing_ import cast_
from zato.common.util.config import resolve_name, replace_query_string_items
from zato.common.util.python_ import get_python_id
from zato.common.util.time_ import utcnow
from logging import Logger
from bunch import Bunch
from zato.common.typing_ import any_, callable_, intnone, strnone
from zato.server.base.parallel import ParallelServer

class _Connection:
    client_queue: Queue
    conn_name: str
    should_block: bool
    block_timeout: intnone
    client: any_
    def __init__(self: Any, client_queue: Queue, conn_name: str, should_block: bool = ..., block_timeout: intnone = ...) -> None: ...
    def __enter__(self: Any) -> None: ...
    def __exit__(self: Any, _type: any_, _value: any_, _traceback: any_) -> None: ...

class ConnectionQueue:
    is_active: bool
    queue: Queue
    queue_build_cap: int
    queue_max_size: int
    conn_id: int
    conn_name: str
    conn_type: str
    address: str
    add_client_func: callable_
    needs_spawn: bool
    max_attempts: int
    keep_connecting: bool
    is_building_conn_queue: bool
    queue_building_stopped: bool
    lock: RLock
    logger: Logger
    in_progress_count: int
    def __init__(self: Any, server: ParallelServer, is_active: bool, pool_size: int, queue_build_cap: int, conn_id: int, conn_name: str, conn_type: str, address: str, add_client_func: callable_, needs_spawn: bool = ..., max_attempts: int = ...) -> None: ...
    def __call__(self: Any, should_block: bool = ..., block_timeout: intnone = ...) -> _Connection: ...
    def put_client(self: Any, client: any_) -> bool: ...
    def connection_exists(self: Any) -> bool: ...
    def should_keep_connecting(self: Any) -> None: ...
    def _build_queue(self: Any) -> None: ...
    def _spawn_add_client_func_no_lock(self: Any, count: int) -> None: ...
    def _spawn_add_client_func(self: Any, count: int = ...) -> None: ...
    def decr_in_progress_count(self: Any) -> None: ...
    def is_in_progress(self: Any) -> bool: ...
    def build_queue(self: Any) -> None: ...

class Wrapper:
    has_delete_reasons: Any
    supports_reconnections: Any
    build_wrapper: Any
    def __init__(self: Any, config: Bunch, conn_type: str, server: ParallelServer) -> None: ...
    def add_client(self: Any) -> None: ...
    def build_queue(self: Any) -> None: ...
    def _get_item_name(self: Any, item: any_) -> str: ...
    def delete_in_progress_connections(self: Any, reason: strnone = ...) -> None: ...
    def delete_queue_connections(self: Any, reason: strnone = ...) -> None: ...
    def delete(self: Any, reason: strnone = ...) -> None: ...
