from typing import Any

import importlib
import inspect
import logging
import os
import sys
from dataclasses import dataclass
from datetime import datetime
from functools import total_ordering
from hashlib import sha256
from importlib import import_module
from inspect import getmodule, getmro, getsourcefile, isclass
from random import randint
from shutil import copy as shutil_copy
from traceback import format_exc
from typing import Any, List
from humanize import naturalsize
from zato.common.api import DONT_DEPLOY_ATTR_NAME, SourceCodeInfo, TRACE1
from zato.common.facade import SecurityFacade
from zato.common.json_internal import dumps
from zato.common.marshal_.api import Model as DataClassModel
from zato.common.marshal_.simpleio import DataClassSimpleIO
from zato.common.odb.model.base import Base as ModelBase
from zato.common.typing_ import cast_, list_
from zato.common.util.api import deployment_info, import_module_from_path, is_python_file, visit_py_source
from zato.common.util.python_ import get_module_name_by_path
from zato.common.util.time_ import utcnow
from zato.server.config import ConfigDict
from zato.server.service import PubSubHook, SchedulerFacade, Service
from zato.server.service.internal import AdminService
from zato.simpleio import CySimpleIO
from yaml import CDumper
from sqlalchemy.orm.session import Session as SASession
from zato.common.hot_deploy_ import HotDeployProject
from zato.common.odb.api import ODBManager
from zato.common.typing_ import any_, anydict, anylist, callable_, intstrdict, module_, stranydict, strdictdict, strint, strintdict, strlist, stroriter, tuple_
from zato.server.base.parallel import ParallelServer
from zato.server.base.worker import WorkerStore
from zato.server.config import ConfigStore
from yaml import Dumper

class _TestingWorkerStore:
    sql_pool_store: Any
    outconn_ldap: Any
    outconn_mongodb: Any
    email_smtp_api: Any
    email_imap_api: Any
    search_es_api: Any
    cache_api: Any
    def __init__(self: Any) -> None: ...

class _TestingWorkerConfig:
    out_odoo: Any
    out_soap: Any
    out_sap: Any

class InRAMService:
    cluster_id: int
    id: int
    impl_name: str
    name: str
    deployment_info: str
    service_class: type[Service]
    is_active: bool
    is_internal: bool
    slow_threshold: int
    source_code_info: SourceCodeInfo
    def __repr__(self: Any) -> str: ...
    def __eq__(self: Any, other: InRAMService) -> bool: ...
    def __lt__(self: Any, other: InRAMService) -> bool: ...
    def __hash__(self: Any) -> int: ...
    def to_dict(self: Any) -> stranydict: ...

class ModelInfo:
    name: str
    path: str
    mod_name: str
    source: str

class DeploymentInfo:
    __slots__: Any
    def __init__(self: Any) -> None: ...

def get_service_name(class_obj: type[Service]) -> str: ...

def get_batch_indexes(services: inramlist, max_batch_size: int) -> anylist: ...

class ServiceStore:
    services: stranydict
    odb: ODBManager
    server: ParallelServer
    is_testing: bool
    def __init__(self: Any) -> None: ...
    def edit_service_data(self: Any, config: stranydict) -> None: ...
    def _delete_service_from_odb(self: Any, service_id: int) -> None: ...
    def _delete_service_data(self: Any, name: str, delete_from_odb: bool = ...) -> None: ...
    def delete_service_data(self: Any, name: str) -> None: ...
    def _delete_model_data(self: Any, name: str) -> None: ...
    def delete_model_data(self: Any, name: str) -> None: ...
    def _collect_objects_by_file_path(self: Any, file_path: str, container: stranydict) -> strlist: ...
    def delete_objects_by_file_path(self: Any, file_path: str) -> None: ...
    def post_deploy(self: Any, class_: type[Service]) -> None: ...
    def _has_io_data_class(self: Any, class_: type[Service], msg_class: any_, msg_type: str) -> bool: ...
    def set_up_class_attributes(self: Any, class_: type[Service], service_store: ServiceStore) -> None: ...
    def has_sio(self: Any, service_name: str) -> bool: ...
    def get_service_info_by_id(self: Any, service_id: strint) -> stranydict: ...
    def get_service_id_by_name(self: Any, service_name: str) -> int: ...
    def get_service_name_by_id(self: Any, service_id: int) -> str: ...
    def get_deployment_info(self: Any, impl_name: str) -> anydict: ...
    def has_service(self: Any, service_name: str) -> bool: ...
    def new_instance(self: Any, impl_name: str, *args: any_, **kwargs: any_) -> tuple_[Service, bool]: ...
    def new_instance_by_id(self: Any, service_id: int, *args: any_, **kwargs: any_) -> tuple_[Service, bool]: ...
    def new_instance_by_name(self: Any, name: str, *args: any_, **kwargs: any_) -> tuple_[Service, bool]: ...
    def service_data(self: Any, impl_name: str) -> stranydict: ...
    def is_deployed(self: Any, name: str) -> bool: ...
    def import_internal_services(self: Any, items: Any, base_dir: Any, sync_internal: Any) -> anylist: ...
    def _store_in_ram(self: Any, session: SASession | None, to_process: inramlist) -> None: ...
    def _store_services_in_odb(self: Any, session: Any, batch_indexes: Any, to_process: Any) -> bool: ...
    def _should_delete_deployed_service(self: Any, service: InRAMService, already_deployed: stranydict) -> bool: ...
    def _store_deployed_services_in_odb(self: Any, session: Any, batch_indexes: Any, to_process: Any) -> None: ...
    def _store_in_odb(self: Any, session: SASession | None, to_process: inramlist) -> None: ...
    def get_basic_data_services(self: Any, session: SASession) -> anydict: ...
    def get_basic_data_deployed_services(self: Any) -> anydict: ...
    def import_services_from_anywhere(self: Any, items: Any, base_dir: Any, is_internal: Any = ...) -> DeploymentInfo: ...
    def after_import(self: Any, session: SASession | None, info: DeploymentInfo) -> None: ...
    def _should_ignore_file(self: Any, file_name: str, base_dir: str) -> bool: ...
    def import_objects_from_file(self: Any, file_name: Any, is_internal: Any, base_dir: Any, visit_func: Any) -> anylist: ...
    def import_models_from_directory(self: Any, dir_name: str, base_dir: str) -> modelinfolist: ...
    def import_models_from_file(self: Any, file_name: Any, is_internal: Any, base_dir: Any) -> modelinfolist: ...
    def import_services_from_file(self: Any, file_name: str, is_internal: bool, base_dir: str) -> anylist: ...
    def import_services_from_directory(self: Any, dir_name: str, base_dir: str) -> anylist: ...
    def import_services_from_module(self: Any, mod_name: str, is_internal: bool) -> anylist: ...
    def import_services_from_module_object(self: Any, mod: module_, is_internal: bool) -> anylist: ...
    def _has_module_import(self: Any, source_code: str, mod_name: str) -> bool: ...
    def _get_service_module_imports(self: Any, mod_name: str) -> strlist: ...
    def _get_model_module_imports(self: Any, mod_name: str) -> strlist: ...
    def get_module_importers(self: Any, mod_name: str) -> strlist: ...
    def _should_deploy_model(self: Any, name: str, item: any_, current_module: module_, fs_location: str) -> bool: ...
    def _should_deploy_service(self: Any, name: str, item: any_, current_module: module_, fs_location: str) -> bool: ...
    def _get_source_code_info(self: Any, mod: any_, class_: any_) -> SourceCodeInfo: ...
    def _visit_class_for_model(self: Any, _ignored_mod: Any, class_: Any, fs_location: Any, _ignored_is_internal: Any) -> ModelInfo: ...
    def _visit_class_for_service(self: Any, mod: Any, class_: Any, fs_location: Any, is_internal: Any) -> InRAMService: ...
    def on_worker_initialized(self: Any) -> None: ...
    def redeploy_on_parent_changed(self: Any, changed_service_name: str, changed_service_impl_name: str) -> None: ...
    def _visit_module_for_objects(self: Any, mod: Any, is_internal: Any, fs_location: Any, should_deploy_func: Any, visit_class_func: Any, needs_before_add_to_store_result: Any) -> anylist: ...
    def _visit_module_for_models(self: Any, mod: module_, is_internal: bool, fs_location: str) -> anylist: ...
    def _visit_module_for_services(self: Any, mod: module_, is_internal: bool, fs_location: str) -> anylist: ...
