# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import billing_pb2 as billing__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in billing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BillingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInvoice = channel.unary_unary(
                '/billing.BillingService/GetInvoice',
                request_serializer=billing__pb2.InvoiceRequest.SerializeToString,
                response_deserializer=billing__pb2.Invoice.FromString,
                _registered_method=True)
        self.ListInvoices = channel.unary_stream(
                '/billing.BillingService/ListInvoices',
                request_serializer=billing__pb2.InvoiceListRequest.SerializeToString,
                response_deserializer=billing__pb2.Invoice.FromString,
                _registered_method=True)
        self.SubmitPayments = channel.stream_unary(
                '/billing.BillingService/SubmitPayments',
                request_serializer=billing__pb2.Payment.SerializeToString,
                response_deserializer=billing__pb2.PaymentSummary.FromString,
                _registered_method=True)
        self.ReconcilePayments = channel.stream_stream(
                '/billing.BillingService/ReconcilePayments',
                request_serializer=billing__pb2.Payment.SerializeToString,
                response_deserializer=billing__pb2.PaymentReceipt.FromString,
                _registered_method=True)


class BillingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetInvoice(self, request, context):
        """Unary in, unary out.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInvoices(self, request, context):
        """Unary in, streaming out.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitPayments(self, request_iterator, context):
        """Streaming in, unary out.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReconcilePayments(self, request_iterator, context):
        """Streaming in, streaming out.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInvoice,
                    request_deserializer=billing__pb2.InvoiceRequest.FromString,
                    response_serializer=billing__pb2.Invoice.SerializeToString,
            ),
            'ListInvoices': grpc.unary_stream_rpc_method_handler(
                    servicer.ListInvoices,
                    request_deserializer=billing__pb2.InvoiceListRequest.FromString,
                    response_serializer=billing__pb2.Invoice.SerializeToString,
            ),
            'SubmitPayments': grpc.stream_unary_rpc_method_handler(
                    servicer.SubmitPayments,
                    request_deserializer=billing__pb2.Payment.FromString,
                    response_serializer=billing__pb2.PaymentSummary.SerializeToString,
            ),
            'ReconcilePayments': grpc.stream_stream_rpc_method_handler(
                    servicer.ReconcilePayments,
                    request_deserializer=billing__pb2.Payment.FromString,
                    response_serializer=billing__pb2.PaymentReceipt.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'billing.BillingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('billing.BillingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BillingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/billing.BillingService/GetInvoice',
            billing__pb2.InvoiceRequest.SerializeToString,
            billing__pb2.Invoice.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInvoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/billing.BillingService/ListInvoices',
            billing__pb2.InvoiceListRequest.SerializeToString,
            billing__pb2.Invoice.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitPayments(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/billing.BillingService/SubmitPayments',
            billing__pb2.Payment.SerializeToString,
            billing__pb2.PaymentSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReconcilePayments(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/billing.BillingService/ReconcilePayments',
            billing__pb2.Payment.SerializeToString,
            billing__pb2.PaymentReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
