# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: billing.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'billing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbilling.proto\x12\x07\x62illing\"$\n\x0eInvoiceRequest\x12\x12\n\ninvoice_id\x18\x01 \x01(\t\"\'\n\x12InvoiceListRequest\x12\x11\n\tmax_items\x18\x01 \x01(\x05\"E\n\x07Invoice\x12\x12\n\ninvoice_id\x18\x01 \x01(\t\x12\x10\n\x08\x63ustomer\x18\x02 \x01(\t\x12\x14\n\x0c\x61mount_cents\x18\x03 \x01(\x03\"3\n\x07Payment\x12\x12\n\ninvoice_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61mount_cents\x18\x02 \x01(\x03\"<\n\x0ePaymentSummary\x12\x15\n\rpayment_count\x18\x01 \x01(\x05\x12\x13\n\x0btotal_cents\x18\x02 \x01(\x03\"8\n\x0ePaymentReceipt\x12\x12\n\ninvoice_id\x18\x01 \x01(\t\x12\x12\n\nis_settled\x18\x02 \x01(\x08\x32\x95\x02\n\x0e\x42illingService\x12\x39\n\nGetInvoice\x12\x17.billing.InvoiceRequest\x1a\x10.billing.Invoice\"\x00\x12\x41\n\x0cListInvoices\x12\x1b.billing.InvoiceListRequest\x1a\x10.billing.Invoice\"\x00\x30\x01\x12?\n\x0eSubmitPayments\x12\x10.billing.Payment\x1a\x17.billing.PaymentSummary\"\x00(\x01\x12\x44\n\x11ReconcilePayments\x12\x10.billing.Payment\x1a\x17.billing.PaymentReceipt\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'billing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVOICEREQUEST']._serialized_start=26
  _globals['_INVOICEREQUEST']._serialized_end=62
  _globals['_INVOICELISTREQUEST']._serialized_start=64
  _globals['_INVOICELISTREQUEST']._serialized_end=103
  _globals['_INVOICE']._serialized_start=105
  _globals['_INVOICE']._serialized_end=174
  _globals['_PAYMENT']._serialized_start=176
  _globals['_PAYMENT']._serialized_end=227
  _globals['_PAYMENTSUMMARY']._serialized_start=229
  _globals['_PAYMENTSUMMARY']._serialized_end=289
  _globals['_PAYMENTRECEIPT']._serialized_start=291
  _globals['_PAYMENTRECEIPT']._serialized_end=347
  _globals['_BILLINGSERVICE']._serialized_start=350
  _globals['_BILLINGSERVICE']._serialized_end=627
# @@protoc_insertion_point(module_scope)
