from typing import Any

import os
import shutil
from base64 import b64decode
from dataclasses import dataclass
from errno import ENOENT
from time import sleep
from traceback import format_exc
from bunch import Bunch
from zato.common.typing_ import cast_
from zato.common.util.api import is_python_file, is_archive_file, publish_file
from zato.common.util.file_system import fs_safe_now
from zato.common.util.open_ import open_w
from zato.common.util.python_ import import_module_by_path
from zato.server.service import AsIs
from zato.server.service.internal import AdminService, AdminSIO
from zato.common.typing_ import any_, anylist, anylistnone, commoniter, intlist, strbytes, strlist, strset
from zato.server.service.store import InRAMService

class DeploymentCtx:
    model_name_list: strlist
    service_id_list: intlist
    service_name_list: strlist

class Create(AdminService):
    def _delete(self: Any, items: commoniter) -> None: ...
    def _backup_last(self: Any, fs_now: str, current_work_dir: str, backup_format: str, last_backup_work_dir: str) -> None: ...
    def _backup_linear_log(self: Any, fs_now: Any, current_work_dir: Any, backup_format: Any, backup_work_dir: Any, backup_history: Any) -> None: ...
    def backup_current_work_dir(self: Any) -> None: ...
    def _redeploy_module_dependencies(self: Any, file_name: str) -> None: ...
    def _deploy_models(self: Any, current_work_dir: str, model_file_name: str) -> strset: ...
    def _deploy_services(self: Any, current_work_dir: str, service_file_name: str) -> intlist: ...
    def _deploy_file(self: Any, current_work_dir: Any, payload: Any, file_name: Any, should_deploy_in_place: Any) -> DeploymentCtx: ...
    def _deploy_package(self: Any, payload: Any, payload_name: Any) -> anylistnone: ...
    def _report_deployment(self: Any, file_name: str, items: anylist, noun: str) -> None: ...
    def deploy_package(self: Any, payload: str, payload_name: str) -> any_: ...
    def handle(self: Any) -> None: ...
