from typing import Any

from numbers import Integral
from zato.common.py23_.past.utils import PY2, with_metaclass
from collections import Iterable
from collections.abc import Iterable

class BaseOldStr(type):
    def __instancecheck__(cls: Any, instance: Any) -> None: ...

def unescape(s: Any) -> None: ...

class oldstr(with_metaclass):
    @property
    def __iter__(self: Any) -> None: ...
    def __dir__(self: Any) -> None: ...
    def __repr__(self: Any) -> None: ...
    def __str__(self: Any) -> None: ...
    def __getitem__(self: Any, y: Any) -> None: ...
    def __getslice__(self: Any, *args: Any) -> None: ...
    def __contains__(self: Any, key: Any) -> None: ...
    def __native__(self: Any) -> None: ...
