from typing import Any, TYPE_CHECKING

from django.template.response import TemplateResponse
from zato.admin.web.views import method_allowed
from zato.admin.web.views.settings.handlers import RestartHandler


class SettingsBaseView:
    page_config: Any
    updater: Any
    template_name: Any
    restart_handler: RestartHandler
    def __init__(self: Any, page_config: Any, updater: Any, template_name: Any) -> None: ...
    def get_index_context(self: Any) -> None: ...
    def index(self: Any, req: Any) -> None: ...
    def restart_scheduler(self: Any, req: Any) -> None: ...
    def restart_server(self: Any, req: Any) -> None: ...
    def restart_proxy(self: Any, req: Any) -> None: ...
    def restart_dashboard(self: Any, req: Any) -> None: ...
