from typing import Any

from logging import getLogger
from zato.admin.web.views.settings.utils import json_response, restart_component
import subprocess
import threading
import os
from zato.common.json_internal import loads
import time
import redis
import requests

class RestartHandler:
    def __init__(self: Any, updater: Any) -> None: ...
    def _restart(self: Any, req: Any, component_name: Any) -> None: ...
    def restart_scheduler(self: Any, req: Any) -> None: ...
    def restart_server(self: Any, req: Any) -> None: ...
    def restart_proxy(self: Any, req: Any) -> None: ...
    def restart_dashboard(self: Any, req: Any) -> None: ...

class ScheduleHandler:
    def __init__(self: Any, updater: Any) -> None: ...
    def save(self: Any, req: Any) -> None: ...
    def load(self: Any, req: Any) -> None: ...
    def delete(self: Any, req: Any) -> None: ...

class AuditLogHandler:
    def __init__(self: Any, updater: Any) -> None: ...
    def get_latest_entry(self: Any, req: Any) -> None: ...
    def get_refresh(self: Any, req: Any) -> None: ...
