from typing import Any, TYPE_CHECKING

import logging
from zato.cli.enmasse.config import ModuleCtx
from zato.cli.enmasse.exporters.cache import CacheExporter
from zato.cli.enmasse.exporters.email_imap import IMAPExporter
from zato.cli.enmasse.exporters.email_smtp import SMTPExporter
from zato.cli.enmasse.exporters.group import GroupExporter
from zato.cli.enmasse.exporters.odoo import OdooExporter
from zato.cli.enmasse.exporters.scheduler import SchedulerExporter
from zato.cli.enmasse.exporters.security import SecurityExporter
from zato.cli.enmasse.exporters.sql import SQLExporter
from zato.cli.enmasse.exporters.channel_rest import ChannelExporter
from zato.cli.enmasse.exporters.channel_openapi import ChannelOpenAPIExporter
from zato.cli.enmasse.exporters.jira import JiraExporter
from zato.cli.enmasse.exporters.ldap import LDAPExporter
from zato.cli.enmasse.exporters.microsoft_365 import Microsoft365Exporter
from zato.cli.enmasse.exporters.confluence import ConfluenceExporter
from zato.cli.enmasse.exporters.es import ElasticSearchExporter
from zato.cli.enmasse.exporters.outgoing_rest import OutgoingRESTExporter
from zato.cli.enmasse.exporters.outgoing_soap import OutgoingSOAPExporter
from zato.cli.enmasse.exporters.pubsub_topic import PubSubTopicExporter
from zato.cli.enmasse.exporters.pubsub_permission import PubSubPermissionExporter
from zato.cli.enmasse.exporters.pubsub_subscription import PubSubSubscriptionExporter
from zato.common.odb.model import Cluster
from sqlalchemy.orm.session import Session as SASession
from zato.common.typing_ import any_, stranydict


class EnmasseYAMLExporter:
    cluster_id: Any
    cache_exporter: CacheExporter
    email_imap_exporter: IMAPExporter
    email_smtp_exporter: SMTPExporter
    group_exporter: GroupExporter
    odoo_exporter: OdooExporter
    scheduler_exporter: SchedulerExporter
    security_exporter: SecurityExporter
    sql_exporter: SQLExporter
    channel_exporter: ChannelExporter
    jira_exporter: JiraExporter
    ldap_exporter: LDAPExporter
    microsoft_365_exporter: Microsoft365Exporter
    confluence_exporter: ConfluenceExporter
    elastic_search_exporter: ElasticSearchExporter
    outgoing_rest_exporter: OutgoingRESTExporter
    outgoing_soap_exporter: OutgoingSOAPExporter
    pubsub_topic_exporter: PubSubTopicExporter
    pubsub_permission_exporter: PubSubPermissionExporter
    pubsub_subscription_exporter: PubSubSubscriptionExporter
    channel_openapi_exporter: ChannelOpenAPIExporter
    def __init__(self: Any) -> None: ...
    def get_cluster(self: Any, session: SASession) -> any_: ...
    def export_cache(self: Any, session: SASession) -> list: ...
    def export_odoo(self: Any, session: SASession) -> list: ...
    def export_scheduler(self: Any, session: SASession) -> list: ...
    def export_sql(self: Any, session: SASession) -> list: ...
    def export_security(self: Any, session: SASession) -> list: ...
    def export_email_imap(self: Any, session: SASession) -> list: ...
    def export_email_smtp(self: Any, session: SASession) -> list: ...
    def export_groups(self: Any, session: SASession) -> list: ...
    def export_channel_rest(self: Any, session: SASession) -> list: ...
    def export_outgoing_rest(self: Any, session: SASession) -> list: ...
    def export_outgoing_soap(self: Any, session: SASession) -> list: ...
    def export_jira(self: Any, session: SASession) -> list: ...
    def export_ldap(self: Any, session: SASession) -> list: ...
    def export_microsoft_365(self: Any, session: SASession) -> list: ...
    def export_confluence(self: Any, session: SASession) -> list: ...
    def export_elastic_search(self: Any, session: SASession) -> list: ...
    def export_pubsub_topic(self: Any, session: SASession) -> list: ...
    def export_pubsub_permission(self: Any, session: SASession) -> list: ...
    def export_pubsub_subscription(self: Any, session: SASession) -> list: ...
    def export_channel_openapi(self: Any, session: SASession) -> list: ...
    def export_to_dict(self: Any, session: SASession) -> stranydict: ...
