from typing import Any, TYPE_CHECKING

import logging
import os
import uuid
from zato.common.util.api import asbool
from zato.common.util.sql import get_security_by_id
from sqlalchemy.orm.session import Session as SASession
from zato.cli.enmasse.importer import EnmasseYAMLImporter
from zato.common.odb.model import HTTPSOAP
from zato.common.typing_ import any_, anydict, bool_, strdict


def get_engine_from_type(raw_type: str) -> str: ...

def get_type_from_engine(engine: str) -> str: ...

def security_needs_update(yaml_item: anydict, db_def: anydict, importer: EnmasseYAMLImporter) -> bool_: ...

def get_value_from_environment(value: any_) -> str: ...

def preprocess_item(item: strdict) -> any_: ...

def assign_security(item: HTTPSOAP, item_def: anydict, importer: EnmasseYAMLImporter, session: SASession) -> None: ...

def reorder_fields(fields: anydict) -> anydict: ...

def get_top_level_order() -> strlist: ...

def get_object_order(object_type: str) -> strlist: ...

class FileWriter:
    path: Any
    def __init__(self: Any, path: str) -> None: ...
    def write(self: Any, data_dict: anydict) -> None: ...
