from typing import Any

import ast
import dataclasses
import importlib.util
import logging
import os
import sys
import typing
from zato.openapi.generator.openapi_ import OpenAPIGenerator

class TypeConversionError(Exception):
    ...

class IOVisitor(ast.NodeVisitor):
    def __init__(self: Any) -> None: ...
    def visit_ClassDef(self: Any, node: Any) -> None: ...
    def visit_AnnAssign(self: Any, node: Any) -> None: ...
    def _parse_annotation(self: Any, annotation: Any) -> None: ...
    def _get_name_from_node(self: Any, node: Any) -> None: ...
    def visit_Assign(self: Any, node: Any) -> None: ...
    def visit_FunctionDef(self: Any, node: Any) -> None: ...

class TypeMapper:
    BASIC_TYPES: Any
    def __init__(self: Any) -> None: ...
    def map_type(self: Any, zato_type: Any, model_definitions: Any = ...) -> None: ...
    def _register_model_schema(self: Any, model_name: Any, model_definitions: Any) -> None: ...
    def get_schema_components(self: Any) -> None: ...

def extract_model_fields_recursive(model_class: Any, all_models: Any, visited: Any = ...) -> None: ...

def _get_runtime_type_name(type_hint: Any) -> None: ...

def _extract_nested_models(type_hint: Any, all_models: Any, visited: Any) -> None: ...

def import_module_from_file(file_path: Any) -> None: ...

def resolve_model_from_import(model_name: Any, file_path: Any) -> None: ...

class IOScanner:
    def __init__(self: Any) -> None: ...
    def is_python_file(self: Any, file_path: Any) -> None: ...
    def scan_file(self: Any, file_path: Any) -> None: ...
    def scan_directory(self: Any, directory: Any) -> None: ...
    def scan_files(self: Any, file_paths: Any) -> None: ...
    def scan_directories(self: Any, directories: Any) -> None: ...

def scan_io(directories: Any, output_file: Any) -> None: ...
