from typing import Any

import logging
import yaml

class TypeConversionError(Exception):
    ...

class OpenAPIGenerator:
    type_mapper: Any
    def __init__(self: Any, type_mapper: Any) -> None: ...
    def _create_request_schema(self: Any, service_input: Any, models: Any) -> None: ...
    def _create_response_schema(self: Any, service_output: Any, models: Any) -> None: ...
    def generate_openapi(self: Any, scan_results: Any, output_file: Any) -> None: ...
