from typing import Any

import ast
import logging
import os
from zato.common.typing_ import dictlist, strlist
from diskcache import Cache
import yaml
from tqdm import tqdm

class ServiceVisitor(ast.NodeVisitor):
    services: Any
    current_class: Any
    is_service: Any
    name: Any
    input: Any
    output: Any
    handle_method_exists: Any
    def __init__(self: Any) -> None: ...
    def visit_ClassDef(self: Any, node: Any) -> None: ...
    def visit_Assign(self: Any, node: Any) -> None: ...
    def visit_FunctionDef(self: Any, node: Any) -> None: ...

class ServiceScanner:
    cache: Cache
    def __init__(self: Any, cache_dir: str = ...) -> None: ...
    def is_python_file(self: Any, file_path: str) -> bool: ...
    def get_file_mtime(self: Any, file_path: str) -> float: ...
    def scan_file(self: Any, file_path: str) -> dictlist: ...
    def scan_directory(self: Any, directory: str) -> dictlist: ...
    def scan_directories(self: Any, directories: strlist) -> dictlist: ...

def scan_services(directories: strlist, output_file: str) -> None: ...
