from typing import Any

import base64
import logging
import os
from datetime import datetime
from math import ceil
from bunch import bunchify
from cryptography.fernet import Fernet, InvalidToken
from cryptography.hazmat.primitives.constant_time import bytes_eq
from builtins import bytes
from zato.common.const import SECRETS
from zato.common.crypto.const import well_known_data, zato_stdin_prefix
from zato.common.ext.configobj_ import ConfigObj
from zato.common.json_internal import loads
from zato.common.typing_ import any_, strbytes
from passlib import hash as passlib_hash
from cpuinfo import get_cpu_info

def is_string_equal(data1: strbytes, data2: strbytes) -> bool: ...

class SecretKeyError(Exception):
    ...

class CryptoManager:
    stdin_data: Any
    hash_scheme: Any
    def __init__(self: Any, repo_dir: Any = ..., secret_key: Any = ..., stdin_data: Any = ..., well_known_data: Any = ...) -> None: ...
    def add_hash_scheme(self: Any, name: Any, rounds: Any, salt_size: Any) -> None: ...
    def get_config(self: Any, repo_dir: Any) -> None: ...
    def _find_secret_key(self: Any, secret_key: Any) -> None: ...
    def set_config(self: Any, secret_key: Any, well_known_data: Any) -> None: ...
    def check_consistency(self: Any) -> None: ...
    @staticmethod
    def generate_key() -> None: ...
    @staticmethod
    def generate_secret(bits: Any = ..., as_str: Any = ...) -> bytes | str: ...
    @staticmethod
    def generate_password(bits: Any = ..., to_str: Any = ...) -> None: ...
    @classmethod
    def from_repo_dir(cls: Any, secret_key: Any, repo_dir: Any, stdin_data: Any) -> None: ...
    @classmethod
    def from_secret_key(cls: Any, secret_key: Any, well_known_data: Any = ..., stdin_data: Any = ...) -> None: ...
    def encrypt(self: Any, data: any_) -> bytes | str: ...
    def decrypt(self: Any, encrypted: Any, _prefix: Any = ...) -> None: ...
    def hash_secret(self: Any, data: any_, name: str = ...) -> str: ...
    def verify_hash(self: Any, given: any_, expected: any_, name: Any = ...) -> bool: ...
    @staticmethod
    def get_hash_rounds(goal: Any, header_func: Any = ..., progress_func: Any = ..., footer_func: Any = ...) -> None: ...
    def get_config_entry(self: Any, entry: Any) -> None: ...

class WebAdminCryptoManager(CryptoManager):
    def get_config(self: Any, repo_dir: Any) -> None: ...

class SchedulerCryptoManager(CryptoManager):
    def get_config(self: Any, repo_dir: Any) -> None: ...

class ServerCryptoManager(CryptoManager):
    def get_config(self: Any, repo_dir: Any) -> None: ...

class HashParamsComputer:
    goal: Any
    header_func: Any
    progress_func: Any
    footer_func: Any
    scheme: Any
    loops: Any
    iters_per_loop: Any
    iters: Any
    salt_size: Any
    rounds_per_iter: Any
    report_per_cent: Any
    report_once_in: Any
    hash_scheme: getattr.using
    cpu_info: self.get_cpu_info
    _round_down_to_nearest: Any
    _round_up_to_nearest: Any
    def __init__(self: Any, goal: Any, header_func: Any = ..., progress_func: Any = ..., footer_func: Any = ..., scheme: Any = ..., loops: Any = ..., iters_per_loop: Any = ..., salt_size: Any = ..., rounds_per_iter: Any = ...) -> None: ...
    def get_cpu_info(self: Any) -> None: ...
    def get_info(self: Any, _utcnow: Any = ...) -> None: ...
    def round_down(self: Any, value: Any) -> None: ...
    def round_up(self: Any, value: Any) -> None: ...
