from typing import Any, TYPE_CHECKING

import types
import sys
import numbers
import functools
import copy
import inspect
import __builtin__
import builtins
from zato.common.ext.future.types import newbytes
import re
from zato.common.ext.future.types.newbytes import newbytes
from zato.common.ext.future.types.newstr import newstr
from zato.common.ext.future.types.newint import newint
from zato.common.ext.future.types.newdict import newdict

reraise = raise_
native_str = str
native_bytes = bytes

def python_2_unicode_compatible(cls: Any) -> None: ...

def with_metaclass(meta: Any, *bases: Any) -> None: ...

def isidentifier(s: Any, dotted: Any = ...) -> None: ...

def viewitems(obj: Any, **kwargs: Any) -> None: ...

def viewkeys(obj: Any, **kwargs: Any) -> None: ...

def viewvalues(obj: Any, **kwargs: Any) -> None: ...

def iteritems(obj: Any, **kwargs: Any) -> None: ...

def iterkeys(obj: Any, **kwargs: Any) -> None: ...

def itervalues(obj: Any, **kwargs: Any) -> None: ...

def bind_method(cls: Any, name: Any, func: Any) -> None: ...

def getexception() -> None: ...

def _get_caller_globals_and_locals() -> None: ...

def _repr_strip(mystring: Any) -> None: ...

def implements_iterator(cls: Any) -> None: ...

def encode_filename(filename: Any) -> None: ...

def is_new_style(cls: Any) -> None: ...

def istext(obj: Any) -> None: ...

def isbytes(obj: Any) -> None: ...

def isnewbytes(obj: Any) -> None: ...

def isint(obj: Any) -> None: ...

def native(obj: Any) -> None: ...

def old_div(a: Any, b: Any) -> None: ...

def as_native_str(encoding: Any = ...) -> None: ...
