from typing import Any

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from logging import getLogger
from traceback import format_exc
from zato.admin.web.views.ai.browser_tools import get_browser_tool_schemas, is_browser_tool
from zato.admin.web.views.ai.mcp.registry import MCPRegistry
from zato.admin.web.views.ai.llm.execution import build_execution_context
from zato.admin.web.views.ai.tools.definitions import get_all_tools as get_enmasse_tools, is_delete_tool, is_update_tool
from zato.admin.web.views.ai.tools.executor import execute_enmasse_batch, is_enmasse_tool, is_service_tool, execute_service_tool
from zato.admin.web.views.ai.tools.delete_executor import execute_delete_tool
from zato.admin.web.views.ai.tools.update_executor import execute_update_tool
from zato.common.ai.prompts.loader import get_system_prompt
from zato.common.typing_ import any_, anylist, generator_
import re
import os
from uuid import uuid4
from zato.admin.web.views.ai.common import get_redis_client
from zato.common.json_internal import loads

class CategorizedToolCalls:
    enmasse: list
    delete: list
    update: list
    service: list
    browser: list
    mcp: list

class BaseLLMClient(ABC):
    def __init__(self: Any, api_key: str, zato_client: any_ = ..., cluster_id: int = ..., cluster: any_ = ..., session_id: str = ...) -> None: ...
    def _build_execution_history_context(self: Any, question: str = ...) -> str: ...
    def _extract_last_user_message(self: Any, messages: list) -> str: ...
    def stream_chat(self: Any, model: str, messages: list) -> generator_: ...
    def _format_error(self: Any, error: any_) -> dict: ...
    def _format_chunk(self: Any, text: str) -> dict: ...
    def _format_waiting(self: Any, waiting_type: str = ...) -> dict: ...
    def _format_done(self: Any, input_tokens: int = ..., output_tokens: int = ...) -> dict: ...
    def _format_object_changed(self: Any, action: str, object_id: any_, object_name: str = ..., object_type: str = ...) -> dict: ...
    def _format_tool_progress(self: Any, status: str, total: int = ..., completed: int = ..., message: str = ..., items: list = ...) -> dict: ...
    def _format_tool_preview(self: Any, file_path: str, code: str, is_new: bool = ...) -> dict: ...
    def _extract_file_previews(self: Any, partial_input: str, already_previewed: set) -> None: ...
    def _get_tool_progress_message(self: Any, tool_names: list, is_done: bool = ..., tool_params: list = ...) -> str: ...
    def _yield_tool_progress_start(self: Any, count: int, tool_names: list = ..., tool_params: list = ...) -> generator_: ...
    def _yield_tool_progress_done(self: Any, count: int, items: list = ..., tool_names: list = ..., tool_params: list = ...) -> generator_: ...
    def _get_done_summary_message(self: Any, tool_names: list, tool_params: list, items: list) -> str: ...
    def _get_mcp_tools(self: Any) -> anylist: ...
    def _get_enmasse_tools(self: Any) -> anylist: ...
    def _get_all_tools(self: Any) -> anylist: ...
    def _categorize_tool_calls(self: Any, tool_calls: list, get_tool_name: callable) -> CategorizedToolCalls: ...
    def _execute_enmasse_batch(self: Any, batch: list) -> dict: ...
    def _execute_delete_tool(self: Any, tool_name: str, arguments: dict) -> dict: ...
    def _execute_update_tool(self: Any, tool_name: str, arguments: dict) -> dict: ...
    def _execute_service_tool(self: Any, tool_name: str, arguments: dict) -> dict: ...
    def _execute_browser_tool(self: Any, tool_name: str, arguments: dict) -> generator_: ...
    def _execute_mcp_tool_core(self: Any, tool_name: str, arguments: dict, all_tools: anylist) -> dict: ...
