from typing import Any

from zato.cli import ManageCommand
from zato.common.util.open_ import open_r
from os.path import join
from zato.common.json_internal import loads
from zato.common.util.tcp import is_port_taken
from zato.common.odb import ping_database
from zato.common.odb.ping import get_ping_query
from zato.common.api import ping_queries
from os.path import abspath, exists, join
from zato.common.ext.configobj_ import ConfigObj
from zato.common.crypto.api import ServerCryptoManager
from zato.common.crypto.api import WebAdminCryptoManager
from zato.common.crypto.secret_key import resolve_secret_key
from zato.common.crypto.api import SchedulerCryptoManager
import os
from psutil import AccessDenied, Process, NoSuchProcess
from zato.common.api import INFO_FORMAT
from zato.common.component_info import get_info

class CheckConfig(ManageCommand):
    def get_json_conf(self: Any, conf_name: Any, repo_dir: Any = ...) -> None: ...
    def ensure_port_free(self: Any, prefix: Any, port: Any, address: Any) -> None: ...
    def ensure_json_config_port_free(self: Any, prefix: Any, conf_name: Any = ..., conf: Any = ...) -> None: ...
    def ping_sql(self: Any, engine_params: Any, ping_query: Any) -> None: ...
    def check_sql_odb_server_scheduler(self: Any, cm: Any, conf: Any, fs_sql_config: Any, needs_decrypt_password: Any = ...) -> None: ...
    def check_sql_odb_web_admin(self: Any, cm: Any, conf: Any) -> None: ...
    def ensure_no_pidfile(self: Any, log_file_marker: Any) -> None: ...
    def on_server_check_port_available(self: Any, server_conf: Any) -> None: ...
    def get_crypto_manager(self: Any, secret_key: Any = ..., stdin_data: Any = ..., class_: Any = ...) -> None: ...
    def get_sql_ini(self: Any, conf_file: Any, repo_dir: Any = ...) -> None: ...
    def _on_server(self: Any, args: Any) -> None: ...
    def _on_web_admin(self: Any, args: Any, *ignored_args: Any, **ignored_kwargs: Any) -> None: ...
    def _on_scheduler(self: Any, args: Any, *ignored_args: Any, **ignored_kwargs: Any) -> None: ...
