from typing import Any

from zato.cli import ManageCommand, ZatoCommand
from zato.common.crypto.api import CryptoManager
from zato.common.crypto.api import WebAdminCryptoManager
from zato.common.crypto.api import ServerCryptoManager
from zato.common.crypto.api import SchedulerCryptoManager
import os
from zato.common.json_internal import dumps

class CreateSecretKey(ZatoCommand):
    def execute(self: Any, args: Any) -> None: ...

class Encrypt(ManageCommand):
    allow_empty_secrets: Any
    opts: Any
    def execute(self: Any, args: Any) -> None: ...
    def _on_web_admin(self: Any, args: Any) -> None: ...
    def _on_server(self: Any, args: Any) -> None: ...
    def _on_scheduler(self: Any, args: Any) -> None: ...

class Decrypt(ManageCommand):
    allow_empty_secrets: Any
    opts: Any
    def execute(self: Any, args: Any) -> None: ...
    def _decrypt(self: Any, class_: Any, args: Any) -> None: ...
    def _on_web_admin(self: Any, args: Any) -> None: ...
    def _on_server(self: Any, args: Any) -> None: ...
    def _on_scheduler(self: Any, args: Any) -> None: ...

class GetHashRounds(ZatoCommand):
    opts: Any
    def allow_empty_secrets(self: Any) -> None: ...
    def header_func(self: Any, cpu_info: Any, goal: Any) -> None: ...
    def footer_func(self: Any, rounds_per_second_str: Any, rounds_str: Any) -> None: ...
    def progress_func(self: Any, current_per_cent: Any) -> None: ...
    def execute(self: Any, args: Any) -> None: ...
