from typing import Any

import os
from shutil import copy as shutil_copy
from zipfile import ZipFile
from zato.cli import ManageCommand
from zato.common.util.file_system import get_tmp_path
from zato.common.util.open_ import open_r
from zato.common.typing_ import any_, anydict, callnone, dictnone, strdict
import logging
from bunch import Bunch
from zato.cli.check_config import CheckConfig
from zato.common.api import MISC
from zato.common.util.proc import start_python_process
import redis
from zato.common.util.updates import setup_update_file_logger
from zato.common.json_internal import loads
from zato.common.util import proc

class ModuleCtx:
    Deploy_Dirs: Any

class Start(ManageCommand):
    opts: Any
    def run_check_config(self: Any) -> None: ...
    def delete_pidfile(self: Any) -> None: ...
    def check_pidfile(self: Any, pidfile: str = ...) -> int: ...
    def start_component(self: Any, py_path: str, name: str, program_dir: str, on_keyboard_interrupt: callnone = ...) -> int: ...
    def _handle_deploy_local_dir_impl(self: Any, src_path: str) -> anydict: ...
    def _handle_deploy_local_dir(self: Any, src_path: str) -> dictnone: ...
    def _handle_deploy_local_zip(self: Any, src_path: str) -> dictnone: ...
    def _maybe_set_up_deploy(self: Any) -> dictnone: ...
    def _on_server(self: Any, *ignored: any_) -> int: ...
    def _on_web_admin(self: Any, *ignored: any_) -> None: ...
    def _on_scheduler(self: Any, *ignored: any_) -> None: ...
