from typing import Any

from zato.common.typing_ import cast_
from argparse import ArgumentParser
from zato.common.typing_ import any_, callnone, dictlist, strlist, tuple_
import sys
import logging
import os
import argparse
from zato.cli import start as start_mod
from zato.common.version import get_version
from zato.cli import cache as cache_mod, check_config as check_config_mod, component_version as component_version_mod, create_cluster as create_cluster_mod, create_odb as create_odb_mod, create_scheduler as create_scheduler_mod, create_server as create_server_mod, create_web_admin as create_web_admin_mod, crypto as crypto_mod, delete_odb as delete_odb_mod, enmasse_command as enmasse_mod, FromConfig, ide as ide_mod, info as info_mod, quickstart as quickstart_mod, service as service_mod, stop as stop_mod, wait as wait_mod, web_admin_auth as web_admin_auth_mod
from zato.cli.rest import channel as rest_channel_mod
from zato.cli.security import api_key as sec_api_key_mod, basic_auth as sec_basic_auth_mod
from zato.cli import run_command

class CommandStore:
    add_start_server_parser: Any
    def add_opts(self: Any, parser: ArgumentParser, opts: dictlist) -> None: ...
    def build_core_parser(self: Any) -> tuple_: ...
    def load_start_parser(self: Any, parser: Any = ..., base_parser: Any = ..., subs: Any = ..., formatter_class: Any = ...) -> ArgumentParser: ...
    def load_version_parser(self: Any) -> ArgumentParser: ...
    def _add_version(self: Any, parser: ArgumentParser) -> None: ...
    def load_full_parser(self: Any) -> ArgumentParser: ...

def pre_process_quickstart(sys_argv: strlist, opts_idx: int) -> None: ...

def pre_process_server(sys_argv: Any, opts_idx: Any, opts: Any) -> None: ...

def pre_process_sys_argv(sys_argv: Any) -> None: ...

def main() -> any_: ...
