from typing import Any

from datetime import datetime
import os
from random import randint
import signal
from ssl import SSLError
import sys
import time
import traceback
from zato.common.util.platform_ import is_posix
from zato.server.ext.zunicorn import six
from zato.server.ext.zunicorn import util
from zato.server.ext.zunicorn.workers.workertmp import PassThroughTmp, WorkerTmp
from zato.server.ext.zunicorn.reloader import reloader_engines
from zato.server.ext.zunicorn.http.errors import InvalidHeader, InvalidHeaderName, InvalidRequestLine, InvalidRequestMethod, InvalidHTTPVersion, LimitRequestLine, LimitRequestHeaders
from zato.server.ext.zunicorn.http.errors import InvalidProxyLine, ForbiddenProxyRequest
from zato.server.ext.zunicorn.http.errors import InvalidSchemeHeaders
from zato.server.ext.zunicorn.http.wsgi import default_environ, Response
from zato.server.ext.zunicorn.six import MAXSIZE
from traceback import format_exc

class Worker:
    PIPE: Any
    def __init__(self: Any, age: Any, ppid: Any, sockets: Any, app: Any, timeout: Any, cfg: Any, log: Any) -> None: ...
    def __str__(self: Any) -> None: ...
    def notify(self: Any) -> None: ...
    def run(self: Any) -> None: ...
    def init_process(self: Any) -> None: ...
    def load_wsgi(self: Any) -> None: ...
    def init_signals(self: Any) -> None: ...
    def handle_usr1(self: Any, sig: Any, frame: Any) -> None: ...
    def handle_exit(self: Any, sig: Any, frame: Any) -> None: ...
    def handle_quit(self: Any, sig: Any, frame: Any) -> None: ...
    def handle_abort(self: Any, sig: Any, frame: Any) -> None: ...
    def handle_error(self: Any, req: Any, client: Any, addr: Any, exc: Any) -> None: ...
    def handle_winch(self: Any, sig: Any, fname: Any) -> None: ...
