from typing import Any

import os
import platform
import tempfile
from zato.server.ext.zunicorn import util

class PassThroughTmp:
    def __init__(self: Any, *ignored_args: Any, **ignored_kwargs: Any) -> None: ...
    def notify(self: Any, *ignored_args: Any, **ignored_kwargs: Any) -> None: ...
    def last_update(self: Any, *ignored_args: Any, **ignored_kwargs: Any) -> None: ...
    def fileno(self: Any, *ignored_args: Any, **ignored_kwargs: Any) -> None: ...
    def close(self: Any, *ignored_args: Any, **ignored_kwargs: Any) -> None: ...

class WorkerTmp:
    spinner: Any
    _tmp: os.fdopen
    def __init__(self: Any, cfg: Any) -> None: ...
    def notify(self: Any) -> None: ...
    def last_update(self: Any) -> None: ...
    def fileno(self: Any) -> None: ...
    def close(self: Any) -> None: ...
