from typing import Any


class ChannelOpenAPIWrapper:
    def __init__(self: Any, config: Any, server: Any) -> None: ...
    def build_wrapper(self: Any) -> None: ...
    def delete(self: Any, reason: Any = ...) -> None: ...
