from typing import Any, TYPE_CHECKING

from logging import getLogger
from traceback import format_exc
from zato.common.typing_ import cast_
from zato.server.connection.confluence_ import ConfluenceClient
from zato.server.connection.queue import Wrapper
from zato.common.typing_ import stranydict


class _ConfluenceClient(ConfluenceClient):
    def __init__(self: Any, config: stranydict) -> None: ...
    def ping(self: Any) -> None: ...

class CloudConfluenceWrapper(Wrapper):
    def __init__(self: Any, config: stranydict, server: Any) -> None: ...
    def add_client(self: Any) -> None: ...
    def ping(self: Any) -> None: ...
    def delete(self: Any, ignored_reason: Any = ...) -> None: ...
