from typing import Any, TYPE_CHECKING

import ssl
from codecs import encode
from logging import getLogger
from traceback import format_exc
from uuid import uuid4
from ldap3 import Connection as LDAPConnection, Server, ServerPool, SYNC, Tls
from zato.common.util.api import spawn_greenlet
from zato.server.connection.queue import Wrapper
from bunch import Bunch
from zato.common.typing_ import any_, stranydict, strdictnone
from zato.server.base.parallel import ParallelServer


class ConnectionWrapper:
    conn: LDAPConnection
    client: Any
    def __init__(self: Any, client: LDAPClient) -> None: ...
    def __enter__(self: Any) -> None: ...
    def __exit__(self: Any, type: Any, value: Any, traceback: Any) -> None: ...

class LDAPClient:
    config: Any
    is_connected: Any
    def __init__(self: Any, config: Bunch) -> None: ...
    def _init(self: Any) -> None: ...
    def get_conn_config(self: Any) -> stranydict: ...
    def connect(self: Any, conn_config: strdictnone = ...) -> LDAPConnection: ...
    def zato_delete_impl(self: Any) -> None: ...
    def get(self: Any) -> None: ...
    def check_credentials(self: Any, user_data: any_, secret: str, raise_on_error: bool = ...) -> None: ...
    def delete(self: Any) -> None: ...
    def ping(self: Any) -> None: ...

class OutconnLDAPWrapper(Wrapper):
    def __init__(self: Any, config: Bunch, server: ParallelServer) -> None: ...
    def ping(self: Any) -> None: ...
    def add_client(self: Any) -> None: ...
