from typing import Any

from zato.common.typing_ import str_
from zato.common.monitoring.context import ProcessContext, get_global_metrics
from zato.common.monitoring.metrics import get_global_metrics_store

def create_context(process_name: str_, ctx_id: str_) -> ProcessContext: ...

def get_metrics_data() -> str_: ...

def push_start(process_name: str_, ctx_id: str_) -> None: ...

def push_end(process_name: str_, ctx_id: str_, status: str_ = ...) -> None: ...

def incr_global(key: str_) -> None: ...

def decr_global(key: str_) -> None: ...

def push_global(key: str_, value: float) -> None: ...
