from typing import Any

from zato.common.typing_ import strdict
from zato.common.util.time_ import utcnow_as_ms
from zato.common.monitoring.metrics import get_global_metrics_store

class ProcessContext:
    def __init__(self: Any, process_name: str, ctx_id: str) -> None: ...
    def push(self: Any, key: str, value: float) -> None: ...
    def push_dict(self: Any, metrics: strdict) -> None: ...
    def incr(self: Any, key: str) -> None: ...
    def incr_by(self: Any, key: str, amount: float) -> None: ...
    def decr(self: Any, key: str) -> None: ...
    def decr_by(self: Any, key: str, amount: float) -> None: ...
    def set_max(self: Any, key: str, value: float) -> None: ...
    def set_min(self: Any, key: str, value: float) -> None: ...
    def push_duration(self: Any, key: str, milliseconds: float) -> None: ...
    def push_timestamp(self: Any, key: str) -> None: ...
    def timer_start(self: Any, key: str) -> None: ...
    def timer_stop(self: Any, key: str) -> None: ...

class GlobalMetrics:
    def __init__(self: Any) -> None: ...
    def incr_global(self: Any, key: str) -> None: ...
    def decr_global(self: Any, key: str) -> None: ...
    def push_global(self: Any, key: str, value: float) -> None: ...

def get_global_metrics() -> GlobalMetrics: ...
