from typing import Any

import logging
from logging import Logger
from zato.common.typing_ import any_, strnone
from zato.server.base.parallel import ParallelServer

class DatadogLogger(Logger):
    cid: str
    server: ParallelServer
    service_name: str
    process_name: str
    service: any_
    warn: Any
    def __init__(self: Any, cid: str, server: ParallelServer, service_name: str, process_name: str, service: any_ = ...) -> None: ...
    def _zato_emit_log(self: Any, level: str, msg: str, event: strnone) -> None: ...
    def debug(self: Any, msg: any_, *args: any_, **kwargs: any_) -> None: ...
    def info(self: Any, msg: any_, *args: any_, **kwargs: any_) -> None: ...
    def warning(self: Any, msg: any_, *args: any_, **kwargs: any_) -> None: ...
    def error(self: Any, msg: any_, *args: any_, **kwargs: any_) -> None: ...
    def critical(self: Any, msg: any_, *args: any_, **kwargs: any_) -> None: ...
