from typing import Any

from threading import RLock
from ddtrace.vendor.dogstatsd.base import statsd
from zato.common.typing_ import anydict, floatnone
from zato.common.util.time_ import utcnow_as_ms
from zato.server.service import Service

class MetricsStore:
    def __init__(self: Any) -> None: ...
    def set_value(self: Any, process_name: str, ctx_id: str, key: str, value: float) -> None: ...
    def get_value(self: Any, process_name: str, ctx_id: str, key: str) -> floatnone: ...
    def increment_value(self: Any, process_name: str, ctx_id: str, key: str, amount: float = ...) -> None: ...
    def decrement_value(self: Any, process_name: str, ctx_id: str, key: str, amount: float = ...) -> None: ...
    def set_max_value(self: Any, process_name: str, ctx_id: str, key: str, value: float) -> None: ...
    def set_min_value(self: Any, process_name: str, ctx_id: str, key: str, value: float) -> None: ...
    def timer_start(self: Any, process_name: str, ctx_id: str, key: str) -> None: ...
    def timer_stop(self: Any, process_name: str, ctx_id: str, key: str) -> floatnone: ...
    def get_prometheus_format(self: Any) -> str: ...

class ServiceMetrics:
    def __init__(self: Any, service: Service) -> None: ...
    def push(self: Any, event_name: str, value: float) -> None: ...
    def incr(self: Any, event_name: str, value: int = ...) -> None: ...

def get_global_metrics_store() -> MetricsStore: ...
