# -*- coding: utf-8 -*-

"""
Copyright (C) 2026, Zato Source s.r.o. https://zato.io

Licensed under AGPLv3, see LICENSE.txt for terms and conditions.
"""

# This file is generated by generate_edifact_message_tests.py - do not edit it by hand.

# stdlib
import unittest

# Zato
from zato.edifact import parse_edifact
from zato.edifact.syntax import parse_una, split_segments
from zato.edifact.testing.live_util import load_message, md_path_for

# ##################################################################################################################################
# ##################################################################################################################################

_md_path = md_path_for('nl', 'nl-medrpt32-segments.md')

def _normalized_lines(raw:'str') -> 'list[str]':
    """ Normalizes wire text to one segment per line, the same form serialize() produces.
    """
    separators, rest = parse_una(raw)

    out:'list[str]' = []

    if raw.startswith('UNA'):
        una_length = len(raw) - len(rest)
        out.append(raw[:una_length])

    for segment_text in split_segments(rest, separators):
        if not segment_text.endswith(separators.terminator):
            segment_text = segment_text + separators.terminator
        out.append(segment_text)

    return out

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg01(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 1
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 1)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 0)
        self.assertEqual(interchange.header.sender.identification, '019283746')
        self.assertEqual(interchange.header.recipient.identification, '019283746')

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 1)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg02(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 2
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 2)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 1)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 2)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg03(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 3
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 3)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 1)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 3)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg04(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 4
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 4)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 4)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 4)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg05(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 5
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 5)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 4)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 5)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg06(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 6
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 6)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 1)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 6)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg07(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 7
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 7)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 1)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 7)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg08(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 8
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 8)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 3)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 8)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg09(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 9
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 9)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 1)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 9)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg10(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 10
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 10)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 3)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 10)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg11(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 11
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 11)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 1)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 11)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg12(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 12
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 12)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 1)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 12)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg13(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 13
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 13)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 2)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 13)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg14(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 14
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 14)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 1)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 14)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg15(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 15
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 15)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 2)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 15)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg16(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 16
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 16)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 3)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 16)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg17(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 17
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 17)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 2)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 17)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg18(unittest.TestCase):
    """ Based on live/nl/nl-medrpt32-segments.md, message no. 18
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 18)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'EDIGenericMessage')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 1)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 18)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

# ##################################################################################################################################
# ##################################################################################################################################

if __name__ == '__main__':
    _ = unittest.main()
