# -*- coding: utf-8 -*-

"""
Copyright (C) 2026, Zato Source s.r.o. https://zato.io

Licensed under AGPLv3, see LICENSE.txt for terms and conditions.
"""

# This file is generated by generate_edifact_message_tests.py - do not edit it by hand.

# stdlib
import unittest

# Zato
import zato.edifact.nl  # noqa: F401 - registers the Dutch message classes
from zato.edifact import parse_edifact
from zato.edifact.syntax import parse_una, split_segments
from zato.edifact.testing.live_util import load_message, md_path_for

# ##################################################################################################################################
# ##################################################################################################################################

_md_path = md_path_for('nl', 'nl-medlab-fragment.md')

def _normalized_lines(raw:'str') -> 'list[str]':
    """ Normalizes wire text to one segment per line, the same form serialize() produces.
    """
    separators, rest = parse_una(raw)

    out:'list[str]' = []

    if raw.startswith('UNA'):
        una_length = len(raw) - len(rest)
        out.append(raw[:una_length])

    for segment_text in split_segments(rest, separators):
        if not segment_text.endswith(separators.terminator):
            segment_text = segment_text + separators.terminator
        out.append(segment_text)

    return out

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg01(unittest.TestCase):
    """ Based on live/nl/nl-medlab-fragment.md, message no. 1
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 1)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'MEDLAB')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 14)

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 1)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

    def test_navigate(self) -> None:
        raw = load_message(_md_path, 1)
        msg = parse_edifact(raw).message

        self.assertEqual(msg.department.department, 'Screening')
        self.assertEqual(msg.hospital.institution_name, 'Bloedafname Oost')
        self.assertEqual(msg.lab_doctors[0].person_name, 'Onbekend')
        self.assertEqual(msg.materials[0].comments[0].text, '5829164')
        self.assertEqual(msg.materials[0].det.date.day, '14')
        self.assertEqual(msg.materials[0].det.date.month, '09')
        self.assertEqual(msg.materials[0].det.date.year, '22')
        self.assertEqual(msg.materials[0].det.time.hour, '10')
        self.assertEqual(msg.materials[0].det.time.minute, '22')
        self.assertEqual(msg.materials[0].ide.complete_code, 'J')
        self.assertEqual(msg.materials[0].ide.identification_number, '000000000')
        self.assertEqual(msg.materials[0].remarks[0].text, '7382916473829')
        self.assertEqual(msg.materials[1].comments[0].text, '5829164')
        self.assertEqual(msg.materials[1].det.date.day, '14')
        self.assertEqual(msg.materials[1].det.date.month, '09')
        self.assertEqual(msg.materials[1].det.date.year, '22')
        self.assertEqual(msg.materials[1].det.time.hour, '10')
        self.assertEqual(msg.materials[1].det.time.minute, '22')
        self.assertEqual(msg.materials[1].ide.complete_code, 'J')
        self.assertEqual(msg.materials[1].ide.identification_number, '000000000')
        self.assertEqual(msg.materials[1].remarks[0].text, '2648159326481')
        self.assertEqual(msg.pad.address.city, 'Plaatsnaam')
        self.assertEqual(msg.pad.address.postcode, '2000BB')
        self.assertEqual(msg.pid.date_of_birth.day, '23')
        self.assertEqual(msg.pid.date_of_birth.month, '11')
        self.assertEqual(msg.pid.date_of_birth.year, '1988')
        self.assertEqual(msg.pid.patient_name.maiden_name, 'Onbekend')
        self.assertEqual(msg.pid.receiver_reference, 'BSN999990032')
        self.assertEqual(msg.pid.sex, 'V')
        self.assertEqual(msg.unh.identifier.message_type, 'MEDLAB')
        self.assertEqual(msg.unh.identifier.version, '1')
        self.assertEqual(msg.unh.reference_number, '5124873962')

# ##################################################################################################################################
# ##################################################################################################################################

if __name__ == '__main__':
    _ = unittest.main()
