# -*- coding: utf-8 -*-

"""
Copyright (C) 2026, Zato Source s.r.o. https://zato.io

Licensed under AGPLv3, see LICENSE.txt for terms and conditions.
"""

# This file is generated by generate_edifact_message_tests.py - do not edit it by hand.

# stdlib
import unittest

# Zato
import zato.edifact.nl  # noqa: F401 - registers the Dutch message classes
from zato.edifact import parse_edifact
from zato.edifact.syntax import parse_una, split_segments
from zato.edifact.testing.live_util import load_message, md_path_for

# ##################################################################################################################################
# ##################################################################################################################################

_md_path = md_path_for('nl', 'nl-medvri-medlab.md')

def _normalized_lines(raw:'str') -> 'list[str]':
    """ Normalizes wire text to one segment per line, the same form serialize() produces.
    """
    separators, rest = parse_una(raw)

    out:'list[str]' = []

    if raw.startswith('UNA'):
        una_length = len(raw) - len(rest)
        out.append(raw[:una_length])

    for segment_text in split_segments(rest, separators):
        if not segment_text.endswith(separators.terminator):
            segment_text = segment_text + separators.terminator
        out.append(segment_text)

    return out

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg01(unittest.TestCase):
    """ Based on live/nl/nl-medvri-medlab.md, message no. 1
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 1)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'MEDVRI')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 11)
        self.assertEqual(interchange.header.sender.identification, '41007001')
        self.assertEqual(interchange.header.recipient.identification, '41008002')

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 1)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

    def test_navigate(self) -> None:
        raw = load_message(_md_path, 1)
        msg = parse_edifact(raw).message

        self.assertEqual(msg.det.date.day, '14')
        self.assertEqual(msg.det.date.month, '02')
        self.assertEqual(msg.det.date.year, '24')
        self.assertEqual(msg.det.time.hour, '09')
        self.assertEqual(msg.det.time.minute, '41')
        self.assertEqual(msg.pad.address.building_number, '27a')
        self.assertEqual(msg.pad.address.city, 'Utrecht')
        self.assertEqual(msg.pad.address.postcode, '3581CD')
        self.assertEqual(msg.pad.address.street, 'Lindelaan')
        self.assertEqual(msg.pad.phone, '+31644556677')
        self.assertEqual(msg.pid.date_of_birth.day, '18')
        self.assertEqual(msg.pid.date_of_birth.month, '03')
        self.assertEqual(msg.pid.date_of_birth.year, '1975')
        self.assertEqual(msg.pid.patient_name.initials, 'M.')
        self.assertEqual(msg.pid.patient_name.maiden_name, 'Peters')
        self.assertEqual(msg.pid.patient_name.maiden_name_prefix, 'de')
        self.assertEqual(msg.pid.patient_name.married_name, 'Dijk')
        self.assertEqual(msg.pid.patient_name.married_name_prefix, 'van der')
        self.assertEqual(msg.pid.receiver_reference, 'BSN999990019')
        self.assertEqual(msg.pid.sex, 'V')
        self.assertEqual(msg.receiver.address.building_number, '8')
        self.assertEqual(msg.receiver.address.city, 'Utrecht')
        self.assertEqual(msg.receiver.address.street, 'Dorpsweg')
        self.assertEqual(msg.receiver.person_name, 'Arts Achternaam')
        self.assertEqual(msg.sender.address.building_number, '14')
        self.assertEqual(msg.sender.address.city, 'Utrecht')
        self.assertEqual(msg.sender.address.postcode, '3511AB')
        self.assertEqual(msg.sender.address.street, 'Kerkstraat')
        self.assertEqual(msg.sender.department, 'Administratie')
        self.assertEqual(msg.sender.institution_name, 'Praktijk Rozenburg')
        self.assertEqual(msg.sender.person_name, 'Praktijk Rozenburg')
        self.assertEqual(msg.sender.phone, '+31611223344')
        self.assertEqual(msg.text[0].text, 'Beste collega')
        self.assertEqual(msg.text[1].text, 'Graag uw beoordeling van deze patient')
        self.assertEqual(msg.text[3].text, 'Met vriendelijke groet')
        self.assertEqual(msg.unh.identifier.message_type, 'MEDVRI')
        self.assertEqual(msg.unh.identifier.version, '1')
        self.assertEqual(msg.unh.reference_number, '7431')
        self.assertEqual(msg.unt.reference_number, '7431')
        self.assertEqual(msg.unt.segment_count, '11')

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg02(unittest.TestCase):
    """ Based on live/nl/nl-medvri-medlab.md, message no. 2
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 2)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'MEDVRI')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 11)
        self.assertEqual(interchange.header.sender.identification, '41007001')
        self.assertEqual(interchange.header.recipient.identification, '41008002')

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 2)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

    def test_navigate(self) -> None:
        raw = load_message(_md_path, 2)
        msg = parse_edifact(raw).message

        self.assertEqual(msg.det.date.day, '12')
        self.assertEqual(msg.det.date.month, '02')
        self.assertEqual(msg.det.date.year, '24')
        self.assertEqual(msg.det.time.hour, '11')
        self.assertEqual(msg.det.time.minute, '05')
        self.assertEqual(msg.pad.address.building_number, '27a')
        self.assertEqual(msg.pad.address.city, 'Utrecht')
        self.assertEqual(msg.pad.address.postcode, '3581CD')
        self.assertEqual(msg.pad.address.street, 'Lindelaan')
        self.assertEqual(msg.pad.phone, '+31644556677')
        self.assertEqual(msg.pid.date_of_birth.day, '21')
        self.assertEqual(msg.pid.date_of_birth.month, '06')
        self.assertEqual(msg.pid.date_of_birth.year, '1988')
        self.assertEqual(msg.pid.patient_name.initials, 'JH')
        self.assertEqual(msg.pid.patient_name.maiden_name, 'Bruin')
        self.assertEqual(msg.pid.patient_name.maiden_name_prefix, 'de')
        self.assertEqual(msg.pid.patient_name.married_name, 'Wolf')
        self.assertEqual(msg.pid.patient_name.married_name_prefix, "van 't")
        self.assertEqual(msg.pid.receiver_reference, 'BSN999990019')
        self.assertEqual(msg.pid.sex, 'V')
        self.assertEqual(msg.receiver.address.building_number, '5C')
        self.assertEqual(msg.receiver.address.city, 'Utrecht')
        self.assertEqual(msg.receiver.address.postcode, '3512EF')
        self.assertEqual(msg.receiver.address.street, 'Molenpad')
        self.assertEqual(msg.receiver.person_name, 'Arts Naam')
        self.assertEqual(msg.receiver.phone, '0301234567')
        self.assertEqual(msg.sender.address.building_number, '14')
        self.assertEqual(msg.sender.address.city, 'Utrecht')
        self.assertEqual(msg.sender.address.postcode, '3511AB')
        self.assertEqual(msg.sender.address.street, 'Kerkstraat')
        self.assertEqual(msg.sender.department, 'Administratie')
        self.assertEqual(msg.sender.institution_name, 'Praktijk Rozenburg')
        self.assertEqual(msg.sender.person_name, 'Praktijk Rozenburg')
        self.assertEqual(msg.sender.phone, '+31611223344')
        self.assertEqual(msg.text[0].text, 'Beste collega')
        self.assertEqual(msg.text[1].text, 'hierbij de afgesproken terugkoppeling')
        self.assertEqual(msg.text[3].text, 'met vriendelijke groet')
        self.assertEqual(msg.unh.identifier.message_type, 'MEDVRI')
        self.assertEqual(msg.unh.identifier.version, '1')
        self.assertEqual(msg.unh.reference_number, '7431')
        self.assertEqual(msg.unt.reference_number, '7431')
        self.assertEqual(msg.unt.segment_count, '11')

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg03(unittest.TestCase):
    """ Based on live/nl/nl-medvri-medlab.md, message no. 3
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 3)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'MEDVRI')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 9)
        self.assertEqual(interchange.header.sender.identification, '41007001')
        self.assertEqual(interchange.header.recipient.identification, '41008002')

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 3)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()

        # Serialization reproduces the wire text exactly, one segment per line
        expected = "\n".join(_normalized_lines(raw))
        self.assertEqual(serialized, expected)

        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

    def test_navigate(self) -> None:
        raw = load_message(_md_path, 3)
        msg = parse_edifact(raw).message

        self.assertEqual(msg.det.date.day, '14')
        self.assertEqual(msg.det.date.month, '02')
        self.assertEqual(msg.det.date.year, '24')
        self.assertEqual(msg.det.time.hour, '09')
        self.assertEqual(msg.det.time.minute, '41')
        self.assertEqual(msg.pad.address.building_number, '27a')
        self.assertEqual(msg.pad.address.city, 'Utrecht')
        self.assertEqual(msg.pad.address.postcode, '3581CD')
        self.assertEqual(msg.pad.address.street, 'Lindelaan')
        self.assertEqual(msg.pad.phone, '+31644556677')
        self.assertEqual(msg.pid.date_of_birth.day, '18')
        self.assertEqual(msg.pid.date_of_birth.month, '03')
        self.assertEqual(msg.pid.date_of_birth.year, '1975')
        self.assertEqual(msg.pid.patient_name.initials, 'M.')
        self.assertEqual(msg.pid.patient_name.maiden_name, 'Peters')
        self.assertEqual(msg.pid.patient_name.maiden_name_prefix, 'de')
        self.assertEqual(msg.pid.patient_name.married_name, 'Dijk')
        self.assertEqual(msg.pid.patient_name.married_name_prefix, 'van der')
        self.assertEqual(msg.pid.receiver_reference, 'BSN999990019')
        self.assertEqual(msg.pid.sex, 'V')
        self.assertEqual(msg.receiver.address.building_number, '8')
        self.assertEqual(msg.receiver.address.city, 'Utrecht')
        self.assertEqual(msg.receiver.address.street, 'Dorpsweg')
        self.assertEqual(msg.receiver.person_name, 'Arts Achternaam')
        self.assertEqual(msg.sender.address.building_number, '14')
        self.assertEqual(msg.sender.address.city, 'Utrecht')
        self.assertEqual(msg.sender.address.postcode, '3511AB')
        self.assertEqual(msg.sender.address.street, 'Kerkstraat')
        self.assertEqual(msg.sender.department, 'Administratie')
        self.assertEqual(msg.sender.institution_name, 'Praktijk Rozenburg')
        self.assertEqual(msg.sender.person_name, 'Praktijk Rozenburg')
        self.assertEqual(msg.sender.phone, '+31611223344')
        self.assertEqual(msg.text[0].text, 'Beste collega')
        self.assertEqual(msg.text[1].text, 'Graag uw beoordeling van deze patient')
        self.assertEqual(msg.unh.identifier.message_type, 'MEDVRI')
        self.assertEqual(msg.unh.identifier.version, '1')
        self.assertEqual(msg.unh.reference_number, '7431')
        self.assertEqual(msg.unt.reference_number, '7431')
        self.assertEqual(msg.unt.segment_count, '9')

# ##################################################################################################################################
# ##################################################################################################################################

class TestMsg04(unittest.TestCase):
    """ Based on live/nl/nl-medvri-medlab.md, message no. 4
    """

    maxDiff = None

    def test_parse(self) -> None:
        raw = load_message(_md_path, 4)
        interchange = parse_edifact(raw)

        self.assertEqual(len(interchange.messages), 1)
        self.assertEqual(type(interchange.messages[0]).__name__, 'MEDLAB')
        self.assertEqual(len(interchange.messages[0]._raw_segments), 24)
        self.assertEqual(interchange.header.sender.identification, '41007001')
        self.assertEqual(interchange.header.recipient.identification, '41008002')

    def test_roundtrip(self) -> None:
        raw = load_message(_md_path, 4)
        interchange = parse_edifact(raw)
        serialized = interchange.serialize()


        # A second parse-serialize cycle is byte-stable
        self.assertEqual(parse_edifact(serialized).serialize(), serialized)

    def test_navigate(self) -> None:
        raw = load_message(_md_path, 4)
        msg = parse_edifact(raw).message

        self.assertEqual(msg.department.department, 'LAB KLINISCHE CHEMIE')
        self.assertEqual(msg.department.phone, '038-4445566')
        self.assertEqual(msg.doctor.address.building_number, '90')
        self.assertEqual(msg.doctor.address.city, 'Zwolle')
        self.assertEqual(msg.doctor.address.postcode, '8016GH')
        self.assertEqual(msg.doctor.address.street, 'Statenlaan')
        self.assertEqual(msg.doctor.doctor_code, '654321')
        self.assertEqual(msg.doctor.doctor_name.last_name, 'Huisartsenpraktijk Noord')
        self.assertEqual(msg.doctor.doctor_type, 'S')
        self.assertEqual(msg.hospital.address.building_number, '22')
        self.assertEqual(msg.hospital.address.city, 'Zwolle')
        self.assertEqual(msg.hospital.address.postcode, '8011AB')
        self.assertEqual(msg.hospital.address.street, 'Hoofdweg')
        self.assertEqual(msg.hospital.institution_name, 'ZIEKENHUIS OOST')
        self.assertEqual(msg.hospital.phone, '038-1112233')
        self.assertEqual(msg.lab_doctors[0].person_name, 'Dr. Visser')
        self.assertEqual(msg.lab_doctors[0].phone, '038-5556677')
        self.assertEqual(msg.materials[0].det.date.day, '09')
        self.assertEqual(msg.materials[0].det.date.month, '02')
        self.assertEqual(msg.materials[0].det.date.year, '24')
        self.assertEqual(msg.materials[0].det.time.hour, '09')
        self.assertEqual(msg.materials[0].det.time.minute, '20')
        self.assertEqual(msg.materials[0].determination_remarks[0].text, '*')
        self.assertEqual(msg.materials[0].determination_remarks[1].text, '-----OPM-----')
        self.assertEqual(msg.materials[0].determination_remarks[2].text, 'Epilepsie 4-10 mg/l, neuralgie 5-10 mg/l, gecombineerde therapie')
        self.assertEqual(msg.materials[0].determination_remarks[3].text, '4-8 mg/l, vrije concentratie 1-3 mg/l, Toxisch > 12 mg/l')
        self.assertEqual(msg.materials[0].determination_remarks[4].text, 'controle na dosisaanpassing')
        self.assertEqual(msg.materials[0].determination_remarks[5].text, '*')
        self.assertEqual(msg.materials[0].determination_remarks[6].text, 'niet betrouwbaar te bepalen')
        self.assertEqual(msg.materials[0].determinations[0].determination, 'MEDICIJNEN')
        self.assertEqual(msg.materials[0].determinations[0].determination_type, '1')
        self.assertEqual(msg.materials[0].determinations[1].determination, 'Carbamazepine')
        self.assertEqual(msg.materials[0].determinations[1].determination_code, 'CARBB SI')
        self.assertEqual(msg.materials[0].determinations[1].determination_type, '0')
        self.assertEqual(msg.materials[0].determinations[1].lower_limit, '4')
        self.assertEqual(msg.materials[0].determinations[1].result, '7.4')
        self.assertEqual(msg.materials[0].determinations[1].unit, 'mg/l')
        self.assertEqual(msg.materials[0].determinations[1].upper_limit, '10')
        self.assertEqual(msg.materials[0].determinations[2].determination, 'DIVERSEN')
        self.assertEqual(msg.materials[0].determinations[2].determination_type, '1')
        self.assertEqual(msg.materials[0].determinations[3].determination, 'Datum inname')
        self.assertEqual(msg.materials[0].determinations[3].determination_code, 'DINN10')
        self.assertEqual(msg.materials[0].determinations[3].determination_type, '0')
        self.assertEqual(msg.materials[0].determinations[3].result, '240208')
        self.assertEqual(msg.materials[0].determinations[4].determination, 'Tijd inname')
        self.assertEqual(msg.materials[0].determinations[4].determination_code, 'TINN10')
        self.assertEqual(msg.materials[0].determinations[4].determination_type, '0')
        self.assertEqual(msg.materials[0].determinations[4].result, '22.15')
        self.assertEqual(msg.materials[0].determinations[4].unit, 'uur')
        self.assertEqual(msg.materials[0].determinations[5].determination, 'Afname tijd')
        self.assertEqual(msg.materials[0].determinations[5].determination_code, 'TAFN10')
        self.assertEqual(msg.materials[0].determinations[5].determination_type, '0')
        self.assertEqual(msg.materials[0].determinations[5].result, '09.20')
        self.assertEqual(msg.materials[0].determinations[5].unit, 'uur')
        self.assertEqual(msg.materials[0].determinations[6].determination, 'Clozapine')
        self.assertEqual(msg.materials[0].determinations[6].determination_code, 'CLOZB')
        self.assertEqual(msg.materials[0].determinations[6].determination_type, '0')
        self.assertEqual(msg.materials[0].determinations[6].result, 'Zie onder')
        self.assertEqual(msg.materials[0].determinations[6].unit, 'ug/l')
        self.assertEqual(msg.materials[0].ide.complete_code, 'J')
        self.assertEqual(msg.materials[0].ide.identification_number, '445566')
        self.assertEqual(msg.pad.address.building_number, '27a')
        self.assertEqual(msg.pad.address.city, 'Utrecht')
        self.assertEqual(msg.pad.address.postcode, '3581CD')
        self.assertEqual(msg.pad.address.street, 'Lindelaan')
        self.assertEqual(msg.pad.phone, '+31644556677')
        self.assertEqual(msg.pid.date_of_birth.day, '18')
        self.assertEqual(msg.pid.date_of_birth.month, '03')
        self.assertEqual(msg.pid.date_of_birth.year, '1975')
        self.assertEqual(msg.pid.patient_name.initials, 'M.')
        self.assertEqual(msg.pid.patient_name.maiden_name, 'Peters')
        self.assertEqual(msg.pid.patient_name.maiden_name_prefix, 'de')
        self.assertEqual(msg.pid.patient_name.married_name, 'Dijk')
        self.assertEqual(msg.pid.patient_name.married_name_prefix, 'van der')
        self.assertEqual(msg.pid.receiver_reference, 'BSN999990019')
        self.assertEqual(msg.pid.sex, 'V')
        self.assertEqual(msg.unh.identifier.message_type, 'MEDLAB')
        self.assertEqual(msg.unh.identifier.version, '1')
        self.assertEqual(msg.unh.reference_number, '7431')
        self.assertEqual(msg.unt.reference_number, '55002187364')
        self.assertEqual(msg.unt.segment_count, '24')

# ##################################################################################################################################
# ##################################################################################################################################

if __name__ == '__main__':
    _ = unittest.main()
