from __future__ import annotations

from zato.fhir.r4_0_1.ukcore.v2_0_2.resources import (
    Address,
    AllergyIntolerance,
    Appointment,
    Coding,
    Composition,
    Condition,
    ContactPoint,
    DiagnosticReport,
    Encounter,
    FamilyMemberHistory,
    Immunization,
    List,
    Medication,
    MedicationRequest,
    MedicationStatement,
    Observation,
    Organization,
    Patient,
    RelatedPerson,
    ServiceRequest,
    Slot,
    Specimen,
)

__all__ = [
    'Address',
    'AllergyIntolerance',
    'Appointment',
    'Coding',
    'Composition',
    'Condition',
    'ContactPoint',
    'DiagnosticReport',
    'Encounter',
    'FamilyMemberHistory',
    'Immunization',
    'List',
    'Medication',
    'MedicationRequest',
    'MedicationStatement',
    'Observation',
    'Organization',
    'Patient',
    'RelatedPerson',
    'ServiceRequest',
    'Slot',
    'Specimen',
]
