<?xml version = '1.0' encoding = 'windows-1252'?>
<definitions name="CCServicesImpl" 
  targetNamespace=
     "http://tempuri.org/jdeveloper/generated/oracle/otnsamples/ws/CCServicesImpl"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:tns=
     "http://tempuri.org/jdeveloper/generated/oracle/otnsamples/ws/CCServicesImpl"
   xmlns:ns1=
     "http://tempuri.org/jdeveloper/generated/oracle/otnsamples/ws/CCServicesImpl/schema">
   <types>
      <schema
         targetNamespace=
         "http://tempuri.org/jdeveloper/generated/oracle/otnsamples/ws/CCServicesImpl/schema"
         xmlns="http://www.w3.org/2001/XMLSchema"
         xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"/>
   </types>
   <message name="validateCard0Request">
      <part name="cardNumber" type="xsd:string"/>
   </message>
   <message name="validateCard0Response"/>
   <portType name="CCServicesImplPortType">
      <operation name="validateCard">
         <input name="validateCard0Request" message="tns:validateCard0Request"/>
         <output name="validateCard0Response" message="tns:validateCard0Response"/>
      </operation>
   </portType>
   <binding name="CCServicesImplBinding" type="tns:CCServicesImplPortType">
      <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="validateCard">
         <soap:operation soapAction="" style="rpc"/>
         <input name="validateCard0Request">
            <soap:body use="encoded" namespace="CCServices" 
                       encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </input>
 
        <output name="validateCard0Response">
            <soap:body use="encoded" namespace="CCServices" 
                       encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
         </output>
      </operation>
   </binding>
   <service name="CCServicesImpl">
      <port name="CCServicesImplPort" binding="tns:CCServicesImplBinding">
         <soap:address location="http://127.0.0.1:8988/vsm/CCServices"/>
      </port>
   </service>
</definitions>
