from typing import Any

import smtplib
import socket
import sys
from email.header import Header
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import formatdate
from zato.common.py23_.past.builtins import basestring

class Email:
    recipients: Any
    subject: Any
    body: Any
    html_body: Any
    charset: Any
    fields: Any
    rfc2231: Any
    def __init__(self: Any, recipients: Any, subject: Any, body: Any = ..., html_body: Any = ..., charset: Any = ..., fields: Any = ..., rfc2231: Any = ...) -> None: ...
    def as_mime(self: Any, attachments: Any = ...) -> None: ...

class Attachment:
    name: Any
    raw: self.raw.encode
    def __init__(self: Any, name: Any, fileobj: Any) -> None: ...
    def read(self: Any) -> None: ...

class Outbox:
    username: Any
    password: Any
    connection_details: Any
    _conn: Any
    def __init__(self: Any, username: Any, password: Any, server: Any, port: Any, mode: Any = ..., debug: Any = ..., timeout: Any = ...) -> None: ...
    def __enter__(self: Any) -> None: ...
    def __exit__(self: Any, type: Any, value: Any, traceback: Any) -> None: ...
    def _login(self: Any) -> None: ...
    def connect(self: Any) -> None: ...
    def authenticate(self: Any, smtp: Any) -> None: ...
    def disconnect(self: Any) -> None: ...
    def send(self: Any, email: Any, attachments: Any = ..., from_: Any = ...) -> None: ...
    def sender_address(self: Any) -> None: ...

class AnonymousOutbox(Outbox):
    def __init__(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def authenticate(self: Any, smtp: Any) -> None: ...

def add_attachment(message: Any, attachment: Any, rfc2231: Any = ...) -> None: ...
