"""Add is_sync to AMQP channel

Revision ID: 0031_96e956cdc1d
Revises: 0030_9271ae91
Create Date: 2015-10-13 16:00:50.475877

"""

# revision identifiers, used by Alembic.
revision = '0031_96e956cdc1d'
down_revision = '0030_9271ae91'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_amqp', sa.Column('is_sync', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_amqp', 'is_sync')
    ### end Alembic commands ###
