"""Add nack_timeout to AMQP synchronous channel

Revision ID: 0032_a02f543e5d8
Revises: 0031_96e956cdc1d
Create Date: 2015-10-14 13:15:06.088485

"""

# revision identifiers, used by Alembic.
revision = '0032_a02f543e5d8'
down_revision = '0031_96e956cdc1d'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_amqp', sa.Column('nack_timeout', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_amqp', 'nack_timeout')
    ### end Alembic commands ###
