"""Add prefetch count option to AMQP channel

Revision ID: 0033_41ce0048dcbd
Revises: 0032_a02f543e5d8
Create Date: 2015-10-22 11:39:55.083472

"""

# revision identifiers, used by Alembic.
revision = '0033_41ce0048dcbd'
down_revision = '0032_a02f543e5d8'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_amqp', sa.Column('prefetch_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_amqp', 'prefetch_count')
    ### end Alembic commands ###

