"""Add blocking capabilities to SOAP outgoing queue

Revision ID: 0034_54ace55036f7
Revises: 0033_41ce0048dcbd
Create Date: 2015-10-27 16:09:26.036082

"""

# revision identifiers, used by Alembic.
revision = '0034_54ace55036f7'
down_revision = '0033_41ce0048dcbd'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('http_soap', sa.Column('blocking', sa.Boolean(), nullable=True, default=False))
    op.add_column('http_soap', sa.Column('blocking_time', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('http_soap', 'blocking')
    op.drop_column('http_soap', 'blocking_time')
    ### end Alembic commands ###
