# Generated - do not edit
from __future__ import annotations

BINDINGS: dict[str, list[dict]] = {
    "Account": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/account-status"},
    ],
    "ActivityDefinition": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "subject", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "kind", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-resource-types"},
        {"field": "intent", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-intent"},
        {"field": "priority", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
        {"field": "participant", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-participant-type"},
    ],
    "AdverseEvent": [
        {"field": "actuality", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/adverse-event-actuality"},
        {"field": "category", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/adverse-event-category"},
        {"field": "severity", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/adverse-event-severity"},
        {"field": "outcome", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/adverse-event-outcome"},
    ],
    "AllergyIntolerance": [
        {"field": "clinicalStatus", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/allergyintolerance-clinical"},
        {"field": "verificationStatus", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/allergyintolerance-verification"},
        {"field": "type", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/allergy-intolerance-type"},
        {"field": "category", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/allergy-intolerance-category"},
        {"field": "criticality", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/allergy-intolerance-criticality"},
        {"field": "reaction", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/reaction-event-severity"},
    ],
    "Appointment": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/appointmentstatus"},
        {"field": "participant", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/encounter-participant-type"},
        {"field": "participant", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/participantrequired"},
        {"field": "participant", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/participationstatus"},
    ],
    "AppointmentResponse": [
        {"field": "participantType", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/encounter-participant-type"},
        {"field": "participantStatus", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/participationstatus"},
    ],
    "AuditEvent": [
        {"field": "type", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/audit-event-type"},
        {"field": "subtype", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/audit-event-sub-type"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/audit-event-action"},
        {"field": "outcome", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/audit-event-outcome"},
        {"field": "purposeOfEvent", "strength": "extensible", "valueSet": "http://terminology.hl7.org/ValueSet/v3-PurposeOfUse"},
        {"field": "agent", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/participation-role-type"},
        {"field": "agent", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/dicm-405-mediatype"},
        {"field": "agent", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/network-type"},
        {"field": "agent", "strength": "extensible", "valueSet": "http://terminology.hl7.org/ValueSet/v3-PurposeOfUse"},
        {"field": "source", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/audit-source-type"},
        {"field": "entity", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/audit-entity-type"},
        {"field": "entity", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/object-role"},
        {"field": "entity", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/object-lifecycle-events"},
        {"field": "entity", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/security-labels"},
    ],
    "Binary": [
        {"field": "contentType", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/mimetypes"},
    ],
    "BiologicallyDerivedProduct": [
        {"field": "productCategory", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/product-category"},
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/product-status"},
        {"field": "storage", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/product-storage-scale"},
    ],
    "Bundle": [
        {"field": "type", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/bundle-type"},
        {"field": "entry", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/search-entry-mode"},
        {"field": "entry", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/http-verb"},
    ],
    "CapabilityStatement": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "kind", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/capability-statement-kind"},
        {"field": "fhirVersion", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/FHIR-version"},
        {"field": "format", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/mimetypes"},
        {"field": "patchFormat", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/mimetypes"},
        {"field": "rest", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/restful-capability-mode"},
        {"field": "rest", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/restful-security-service"},
        {"field": "rest", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/resource-types"},
        {"field": "rest", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/type-restful-interaction"},
        {"field": "rest", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/versioning-policy"},
        {"field": "rest", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/conditional-read-status"},
        {"field": "rest", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/conditional-delete-status"},
        {"field": "rest", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/reference-handling-policy"},
        {"field": "rest", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/search-param-type"},
        {"field": "rest", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/system-restful-interaction"},
        {"field": "messaging", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/message-transport"},
        {"field": "messaging", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/event-capability-mode"},
        {"field": "document", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/document-mode"},
    ],
    "CarePlan": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-status"},
        {"field": "intent", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/care-plan-intent"},
        {"field": "activity", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/care-plan-activity-kind"},
        {"field": "activity", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/care-plan-activity-status"},
    ],
    "CareTeam": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/care-team-status"},
    ],
    "CatalogEntry": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "relatedEntry", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/relation-type"},
    ],
    "ChargeItem": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/chargeitem-status"},
    ],
    "ChargeItemDefinition": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "propertyGroup", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/invoice-priceComponentType"},
    ],
    "Claim": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/fm-status"},
        {"field": "type", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/claim-type"},
        {"field": "use", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/claim-use"},
        {"field": "accident", "strength": "extensible", "valueSet": "http://terminology.hl7.org/ValueSet/v3-ActIncidentCode"},
    ],
    "ClaimResponse": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/fm-status"},
        {"field": "type", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/claim-type"},
        {"field": "use", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/claim-use"},
        {"field": "outcome", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/remittance-outcome"},
        {"field": "processNote", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/note-type"},
    ],
    "ClinicalImpression": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/clinicalimpression-status"},
    ],
    "CodeSystem": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "hierarchyMeaning", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/codesystem-hierarchy-meaning"},
        {"field": "content", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/codesystem-content-mode"},
        {"field": "filter", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/filter-operator"},
        {"field": "property", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/concept-property-type"},
        {"field": "concept", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/designation-use"},
    ],
    "Communication": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/event-status"},
        {"field": "priority", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
    ],
    "CommunicationRequest": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-status"},
        {"field": "priority", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
    ],
    "CompartmentDefinition": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "code", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/compartment-type"},
        {"field": "resource", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/resource-types"},
    ],
    "Composition": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/composition-status"},
        {"field": "confidentiality", "strength": "required", "valueSet": "http://terminology.hl7.org/ValueSet/v3-ConfidentialityClassification"},
        {"field": "attester", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/composition-attestation-mode"},
        {"field": "relatesTo", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/document-relationship-type"},
        {"field": "section", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/list-mode"},
    ],
    "ConceptMap": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "group", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/concept-map-equivalence"},
        {"field": "group", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/conceptmap-unmapped-mode"},
    ],
    "Condition": [
        {"field": "clinicalStatus", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/condition-clinical"},
        {"field": "verificationStatus", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/condition-ver-status"},
        {"field": "category", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/condition-category"},
    ],
    "Consent": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/consent-state-codes"},
        {"field": "scope", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/consent-scope"},
        {"field": "category", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/consent-category"},
        {"field": "policyRule", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/consent-policy"},
        {"field": "provision", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/consent-provision-type"},
        {"field": "provision", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/security-role-type"},
        {"field": "provision", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/security-labels"},
        {"field": "provision", "strength": "extensible", "valueSet": "http://terminology.hl7.org/ValueSet/v3-PurposeOfUse"},
        {"field": "provision", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/consent-content-class"},
        {"field": "provision", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/consent-data-meaning"},
    ],
    "Contract": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/contract-status"},
        {"field": "legalState", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/contract-legalstate"},
        {"field": "contentDefinition", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/contract-publicationstatus"},
        {"field": "term", "strength": "extensible", "valueSet": "http://terminology.hl7.org/ValueSet/v3-ActConsentDirective"},
        {"field": "term", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/consent-content-class"},
    ],
    "Coverage": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/fm-status"},
        {"field": "relationship", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subscriber-relationship"},
        {"field": "class", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/coverage-class"},
        {"field": "costToBeneficiary", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/coverage-copay-type"},
    ],
    "CoverageEligibilityRequest": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/fm-status"},
        {"field": "purpose", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/eligibilityrequest-purpose"},
    ],
    "CoverageEligibilityResponse": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/fm-status"},
        {"field": "purpose", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/eligibilityresponse-purpose"},
        {"field": "outcome", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/remittance-outcome"},
    ],
    "DetectedIssue": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "severity", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/detectedissue-severity"},
    ],
    "Device": [
        {"field": "udiCarrier", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/udi-entry-type"},
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/device-status"},
        {"field": "statusReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/device-status-reason"},
        {"field": "deviceName", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/device-nametype"},
    ],
    "DeviceDefinition": [
        {"field": "deviceName", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/device-nametype"},
    ],
    "DeviceMetric": [
        {"field": "operationalStatus", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/metric-operational-status"},
        {"field": "color", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/metric-color"},
        {"field": "category", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/metric-category"},
        {"field": "calibration", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/metric-calibration-type"},
        {"field": "calibration", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/metric-calibration-state"},
    ],
    "DeviceRequest": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-status"},
        {"field": "intent", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-intent"},
        {"field": "priority", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
    ],
    "DeviceUseStatement": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/device-statement-status"},
    ],
    "DiagnosticReport": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/diagnostic-report-status"},
    ],
    "DocumentManifest": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/document-reference-status"},
    ],
    "DocumentReference": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/document-reference-status"},
        {"field": "docStatus", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/composition-status"},
        {"field": "relatesTo", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/document-relationship-type"},
        {"field": "securityLabel", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/security-labels"},
    ],
    "EffectEvidenceSynthesis": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "synthesisType", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/synthesis-type"},
        {"field": "studyType", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/study-type"},
        {"field": "resultsByExposure", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/exposure-state"},
        {"field": "resultsByExposure", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/evidence-variant-state"},
        {"field": "effectEstimate", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/effect-estimate-type"},
        {"field": "effectEstimate", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/evidence-variant-state"},
        {"field": "effectEstimate", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-units"},
        {"field": "effectEstimate", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/precision-estimate-type"},
        {"field": "certainty", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/evidence-quality"},
        {"field": "certainty", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/certainty-subcomponent-type"},
        {"field": "certainty", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/certainty-subcomponent-rating"},
    ],
    "Encounter": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/encounter-status"},
        {"field": "statusHistory", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/encounter-status"},
        {"field": "class", "strength": "extensible", "valueSet": "http://terminology.hl7.org/ValueSet/v3-ActEncounterCode"},
        {"field": "classHistory", "strength": "extensible", "valueSet": "http://terminology.hl7.org/ValueSet/v3-ActEncounterCode"},
        {"field": "participant", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/encounter-participant-type"},
        {"field": "location", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/encounter-location-status"},
    ],
    "Endpoint": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/endpoint-status"},
        {"field": "connectionType", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/endpoint-connection-type"},
        {"field": "payloadMimeType", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/mimetypes"},
    ],
    "EnrollmentRequest": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/fm-status"},
    ],
    "EnrollmentResponse": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/fm-status"},
        {"field": "outcome", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/remittance-outcome"},
    ],
    "EpisodeOfCare": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/episode-of-care-status"},
        {"field": "statusHistory", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/episode-of-care-status"},
    ],
    "EventDefinition": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "subject", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
    ],
    "Evidence": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
    ],
    "EvidenceVariable": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "type", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/variable-type"},
        {"field": "characteristic", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/group-measure"},
    ],
    "ExampleScenario": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "actor", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/examplescenario-actor-type"},
        {"field": "instance", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/resource-types"},
    ],
    "ExplanationOfBenefit": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/explanationofbenefit-status"},
        {"field": "type", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/claim-type"},
        {"field": "use", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/claim-use"},
        {"field": "outcome", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/remittance-outcome"},
        {"field": "accident", "strength": "extensible", "valueSet": "http://terminology.hl7.org/ValueSet/v3-ActIncidentCode"},
        {"field": "processNote", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/note-type"},
    ],
    "FamilyMemberHistory": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/history-status"},
        {"field": "sex", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/administrative-gender"},
    ],
    "Flag": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/flag-status"},
    ],
    "Goal": [
        {"field": "lifecycleStatus", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/goal-status"},
    ],
    "GraphDefinition": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "start", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/resource-types"},
        {"field": "link", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/resource-types"},
        {"field": "link", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/graph-compartment-use"},
        {"field": "link", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/compartment-type"},
        {"field": "link", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/graph-compartment-rule"},
    ],
    "Group": [
        {"field": "type", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/group-type"},
    ],
    "GuidanceResponse": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/guidance-response-status"},
    ],
    "HealthcareService": [
        {"field": "availableTime", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/days-of-week"},
    ],
    "ImagingStudy": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/imagingstudy-status"},
        {"field": "modality", "strength": "extensible", "valueSet": "http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_29.html"},
        {"field": "procedureCode", "strength": "extensible", "valueSet": "http://www.rsna.org/RadLex_Playbook.aspx"},
        {"field": "series", "strength": "extensible", "valueSet": "http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_29.html"},
        {"field": "series", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/series-performer-function"},
        {"field": "series", "strength": "extensible", "valueSet": "http://dicom.nema.org/medical/dicom/current/output/chtml/part04/sect_B.5.html#table_B.5-1"},
    ],
    "Immunization": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/immunization-status"},
        {"field": "performer", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/immunization-function"},
    ],
    "ImmunizationEvaluation": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/immunization-evaluation-status"},
    ],
    "ImplementationGuide": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "license", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/spdx-license"},
        {"field": "fhirVersion", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/FHIR-version"},
        {"field": "global", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/resource-types"},
        {"field": "definition", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/FHIR-version"},
        {"field": "definition", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/guide-page-generation"},
        {"field": "definition", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/guide-parameter-code"},
    ],
    "InsurancePlan": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "contact", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/contactentity-type"},
        {"field": "plan", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/insuranceplan-applicability"},
    ],
    "Invoice": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/invoice-status"},
        {"field": "lineItem", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/invoice-priceComponentType"},
    ],
    "Library": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "type", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/library-type"},
        {"field": "subject", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
    ],
    "Linkage": [
        {"field": "item", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/linkage-type"},
    ],
    "List": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/list-status"},
        {"field": "mode", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/list-mode"},
    ],
    "Location": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/location-status"},
        {"field": "mode", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/location-mode"},
        {"field": "type", "strength": "extensible", "valueSet": "http://terminology.hl7.org/ValueSet/v3-ServiceDeliveryLocationRoleType"},
        {"field": "hoursOfOperation", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/days-of-week"},
    ],
    "Measure": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "subject", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "scoring", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/measure-scoring"},
        {"field": "compositeScoring", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/composite-measure-scoring"},
        {"field": "type", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/measure-type"},
        {"field": "improvementNotation", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/measure-improvement-notation"},
        {"field": "group", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/measure-population"},
        {"field": "supplementalData", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/measure-data-usage"},
    ],
    "MeasureReport": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/measure-report-status"},
        {"field": "type", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/measure-report-type"},
        {"field": "improvementNotation", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/measure-improvement-notation"},
        {"field": "group", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/measure-population"},
        {"field": "group", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/measure-population"},
    ],
    "Media": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/event-status"},
        {"field": "type", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/media-type"},
    ],
    "Medication": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/medication-status"},
    ],
    "MedicationAdministration": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/medication-admin-status"},
    ],
    "MedicationDispense": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/medicationdispense-status"},
    ],
    "MedicationKnowledge": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/medicationknowledge-status"},
    ],
    "MedicationRequest": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/medicationrequest-status"},
        {"field": "intent", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/medicationrequest-intent"},
        {"field": "priority", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
    ],
    "MedicationStatement": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/medication-statement-status"},
    ],
    "MessageDefinition": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "category", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/message-significance-category"},
        {"field": "focus", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/resource-types"},
        {"field": "responseRequired", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/messageheader-response-request"},
    ],
    "MessageHeader": [
        {"field": "response", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/response-code"},
    ],
    "MolecularSequence": [
        {"field": "type", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/sequence-type"},
        {"field": "referenceSeq", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/orientation-type"},
        {"field": "referenceSeq", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/strand-type"},
        {"field": "quality", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/quality-type"},
        {"field": "repository", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/repository-type"},
        {"field": "structureVariant", "strength": "required", "valueSet": "http://loinc.org/vs/LL379-9"},
    ],
    "NamingSystem": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "kind", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/namingsystem-type"},
        {"field": "type", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/identifier-type"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "uniqueId", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/namingsystem-identifier-type"},
    ],
    "NutritionOrder": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-status"},
        {"field": "intent", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-intent"},
        {"field": "enteralFormula", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/enteral-route"},
    ],
    "Observation": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
    "ObservationDefinition": [
        {"field": "permittedDataType", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/permitted-data-type"},
        {"field": "quantitativeDetails", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-units"},
        {"field": "quantitativeDetails", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-units"},
        {"field": "qualifiedInterval", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-range-category"},
        {"field": "qualifiedInterval", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/referencerange-meaning"},
        {"field": "qualifiedInterval", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/administrative-gender"},
    ],
    "OperationDefinition": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "kind", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/operation-kind"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "resource", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/resource-types"},
        {"field": "parameter", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/operation-parameter-use"},
        {"field": "parameter", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/all-types"},
        {"field": "parameter", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/search-param-type"},
        {"field": "parameter", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/binding-strength"},
    ],
    "OperationOutcome": [
        {"field": "issue", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/issue-severity"},
        {"field": "issue", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/issue-type"},
    ],
    "Organization": [
        {"field": "contact", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/contactentity-type"},
    ],
    "Patient": [
        {"field": "gender", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/administrative-gender"},
        {"field": "maritalStatus", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/marital-status"},
        {"field": "contact", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/patient-contactrelationship"},
        {"field": "contact", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/administrative-gender"},
        {"field": "link", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/link-type"},
    ],
    "PaymentNotice": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/fm-status"},
    ],
    "PaymentReconciliation": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/fm-status"},
        {"field": "outcome", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/remittance-outcome"},
        {"field": "processNote", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/note-type"},
    ],
    "Person": [
        {"field": "gender", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/administrative-gender"},
        {"field": "link", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/identity-assuranceLevel"},
    ],
    "PlanDefinition": [
        {"field": "type", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/plan-definition-type"},
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "subject", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
        {"field": "action", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-condition-kind"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-relationship-type"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-participant-type"},
        {"field": "action", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/action-type"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-grouping-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-selection-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-required-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-precheck-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-cardinality-behavior"},
    ],
    "Practitioner": [
        {"field": "gender", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/administrative-gender"},
    ],
    "PractitionerRole": [
        {"field": "availableTime", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/days-of-week"},
    ],
    "Procedure": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/event-status"},
    ],
    "Provenance": [
        {"field": "reason", "strength": "extensible", "valueSet": "http://terminology.hl7.org/ValueSet/v3-PurposeOfUse"},
        {"field": "activity", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/provenance-activity-type"},
        {"field": "agent", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/provenance-agent-type"},
        {"field": "entity", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/provenance-entity-role"},
    ],
    "Questionnaire": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "subjectType", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/resource-types"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "item", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/item-type"},
        {"field": "item", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/questionnaire-enable-operator"},
        {"field": "item", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/questionnaire-enable-behavior"},
    ],
    "QuestionnaireResponse": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/questionnaire-answers-status"},
    ],
    "RelatedPerson": [
        {"field": "gender", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/administrative-gender"},
    ],
    "RequestGroup": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-status"},
        {"field": "intent", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-intent"},
        {"field": "priority", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-condition-kind"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-relationship-type"},
        {"field": "action", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/action-type"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-grouping-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-selection-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-required-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-precheck-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-cardinality-behavior"},
    ],
    "ResearchDefinition": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "subject", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
    ],
    "ResearchElementDefinition": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "subject", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "type", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/research-element-type"},
        {"field": "variableType", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/variable-type"},
        {"field": "characteristic", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-units"},
        {"field": "characteristic", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/group-measure"},
        {"field": "characteristic", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/group-measure"},
    ],
    "ResearchStudy": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/research-study-status"},
        {"field": "primaryPurposeType", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/research-study-prim-purp-type"},
        {"field": "location", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
    ],
    "ResearchSubject": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/research-subject-status"},
    ],
    "RiskAssessment": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
    ],
    "RiskEvidenceSynthesis": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "synthesisType", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/synthesis-type"},
        {"field": "studyType", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/study-type"},
        {"field": "riskEstimate", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/risk-estimate-type"},
        {"field": "riskEstimate", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-units"},
        {"field": "riskEstimate", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/precision-estimate-type"},
        {"field": "certainty", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/evidence-quality"},
        {"field": "certainty", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/certainty-subcomponent-type"},
        {"field": "certainty", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/certainty-subcomponent-rating"},
    ],
    "SearchParameter": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "base", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/resource-types"},
        {"field": "type", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/search-param-type"},
        {"field": "xpathUsage", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/search-xpath-usage"},
        {"field": "target", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/resource-types"},
        {"field": "comparator", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/search-comparator"},
        {"field": "modifier", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/search-modifier-code"},
    ],
    "ServiceRequest": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-status"},
        {"field": "intent", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-intent"},
        {"field": "priority", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
    ],
    "Slot": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/slotstatus"},
    ],
    "Specimen": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/specimen-status"},
        {"field": "collection", "strength": "extensible", "valueSet": "http://terminology.hl7.org/ValueSet/v2-0916"},
        {"field": "condition", "strength": "extensible", "valueSet": "http://terminology.hl7.org/ValueSet/v2-0493"},
    ],
    "SpecimenDefinition": [
        {"field": "typeTested", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/specimen-contained-preference"},
    ],
    "StructureDefinition": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "keyword", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/definition-use"},
        {"field": "fhirVersion", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/FHIR-version"},
        {"field": "kind", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/structure-definition-kind"},
        {"field": "context", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/extension-context-type"},
        {"field": "type", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/defined-types"},
        {"field": "derivation", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/type-derivation-rule"},
    ],
    "StructureMap": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "structure", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/map-model-mode"},
        {"field": "group", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/map-group-type-mode"},
        {"field": "group", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/map-input-mode"},
        {"field": "group", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/map-source-list-mode"},
        {"field": "group", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/map-context-type"},
        {"field": "group", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/map-target-list-mode"},
        {"field": "group", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/map-transform"},
    ],
    "Subscription": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/subscription-status"},
        {"field": "channel", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/subscription-channel-type"},
        {"field": "channel", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/mimetypes"},
    ],
    "Substance": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/substance-status"},
        {"field": "category", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/substance-category"},
    ],
    "SupplyDelivery": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/supplydelivery-status"},
        {"field": "type", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/supplydelivery-type"},
    ],
    "SupplyRequest": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/supplyrequest-status"},
        {"field": "priority", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
    ],
    "Task": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/task-status"},
        {"field": "intent", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/task-intent"},
        {"field": "priority", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
    ],
    "TerminologyCapabilities": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "kind", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/capability-statement-kind"},
        {"field": "codeSearch", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/code-search-support"},
    ],
    "TestReport": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/report-status-codes"},
        {"field": "result", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/report-result-codes"},
        {"field": "participant", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/report-participant-type"},
        {"field": "setup", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/report-action-result-codes"},
        {"field": "setup", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/report-action-result-codes"},
    ],
    "TestScript": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "origin", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/testscript-profile-origin-types"},
        {"field": "destination", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/testscript-profile-destination-types"},
        {"field": "setup", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/testscript-operation-codes"},
        {"field": "setup", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/defined-types"},
        {"field": "setup", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/mimetypes"},
        {"field": "setup", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/mimetypes"},
        {"field": "setup", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/http-operations"},
        {"field": "setup", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/assert-direction-codes"},
        {"field": "setup", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/mimetypes"},
        {"field": "setup", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/assert-operator-codes"},
        {"field": "setup", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/http-operations"},
        {"field": "setup", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/defined-types"},
        {"field": "setup", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/assert-response-code-types"},
    ],
    "ValueSet": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "compose", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/designation-use"},
        {"field": "compose", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/filter-operator"},
    ],
    "VerificationResult": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/verificationresult-status"},
    ],
    "VisionPrescription": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/fm-status"},
        {"field": "lensSpecification", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/vision-eye-codes"},
        {"field": "lensSpecification", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/vision-base-codes"},
    ],
    "actualgroup": [
        {"field": "type", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/group-type"},
    ],
    "bmi": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "code", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "value", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/quantity-comparator"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "component", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-vitals-common"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
    "bodyheight": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "code", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "value", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/quantity-comparator"},
        {"field": "value", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-bodylength"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "component", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-vitals-common"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
    "bodytemp": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "code", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "value", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/quantity-comparator"},
        {"field": "value", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-bodytemp"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "component", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-vitals-common"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
    "bodyweight": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "code", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "value", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/quantity-comparator"},
        {"field": "value", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-bodyweight"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "component", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-vitals-common"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
    "bp": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "code", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "component", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-vitals-common"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "component", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-vitals-common"},
        {"field": "component", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/quantity-comparator"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "component", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-vitals-common"},
        {"field": "component", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/quantity-comparator"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
    "catalog": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/composition-status"},
        {"field": "confidentiality", "strength": "required", "valueSet": "http://terminology.hl7.org/ValueSet/v3-ConfidentialityClassification"},
        {"field": "attester", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/composition-attestation-mode"},
        {"field": "relatesTo", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/document-relationship-type"},
        {"field": "section", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/list-mode"},
    ],
    "cdshooksguidanceresponse": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/guidance-response-status"},
    ],
    "cdshooksrequestgroup": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-status"},
        {"field": "intent", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-intent"},
        {"field": "priority", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-condition-kind"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-relationship-type"},
        {"field": "action", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/action-type"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-grouping-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-selection-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-required-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-precheck-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-cardinality-behavior"},
    ],
    "cdshooksserviceplandefinition": [
        {"field": "type", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/plan-definition-type"},
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "subject", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
        {"field": "action", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-condition-kind"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-relationship-type"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-participant-type"},
        {"field": "action", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/action-type"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-grouping-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-selection-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-required-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-precheck-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-cardinality-behavior"},
    ],
    "cholesterol": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "value", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/quantity-comparator"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
    "clinicaldocument": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/composition-status"},
        {"field": "confidentiality", "strength": "required", "valueSet": "http://terminology.hl7.org/ValueSet/v3-ConfidentialityClassification"},
        {"field": "attester", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/composition-attestation-mode"},
        {"field": "relatesTo", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/document-relationship-type"},
        {"field": "section", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/list-mode"},
    ],
    "computableplandefinition": [
        {"field": "type", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/plan-definition-type"},
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "subject", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
        {"field": "action", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-condition-kind"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-relationship-type"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-participant-type"},
        {"field": "action", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/action-type"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-grouping-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-selection-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-required-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-precheck-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-cardinality-behavior"},
    ],
    "cqf-questionnaire": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "subjectType", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/resource-types"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "item", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/item-type"},
        {"field": "item", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/questionnaire-enable-operator"},
        {"field": "item", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/questionnaire-enable-behavior"},
    ],
    "cqllibrary": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "type", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/library-type"},
        {"field": "subject", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
    ],
    "devicemetricobservation": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
    "diagnosticreport-genetics": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/diagnostic-report-status"},
    ],
    "ehrsrle-auditevent": [
        {"field": "type", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/audit-event-type"},
        {"field": "subtype", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/audit-event-sub-type"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/audit-event-action"},
        {"field": "outcome", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/audit-event-outcome"},
        {"field": "purposeOfEvent", "strength": "extensible", "valueSet": "http://terminology.hl7.org/ValueSet/v3-PurposeOfUse"},
        {"field": "agent", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/participation-role-type"},
        {"field": "agent", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/dicm-405-mediatype"},
        {"field": "agent", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/network-type"},
        {"field": "agent", "strength": "extensible", "valueSet": "http://terminology.hl7.org/ValueSet/v3-PurposeOfUse"},
        {"field": "source", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/audit-source-type"},
        {"field": "entity", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/audit-entity-type"},
        {"field": "entity", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/object-role"},
        {"field": "entity", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/object-lifecycle-events"},
        {"field": "entity", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/security-labels"},
    ],
    "ehrsrle-provenance": [
        {"field": "reason", "strength": "extensible", "valueSet": "http://terminology.hl7.org/ValueSet/v3-PurposeOfUse"},
        {"field": "activity", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/provenance-activity-type"},
        {"field": "agent", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/provenance-agent-type"},
        {"field": "entity", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/provenance-entity-role"},
    ],
    "familymemberhistory-genetic": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/history-status"},
        {"field": "sex", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/administrative-gender"},
    ],
    "groupdefinition": [
        {"field": "type", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/group-type"},
    ],
    "hdlcholesterol": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
    "headcircum": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "code", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "value", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/quantity-comparator"},
        {"field": "value", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-bodylength"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "component", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-vitals-common"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
    "heartrate": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "code", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "value", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/quantity-comparator"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "component", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-vitals-common"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
    "hlaresult": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/diagnostic-report-status"},
    ],
    "ldlcholesterol": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "code", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ldlcholesterol-codes"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
    "lipidprofile": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/diagnostic-report-status"},
    ],
    "observation-genetics": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
    "oxygensat": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "code", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "value", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/quantity-comparator"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "component", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-vitals-common"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
    "picoelement": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "type", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/variable-type"},
        {"field": "characteristic", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/group-measure"},
    ],
    "provenance-relevant-history": [
        {"field": "reason", "strength": "extensible", "valueSet": "http://terminology.hl7.org/ValueSet/v3-PurposeOfUse"},
        {"field": "activity", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/provenance-history-record-activity"},
        {"field": "agent", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/provenance-history-agent-type"},
        {"field": "agent", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/provenance-agent-type"},
        {"field": "entity", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/provenance-entity-role"},
    ],
    "resprate": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "code", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "value", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/quantity-comparator"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "component", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-vitals-common"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
    "servicerequest-genetics": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-status"},
        {"field": "intent", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-intent"},
        {"field": "priority", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
    ],
    "shareableactivitydefinition": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "subject", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "kind", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-resource-types"},
        {"field": "intent", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-intent"},
        {"field": "priority", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
        {"field": "participant", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-participant-type"},
    ],
    "shareablecodesystem": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "hierarchyMeaning", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/codesystem-hierarchy-meaning"},
        {"field": "content", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/codesystem-content-mode"},
        {"field": "filter", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/filter-operator"},
        {"field": "property", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/concept-property-type"},
        {"field": "concept", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/designation-use"},
    ],
    "shareablelibrary": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "type", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/library-type"},
        {"field": "subject", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
    ],
    "shareablemeasure": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "subject", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "scoring", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/measure-scoring"},
        {"field": "compositeScoring", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/composite-measure-scoring"},
        {"field": "type", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/measure-type"},
        {"field": "improvementNotation", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/measure-improvement-notation"},
        {"field": "group", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/measure-population"},
        {"field": "supplementalData", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/measure-data-usage"},
    ],
    "shareableplandefinition": [
        {"field": "type", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/plan-definition-type"},
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "subject", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/request-priority"},
        {"field": "action", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/subject-type"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-condition-kind"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-relationship-type"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-participant-type"},
        {"field": "action", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/action-type"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-grouping-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-selection-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-required-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-precheck-behavior"},
        {"field": "action", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/action-cardinality-behavior"},
    ],
    "shareablevalueset": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
        {"field": "compose", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/designation-use"},
        {"field": "compose", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/filter-operator"},
    ],
    "synthesis": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/publication-status"},
        {"field": "jurisdiction", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/jurisdiction"},
    ],
    "triglyceride": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
    "vitalsigns": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "code", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "component", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-vitals-common"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
    "vitalspanel": [
        {"field": "status", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/observation-status"},
        {"field": "code", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "dataAbsentReason", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "interpretation", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-vitalsignresult"},
        {"field": "component", "strength": "required", "valueSet": "http://hl7.org/fhir/ValueSet/ucum-vitals-common"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/data-absent-reason"},
        {"field": "component", "strength": "extensible", "valueSet": "http://hl7.org/fhir/ValueSet/observation-interpretation"},
    ],
}
