from typing import Any

import logging
from base64 import b64encode
from datetime import datetime, timedelta
from itertools import chain
from traceback import format_exc
from bunch import Bunch
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseServerError
from pytz import UTC
from zato.admin.web import from_utc_to_user
from zato.admin.web.util import get_template_response
from zato.common.api import CONNECTION, SEC_DEF_TYPE_NAME, URL_TYPE, ZATO_NONE
from zato.common.exception import ZatoException
from zato.common.json_internal import dumps
from zato.common.util.api import validate_python_syntax
from django.urls import reverse as django_url_reverse
from django.utils.text import slugify
from zato.client import ServiceInvokeResponse
from zato.common.typing_ import any_, anylist

def parse_response_data(response: Any) -> None: ...

def invoke_list_service(client: Any, cluster: Any, service: Any, extra: Any = ...) -> None: ...

def get_outconn_rest_list(req: Any, name_to_id: Any = ...) -> None: ...

def get_sample_dt(user_profile: Any) -> None: ...

def get_js_dt_format(user_profile: Any) -> None: ...

def method_allowed(*methods_allowed: Any) -> None: ...

def set_servers_state(cluster: Any, client: Any) -> None: ...

def change_password(req: Any, service_name: Any, field1: Any = ..., field2: Any = ..., success_msg: Any = ..., data: Any = ...) -> None: ...

def get_security_id_from_select(params: Any, prefix: Any, field_name: Any = ...) -> None: ...

def get_security_groups_from_checkbox_list(params: Any, prefix: Any, field_name_prefix: Any = ...) -> None: ...

def build_sec_def_link(cluster_id: Any, sec_type: Any, sec_name: Any) -> None: ...

def build_sec_def_link_by_input(req: Any, cluster_id: Any, input_data: Any) -> None: ...

class BaseView:
    method_allowed: Any
    service_name: Any
    async_invoke: Any
    form_prefix: Any
    req: Any
    cluster_id: Any
    ctx: Any
    def __init__(self: Any) -> None: ...
    def __call__(self: Any, req: Any, *args: Any, **kwargs: Any) -> None: ...
    def build_sec_def_link_by_input(self: Any, input_data: Any) -> None: ...
    def on_before_append_item(self: Any, item: Any) -> None: ...
    def get_output_class(self: Any) -> None: ...
    def on_after_set_input(self: Any) -> None: ...
    def clear_user_message(self: Any) -> None: ...
    def get_service_name(self: Any, *_args: Any, **_kwargs: Any) -> None: ...
    def fetch_cluster_id(self: Any) -> None: ...
    def populate_initial_input_dict(self: Any, initial_input_dict: Any) -> None: ...
    def get_sec_def_list(self: Any, sec_type: Any) -> None: ...
    def set_input(self: Any, req: Any = ..., default_attrs: Any = ...) -> None: ...

class Index(BaseView):
    url_name: Any
    template: Any
    wrapper_type: Any
    output_class: Any
    clear_self_items: Any
    update_request_with_self_input: Any
    input: Bunch
    items: Any
    item: Any
    def __init__(self: Any) -> None: ...
    def can_invoke_admin_service(self: Any) -> None: ...
    def before_invoke_admin_service(self: Any) -> None: ...
    def get_service_name(self: Any, _req: Any) -> None: ...
    def get_initial_input(self: Any) -> None: ...
    def get_template_name(self: Any) -> None: ...
    def should_extract_top_level(self: Any, _keys: Any) -> None: ...
    def invoke_admin_service(self: Any) -> ServiceInvokeResponse: ...
    def should_include(self: Any, item: Any) -> bool: ...
    def _handle_single_item_list(self: Any, container: Any, item_list: Any) -> None: ...
    def handle_item_list(self: Any, item_list: Any, _ignored_is_extracted: Any) -> None: ...
    def _handle_item(self: Any, item: Any) -> None: ...
    def handle_return_data(self: Any, return_data: Any) -> None: ...
    def __call__(self: Any, req: Any, *args: Any, **kwargs: Any) -> None: ...
    def handle(self: Any, req: Any = ..., *args: Any, **kwargs: Any) -> None: ...

class CreateEdit(BaseView):
    input: Bunch
    input_dict: Any
    def __init__(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def __call__(self: Any, req: Any, initial_input_dict: Any = ..., initial_return_data: Any = ..., *args: Any, **kwargs: Any) -> None: ...
    def pre_process_input_dict(self: Any, input_dict: Any) -> None: ...
    def pre_process_item(self: Any, name: Any, value: Any) -> None: ...
    def success_message(self: Any, item: Any) -> None: ...
    def post_process_return_data(self: Any, return_data: Any) -> None: ...
    @property
    def verb(self: Any) -> None: ...

class BaseCallView(BaseView):
    method_allowed: Any
    error_message: Any
    def get_input_dict(self: Any) -> None: ...
    def build_http_response(self: Any, response: Any) -> None: ...
    def __call__(self: Any, req: Any, initial_input_dict: Any = ..., *args: Any, **kwargs: Any) -> None: ...

class Delete(BaseCallView):
    id_elem: Any
    def get_input_dict(self: Any) -> None: ...

class SecurityList:
    needs_def_type_name_label: Any
    def_items: Any
    def __init__(self: Any, needs_def_type_name_label: Any = ...) -> None: ...
    def __iter__(self: Any) -> None: ...
    def append(self: Any, def_item: Any) -> None: ...
    @staticmethod
    def from_service(client: Any, cluster_id: Any, sec_type: Any = ..., needs_def_type_name_label: Any = ...) -> None: ...

def id_only_service(req: Any, service: Any, id: Any, error_template: Any = ..., initial: Any = ...) -> None: ...

def ping_connection(req: Any, service: Any, connection_id: Any, connection_type: Any = ..., ping_path: Any = ...) -> any_: ...

def invoke_service_with_json_response(req: Any, service: Any, input_dict: Any, ok_msg: Any, error_template: Any = ..., content_type: Any = ..., extra: Any = ...) -> None: ...

def upload_to_server(client: Any, data: Any, payload_name: Any, cluster_id: Any = ..., service: Any = ..., error_msg_template: Any = ...) -> None: ...

def extract_security_id(item: Any) -> None: ...

def get_http_channel_security_id(item: Any) -> None: ...

def invoke_action_handler(req: Any, service_name: str, send_attrs: any_ = ..., extra: Any = ...) -> any_: ...

def get_security_name_link(req: Any, sec_type: Any, sec_name: Any) -> None: ...

def get_group_list(req: any_, group_type: str) -> anylist: ...
