from typing import Any

import os
from logging import getLogger
from zato.admin.web.views import method_allowed
from zato.admin.web.views.settings.base import SettingsBaseView
from zato.admin.web.views.settings.config import updates_page_config
from zato.admin.web.views.settings.handlers import ScheduleHandler, AuditLogHandler
from zato.admin.web.views.settings.utils import json_response
from zato.common.util.updates import Updater, UpdaterConfig
from django.http import FileResponse, HttpResponse
import redis

class UpdatesView(SettingsBaseView):
    def __init__(self: Any) -> None: ...
    def get_index_context(self: Any) -> None: ...
    def save_schedule(self: Any, req: Any) -> None: ...
    def load_schedule(self: Any, req: Any) -> None: ...
    def delete_schedule(self: Any, req: Any) -> None: ...
    def get_latest_audit_entry(self: Any, req: Any) -> None: ...
    def get_audit_log_refresh(self: Any, req: Any) -> None: ...

def check_availability(req: Any) -> None: ...

def download_and_install(req: Any) -> None: ...

def check_latest_version(req: Any) -> None: ...

def download_logs(req: Any) -> None: ...
