from __future__ import annotations

from zato.hl7v2.tests.fakers.msg_ras import *
from zato.hl7v2.tests.fakers.msg_rcv import *
from zato.hl7v2.tests.fakers.msg_rde import *
from zato.hl7v2.tests.fakers.msg_rdr import *
from zato.hl7v2.tests.fakers.msg_rds import *
from zato.hl7v2.tests.fakers.msg_rdy import *
from zato.hl7v2.tests.fakers.msg_ref import *
from zato.hl7v2.tests.fakers.msg_rgv import *
from zato.hl7v2.tests.fakers.msg_rpa import *
from zato.hl7v2.tests.fakers.msg_rpi import *
from zato.hl7v2.tests.fakers.msg_rpl import *
from zato.hl7v2.tests.fakers.msg_rpr import *
from zato.hl7v2.tests.fakers.msg_rqa import *
from zato.hl7v2.tests.fakers.msg_rqi import *
from zato.hl7v2.tests.fakers.msg_rqp import *
from zato.hl7v2.tests.fakers.msg_rra import *
from zato.hl7v2.tests.fakers.msg_rrd import *
from zato.hl7v2.tests.fakers.msg_rre import *
from zato.hl7v2.tests.fakers.msg_rrg import *
from zato.hl7v2.tests.fakers.msg_rri import *
from zato.hl7v2.tests.fakers.msg_rsp import *
from zato.hl7v2.tests.fakers.msg_rtb import *
