from __future__ import annotations

from zato.hl7v2.tests.fakers.msg_omb import *
from zato.hl7v2.tests.fakers.msg_omd import *
from zato.hl7v2.tests.fakers.msg_omg import *
from zato.hl7v2.tests.fakers.msg_omi import *
from zato.hl7v2.tests.fakers.msg_oml import *
from zato.hl7v2.tests.fakers.msg_omn import *
from zato.hl7v2.tests.fakers.msg_omp import *
from zato.hl7v2.tests.fakers.msg_omq import *
from zato.hl7v2.tests.fakers.msg_oms import *
from zato.hl7v2.tests.fakers.msg_opl import *
from zato.hl7v2.tests.fakers.msg_opr import *
from zato.hl7v2.tests.fakers.msg_opu import *
from zato.hl7v2.tests.fakers.msg_ora import *
from zato.hl7v2.tests.fakers.msg_orb import *
from zato.hl7v2.tests.fakers.msg_ord import *
from zato.hl7v2.tests.fakers.msg_org import *
from zato.hl7v2.tests.fakers.msg_ori import *
from zato.hl7v2.tests.fakers.msg_orl import *
from zato.hl7v2.tests.fakers.msg_orm import *
from zato.hl7v2.tests.fakers.msg_orn import *
from zato.hl7v2.tests.fakers.msg_orp import *
from zato.hl7v2.tests.fakers.msg_ors import *
from zato.hl7v2.tests.fakers.msg_oru import *
from zato.hl7v2.tests.fakers.msg_orx import *
from zato.hl7v2.tests.fakers.msg_osm import *
from zato.hl7v2.tests.fakers.msg_osu import *
from zato.hl7v2.tests.fakers.msg_oul import *
