from typing import Any, TYPE_CHECKING

from __future__ import print_function
import os
import sys
import traceback
from zato.server.ext.zunicorn._compat import execfile_
from zato.server.ext.zunicorn import util
from zato.server.ext.zunicorn.arbiter import Arbiter
from zato.server.ext.zunicorn.config import Config, get_default_config_file
from zato.server.ext.zunicorn import debug


class BaseApplication:
    usage: Any
    cfg: Any
    callable: Any
    prog: Any
    logger: Any
    def __init__(self: Any, usage: Any = ..., prog: Any = ...) -> None: ...
    def do_load_config(self: Any) -> None: ...
    def load_default_config(self: Any) -> None: ...
    def init(self: Any, parser: Any, opts: Any, args: Any) -> None: ...
    def load(self: Any) -> None: ...
    def load_config(self: Any) -> None: ...
    def reload(self: Any) -> None: ...
    def wsgi(self: Any) -> None: ...
    def run(self: Any) -> None: ...

class Application(BaseApplication):
    def chdir(self: Any) -> None: ...
    def get_config_from_filename(self: Any, filename: Any) -> None: ...
    def get_config_from_module_name(self: Any, module_name: Any) -> None: ...
    def load_config_from_module_name_or_filename(self: Any, location: Any) -> None: ...
    def load_config_from_file(self: Any, filename: Any) -> None: ...
    def load_config(self: Any) -> None: ...
    def run(self: Any) -> None: ...
