
.PHONY: build

sso-test:
#	py $(CURDIR)/test/zato/test_user.py      &&
#	py $(CURDIR)/test/zato/test_session.py   &&
#	py $(CURDIR)/test/zato/test_user_attr_create.py &&
	py $(CURDIR)/test/zato/test_user_attr_update.py
