from typing import Any

from threading import Lock
from colorama import Fore, Style
from zato.common.util.api import utcnow
from datetime import timedelta

class ProgressTracker:
    def __init__(self: Any, total_producers: int, total_messages: int) -> None: ...
    def update_progress(self: Any, success: bool = ..., count: int = ...) -> None: ...
    def _display_progress(self: Any) -> None: ...
    def finish(self: Any) -> None: ...
