from typing import Any

from copy import deepcopy
from logging import getLogger
from threading import RLock
from paste.util.multidict import MultiDict
from zato.bunch import Bunch
from zato.common.ext.future.utils import itervalues
from zato.common.py23_.past.builtins import unicode
from zato.common.api import ZATO_NONE
from zato.common.const import SECRETS
from zato.common.util.config import resolve_name, resolve_value
from zato.common.util.sql import ElemsWithOpaqueMaker
from zato.common.typing_ import anylist, stranydict
from zato.server.connection.ftp import FTPStore

class ConfigDict:
    __setitem__: Any
    __str__: Any
    name: Any
    _impl: Any
    lock: RLock
    def __init__(self: Any, name: Any, _bunch: Any = ...) -> None: ...
    def get(self: Any, key: Any, default: Any = ...) -> None: ...
    def set(self: Any, key: Any, value: Any) -> None: ...
    def __getitem__(self: Any, key: Any) -> None: ...
    def __delitem__(self: Any, key: Any) -> None: ...
    def pop(self: Any, key: Any, default: Any) -> None: ...
    def update(self: Any, dict_: Any) -> None: ...
    def __iter__(self: Any) -> None: ...
    def __repr__(self: Any) -> None: ...
    def __nonzero__(self: Any) -> None: ...
    def keys(self: Any) -> None: ...
    def values(self: Any) -> None: ...
    def itervalues(self: Any) -> None: ...
    def items(self: Any) -> None: ...
    def get_by_id(self: Any, key_id: Any, default: Any = ...) -> None: ...
    def set_key_id_data(self: Any, config: Any) -> None: ...
    def copy(self: Any) -> None: ...
    def get_config_list(self: Any, predicate: Any = ...) -> None: ...
    def copy_keys(self: Any, skip_ids: Any = ...) -> None: ...
    @staticmethod
    def from_query(name: Any, query_data: Any, impl_class: Any = ..., item_class: Any = ..., list_config: Any = ..., decrypt_func: Any = ..., drop_opaque: Any = ...) -> None: ...
    @staticmethod
    def from_generic(config_dict: Any) -> None: ...

class ConfigStore:
    out_ftp: Any
    out_odoo: Any
    out_soap: Any
    out_sql: Any
    out_sap: Any
    out_plain_http: Any
    out_amqp: Any
    email_smtp: Any
    email_imap: Any
    generic_connection: Any
    service: Any
    search_es: Any
    cache_builtin: Any
    repo_location: Any
    apikey: Any
    basic_auth: Any
    ntlm: Any
    oauth: Any
    url_sec: Any
    http_soap: Any
    broker_config: Any
    odb_data: Bunch
    simple_io: Any
    channel_amqp: Any
    def __init__(self: Any) -> None: ...
    def get_config_by_item_id(self: Any, attr_name: Any, item_id: Any) -> None: ...
    def __getitem__(self: Any, key: Any) -> None: ...
    def outgoing_connections(self: Any) -> None: ...
    def copy(self: Any) -> None: ...
