from typing import Any, TYPE_CHECKING

from __future__ import absolute_import, division, print_function, unicode_literals
import weakref
from copy import deepcopy
from logging import getLogger
from traceback import format_exc
from bunch import Bunch
from zato.common.api import SECRET_SHADOW
from zato.common.exception import Inactive


class BaseAPI:
    _conn_store: Any
    def __init__(self: Any, conn_store: Any) -> None: ...
    def get(self: Any, name: Any, skip_inactive: Any = ...) -> None: ...
    def __getitem__(self: Any, name: Any) -> None: ...
    def create(self: Any, name: Any, msg: Any, *args: Any, **extra: Any) -> None: ...
    def edit(self: Any, name: Any, msg: Any, **extra: Any) -> None: ...
    def delete(self: Any, name: Any) -> None: ...
    def change_password(self: Any, config: Any) -> None: ...

class BaseStore:
    items: Any
    lock: RLock
    def __init__(self: Any) -> None: ...
    def __getitem__(self: Any, name: Any) -> None: ...
    def get(self: Any, name: Any) -> None: ...
    def _create(self: Any, name: Any, config: Any, **extra: Any) -> None: ...
    def create(self: Any, name: Any, config: Any, **extra: Any) -> None: ...
    def _delete(self: Any, name: Any) -> None: ...
    def delete(self: Any, name: Any) -> None: ...
    def _edit(self: Any, name: Any, config: Any, **extra: Any) -> None: ...
    def edit(self: Any, name: Any, config: Any, **extra: Any) -> None: ...
    def change_password(self: Any, password_data: Any) -> None: ...
    def create_impl(self: Any) -> None: ...
    def delete_impl(self: Any) -> None: ...
