from typing import Any

import types
from collections import OrderedDict as odict
from exceptions import CandvConstantAlreadyBoundError
from exceptions import CandvContainerMisusedError
from exceptions import CandvInvalidConstantClass
from exceptions import CandvInvalidGroupMemberError
from exceptions import CandvMissingConstantError
from _utils import export

class SimpleConstant:
    def __init__(self: Any) -> None: ...
    def _post_init(self: Any, name: Any, container: Any = ...) -> None: ...
    def to_group(self: Any, group_class: Any, **group_members: Any) -> None: ...
    def merge_into_group(self: Any, group: Any) -> None: ...
    @property
    def full_name(self: Any) -> None: ...
    def to_primitive(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def __repr__(self: Any) -> None: ...
    def __hash__(self: Any) -> None: ...
    def __eq__(self: Any, other: Any) -> None: ...
    def __ne__(self: Any, other: Any) -> None: ...

class _LazyConstantsGroup:
    def __init__(self: Any, constant: Any, group_class: Any, **group_members: Any) -> None: ...
    @staticmethod
    def _validate_group_members(group_members: Any) -> None: ...
    def _evaluate(self: Any, parent: Any, name: Any) -> None: ...
    @staticmethod
    def _make_to_primitive(group: Any, constant: Any) -> None: ...

class _ConstantsContainerMeta(type):
    values: Any
    itervalues: Any
    def __new__(self: Any, class_name: Any, bases: Any, attributes: Any) -> None: ...
    @staticmethod
    def _ensure_attribute(attributes: Any, attribute_name: Any, default_value: Any) -> None: ...
    @staticmethod
    def _validate_constant_class(target_cls: Any) -> None: ...
    @staticmethod
    def _get_or_make_repr_value(attributes: Any) -> None: ...
    @classmethod
    def _make_members_from_attributes(cls: Any, target_cls: Any, attributes: Any) -> None: ...
    @staticmethod
    def _validate_constant_is_not_bound(target_cls: Any, attribute_name: Any, the_object: Any) -> None: ...
    def __repr__(self: Any) -> None: ...
    def __getitem__(self: Any, name: Any) -> None: ...
    def __contains__(self: Any, name: Any) -> None: ...
    def __len__(self: Any) -> None: ...
    def __iter__(self: Any) -> None: ...
    def get(self: Any, name: Any, default: Any = ...) -> None: ...
    def has_name(self: Any, name: Any) -> None: ...
    def names(self: Any) -> None: ...
    def iternames(self: Any) -> None: ...
    def constants(self: Any) -> None: ...
    def iterconstants(self: Any) -> None: ...
    def items(self: Any) -> None: ...
    def iteritems(self: Any) -> None: ...
    def to_primitive(self: Any, *args: Any, **kwargs: Any) -> None: ...

class Constants:
    constant_class: Any
    def __new__(cls: Any) -> None: ...

def with_constant_class(the_class: Any) -> None: ...
