from typing import Any, TYPE_CHECKING

import operator
from core import Constants
from core import SimpleConstant
from exceptions import CandvValueNotFoundError
from _utils import export


class VerboseMixin:
    verbose_name: kwargs.pop
    help_text: kwargs.pop
    def __init__(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def merge_into_group(self: Any, group: Any) -> None: ...
    def to_primitive(self: Any, *args: Any, **kwargs: Any) -> None: ...

class VerboseConstant(VerboseMixin, SimpleConstant):
    def __init__(self: Any, verbose_name: Any = ..., help_text: Any = ...) -> None: ...

class ValueConstant(SimpleConstant):
    value: Any
    def __init__(self: Any, value: Any) -> None: ...
    def merge_into_group(self: Any, group: Any) -> None: ...
    def to_primitive(self: Any, *args: Any, **kwargs: Any) -> None: ...

class VerboseValueConstant(VerboseMixin, ValueConstant):
    def __init__(self: Any, value: Any, verbose_name: Any = ..., help_text: Any = ...) -> None: ...

class Values(Constants):
    constant_class: Any
    @classmethod
    def get_by_value(cls: Any, value: Any) -> None: ...
    @classmethod
    def filter_by_value(cls: Any, value: Any) -> None: ...
    @classmethod
    def values(cls: Any) -> None: ...
    @classmethod
    def itervalues(cls: Any) -> None: ...
