from typing import Any, TYPE_CHECKING

from __future__ import print_function
import errno
import os
import random
import select
import signal
import sys
import time
import traceback
from zato.common.api import OS_Env
from zato.common.util.platform_ import is_posix
from zato.common.version import get_version
from zato.server.ext.zunicorn import SERVER_SOFTWARE, sock, systemd, util
from zato.server.ext.zunicorn.errors import HaltServer, AppImportError
from zato.server.ext.zunicorn.pidfile import Pidfile
from zato.server.ext.zunicorn.util import is_forking


class Arbiter:
    zato_deployment_key: str
    WORKER_BOOT_ERROR: Any
    APP_LOAD_ERROR: Any
    START_CTX: Any
    LISTENERS: Any
    WORKERS: Any
    PIPE: Any
    SIG_QUEUE: Any
    SIG_NAMES: Any
    num_workers: Any
    _num_workers: Any
    _last_logged_active_worker_count: Any
    log: Any
    pidfile: Any
    systemd: Any
    worker_age: Any
    reexec_pid: Any
    master_pid: Any
    master_name: Any
    START_CTX: Any
    def __init__(self: Any, app: Any) -> None: ...
    def _get_num_workers(self: Any) -> None: ...
    def _set_num_workers(self: Any, value: Any) -> None: ...
    def setup(self: Any, app: Any) -> None: ...
    def start(self: Any) -> None: ...
    def init_signals(self: Any) -> None: ...
    def signal(self: Any, sig: Any, frame: Any) -> None: ...
    def run(self: Any) -> None: ...
    def handle_chld(self: Any, sig: Any, frame: Any) -> None: ...
    def handle_hup(self: Any) -> None: ...
    def handle_term(self: Any) -> None: ...
    def handle_int(self: Any) -> None: ...
    def handle_quit(self: Any) -> None: ...
    def handle_ttin(self: Any) -> None: ...
    def handle_ttou(self: Any) -> None: ...
    def handle_usr1(self: Any) -> None: ...
    def handle_usr2(self: Any) -> None: ...
    def handle_winch(self: Any) -> None: ...
    def maybe_promote_master(self: Any) -> None: ...
    def wakeup(self: Any) -> None: ...
    def halt(self: Any, reason: Any = ..., exit_status: Any = ...) -> None: ...
    def sleep(self: Any) -> None: ...
    def stop(self: Any, graceful: Any = ...) -> None: ...
    def reexec(self: Any) -> None: ...
    def reload(self: Any) -> None: ...
    def murder_workers(self: Any) -> None: ...
    def reap_workers(self: Any) -> None: ...
    def manage_workers(self: Any) -> None: ...
    def spawn_worker(self: Any) -> None: ...
    def spawn_workers(self: Any) -> None: ...
    def kill_workers(self: Any, sig: Any) -> None: ...
    def kill_worker(self: Any, pid: Any, sig: Any) -> None: ...
