from typing import Any

import copy as _copy
import os as _os
import re as _re
import sys as _sys
import textwrap as _textwrap
from gettext import gettext as _
from sets import Set as set
import warnings

def _callable(obj: Any) -> None: ...

class _AttributeHolder:
    def __repr__(self: Any) -> None: ...
    def _get_kwargs(self: Any) -> None: ...
    def _get_args(self: Any) -> None: ...

def _ensure_value(namespace: Any, name: Any, value: Any) -> None: ...

class HelpFormatter:
    def __init__(self: Any, prog: Any, indent_increment: Any = ..., max_help_position: Any = ..., width: Any = ...) -> None: ...
    def _indent(self: Any) -> None: ...
    def _dedent(self: Any) -> None: ...
    def _add_item(self: Any, func: Any, args: Any) -> None: ...
    def start_section(self: Any, heading: Any) -> None: ...
    def end_section(self: Any) -> None: ...
    def add_text(self: Any, text: Any) -> None: ...
    def add_usage(self: Any, usage: Any, actions: Any, groups: Any, prefix: Any = ...) -> None: ...
    def add_argument(self: Any, action: Any) -> None: ...
    def add_arguments(self: Any, actions: Any) -> None: ...
    def format_help(self: Any) -> None: ...
    def _join_parts(self: Any, part_strings: Any) -> None: ...
    def _format_usage(self: Any, usage: Any, actions: Any, groups: Any, prefix: Any) -> None: ...
    def _format_actions_usage(self: Any, actions: Any, groups: Any) -> None: ...
    def _format_text(self: Any, text: Any) -> None: ...
    def _format_action(self: Any, action: Any) -> None: ...
    def _format_action_invocation(self: Any, action: Any) -> None: ...
    def _metavar_formatter(self: Any, action: Any, default_metavar: Any) -> None: ...
    def _format_args(self: Any, action: Any, default_metavar: Any) -> None: ...
    def _expand_help(self: Any, action: Any) -> None: ...
    def _iter_indented_subactions(self: Any, action: Any) -> None: ...
    def _split_lines(self: Any, text: Any, width: Any) -> None: ...
    def _fill_text(self: Any, text: Any, width: Any, indent: Any) -> None: ...
    def _get_help_string(self: Any, action: Any) -> None: ...

class RawDescriptionHelpFormatter(HelpFormatter):
    def _fill_text(self: Any, text: Any, width: Any, indent: Any) -> None: ...

class RawTextHelpFormatter(RawDescriptionHelpFormatter):
    def _split_lines(self: Any, text: Any, width: Any) -> None: ...

class ArgumentDefaultsHelpFormatter(HelpFormatter):
    def _get_help_string(self: Any, action: Any) -> None: ...

def _get_action_name(argument: Any) -> None: ...

class ArgumentError(Exception):
    def __init__(self: Any, argument: Any, message: Any) -> None: ...
    def __str__(self: Any) -> None: ...

class ArgumentTypeError(Exception):
    ...

class Action(_AttributeHolder):
    def __init__(self: Any, option_strings: Any, dest: Any, nargs: Any = ..., const: Any = ..., default: Any = ..., type: Any = ..., choices: Any = ..., required: Any = ..., help: Any = ..., metavar: Any = ...) -> None: ...
    def _get_kwargs(self: Any) -> None: ...
    def __call__(self: Any, parser: Any, namespace: Any, values: Any, option_string: Any = ...) -> None: ...

class _StoreAction(Action):
    def __init__(self: Any, option_strings: Any, dest: Any, nargs: Any = ..., const: Any = ..., default: Any = ..., type: Any = ..., choices: Any = ..., required: Any = ..., help: Any = ..., metavar: Any = ...) -> None: ...
    def __call__(self: Any, parser: Any, namespace: Any, values: Any, option_string: Any = ...) -> None: ...

class _StoreConstAction(Action):
    def __init__(self: Any, option_strings: Any, dest: Any, const: Any, default: Any = ..., required: Any = ..., help: Any = ..., metavar: Any = ...) -> None: ...
    def __call__(self: Any, parser: Any, namespace: Any, values: Any, option_string: Any = ...) -> None: ...

class _StoreTrueAction(_StoreConstAction):
    def __init__(self: Any, option_strings: Any, dest: Any, default: Any = ..., required: Any = ..., help: Any = ...) -> None: ...

class _StoreFalseAction(_StoreConstAction):
    def __init__(self: Any, option_strings: Any, dest: Any, default: Any = ..., required: Any = ..., help: Any = ...) -> None: ...

class _AppendAction(Action):
    def __init__(self: Any, option_strings: Any, dest: Any, nargs: Any = ..., const: Any = ..., default: Any = ..., type: Any = ..., choices: Any = ..., required: Any = ..., help: Any = ..., metavar: Any = ...) -> None: ...
    def __call__(self: Any, parser: Any, namespace: Any, values: Any, option_string: Any = ...) -> None: ...

class _AppendConstAction(Action):
    def __init__(self: Any, option_strings: Any, dest: Any, const: Any, default: Any = ..., required: Any = ..., help: Any = ..., metavar: Any = ...) -> None: ...
    def __call__(self: Any, parser: Any, namespace: Any, values: Any, option_string: Any = ...) -> None: ...

class _CountAction(Action):
    def __init__(self: Any, option_strings: Any, dest: Any, default: Any = ..., required: Any = ..., help: Any = ...) -> None: ...
    def __call__(self: Any, parser: Any, namespace: Any, values: Any, option_string: Any = ...) -> None: ...

class _HelpAction(Action):
    def __init__(self: Any, option_strings: Any, dest: Any = ..., default: Any = ..., help: Any = ...) -> None: ...
    def __call__(self: Any, parser: Any, namespace: Any, values: Any, option_string: Any = ...) -> None: ...

class _VersionAction(Action):
    def __init__(self: Any, option_strings: Any, version: Any = ..., dest: Any = ..., default: Any = ..., help: Any = ...) -> None: ...
    def __call__(self: Any, parser: Any, namespace: Any, values: Any, option_string: Any = ...) -> None: ...

class _SubParsersAction(Action):
    def __init__(self: Any, option_strings: Any, prog: Any, parser_class: Any, dest: Any = ..., help: Any = ..., metavar: Any = ...) -> None: ...
    def add_parser(self: Any, name: Any, **kwargs: Any) -> None: ...
    def _get_subactions(self: Any) -> None: ...
    def __call__(self: Any, parser: Any, namespace: Any, values: Any, option_string: Any = ...) -> None: ...

class FileType:
    def __init__(self: Any, mode: Any = ..., bufsize: Any = ...) -> None: ...
    def __call__(self: Any, string: Any) -> None: ...
    def __repr__(self: Any) -> None: ...

class Namespace(_AttributeHolder):
    __hash__: Any
    def __init__(self: Any, **kwargs: Any) -> None: ...
    def __eq__(self: Any, other: Any) -> None: ...
    def __ne__(self: Any, other: Any) -> None: ...
    def __contains__(self: Any, key: Any) -> None: ...

class _ActionsContainer:
    def __init__(self: Any, description: Any, prefix_chars: Any, argument_default: Any, conflict_handler: Any) -> None: ...
    def register(self: Any, registry_name: Any, value: Any, object: Any) -> None: ...
    def _registry_get(self: Any, registry_name: Any, value: Any, default: Any = ...) -> None: ...
    def set_defaults(self: Any, **kwargs: Any) -> None: ...
    def get_default(self: Any, dest: Any) -> None: ...
    def add_argument(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def add_argument_group(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def add_mutually_exclusive_group(self: Any, **kwargs: Any) -> None: ...
    def _add_action(self: Any, action: Any) -> None: ...
    def _remove_action(self: Any, action: Any) -> None: ...
    def _add_container_actions(self: Any, container: Any) -> None: ...
    def _get_positional_kwargs(self: Any, dest: Any, **kwargs: Any) -> None: ...
    def _get_optional_kwargs(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def _pop_action_class(self: Any, kwargs: Any, default: Any = ...) -> None: ...
    def _get_handler(self: Any) -> None: ...
    def _check_conflict(self: Any, action: Any) -> None: ...
    def _handle_conflict_error(self: Any, action: Any, conflicting_actions: Any) -> None: ...
    def _handle_conflict_resolve(self: Any, action: Any, conflicting_actions: Any) -> None: ...

class _ArgumentGroup(_ActionsContainer):
    def __init__(self: Any, container: Any, title: Any = ..., description: Any = ..., **kwargs: Any) -> None: ...
    def _add_action(self: Any, action: Any) -> None: ...
    def _remove_action(self: Any, action: Any) -> None: ...

class _MutuallyExclusiveGroup(_ArgumentGroup):
    def __init__(self: Any, container: Any, required: Any = ...) -> None: ...
    def _add_action(self: Any, action: Any) -> None: ...
    def _remove_action(self: Any, action: Any) -> None: ...

class ArgumentParser(_AttributeHolder, _ActionsContainer):
    def __init__(self: Any, prog: Any = ..., usage: Any = ..., description: Any = ..., epilog: Any = ..., version: Any = ..., parents: Any = ..., formatter_class: Any = ..., prefix_chars: Any = ..., fromfile_prefix_chars: Any = ..., argument_default: Any = ..., conflict_handler: Any = ..., add_help: Any = ...) -> None: ...
    def _get_kwargs(self: Any) -> None: ...
    def add_subparsers(self: Any, **kwargs: Any) -> None: ...
    def _add_action(self: Any, action: Any) -> None: ...
    def _get_optional_actions(self: Any) -> None: ...
    def _get_positional_actions(self: Any) -> None: ...
    def parse_args(self: Any, args: Any = ..., namespace: Any = ...) -> None: ...
    def parse_known_args(self: Any, args: Any = ..., namespace: Any = ...) -> None: ...
    def _parse_known_args(self: Any, arg_strings: Any, namespace: Any) -> None: ...
    def _read_args_from_files(self: Any, arg_strings: Any) -> None: ...
    def convert_arg_line_to_args(self: Any, arg_line: Any) -> None: ...
    def _match_argument(self: Any, action: Any, arg_strings_pattern: Any) -> None: ...
    def _match_arguments_partial(self: Any, actions: Any, arg_strings_pattern: Any) -> None: ...
    def _parse_optional(self: Any, arg_string: Any) -> None: ...
    def _get_option_tuples(self: Any, option_string: Any) -> None: ...
    def _get_nargs_pattern(self: Any, action: Any) -> None: ...
    def _get_values(self: Any, action: Any, arg_strings: Any) -> None: ...
    def _get_value(self: Any, action: Any, arg_string: Any) -> None: ...
    def _check_value(self: Any, action: Any, value: Any) -> None: ...
    def format_usage(self: Any) -> None: ...
    def format_help(self: Any) -> None: ...
    def format_version(self: Any) -> None: ...
    def _get_formatter(self: Any) -> None: ...
    def print_usage(self: Any, file: Any = ...) -> None: ...
    def print_help(self: Any, file: Any = ...) -> None: ...
    def print_version(self: Any, file: Any = ...) -> None: ...
    def _print_message(self: Any, message: Any, file: Any = ...) -> None: ...
    def exit(self: Any, status: Any = ..., message: Any = ...) -> None: ...
    def error(self: Any, message: Any) -> None: ...
