from typing import Any, TYPE_CHECKING

import base64
import binascii
import time
import logging
from logging.config import fileConfig
import os
import socket
import sys
import threading
import traceback
from zato.server.ext.zunicorn import util
from zato.server.ext.zunicorn.six import PY3, string_types
from logging.config import dictConfig


def loggers() -> None: ...

class SafeAtoms(dict):
    def __init__(self: Any, atoms: Any) -> None: ...
    def __getitem__(self: Any, k: Any) -> None: ...

def parse_syslog_address(addr: Any) -> None: ...

class Logger:
    LOG_LEVELS: Any
    loglevel: Any
    error_fmt: Any
    datefmt: Any
    access_fmt: Any
    syslog_fmt: Any
    atoms_wrapper_class: Any
    error_log: logging.getLogger
    access_log: logging.getLogger
    error_handlers: Any
    access_handlers: Any
    logfile: Any
    lock: threading.Lock
    cfg: Any
    def __init__(self: Any, cfg: Any) -> None: ...
    def setup(self: Any, cfg: Any) -> None: ...
    def critical(self: Any, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def error(self: Any, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def warning(self: Any, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def info(self: Any, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def debug(self: Any, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def exception(self: Any, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def log(self: Any, lvl: Any, msg: Any, *args: Any, **kwargs: Any) -> None: ...
    def atoms(self: Any, resp: Any, req: Any, environ: Any, request_time: Any) -> None: ...
    def access(self: Any, resp: Any, req: Any, environ: Any, request_time: Any) -> None: ...
    def now(self: Any) -> None: ...
    def reopen_files(self: Any) -> None: ...
    def close_on_exec(self: Any) -> None: ...
    def _get_gunicorn_handler(self: Any, log: Any) -> None: ...
    def _set_handler(self: Any, log: Any, output: Any, fmt: Any, stream: Any = ...) -> None: ...
    def _set_syslog_handler(self: Any, log: Any, cfg: Any, fmt: Any, name: Any) -> None: ...
    def _get_user(self: Any, environ: Any) -> None: ...
