from typing import Any

import errno
import os
import tempfile

class Pidfile(object):
    def __init__(self: Any, fname: Any) -> None: ...
    def create(self: Any, pid: Any) -> None: ...
    def rename(self: Any, path: Any) -> None: ...
    def unlink(self: Any) -> None: ...
    def validate(self: Any) -> None: ...
