from typing import Any, TYPE_CHECKING

import errno
import os
import tempfile


class Pidfile(object):
    fname: Any
    pid: Any
    def __init__(self: Any, fname: Any) -> None: ...
    def create(self: Any, pid: Any) -> None: ...
    def rename(self: Any, path: Any) -> None: ...
    def unlink(self: Any) -> None: ...
    def validate(self: Any) -> None: ...
