from typing import Any, TYPE_CHECKING

from abc import ABCMeta, abstractmethod
from collections import namedtuple, Mapping
import math
import select
import sys
from zato.server.ext.zunicorn._compat import wrap_error, InterruptedError
from zato.server.ext.zunicorn import six


def _fileobj_to_fd(fileobj: Any) -> None: ...

class _SelectorMapping(Mapping):
    _selector: Any
    def __init__(self: Any, selector: Any) -> None: ...
    def __len__(self: Any) -> None: ...
    def __getitem__(self: Any, fileobj: Any) -> None: ...
    def __iter__(self: Any) -> None: ...

class BaseSelector(six.with_metaclass):
    def register(self: Any, fileobj: Any, events: Any, data: Any = ...) -> None: ...
    def unregister(self: Any, fileobj: Any) -> None: ...
    def modify(self: Any, fileobj: Any, events: Any, data: Any = ...) -> None: ...
    def select(self: Any, timeout: Any = ...) -> None: ...
    def close(self: Any) -> None: ...
    def get_key(self: Any, fileobj: Any) -> None: ...
    def get_map(self: Any) -> None: ...
    def __enter__(self: Any) -> None: ...
    def __exit__(self: Any, *args: Any) -> None: ...

class _BaseSelectorImpl(BaseSelector):
    _fd_to_key: Any
    _map: _SelectorMapping
    def __init__(self: Any) -> None: ...
    def _fileobj_lookup(self: Any, fileobj: Any) -> None: ...
    def register(self: Any, fileobj: Any, events: Any, data: Any = ...) -> None: ...
    def unregister(self: Any, fileobj: Any) -> None: ...
    def modify(self: Any, fileobj: Any, events: Any, data: Any = ...) -> None: ...
    def close(self: Any) -> None: ...
    def get_map(self: Any) -> None: ...
    def _key_from_fd(self: Any, fd: Any) -> None: ...

class SelectSelector(_BaseSelectorImpl):
    _readers: set
    _writers: set
    def __init__(self: Any) -> None: ...
    def register(self: Any, fileobj: Any, events: Any, data: Any = ...) -> None: ...
    def unregister(self: Any, fileobj: Any) -> None: ...
    def select(self: Any, timeout: Any = ...) -> None: ...
