from typing import Any

from __future__ import absolute_import
import functools
import operator
import sys
import types
from zato.common.py23_.past.builtins import basestring, execfile, long, unicode
import io
import StringIO

def _add_doc(func: Any, doc: Any) -> None: ...

def _import_module(name: Any) -> None: ...

class _LazyDescr:
    name: Any
    def __init__(self: Any, name: Any) -> None: ...
    def __get__(self: Any, obj: Any, tp: Any) -> None: ...

class MovedModule(_LazyDescr):
    mod: Any
    def __init__(self: Any, name: Any, old: Any, new: Any = ...) -> None: ...
    def _resolve(self: Any) -> None: ...
    def __getattr__(self: Any, attr: Any) -> None: ...

class _LazyModule(types.ModuleType):
    _moved_attributes: Any
    __doc__: Any
    def __init__(self: Any, name: Any) -> None: ...
    def __dir__(self: Any) -> None: ...

class MovedAttribute(_LazyDescr):
    mod: Any
    attr: Any
    def __init__(self: Any, name: Any, old_mod: Any, new_mod: Any, old_attr: Any = ..., new_attr: Any = ...) -> None: ...
    def _resolve(self: Any) -> None: ...

class _SixMetaPathImporter:
    get_source: Any
    name: Any
    known_modules: Any
    def __init__(self: Any, six_module_name: Any) -> None: ...
    def _add_module(self: Any, mod: Any, *fullnames: Any) -> None: ...
    def _get_module(self: Any, fullname: Any) -> None: ...
    def find_module(self: Any, fullname: Any, path: Any = ...) -> None: ...
    def __get_module(self: Any, fullname: Any) -> None: ...
    def load_module(self: Any, fullname: Any) -> None: ...
    def is_package(self: Any, fullname: Any) -> None: ...
    def get_code(self: Any, fullname: Any) -> None: ...

class _MovedItems(_LazyModule):
    __path__: Any

class Module_six_moves_urllib_parse(_LazyModule):
    ...

class Module_six_moves_urllib_error(_LazyModule):
    ...

class Module_six_moves_urllib_request(_LazyModule):
    ...

class Module_six_moves_urllib_response(_LazyModule):
    ...

class Module_six_moves_urllib_robotparser(_LazyModule):
    ...

class Module_six_moves_urllib(types.ModuleType):
    __path__: Any
    parse: Any
    error: Any
    request: Any
    response: Any
    robotparser: Any
    def __dir__(self: Any) -> None: ...

def add_move(move: Any) -> None: ...

def remove_move(name: Any) -> None: ...

def with_metaclass(meta: Any, *bases: Any) -> None: ...

def add_metaclass(metaclass: Any) -> None: ...
