from typing import Any

import errno
import os
import socket
import stat
import sys
import time
from zato.common.util.platform_ import is_posix
from zato.server.ext.zunicorn import util
from zato.server.ext.zunicorn.six import string_types

class BaseSocket:
    def __init__(self: Any, address: Any, conf: Any, log: Any, fd: Any = ...) -> None: ...
    def __str__(self: Any) -> None: ...
    def __getattr__(self: Any, name: Any) -> None: ...
    def set_options(self: Any, sock: Any, bound: Any = ...) -> None: ...
    def bind(self: Any, sock: Any) -> None: ...
    def close(self: Any) -> None: ...

class TCPSocket(BaseSocket):
    FAMILY: Any
    def __str__(self: Any) -> None: ...
    def set_options(self: Any, sock: Any, bound: Any = ...) -> None: ...

class TCP6Socket(TCPSocket):
    FAMILY: Any
    def __str__(self: Any) -> None: ...

class UnixSocket(BaseSocket):
    def __init__(self: Any, addr: Any, conf: Any, log: Any, fd: Any = ...) -> None: ...
    def __str__(self: Any) -> None: ...
    def bind(self: Any, sock: Any) -> None: ...

def _sock_type(addr: Any) -> None: ...

def create_sockets(conf: Any, log: Any, fds: Any = ...) -> None: ...

def close_sockets(listeners: Any, unlink: Any = ...) -> None: ...
