from typing import Any, TYPE_CHECKING

from __future__ import print_function
import email.utils
import io
import os
import pkg_resources
import random
import socket
import sys
import textwrap
import time
import traceback
import inspect
import errno
import warnings
import logging
import re
from platform import system as platform_system
from time import gmtime
from zato.server.ext.zunicorn import _compat
from zato.server.ext.zunicorn.errors import AppImportError
from zato.server.ext.zunicorn.six import text_type
from zato.server.ext.zunicorn.workers import SUPPORTED_WORKERS
from setproctitle import setproctitle
from importlib import import_module
import pwd
import fcntl
from os import closerange

is_forking = is_linux

def load_class(uri: Any, default: Any = ..., section: Any = ...) -> None: ...

def get_username(uid: Any) -> None: ...

def set_owner_process(uid: Any, gid: Any, initgroups: Any = ...) -> None: ...

def chown(path: Any, uid: Any, gid: Any) -> None: ...

def unlink(filename: Any) -> None: ...

def is_ipv6(addr: Any) -> None: ...

def parse_address(netloc: Any, default_port: Any = ...) -> None: ...

def close_on_exec(fd: Any) -> None: ...

def set_non_blocking(fd: Any) -> None: ...

def close(sock: Any) -> None: ...

def write_chunk(sock: Any, data: Any) -> None: ...

def write(sock: Any, data: Any, chunked: Any = ...) -> None: ...

def write_nonblock(sock: Any, data: Any, chunked: Any = ...) -> None: ...

def write_error(sock: Any, status_int: Any, reason: Any, mesg: Any) -> None: ...

def import_app(module: Any) -> None: ...

def getcwd() -> None: ...

def http_date(_gmtime: Any = ..., _days: Any = ..., _months: Any = ...) -> None: ...

def is_hoppish(header: Any) -> None: ...

def daemonize(enable_stdio_inheritance: Any = ...) -> None: ...

def seed() -> None: ...

def check_is_writeable(path: Any) -> None: ...

def to_bytestring(value: Any, encoding: Any = ...) -> None: ...

def has_fileno(obj: Any) -> None: ...

def warn(msg: Any) -> None: ...

def make_fail_app(msg: Any) -> None: ...

def split_request_uri(uri: Any) -> None: ...
