from typing import Any, TYPE_CHECKING

from __future__ import absolute_import, division, print_function
import sys
import logging
import contextlib
import types
import copy
import os
from zato.common.ext.future.utils import PY2, PY3
import urllib
from zato.common.ext.future.backports.urllib import request
from zato.common.ext.future.backports.urllib import response
from zato.common.ext.future.backports.urllib import parse
from zato.common.ext.future.backports.urllib import error
from zato.common.ext.future.backports.urllib import robotparser
import email
import pickle
import importlib
from importlib.util import find_spec as find_module
from importlib import import_module as load_module
import test
from zato.common.ext.future.moves.test import support
import dbm
from zato.common.ext.future.moves.dbm import dumb
from zato.common.ext.future.moves.dbm import gnu
from zato.common.ext.future.moves.dbm import ndbm


class RenameImport(object):
    RENAMER: Any
    old_to_new: Any
    new_to_old: dict
    def __init__(self: Any, old_to_new: Any) -> None: ...
    def find_module(self: Any, fullname: Any, path: Any = ...) -> None: ...
    def load_module(self: Any, name: Any) -> None: ...
    def _find_and_load_module(self: Any, name: Any, path: Any = ...) -> None: ...

class hooks(object):
    def __enter__(self: Any) -> None: ...
    def __exit__(self: Any, *args: Any) -> None: ...

def is_py2_stdlib_module(m: Any) -> None: ...

def scrub_py2_sys_modules() -> None: ...

def scrub_future_sys_modules() -> None: ...

class suspend_hooks(object):
    def __enter__(self: Any) -> None: ...
    def __exit__(self: Any, *args: Any) -> None: ...

def restore_sys_modules(scrubbed: Any) -> None: ...

def install_aliases() -> None: ...

def install_hooks() -> None: ...

def enable_hooks() -> None: ...

def remove_hooks(scrub_sys_modules: Any = ...) -> None: ...

def disable_hooks() -> None: ...

def detect_hooks() -> None: ...

def cache_py2_modules() -> None: ...

def import_(module_name: Any, backport: Any = ...) -> None: ...

def from_import(module_name: Any, *symbol_names: Any, **kwargs: Any) -> None: ...

class exclude_local_folder_imports(object):
    module_names: Any
    def __init__(self: Any, *args: Any) -> None: ...
    def __enter__(self: Any) -> None: ...
    def __exit__(self: Any, *args: Any) -> None: ...

def import_top_level_modules() -> None: ...
