
.PHONY: static-check

Zato_Python_Dir=$(CURDIR)/../bin
Zato_Package_Name=zato-lib

pylint:
	#
	# There is nothing to check in zato-lib
	#

flake8:
	#
	# There is nothing to check in zato-lib
	#

static-check:
	#
	# There is nothing to check in zato-lib
	#
