
.PHONY: static-check

PY_DIR=$(CURDIR)/../bin

pylint:
	#
	# There is nothing to check in zato-lib
	#
	#echo Running pylint in zato-lib
	#$(PY_DIR)/pylint --verbose \
	#	--rcfile $(CURDIR)/../pylint.ini \
	#			 $(CURDIR)/../zato-lib/src/zato/lib

static-check:
	#
	# There is nothing to check in zato-lib
	#
	#echo "Running static checks in zato-lib"
	#$(PY_DIR)/flake8 --config=$(CURDIR)/../tox.ini $(CURDIR)/
