
.PHONY: static-check

pylint:
	#
	# There is nothing to check in zato-lib
	#
	#echo Running pylint in zato-lib
	#$(CURDIR)/../bin/pylint --verbose \
	#	--rcfile $(CURDIR)/../pylint.ini \
	#			 $(CURDIR)/../zato-lib/src/zato/lib

static-check:
	#
	# There is nothing to check in zato-lib
	#
	#echo "Running static checks in zato-lib"
	#$(CURDIR)/../bin/flake8 --config=$(CURDIR)/../tox.ini $(CURDIR)/
