from typing import Any, TYPE_CHECKING

import os
from queue import Queue, Empty
from threading import RLock
from traceback import format_exc
from logging import getLogger
from kombu import Connection
from kombu.exceptions import OperationalError
from prometheus_client import Histogram
from werkzeug.wrappers import Request
from zato.common.api import PubSub
from zato.common.pubsub.models import APIResponse, BadRequestResponse, UnauthorizedResponse, _base_response
from zato.common.pubsub.server.rest_base import BaseRESTServer
from zato.common.pubsub.util import set_time_since
from zato.common.util.api import as_bool, utcnow
from zato.common.pubsub.models import Subscription
from zato.common.typing_ import any_, anydict

_default_priority = PubSub.Message.Priority_Default
_default_expiration = PubSub.Message.Default_Expiration
_max_len_limit = PubSub.Message.Default_Max_Len
_default_max_messages = PubSub.Message.Default_Max_Messages

class PubSubRESTServerPull(BaseRESTServer):
    server_type: Any
    _connection_pool: Queue
    _pool_lock: RLock
    _pool_initialized: Any
    def __init__(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def _init_connection_pool(self: Any) -> None: ...
    def _create_amqp_connection(self: Any) -> Connection: ...
    def _get_connection(self: Any) -> Connection: ...
    def _return_connection(self: Any, connection: Connection) -> None: ...
    def _validate_get_params(self: Any, data: dict) -> tuple[int, int, bool]: ...
    def _find_user_sub_key(self: Any, cid: str, username: str) -> str | None: ...
    def _find_user_subscription(self: Any, username: str) -> Subscription | None: ...
    def _build_rabbitmq_request(self: Any, sub_key: str, max_messages: int, max_len: int) -> tuple[str, dict]: ...
    def _fetch_from_rabbitmq(self: Any, cid: str, queue_name: str, max_messages: int) -> list: ...
    def _transform_messages(self: Any, messages_data: list) -> list: ...
    def _build_success_response(self: Any, cid: str, messages: list, max_messages: int, wrap_in_list: bool) -> _base_response: ...
    def _build_error_response(self: Any, cid: str, details: str) -> _base_response: ...
    def _on_messages_get(self: Any, cid: str, environ: anydict, start_response: any_) -> _base_response: ...
    def on_messages_get(self: Any, cid: str, environ: anydict, start_response: any_) -> _base_response: ...
