from typing import Any, TYPE_CHECKING

from zato.common.rules.models import Container, MatchResult, Rule
from zato.common.rules.cache import CachedRule
from logging import getLogger
from pathlib import Path
from threading import RLock
from time import time
from rule_engine import Rule as RuleImpl
from zato.common.rules.parser import parse_file
from zato.common.typing_ import any_, dict_, float_, int_, strdict, strlist

Container = Container
MatchResult = MatchResult
Rule = Rule

class RulesManager:
    _all_rules: Any
    _containers: Any
    _lock: RLock
    cached_rules: Any
    performance_stats: Any
    def __init__(self: Any) -> None: ...
    def __getitem__(self: Any, name: str) -> Rule | Container: ...
    def __getattr__(self: Any, name: str) -> Rule | Container: ...
    def match(self: Any, data: strdict, rules: any_) -> MatchResult | None: ...
    def _update_stats(self: Any, condition_cache: dict_[str, any_], cached_rule: CachedRule | None = ..., start_time: float_ = ...) -> None: ...
    def get_performance_stats(self: Any) -> dict_[str, int_ | float_]: ...
    def reset_performance_stats(self: Any) -> None: ...
    def load_parsed_rules(self: Any, parsed: strdict, container_name: str) -> strlist: ...
    def load_rules_from_file(self: Any, file_path: str | Path) -> strlist: ...
    def load_rules_from_directory(self: Any, root_dir: str | Path) -> strlist: ...
