from typing import Any

from copy import deepcopy
from logging import getLogger
from rule_engine.ast import ExpressionBase, LogicExpression
from zato.common.rules.models import MatchResult, resolve_then_values
from zato.common.typing_ import any_, anydict, bool_, dict_
from zato.common.rules.models import Rule

class CachedRule:
    def __init__(self: Any, rule: Rule) -> None: ...
    def match(self: Any, data: anydict, condition_cache: dict_[str, any_] = ...) -> MatchResult: ...
    def _get_cache_key(self: Any, expression: ExpressionBase) -> str: ...
    def _evaluate_with_cache(self: Any, expression: ExpressionBase, data: anydict, cache: dict_[str, any_]) -> bool_: ...

def identify_common_expressions(rules: dict_[str, Rule]) -> list[str]: ...

def _extract_expressions(expression: ExpressionBase) -> list[ExpressionBase]: ...

def precompute_common_expressions(common_expressions: list[str], data: anydict, cache: dict_[str, any_]) -> None: ...

def _extract_field_names(expression: ExpressionBase) -> set[str]: ...

def build_field_index(rules: dict_[str, Rule]) -> dict_[str, set[str]]: ...
