from typing import Any

from logging import getLogger
from pathlib import Path
from zato.common.rules.cache import build_field_index
from zato.common.rules.evaluation import RuleEvaluator
from zato.common.rules.loader import RuleLoader
from zato.common.rules.models import Container, MatchResult, Rule
from zato.common.rules.cache import CachedRule
from zato.common.typing_ import any_, dict_, strdict, strlist

class RulesManager:
    def __init__(self: Any) -> None: ...
    def __getitem__(self: Any, name: str) -> Rule | Container: ...
    def __getattr__(self: Any, name: str) -> Rule | Container: ...
    def _count_nodes(self: Any, expression: Any) -> int: ...
    def _calculate_rule_complexity(self: Any, rule: Rule) -> int: ...
    def _sort_rules_by_complexity(self: Any) -> None: ...
    def _build_field_index(self: Any) -> None: ...
    def _filter_rules_by_fields(self: Any, rules: list[str], data: strdict) -> list[str]: ...
    def match(self: Any, data: strdict, rules: any_) -> MatchResult | None: ...
    def get_performance_stats(self: Any) -> dict_[str, any_]: ...
    def reset_performance_stats(self: Any) -> None: ...
    def load_parsed_rules(self: Any, parsed: strdict, container_name: str) -> strlist: ...
    def load_rules_from_file(self: Any, file_path: str | Path) -> strlist: ...
    def load_rules_from_directory(self: Any, root_dir: str | Path) -> strlist: ...
