from typing import Any, TYPE_CHECKING

from logging import getLogger
from time import time
from zato.common.rules.api import RulesManager as BaseRulesManager, MatchResult
from zato.common.rules.rule_cache import CachedRule
from pathlib import Path
from zato.common.typing_ import any_, dict_, strdict, strlist


class RulesManager(BaseRulesManager):
    cached_rules: Any
    performance_stats: Any
    def __init__(self: Any) -> None: ...
    def load_parsed_rules(self: Any, parsed: strdict, container_name: str) -> strlist: ...
    def load_rules_from_file(self: Any, file_path: str | Path) -> strlist: ...
    def match(self: Any, data: strdict, rules: any_) -> MatchResult | None: ...
    def _update_stats(self: Any, condition_cache: dict_[str, any_], cached_rule: CachedRule | None = ..., start_time: float = ...) -> None: ...
    def get_performance_stats(self: Any) -> dict_[str, int | float]: ...
    def reset_performance_stats(self: Any) -> None: ...
