from typing import Any, TYPE_CHECKING

from dataclasses import dataclass
from typing import Dict, List, Optional
import re
from zato.common.api import PubSub
from zato.common.pubsub.util import validate_pattern, validate_topic_name
from typing import Pattern
from zato.common.typing_ import anydict, strlist


class ModuleCtx:
    Max_Length: Any

class PatternInfo:
    pattern: str
    compiled_regex: Pattern[str]
    is_pub: bool
    is_sub: bool
    has_wildcards: bool

class ClientPermissions:
    client_id: str
    pub_patterns: List[PatternInfo]
    sub_patterns: List[PatternInfo]

class EvaluationResult:
    is_ok: bool
    client_id: str
    topic: str
    operation: str
    matched_pattern: Optional[str]
    reason: Optional[str]

class CacheEntry:
    compiled_regex: Pattern[str]
    pattern: str

class ParsedPermissions:
    pub_patterns: List[str]
    sub_patterns: List[str]

class PatternMatcher:
    _lock: RLock
    def __init__(self: Any) -> None: ...
    def _compile_pattern(self: Any, pattern: str) -> Pattern[str]: ...
    def _parse_permissions(self: Any, permissions: List[anydict]) -> ParsedPermissions: ...
    def _clear_evaluation_cache(self: Any) -> None: ...
    def add_client(self: Any, client_id: str, permissions: List[anydict]) -> None: ...
    def remove_client(self: Any, client_id: str) -> None: ...
    def change_client_id(self: Any, old_client_id: str, new_client_id: str) -> None: ...
    def set_permissions(self: Any, client_id: str, permissions: List[anydict]) -> None: ...
    def _pattern_sort_key(self: Any, pattern_info: PatternInfo) -> tuple: ...
    def _pattern_info_sort_key(self: Any, pattern_info: PatternInfo) -> tuple: ...
    def _has_more_specific_pattern(self: Any, client_permissions: ClientPermissions, topic: str, operation: str) -> bool: ...
    def _create_success_result(self: Any, client_id: str, topic: str, operation: str, matched_pattern: str) -> EvaluationResult: ...
    def _check_cached_match(self: Any, cache_key: str, client_id: str, topic: str, operation: str, pattern: str) -> EvaluationResult | None: ...
    def _evaluate_and_cache_match(self: Any, cache_key: str, matches: bool, client_id: str, topic: str, operation: str, pattern: str) -> EvaluationResult | None: ...
    def _try_pattern_match(self: Any, pattern_info: PatternInfo, topic: str, client_id: str, operation: str) -> EvaluationResult | None: ...
    def _create_pattern_info(self: Any, pattern: str, is_pub: bool, is_sub: bool) -> PatternInfo: ...
    def evaluate(self: Any, client_id: str, topic: str, operation: str) -> EvaluationResult: ...
    def get_client_count(self: Any) -> int: ...
    def get_cache_size(self: Any) -> int: ...
    def clear_cache(self: Any) -> None: ...
    def rename_topic(self: Any, client_id: str, old_topic_name: str, new_topic_name: str) -> None: ...
    def delete_topic(self: Any, client_id: str, topic_name: str) -> None: ...
