from typing import Any

import json
import os
import urllib.request
from logging import getLogger
from traceback import format_exc
import orjson
from zato.common.typing_ import dict_
from zato.common.util.api import as_bool
from zato.common.typing_ import dict_, list_

def _get_connections_data(vhost: str) -> dict_: ...

def _get_consumers_data(vhost: str) -> dict_: ...

def _parse_client_properties(client_props_list: list_) -> dict_: ...

def _parse_connections_output(stdout: str) -> list_: ...

def _parse_consumers_output(stdout: str) -> dict_: ...

def _parse_consumers_details(stdout: str, vhost: str) -> list_: ...

def _analyze_connections(connections: list_) -> dict_: ...

def get_queue_consumers(cid: str, vhost: str, queue_name: str) -> list_: ...

def list_connections(cid: str, vhost: str, queue_name: str = ...) -> dict_: ...

def close_queue_consumers(cid: str, vhost: str, queue_name: str) -> None: ...
