"""
Semantic component name mappings for HL7 v2.9 datatypes.
Maps position -> human-readable name per HL7 v2.9 standard.
"""
from __future__ import annotations


SEMANTIC_NAMES: dict[str, dict[int, str]] = {
    "AD": {
        1: "street_address",
        2: "other_designation",
        3: "city",
        4: "state_or_province",
        5: "zip_or_postal_code",
        6: "country",
        7: "address_type",
        8: "other_geographic_designation",
    },
    "AUI": {
        1: "authorization_number",
        2: "date",
        3: "source",
    },
    "CCD": {
        1: "invocation_event",
        2: "datetime",
    },
    "CCP": {
        1: "channel_calibration_sensitivity_correction_factor",
        2: "channel_calibration_baseline",
        3: "channel_calibration_time_skew",
    },
    "CD": {
        1: "channel_identifier",
        2: "waveform_source",
        3: "channel_sensitivity_and_units",
        4: "channel_calibration_parameters",
        5: "channel_sampling_frequency",
        6: "minimum_and_maximum_data_values",
    },
    "CF": {
        1: "identifier",
        2: "formatted_text",
        3: "name_of_coding_system",
        4: "alternate_identifier",
        5: "alternate_formatted_text",
        6: "name_of_alternate_coding_system",
        7: "coding_system_version_id",
        8: "alternate_coding_system_version_id",
        9: "original_text",
        10: "second_alternate_identifier",
        11: "second_alternate_formatted_text",
        12: "name_of_second_alternate_coding_system",
        13: "second_alternate_coding_system_version_id",
        14: "coding_system_oid",
        15: "value_set_oid",
        16: "value_set_version_id",
        17: "alternate_coding_system_oid",
        18: "alternate_value_set_oid",
        19: "alternate_value_set_version_id",
        20: "second_alternate_coding_system_oid",
        21: "second_alternate_value_set_oid",
        22: "second_alternate_value_set_version_id",
    },
    "CNE": {
        1: "identifier",
        2: "text",
        3: "name_of_coding_system",
        4: "alternate_identifier",
        5: "alternate_text",
        6: "name_of_alternate_coding_system",
        7: "coding_system_version_id",
        8: "alternate_coding_system_version_id",
        9: "original_text",
        10: "second_alternate_identifier",
        11: "second_alternate_text",
        12: "name_of_second_alternate_coding_system",
        13: "second_alternate_coding_system_version_id",
        14: "coding_system_oid",
        15: "value_set_oid",
        16: "value_set_version_id",
        17: "alternate_coding_system_oid",
        18: "alternate_value_set_oid",
        19: "alternate_value_set_version_id",
        20: "second_alternate_coding_system_oid",
        21: "second_alternate_value_set_oid",
        22: "second_alternate_value_set_version_id",
    },
    "CNN": {
        1: "id_number",
        2: "family_name",
        3: "given_name",
        4: "second_and_further_given_names_or_initials_thereof",
        5: "suffix",
        6: "prefix",
        7: "degree",
        8: "source_table",
        9: "assigning_authority_namespace_id",
        10: "assigning_authority_universal_id",
        11: "assigning_authority_universal_id_type",
    },
    "CP": {
        1: "price",
        2: "price_type",
        3: "from_value",
        4: "to_value",
        5: "range_units",
        6: "range_type",
    },
    "CQ": {
        1: "quantity",
        2: "units",
    },
    "CSU": {
        1: "channel_sensitivity",
        2: "unit_of_measure_identifier",
        3: "unit_of_measure_description",
        4: "unit_of_measure_coding_system",
        5: "alternate_unit_of_measure_identifier",
        6: "alternate_unit_of_measure_description",
        7: "alternate_unit_of_measure_coding_system",
        8: "unit_of_measure_coding_system_version_id",
        9: "alternate_unit_of_measure_coding_system_version_id",
        10: "original_text",
        11: "second_alternate_unit_of_measure_identifier",
        12: "second_alternate_unit_of_measure_text",
        13: "name_of_second_alternate_unit_of_measure_coding_system",
        14: "second_alternate_unit_of_measure_coding_system_version_id",
        15: "unit_of_measure_coding_system_oid",
        16: "unit_of_measure_value_set_oid",
        17: "unit_of_measure_value_set_version_id",
        18: "alternate_unit_of_measure_coding_system_oid",
        19: "alternate_unit_of_measure_value_set_oid",
        20: "alternate_unit_of_measure_value_set_version_id",
        21: "second_alternate_unit_of_measure_coding_system_oid",
        22: "second_alternate_unit_of_measure_value_set_oid",
        23: "second_alternate_unit_of_measure_value_set_version_id",
    },
    "CWE": {
        1: "identifier",
        2: "text",
        3: "name_of_coding_system",
        4: "alternate_identifier",
        5: "alternate_text",
        6: "name_of_alternate_coding_system",
        7: "coding_system_version_id",
        8: "alternate_coding_system_version_id",
        9: "original_text",
        10: "second_alternate_identifier",
        11: "second_alternate_text",
        12: "name_of_second_alternate_coding_system",
        13: "second_alternate_coding_system_version_id",
        14: "coding_system_oid",
        15: "value_set_oid",
        16: "value_set_version_id",
        17: "alternate_coding_system_oid",
        18: "alternate_value_set_oid",
        19: "alternate_value_set_version_id",
        20: "second_alternate_coding_system_oid",
        21: "second_alternate_value_set_oid",
        22: "second_alternate_value_set_version_id",
    },
    "CX": {
        1: "id_number",
        2: "identifier_check_digit",
        3: "check_digit_scheme",
        4: "assigning_authority",
        5: "identifier_type_code",
        6: "assigning_facility",
        7: "effective_date",
        8: "expiration_date",
        9: "assigning_jurisdiction",
        10: "assigning_agency_or_department",
        11: "security_check",
        12: "security_check_scheme",
    },
    "DDI": {
        1: "delay_days",
        2: "monetary_amount",
        3: "number_of_days",
    },
    "DIN": {
        1: "date",
        2: "institution_name",
    },
    "DLD": {
        1: "discharge_to_location",
        2: "effective_date",
    },
    "DLN": {
        1: "drivers_license_number",
        2: "issuing_state_province_country",
        3: "expiration_date",
    },
    "DLT": {
        1: "normal_range",
        2: "numeric_threshold",
        3: "change_computation",
        4: "days_retained",
    },
    "DR": {
        1: "range_start_date_time",
        2: "range_end_date_time",
    },
    "DTN": {
        1: "day_type",
        2: "number_of_days",
    },
    "ED": {
        1: "source_application",
        2: "type_of_data",
        3: "data_subtype",
        4: "encoding",
        5: "data",
    },
    "EI": {
        1: "entity_identifier",
        2: "namespace_id",
        3: "universal_id",
        4: "universal_id_type",
    },
    "EIP": {
        1: "placer_assigned_identifier",
        2: "filler_assigned_identifier",
    },
    "ERL": {
        1: "segment_id",
        2: "segment_sequence",
        3: "field_position",
        4: "field_repetition",
        5: "component_number",
        6: "sub_component_number",
    },
    "FC": {
        1: "financial_class_code",
        2: "effective_date",
    },
    "FN": {
        1: "surname",
        2: "own_surname_prefix",
        3: "own_surname",
        4: "surname_prefix_from_partner",
        5: "surname_from_partner",
    },
    "HD": {
        1: "namespace_id",
        2: "universal_id",
        3: "universal_id_type",
    },
    "ICD": {
        1: "certification_patient_type",
        2: "certification_required",
        3: "date_time_certification_required",
    },
    "JCC": {
        1: "job_code",
        2: "job_class",
        3: "job_description_text",
    },
    "MA": {
        1: "sample_y_from_channel_1",
        2: "sample_y_from_channel_2",
        3: "sample_y_from_channel_3",
        4: "sample_y_from_channel_4",
    },
    "MO": {
        1: "quantity",
        2: "denomination",
    },
    "MOC": {
        1: "monetary_amount",
        2: "charge_code",
    },
    "MOP": {
        1: "money_or_percentage_indicator",
        2: "money_or_percentage_quantity",
        3: "monetary_denomination",
    },
    "MSG": {
        1: "message_code",
        2: "trigger_event",
        3: "message_structure",
    },
    "NA": {
        1: "value1",
        2: "value2",
        3: "value3",
        4: "value4",
    },
    "NDL": {
        1: "name",
        2: "start_date_time",
        3: "end_date_time",
        4: "point_of_care",
        5: "room",
        6: "bed",
        7: "facility",
        8: "location_status",
        9: "patient_location_type",
        10: "building",
        11: "floor",
    },
    "NR": {
        1: "low_value",
        2: "high_value",
    },
    "OCD": {
        1: "occurrence_code",
        2: "occurrence_date",
    },
    "OG": {
        1: "original_sub_identifier",
        2: "group",
        3: "sequence",
        4: "identifier",
    },
    "OSP": {
        1: "occurrence_span_code",
        2: "occurrence_span_start_date",
        3: "occurrence_span_stop_date",
    },
    "PIP": {
        1: "privilege",
        2: "privilege_class",
        3: "expiration_date",
        4: "activation_date",
        5: "facility",
    },
    "PL": {
        1: "point_of_care",
        2: "room",
        3: "bed",
        4: "facility",
        5: "location_status",
        6: "person_location_type",
        7: "building",
        8: "floor",
        9: "location_description",
        10: "comprehensive_location_identifier",
        11: "assigning_authority_for_location",
    },
    "PLN": {
        1: "id_number",
        2: "type_of_id_number",
        3: "state_other_qualifying_information",
        4: "expiration_date",
    },
    "PPN": {
        1: "person_identifier",
        2: "family_name",
        3: "given_name",
        4: "second_and_further_given_names_or_initials_thereof",
        5: "suffix",
        6: "prefix",
        7: "degree",
        8: "source_table",
        9: "assigning_authority",
        10: "name_type_code",
        11: "identifier_check_digit",
        12: "check_digit_scheme",
        13: "identifier_type_code",
        14: "assigning_facility",
        15: "date_time_action_performed",
        16: "name_representation_code",
        17: "name_context",
        18: "name_validity_range",
        19: "name_assembly_order",
        20: "effective_date",
        21: "expiration_date",
        22: "professional_suffix",
        23: "assigning_jurisdiction",
    },
    "PRL": {
        1: "parent_observation_identifier",
        2: "parent_observation_subidentifier",
        3: "parent_observation_value_descriptor",
    },
    "PT": {
        1: "processing_id",
        2: "processing_mode",
    },
    "PTA": {
        1: "policy_type",
        2: "amount_class",
        3: "money_or_percentage_quantity",
    },
    "QIP": {
        1: "segment_field_name",
        2: "values",
    },
    "QSC": {
        1: "segment_field_name",
        2: "relational_operator",
        3: "value",
        4: "relational_conjunction",
    },
    "RCD": {
        1: "segment_field_name",
        2: "hl7_data_type",
        3: "maximum_column_width",
    },
    "RFR": {
        1: "numeric_range",
        2: "sex",
        3: "age_range",
        4: "gestational_age_range",
        5: "species",
        6: "race_subspecies",
        7: "conditions",
    },
    "RI": {
        1: "repeat_pattern",
        2: "explicit_time_interval",
    },
    "RMC": {
        1: "risk_management_classification",
        2: "risk_management_code",
        3: "risk_management_code_text",
    },
    "RP": {
        1: "pointer",
        2: "application_id",
        3: "type_of_data",
        4: "subtype",
    },
    "RPT": {
        1: "repeat_pattern_code",
        2: "calendar_alignment",
        3: "phase_range_begin_value",
        4: "phase_range_end_value",
        5: "period_quantity",
        6: "period_units",
        7: "institution_specified_time",
        8: "event",
        9: "event_offset_quantity",
        10: "event_offset_units",
        11: "general_timing_specification",
    },
    "SAD": {
        1: "street_or_mailing_address",
        2: "street_name",
        3: "dwelling_number",
    },
    "SCV": {
        1: "parameter_class",
        2: "parameter_value",
    },
    "SN": {
        1: "comparator",
        2: "num1",
        3: "separator_suffix",
        4: "num2",
    },
    "SPD": {
        1: "specialty_name",
        2: "governing_board",
        3: "eligible_or_certified",
        4: "date_of_certification",
    },
    "SRT": {
        1: "sort_by_field",
        2: "sequencing",
    },
    "UVC": {
        1: "value_code",
        2: "value_amount",
        3: "non_monetary_value_amount_quantity",
        4: "non_monetary_value_amount_units",
    },
    "VH": {
        1: "start_day_range",
        2: "end_day_range",
        3: "start_hour_range",
        4: "end_hour_range",
    },
    "VID": {
        1: "version_id",
        2: "internationalization_code",
        3: "international_version_id",
    },
    "VR": {
        1: "first_data_code_value",
        2: "last_data_code_value",
    },
    "WVI": {
        1: "channel_number",
        2: "channel_name",
    },
    "WVS": {
        1: "source_one_name",
        2: "source_two_name",
    },
    "XAD": {
        1: "street_address",
        2: "other_designation",
        3: "city",
        4: "state_or_province",
        5: "zip_or_postal_code",
        6: "country",
        7: "address_type",
        8: "other_geographic_designation",
        9: "county_parish_code",
        10: "census_tract",
        11: "address_representation_code",
        12: "address_validity_range",
        13: "effective_date",
        14: "expiration_date",
        15: "expiration_reason",
        16: "temporary_indicator",
        17: "bad_address_indicator",
        18: "address_usage",
        19: "addressee",
        20: "comment",
        21: "preference_order",
        22: "protection_code",
    },
    "XCN": {
        1: "person_identifier",
        2: "family_name",
        3: "given_name",
        4: "second_and_further_given_names_or_initials_thereof",
        5: "suffix",
        6: "prefix",
        7: "degree",
        8: "source_table",
        9: "assigning_authority",
        10: "name_type_code",
        11: "identifier_check_digit",
        12: "check_digit_scheme",
        13: "identifier_type_code",
        14: "assigning_facility",
        15: "name_representation_code",
        16: "name_context",
        17: "name_validity_range",
        18: "name_assembly_order",
        19: "effective_date",
        20: "expiration_date",
        21: "professional_suffix",
        22: "assigning_jurisdiction",
        23: "assigning_agency_or_department",
    },
    "XON": {
        1: "organization_name",
        2: "organization_name_type_code",
        3: "id_number",
        4: "identifier_check_digit",
        5: "check_digit_scheme",
        6: "assigning_authority",
        7: "identifier_type_code",
    },
    "XPN": {
        1: "family_name",
        2: "given_name",
        3: "second_and_further_given_names_or_initials_thereof",
        4: "suffix",
        5: "prefix",
        6: "degree",
        7: "name_type_code",
        8: "name_representation_code",
        9: "name_context",
        10: "name_validity_range",
        11: "name_assembly_order",
        12: "effective_date",
        13: "expiration_date",
    },
    "XTN": {
        1: "telephone_number",
        2: "telecommunication_use_code",
        3: "telecommunication_equipment_type",
        4: "communication_address",
        5: "country_code",
        6: "area_city_code",
        7: "local_number",
        8: "extension",
        9: "any_text",
        10: "extension_prefix",
        11: "speed_dial_code",
        12: "unformatted_telephone_number",
        13: "effective_start_date",
        14: "expiration_date",
        15: "expiration_reason",
        16: "protection_code",
        17: "shared_telecommunication_identifier",
    },
}


POSITIONAL_TO_SEMANTIC: dict[str, dict[str, str]] = {}
SEMANTIC_TO_POSITIONAL: dict[str, dict[str, int]] = {}

for dt, comps in SEMANTIC_NAMES.items():
    dt_lower = dt.lower()
    POSITIONAL_TO_SEMANTIC[dt] = {}
    SEMANTIC_TO_POSITIONAL[dt] = {}
    for pos, name in comps.items():
        positional = f"{dt_lower}_{pos}"
        POSITIONAL_TO_SEMANTIC[dt][positional] = name
        SEMANTIC_TO_POSITIONAL[dt][name] = pos
