from typing import Any

from datetime import datetime
from logging import getLogger
from tempfile import NamedTemporaryFile
from time import sleep
from random import choice, randint
from unittest import TestCase
from uuid import uuid4
from bunch import Bunch, bunchify
from six import string_types
from sqlalchemy import create_engine
from zato.common.api import CHANNEL, DATA_FORMAT, SIMPLE_IO
from zato.common.ext.configobj_ import ConfigObj
from zato.common.json_internal import loads
from zato.common.marshal_.api import MarshalAPI
from zato.common.odb import model
from zato.common.odb.model import Cluster, ElasticSearch
from zato.common.odb.api import SessionWrapper, SQLConnectionPool
from zato.common.odb.query import search_es_list
from zato.common.simpleio_ import get_bytes_to_str_encoding, get_sio_server_config, simple_io_conf_contents
from zato.common.py23_ import maxint
from zato.common.typing_ import cast_
from zato.common.util.api import is_port_taken, new_cid
from zato.server.service import Service
from zato.simpleio import CySimpleIO
from zato.common.py23_.past.builtins import basestring, cmp, unicode, xrange
from zato.common.odb.api import ODBManager
from zato.common.typing_ import any_, anydict, anylist, intnone, strnone
from zato.common.util.search import SearchResults
from mock import MagicMock, Mock
import os
from zato.common.util.cli import CommandLineInvoker
from zato.common.util.cli import CommandLineServiceInvoker

class test_odb_data:
    cluster_id: Any
    name: Any
    is_active: Any
    es_hosts: Any
    es_timeout: Any
    es_body_as: Any

class PubSubConfig:
    PathPublish: Any
    PathReceive: Any
    PathSubscribe: Any
    PathUnsubscribe: Any
    TestTopicPrefix: Any

def rand_bool() -> None: ...

def rand_csv(count: Any = ...) -> None: ...

def rand_dict() -> None: ...

def rand_list() -> None: ...

def rand_list_of_dicts() -> None: ...

def rand_opaque() -> None: ...

def rand_datetime(to_string: Any = ...) -> None: ...

def rand_int(start: int = ..., stop: int = ..., count: int = ...) -> any_: ...

def rand_float(start: Any = ..., stop: Any = ...) -> None: ...

def rand_string(count: Any = ..., prefix: Any = ...) -> any_: ...

def rand_unicode() -> None: ...

def rand_object() -> None: ...

def rand_date_utc(as_string: Any = ...) -> None: ...

def is_like_cid(cid: Any) -> None: ...

def get_free_tcp_port(start: Any = ..., stop: Any = ...) -> None: ...

def enrich_with_static_config(object_: Any) -> None: ...

class TestCluster:
    name: Any
    def __init__(self: Any, name: str) -> None: ...

class TestParallelServer:
    cluster: Any
    cluster_name: Any
    odb: Any
    name: Any
    def __init__(self: Any, cluster: Any, odb: Any, server_name: Any) -> None: ...
    def decrypt(self: Any, data: str) -> str: ...
    def invoke_all_pids(*args: Any, **kwargs: Any) -> None: ...

class Expected:
    data: Any
    def __init__(self: Any) -> None: ...
    def add(self: Any, item: Any) -> None: ...
    def get_data(self: Any) -> None: ...

class TestBrokerClient:
    publish_args: Any
    publish_kwargs: Any
    invoke_async_args: Any
    invoke_async_kwargs: Any
    def __init__(self: Any) -> None: ...
    def publish(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def invoke_async(self: Any, *args: Any, **kwargs: Any) -> None: ...

class TestKVDB:
    conn: self.TestConn
    def __init__(self: Any) -> None: ...
    def translate(self: Any, *ignored_args: Any, **ignored_kwargs: Any) -> None: ...

class TestServices:
    def __getitem__(self: Any, ignored: Any) -> None: ...

class TestServiceStore:
    services: TestServices
    name_to_impl_name: Any
    impl_name_to_service: Any
    def __init__(self: Any, name_to_impl_name: Any = ..., impl_name_to_service: Any = ...) -> None: ...
    def new_instance(self: Any, impl_name: Any, is_active: Any = ...) -> None: ...

class TestODB:
    def session(self: Any, *ignored_args: Any, **ignored_kwargs: Any) -> None: ...

class TestServer:
    odb: TestODB
    kvdb: TestKVDB
    service_store: TestServiceStore
    marshal_api: MarshalAPI
    worker_store: Any
    repo_location: rand_string
    delivery_store: Any
    user_config: Bunch
    static_config: Bunch
    time_util: Bunch
    servers: Any
    component_enabled: Bunch
    cluster_id: Any
    name: Any
    pid: Any
    fs_server_config: Bunch
    ctx: Any
    def __init__(self: Any, service_store_name_to_impl_name: Any = ..., service_store_impl_name_to_service: Any = ..., worker_store: Any = ...) -> None: ...
    def invoke(self: Any, service: any_, request: any_) -> None: ...
    def on_wsx_outconn_stopped_running(self: Any, conn_id: str) -> None: ...
    def on_wsx_outconn_connected(self: Any, conn_id: str) -> None: ...

class SIOElemWrapper:
    value: Any
    def __init__(self: Any, value: Any) -> None: ...
    def __cmp__(self: Any, other: Any) -> None: ...

class ServiceTestCase(TestCase):
    maxDiff: Any
    def __init__(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def invoke(self: Any, class_: Any, request_data: Any, expected: Any, mock_data: Any = ..., channel: Any = ..., job_type: Any = ..., data_format: Any = ..., service_store_name_to_impl_name: Any = ..., service_store_impl_name_to_service: Any = ...) -> None: ...
    def _check_sio_request_input(self: Any, instance: Any, request_data: Any) -> None: ...
    def check_impl(self: Any, service_class: Any, request_data: Any, response_data: Any, response_elem: Any, mock_data: Any = ...) -> None: ...
    def check_impl_list(self: Any, service_class: Any, item_class: Any, request_data: Any, response_data: Any, request_elem: Any, response_elem: Any, mock_data: Any = ...) -> None: ...
    def wrap_force_type(self: Any, elem: Any) -> None: ...

class ODBTestCase(TestCase):
    def setUp(self: Any) -> None: ...
    def tearDown(self: Any) -> None: ...
    def get_session(self: Any) -> None: ...
    def get_sample_odb_orm_result(self: Any, is_list: Any) -> None: ...

class MyODBService(Service):
    ...

class MyODBServiceWithResponseElem(MyODBService):
    ...

class MyZatoClass:
    def to_zato(self: Any) -> None: ...

class BaseSIOTestCase(TestCase):
    def setUp(self: Any) -> None: ...
    def get_server_config(self: Any, needs_response_elem: Any = ...) -> None: ...
    def get_sio(self: Any, declaration: Any, class_: Any) -> None: ...

class BaseZatoTestCase(TestCase):
    maxDiff: Any
    logger: getLogger
    def __init__(self: Any, *args: Any, **kwargs: Any) -> None: ...
    def create_pubsub_topic(self: Any) -> anydict: ...
    def _handle_cli_out(self: Any, out: str, assert_ok: bool, load_json: bool = ...) -> str: ...
    def run_zato_cli_command(self: Any, cli_params: anylist, command_name: str = ..., assert_ok: bool = ..., load_json: bool = ...) -> any_: ...
    def run_zato_cli_json_command(self: Any, *args: Any, **kwargs: Any) -> any_: ...
    def delete_pubsub_topics_by_pattern(self: Any, pattern: str) -> any_: ...

class CommandLineTestCase(BaseZatoTestCase):
    ...

class CommandLineServiceTestCase(BaseZatoTestCase):
    def run_zato_service_test(self: Any, service_name: str, assert_ok: bool = ...) -> str: ...
