from typing import Any

import os
from logging import getLogger
from pathlib import Path
from zato.common.rules.api import RulesManager
from zato.common.typing_ import any_, anydict, strlist

class RuleTestHelper:
    def __init__(self: Any, rules_dir: Any = ..., include_perf_files: Any = ...) -> None: ...
    def _load_rules(self: Any, directory: Path) -> None: ...
    def find_rules_with_condition(self: Any, condition_text: str) -> strlist: ...
    def find_rules_with_all_conditions(self: Any, condition_texts: strlist) -> strlist: ...
    def find_rules_without_conditions(self: Any, condition_texts: strlist) -> strlist: ...
    def find_rules_with_condition_and_without_others(self: Any, include_text: str, exclude_texts: strlist) -> strlist: ...
    def find_rules_with_parentheses(self: Any) -> strlist: ...
    def find_simple_equality_rules(self: Any) -> strlist: ...
    def find_rule_by_pattern(self: Any, pattern: str) -> str: ...
    def get_rule_condition(self: Any, rule_name: str) -> str: ...
    def match_rule(self: Any, rule_name: str, data: anydict) -> any_: ...
