from typing import Any

from time import sleep
from zato.common import PUBSUB
from zato.common.test import PubSubConfig
from zato.common.test.rest_client import RESTClient, RESTClientTestCase
from zato.common.typing_ import cast_
from zato.common.typing_ import any_, anydict, anylist, stranydict

class PubSubAPIRestImpl:
    def __init__(self: Any, test: BasePubSubRestTestCase, rest_client: RESTClient) -> None: ...
    def _publish(self: Any, topic_name: str, data: any_) -> stranydict: ...
    def _receive(self: Any, topic_name: str, needs_sleep: bool = ..., expect_ok: bool = ...) -> anylist: ...
    def _subscribe(self: Any, topic_name: str, needs_unsubscribe: bool = ...) -> str: ...
    def _unsubscribe(self: Any, topic_name: str) -> anydict: ...

class BasePubSubRestTestCase(RESTClientTestCase):
    needs_current_app: Any
    payload_only_messages: Any
    should_init_rest_client: Any
    def setUp(self: Any) -> None: ...
    def _publish(self: Any, topic_name: str, data: any_) -> stranydict: ...
    def _receive(self: Any, topic_name: str, needs_sleep: bool = ..., expect_ok: bool = ...) -> anylist: ...
    def _subscribe(self: Any, topic_name: str, needs_unsubscribe: bool = ...) -> str: ...
    def _unsubscribe(self: Any, topic_name: str) -> anydict: ...
