from typing import Any

import logging
from base64 import b64encode
from operator import itemgetter
from threading import RLock
from traceback import format_exc
from uuid import uuid4
from zato.common.ext.future.utils import iteritems
from zato.common.py23_.past.builtins import unicode
from zato.bunch import Bunch
from zato.common.api import CHANNEL, CONNECTION, MISC, SEC_DEF_TYPE, ZATO_NONE
from zato.common.broker_message import code_to_name, SECURITY
from zato.common.dispatch import dispatcher
from zato.common.util.api import update_apikey_username_to_channel, wait_for_dict_key
from zato.common.util.auth import enrich_with_sec_data, on_basic_auth
from zato.common.util.url_dispatcher import get_match_target
from zato.server.connection.http_soap import Unauthorized
from zato.server.connection.http_soap.url_dispatcher import Matcher, PyURLData
from zato.server.base.worker import WorkerStore

class URLData(PyURLData):
    def __init__(self: Any, worker: Any, channel_data: Any = ..., url_sec: Any = ..., basic_auth_config: Any = ..., ntlm_config: Any = ..., oauth_config: Any = ..., apikey_config: Any = ..., broker_client: Any = ..., odb: Any = ...) -> None: ...
    def set_security_objects(self: Any) -> None: ...
    def dispatcher_callback(self: Any, event: Any, ctx: Any, **opaque: Any) -> None: ...
    def _handle_security_apikey(self: Any, cid: Any, sec_def: Any, path_info: Any, body: Any, wsgi_environ: Any, ignored_post_data: Any = ..., enforce_auth: Any = ...) -> None: ...
    def _handle_security_basic_auth(self: Any, cid: Any, sec_def: Any, path_info: Any, body: Any, wsgi_environ: Any, ignored_post_data: Any = ..., enforce_auth: Any = ...) -> None: ...
    def check_security(self: Any, sec: Any, cid: Any, channel_item: Any, path_info: Any, payload: Any, wsgi_environ: Any, post_data: Any, worker_store: Any) -> None: ...
    def _update_url_sec(self: Any, msg: Any, sec_def_type: Any, delete: Any = ...) -> None: ...
    def _delete_channel_data(self: Any, sec_type: Any, sec_name: Any) -> None: ...
    def _update_apikey(self: Any, name: Any, config: Any) -> None: ...
    def apikey_get(self: Any, name: Any) -> None: ...
    def apikey_get_by_id(self: Any, def_id: Any) -> None: ...
    def on_broker_msg_SECURITY_APIKEY_CREATE(self: Any, msg: Any, *args: Any) -> None: ...
    def on_broker_msg_SECURITY_APIKEY_EDIT(self: Any, msg: Any, *args: Any) -> None: ...
    def on_broker_msg_SECURITY_APIKEY_DELETE(self: Any, msg: Any, *args: Any) -> None: ...
    def on_broker_msg_SECURITY_APIKEY_CHANGE_PASSWORD(self: Any, msg: Any, *args: Any) -> None: ...
    def _get_sec_def_by_id(self: Any, def_type: Any, def_id: Any) -> None: ...
    def _update_basic_auth(self: Any, name: Any, config: Any) -> None: ...
    def basic_auth_get(self: Any, name: Any) -> None: ...
    def basic_auth_get_by_id(self: Any, def_id: Any) -> None: ...
    def on_broker_msg_SECURITY_BASIC_AUTH_CREATE(self: Any, msg: Any, *args: Any) -> None: ...
    def on_broker_msg_SECURITY_BASIC_AUTH_EDIT(self: Any, msg: Any, *args: Any) -> None: ...
    def on_broker_msg_SECURITY_BASIC_AUTH_DELETE(self: Any, msg: Any, *args: Any) -> None: ...
    def on_broker_msg_SECURITY_BASIC_AUTH_CHANGE_PASSWORD(self: Any, msg: Any, *args: Any) -> None: ...
    def _update_ntlm(self: Any, name: Any, config: Any) -> None: ...
    def ntlm_get(self: Any, name: Any) -> None: ...
    def on_broker_msg_SECURITY_NTLM_CREATE(self: Any, msg: Any, *args: Any) -> None: ...
    def on_broker_msg_SECURITY_NTLM_EDIT(self: Any, msg: Any, *args: Any) -> None: ...
    def on_broker_msg_SECURITY_NTLM_DELETE(self: Any, msg: Any, *args: Any) -> None: ...
    def on_broker_msg_SECURITY_NTLM_CHANGE_PASSWORD(self: Any, msg: Any, *args: Any) -> None: ...
    def _update_oauth(self: Any, name: Any, config: Any) -> None: ...
    def oauth_get(self: Any, name: Any) -> None: ...
    def oauth_get_by_id(self: Any, def_id: Any) -> None: ...
    def on_broker_msg_SECURITY_OAUTH_CREATE(self: Any, msg: Any, *args: Any) -> None: ...
    def on_broker_msg_SECURITY_OAUTH_EDIT(self: Any, msg: Any, *args: Any) -> None: ...
    def on_broker_msg_SECURITY_OAUTH_DELETE(self: Any, msg: Any, *args: Any) -> None: ...
    def on_broker_msg_SECURITY_OAUTH_CHANGE_PASSWORD(self: Any, msg: Any, *args: Any) -> None: ...
    def get_channel_by_name(self: Any, name: Any, _channel: Any = ...) -> None: ...
    def sort_channel_data(self: Any) -> None: ...
    def _channel_item_from_msg(self: Any, msg: Any, match_target: Any, old_data: Any = ...) -> None: ...
    def _sec_info_from_msg(self: Any, msg: Any) -> None: ...
    def _create_channel(self: Any, msg: Any, old_data: Any) -> None: ...
    def _delete_channel(self: Any, msg: Any) -> None: ...
    def on_broker_msg_CHANNEL_HTTP_SOAP_CREATE_EDIT(self: Any, msg: Any, *args: Any) -> None: ...
    def on_broker_msg_CHANNEL_HTTP_SOAP_DELETE(self: Any, msg: Any, *args: Any) -> None: ...
