from typing import Any

from logging import getLogger
from zato.common.typing_ import stranydict
from O365 import Account as Office365Account
from json import loads
from O365 import Account

class Microsoft365Client:
    def __init__(self: Any, config: stranydict) -> None: ...
    def impl_from_config(self: Any, config: stranydict) -> Office365Account: ...
    def refresh(self: Any) -> None: ...
    def api(self: Any) -> Office365Account: ...
    def ping(self: Any) -> None: ...
