from typing import Any

import http.client as http_client
import logging
import msal
import requests
from zato.common.typing_ import anydict, anydictnone, dictnone, strnone

class DataverseClient:
    def __init__(self: Any, tenant_id: str, client_id: str, client_secret: str, org_url: str) -> None: ...
    def get_access_token(self: Any) -> strnone: ...
    def _get_headers(self: Any) -> anydict: ...
    def _make_request(self: Any, method: str, path: str, data: anydictnone = ...) -> dictnone: ...
    def get(self: Any, path: str) -> dictnone: ...
    def post(self: Any, path: str, data: anydict) -> dictnone: ...
    def patch(self: Any, path: str, data: anydict) -> dictnone: ...
    def delete(self: Any, path: str) -> dictnone: ...
